### ISSUE TITLE
feat (jans-cedarling): Add Bootstrap property for JWKS

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#10005]
Instead of downloading the JWKS from the `jwks_endpoint`, it would be helpful in some cases if we could provide a bootstrap property to specify the jwks file. 

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by rmarinn** [comment]
This should be supported after PR #10306
