### ISSUE TITLE
fix(jans-casa): consent revoke failing

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#10031]
An error is shown on UI when trying to remove client's authorization through the consent mgmt plugin

**Comment by jgomer2001** [comment]
Probably failing because table `jansClntAuthz` has column `jansClnId` which is multivalued - should just be `clnId` which is single-valued. Awaiting for update

**Comment by yuriyz** [comment]
Changed in https://github.com/JanssenProject/jans/pull/10034
