### ISSUE TITLE
feat(jans-cedarling): Implement check authorization principals based on the schema for action

### ISSUE THREAD

**Issue by olehbozhok** [JanssenProject/jans#10072]
**Is your feature request related to a problem? Please describe.**
In cedar-policy schema from agama-lab we have 3 principals Workload, User and Role
Currently, for each request we make authorization check for each principal.

And it is hard coded that each principal use namespace "Jans"

**Describe the solution you'd like**
- improve parsing cedar-policy schema and add check if principal can be applied to `cedar-policy` `Action`
- add usage of namespace stored in the `policy-store`

**Additional context**
In policy store field `name` describe `namespace` in the cedar-policy schema

**Comment by nynymike** [comment]
Rather then making three authz requests, which may have three different diagnostics, is it possible to combine these three queries into one authz request?

**Comment by olehbozhok** [comment]
@nynymike agama-lab already implemented creating `cedar-policy` schema with 3 possible principals. 
To make all checks in one, we need to figure out possible solutions. But looks like we need to implement a `principal` entity that can hold values of all current principals.

I think it is a huge change and may have impact on demo deadline.
