### ISSUE TITLE
fix(jans-linux-setup): api-admin revoking session permissions

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#10153]
These permissions should be added to **api-admin** 

- https://jans.io/oauth/jans-auth-server/session.delete
- revoke_session

at https://github.com/JanssenProject/jans/blob/passkeys-project/jans-linux-setup/jans_setup/templates/jans-auth/role-scope-mappings.json#L606

**Comment by pujavs** [comment]
Yes delete session requires both these permission
