### ISSUE TITLE
fix(cloud-native): applications are failing to start when prometheus metrics are enabled

### ISSUE THREAD

**Issue by polsson12** [JanssenProject/jans#10224]
**Describe the bug**
We are running version 1.1.5 of Janssen in a kubernetes microservice setup. When enabling prometheus metrics by setting janssen.global.cnPrometheusPort=9093 we are seeing that the java applications inside the containers are failing to start and the readiness probe is failing. 
 
**To Reproduce**
In a kubernetes microservice setup, enable promethues by setting the value
`janssen.global.cnPrometheusPort=9093` in the values.yaml file.

**Expected behavior**
We expect the applications to start successfully and expose metrics inside the container under `http://localhost:9093/metrics`.

**The problem**
The entrypoint script is fetching the prometheus lib on demand if not already present on the machine when the CN_PROMETHUES_PORT env variable is present on the machine by running the `get_prometheus_lib` function. I think that there's a problem with the current wget version (BusyBox v1.36.1 (2024-06-10 07:11:47 UTC) multi-call binary). When logging into the container and execute the below command it gets stuck forever:

```
wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.17.2/jmx_prometheus_javaagent-0.17.2.jar -O /tmp/jmx_prometheus_javaagent.jar
Connecting to repo1.maven.org
...
```

```
get_prometheus_lib() {
    if [ -n "${CN_PROMETHEUS_PORT}" ]; then
        prom_agent_version="0.17.2"

        if [ ! -f /opt/prometheus/jmx_prometheus_javaagent.jar ]; then
            wget -q https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${prom_agent_version}/jmx_prometheus_javaagent-${prom_agent_version}.jar -O /opt/prometheus/jmx_prometheus_javaagent.jar
        fi
    fi
}
```

**Suggestions**
Alt 1) My preferred solution would be to include the prometheus lib in the applications from the beginning. Makes the entrypoint script cleaner and overall project structure cleaner imo.
Alt 2) Change command from `wget` to `curl`. By using curl it works just fine. It seems casa doesn't come with curl, so at least that one would need to be included there.
Alt 3) Upgrade wget to a version where the command works.

**Comment by iromli** [comment]
I'm unable to reproduce the issue, the JAR file is downloaded successfully.

@misba7 can you test on your setup to see if there's any network issue downloading file from repo1.maven.org?

**Comment by polsson12** [comment]
Hi again,

The issue might be related to that wget has to go through our proxy and then to maven in order to fetch the dependency.

I saw that issue was added to the next release milestone. Did you manage to reproduce the issue?

**Comment by misba7** [comment]
> I'm unable to reproduce the issue, the JAR file is downloaded successfully.
> 
> [@misba7](https://github.com/misba7) can you test on your setup to see if there's any network issue downloading file from repo1.maven.org?

Looks fine on my end too.

![Image](https://github.com/user-attachments/assets/8fbf86a6-a0cb-4d69-8b8f-7058de07caf8)

**Comment by polsson12** [comment]
Are you guys able to set up a intermediate proxy that the request have to go trough in order to get the dependency?

That might be the root cause of the problem with wget.

In our organisation there's no option to not bypass that proxy in order to fetch libs.

**Comment by iromli** [comment]
@polsson12 we're not using any intermediate proxy.

Anyway, you mentioned that it works when using `curl`, would you like to submit PR?
