### ISSUE TITLE
fix(jans-config): Enhance the endpoint to support date range search in the session and client section based on creation date, expiration date, and authentication date.

### ISSUE THREAD

**Issue by mjatin-dev** [JanssenProject/jans#10227]
**Describe the bug**
1) Enhance the endpoint to support date range search in the session section based on creation date, expiration date, and authentication date with time.
    **Endpoint** - /api/v1/token/search?limit=10&startIndex=0&fieldValuePair=clnId%3D2001.80537456-a3e3-406b-aad1-f90a90917afa

2) Enhance the endpoint to support date range search in the client section based on creation date with time.
    **Endpoint** - /api/v1/token/search?limit=10&startIndex=0&fieldValuePair=clnId%3D2001.80537456-a3e3-406b-aad1-f90a90917afa

**Comment by pujavs** [comment]
Based on discussion @mjatin-dev to confirm if this change is required

**Comment by pujavs** [comment]
Closing issue as confirmed by @mjatin-dev that admin-ui did change in-line with TUI and hence no change required in config-api.
