### ISSUE TITLE
feat(jans-cedarling): pass token entities data into the context

### ISSUE THREAD

**Issue by rmarinn** [JanssenProject/jans#10249]
## **Is your feature request related to a problem? Please describe.**

We want to implement ABAC but get the attributes from the JWTs. One way to implement this is to get the attributes from the parsed Cedar Entity then send it in with the context on the call to `authorize`.

Consider the following Cedar policy:
```
permit(
    principal is Jans::Workload,
    action in [Jans::Action::"Update",Jans::Action::"UpdateForWorkload",Jans::Action::"UpdateForWorkloadAndRole"],
    resource is Jans::Issue
)when{
    principal.org_id == resource.org_id
};

// Schema
action "Update" appliesTo {
    principal: [Workload, User, Role],
    resource: [Issue],
    context: {}
};
```

To be able add a condition checking if the `id_token` was from a particular issuer, we need to pass it in through the context:

```cedar
permit(
    principal is Jans::Workload,
    action in [Jans::Action::"Update",Jans::Action::"UpdateForWorkload",Jans::Action::"UpdateForWorkloadAndRole"],
    resource is Jans::Issue
)when{
    principal.org_id == resource.org_id
    context.id_token.iss == "https://account.gluu.org"
};

// Updated Schema
entity Issue = {"country": String, "org_id": String};
entity Role;
entity User in [Role] = {"country": String};
entity Workload = {"org_id": String};
entity Access_token = {"aud": String,"iss": String, "jti": String, "client_id": String,"org_id": String};
entity id_token = {"aud": String,"iss": String, "sub": String};
entity Userinfo_token  = {"iss": String, "jti": String, "client_id": String};
type  Context = {
    user: User,
    workload: Workload,
    access_token: Access_token,
    id_token: id_token,
    userinfo_token: Userinfo_token,
};
action "Update" appliesTo {
    principal: [Workload, User, Role],
    resource: [Issue],
    context: {
       id_token: { "iss": String }
    }
};
```

## **Describe the solution you'd like**

Currently, users pass the context into `authorize` in this format:

```json
{
  "ip_address": "54.9.21.201",
  "network_type": "VPN",
  "user_agent": "Chrome 125.0.6422.77 (Official Build) (arm64)",
  "time": "1719266610.98636",
}
```

However, we want to pass in attributes from the JWTs into the context. The user can already pass in in the JWT when we call authorize but it's encode in Base64. Since we don't want the user to be extracting the token claims on their own, we can handle it internally.

To implement passing in data from the token claims into the context, we can:

1. Parse the entities (already implemented).
2. Check the Cedar schema if it requires the entities in the context.
3. Insert the entities' data or entity references into the context before proceeding with the authorization step.

### Possible issues:

An If we take take entities from the tokens then automatically add that in the context, it might be unclear that we are also checking for the context when calling `authorize`. For example, look at the following function call:

```js
input = { 
           "access_token": "...", 
           "id_token": "...", 
           "userinfo_token": "...", 
           "tx_token": "...",
           "resource": {"id": "12345", "type": "Ticket", "creator": "mike@gluu.org", "organization": "gluu"},
           "action": "View",
           "context": {
                       "ip_address": "54.9.21.201",
                       "network_type": "VPN",
                       "user_agent": "Chrome 125.0.6422.77 (Official Build) (arm64)",
                       "time": "1719266610.98636",
                      }
         }

decision_result = authz(input)
```

If we have a policy that requires: `context.id_token.iss == https://account.gluu.org`. The implementation that the id_token's issuer will be automatically passed into the context is hidden from the caller.

**Comment by nynymike** [comment]
The id_token does not need to be passed in the Context. The developer has already passed it in the Authz request. What I'm saying is that the Cederling should add it to the Context automatically.
