### ISSUE TITLE
feat(ProjectPasskeys): ..../.well-known/webauthn

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#10245]
**Issue details :** 

https://developer.chrome.com/blog/passkeys-updates-chrome-129?hl=en

**Test case to be written**

On the same lines as this - https://web.dev/articles/webauthn-related-origin-requests#how_to_set_up_related_origin_requests

**Comment by imran-ishaq** [comment]
![Image](https://github.com/user-attachments/assets/45fb25f6-0d53-4c2c-97e0-6b433cf6edf0)
