### ISSUE TITLE
fix(jans-cli-tui): version are not showing

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#10255]
**Describe the bug**
versions are not showing

**To Reproduce**
1. install jans 1.1.6 or flex 5.1.6.nightly
2. launch TUI
3. check for application version

**Expected behavior**
should get all application version 

**Screenshots**
![Image](https://github.com/user-attachments/assets/96c94cb0-f314-417f-aa0b-0f6a997a017d)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.6/flex 5.1.6.nightly
-DB pgsql
**Smartphone (please complete the following information):**

**Additional context**

**Comment by moabu** [comment]
@manojs1978 the 5.1.6 nightly build is expected since its pulling from main however are you sure jans stable release tui gives the same ?

**Comment by devrimyatar** [comment]
This is not TUI issue. Build numbers were given 0.0.0 for nighlty builds
