### ISSUE TITLE
feat(jans-cedarling): New bootstrap properties to request authz for User, Workload or both

### ISSUE THREAD

**Issue by olehbozhok** [JanssenProject/jans#10265]
**Is your feature request related to a problem? Please describe.**
We need to implement bootstrap properties related to executing authorize request

CEDARLING_USER_AUTHZ : When enabled, Cedar engine authorization is queried for a User principal.

CEDARLING_WORKLOAD_AUTHZ : When enabled, Cedar engine authorization is queried for a Workload principal.

CEDARLING_USER_WORKLOAD_BOOLEAN_OPERATION : AND, OR

**Describe alternatives you've considered**

**Additional context**

**Comment by olehbozhok** [comment]
Result was merged to https://github.com/JanssenProject/jans/pull/10216

**Comment by SafinWasi** [comment]
Closed by #10216
