### ISSUE TITLE
feat(jans-cedarling): Improve logging of cedarling

### ISSUE THREAD

**Issue by olehbozhok** [JanssenProject/jans#10276]
**Is your feature request related to a problem? Please describe.**
We need to improve logging to maximize the information that helps us with forensic analysis, and minimize useless information.

**Describe the solution you'd like**
We conclude to update diagnostic information to store in `reason` the description of the policy that was executed on authorize request.

About other information we did not find a general solution.

**Comment by olehbozhok** [comment]
Agreed to log policy ID and description. Also agreed to log all `cedar-policy` entities data that was used for authorize request.

**Comment by olehbozhok** [comment]
Continue in https://github.com/JanssenProject/jans/issues/10303

**Comment by SafinWasi** [comment]
Closed by #10338
