### ISSUE TITLE
feat (jans-cedarling): Create Decision Log optimized for Centralized Log Storage

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#10303]
The decision log is optimized to store the mimimal information needed to create a record of all the identifiable components involved in a decion. It's should be small enough to send it over the network to a central server for storage. 

Here is what a sample Decision log would look like: 

```
{
  "request_id": "01937015-4649-7aad-8df8-4976e4bd8565",
  "timestamp": "2024-11-27T10:10:50.654Z",
  "pdp_id": "20939sdf9s89021304958",
  "policystore_id": "564lk460gdlfkg340",
  "policystore_version": "1.2.1",
  "principal": "User" | "Workload", 
  "User": {"email":"foo@acme.com", "sub":"qzxn1Scrb9lWtGxVedMCky-Ql_ILspZaQA6fyuYktw0"},   <-- claims set in Bootstrap properties | could be empty
  "Workload" {"client_id":"123456", "rp_id": "5478963214"},                                                       <-- claims set in Bootstrap properties | could be empty
  "lock_client_id": "987654",
  "action": ""Jans::Action::Read",
  "resource": "Jans::Application::\"some_id\"",
  "decision": "ALLOW",
  "tokens": {"id_token": {"jti": "ijLZO1ooRyWrgIn7cIdNyA"}, 
             "Userinfo": {"jti": "huKL87hhQuQcnhd5dQqZaZ"},
             "access": {"jti": "PiLYppReSD2Ldkuyd72KPI"}
             }
 "decision_time_ms": 1,
}
```

### Field Definitions
*  `request_id`: unique identifier for the decision request
*  `timestamp`: Derived if possible from the system or context--may be empty in cases where WASM can't access the system clock, and the time wasn't sent in the context. 
*  `pdp_id`: unique identifier for the Cedarling
*  `policystore_id`: What policystore this Cedarling instance is using
*  `policystore_version`: What version of the policystore the Cedarling is using
*  `principal`: `User` | `Workload`
*  `User`: A list of claims, specified by the `CEDARLING_DECISION_LOG_USER_CLAIMS` property, that must be present in the Cedar User entity
*  `Workload`:  A list of claims, specified by the `CEDARLING_DECISION_LOG_WORKLOAD_CLAIMS` property, that must be present in the Cedar Workload entity
*  `lock_client_id`: If this Cedarling has registered with a Lock Server, what is the client_id it received
*  `action`: From the request
*  `resource`: From the Request
*  `decision`: `ALLOW` or `DENY` 
*  `tokens`: Dictionary with the token type and claims which should be included in the log
*  `decision_time_ms`: how long the decision took

**Comment by olehbozhok** [comment]
@nynymike  cedar return set of policies that was executed during req

`"policystore_id": "564lk460gdlfkg340",` 

so I will return  the list
`"policystore_ids": ["564lk460gdlfkg340"]`

**Comment by nynymike** [comment]
The decision log will not be impacted by log_level. That should only be for the `System` log
