### ISSUE TITLE
feat(config-api) - Implement an endpoint that returns an ArrayBuffer for the selected Agama project's github download URL.

### ISSUE THREAD

**Issue by mjatin-dev** [JanssenProject/jans#10454]
Parent issue [8785](https://github.com/JanssenProject/jans/issues/8785)

**Expected behavior**
Need an API with a GET endpoint that takes a GitHub download URL as input and returns the corresponding data as an ArrayBuffer in the response.

**Comment by pujavs** [comment]
@mjatin-dev, introduced new endpoint `jans-config-api/api/v1/agama-repo/download/?downloadLink=<agama-downlaod-url>`

- **Example:** `jans-config-api/api/v1/agama-repo/download/?downloadLink=https%3A%2F%2Fgithub.com%2FGluuFederation%2Fagama-passkey%2Freleases%2Fdownload%2Fv1.0.0%2Fagama-passkey.gama`
- **Note:** `downlaod-url` should be encoded.

![Image](https://github.com/user-attachments/assets/53953fbb-4b44-4183-ab35-b8fb6505d5a7)
