### ISSUE TITLE
feat: auth Server should Support Client Registration Language Metadata

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1057]
[Section 2.1 of OpenID Client Reg](https://openid.net/specs/openid-connect-registration-1_0.html#LanguagesAndScripts) states:

   Human-readable Client Metadata values and Client Metadata values that reference human-readable values MAY be 
   represented in multiple languages and scripts. For example, values such as client_name, tos_uri, policy_uri, logo_uri, and 
   client_uri might have multiple locale-specific values in some Client registrations.

   To specify the languages and scripts, [BCP47](https://openid.net/specs/openid-connect-registration-1_0.html#RFC5646) 
   [RFC5646] language tags are added to Client Metadata member names, delimited by a # character. The same syntax is used 
   for representing languages and scripts for Client Metadata as is used for Claims, as described in Section 5.2 (Claims 
   Languages and Scripts) of [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-registration-
   1_0.html#OpenID.Core) [OpenID.Core].

   If such a human-readable field is sent without a language tag, parties using it MUST NOT make any assumptions about the 
   language, character set, or script of the string value, and the string value MUST be used as-is wherever it is presented in a 
   user interface. To facilitate interoperability, it is RECOMMENDED that any human-readable fields sent without language tags 
   contain values suitable for display on a wide variety of systems.

* The highest priority claims are `client_name` and `client_uri`.

**Comment by qbert2k** [comment]
The Client metadata values: client_name (displayName), logo_uri (jansLogoURI), client_uri (jansClntURI), policy_uri (jansPolicyURI), and tos_uri (jansTosURI) now stores a JSON with values for multiple languages and scripts. For example:

### MySQL, Couchbase, Spanner, etc.

##### client_name (displayName)
![image](https://user-images.githubusercontent.com/2474616/164330221-a95dcd62-8be9-42e1-be35-434a8c4adbd3.png)

##### logo_uri (jansLogoURI)

![image](https://user-images.githubusercontent.com/2474616/164330837-d1b7c51f-4a39-48f8-b0f2-3cff7acf5a25.png)

##### client_uri (jansClntURI)

![image](https://user-images.githubusercontent.com/2474616/164331213-5b7f69fd-a52e-475d-bdde-8986e961d876.png)

##### policy_uri (jansPolicyURI)

![image](https://user-images.githubusercontent.com/2474616/164331625-74c8a55a-f148-47a8-a16f-f4f09f40e58c.png)

##### tos_uri (jansTosURI)

![image](https://user-images.githubusercontent.com/2474616/164332100-a2c8de56-76b5-42aa-8c98-b29a69822afb.png)

### LDAP

LDAP has support for Language Tags

![image](https://user-images.githubusercontent.com/2474616/164333745-cb8d0e39-2478-46b7-82a7-c5f1690955bb.png)

**Comment by yurem** [comment]
This is problem related to this: https://github.com/JanssenProject/jans/issues/1482

LanguageTag should support read from DB and search in filters.

Why ORM layer should know how to handle specialized LanguageTag annotation? ORM has generic solution towork with JSON objects. Instead of this:
```
    @LanguageTag
    private LocalizedString logoUri = new LocalizedString();
```

We can use:
```
    @JsonObject
    private LocalizedString logoUri = new LocalizedString();
```

**Comment by qbert2k** [comment]
The LocalizedString is handled as JSON for MySQL, Couchbase, Spanner, etc.
But, LDAP has support for Language Tags so it is not handled as JSON.
That's the reason I have created a new annotation @LanguageTag to be able to perform a different treatment according to the case.

**Comment by yurem** [comment]
I saw your implementation for LDAP. In this case ORM based on server functionality. But in all other cases there is no in DB special support for language tags, etc. LDAP is losing it's positions in CE. I think in this case there is no major point to implement something special for it.

For me @LanguageTag  == @JsonObject . In both cases we store data in JSON. @JsonObject we already support in setup in all projects, etc.. For me is better to use one @JsonObject to keep ORM layer sampler for support.
Can you share special case which you mentioned in last comment for discussion?

**Comment by yurem** [comment]
If you need to implement special behavior you can use 2 or more tags. Sample:
```
    @JsonObject
    @TagForSpecialBehaviour
    private LocalizedString logoUri = new LocalizedString();
```

**Comment by Milton-Ch** [comment]
Looks like there are many tests that are failing because of this issue, do we have some fix coming?
https://jenkins.jans.io/jenkins/job/jans-auth-server/6661/

**Comment by yuriyz** [comment]
@qbert2k where are with this issue? It still effects integration tests and keeps as blind with server functionality overall. Can you take it as priority?

**Comment by qbert2k** [comment]
@yuriyz
I cannot reproduce locally, also cannot reproduce locally, also I tried from a fresh dev env. The claim is returned normally after client registration.

I will contact you by chat with more details.

**Comment by yuriyz** [comment]
@qbert2k does tests work ok for you ? It does not on jenkins as you can see.

**Comment by Milton-Ch** [comment]
In tests, we have this test that couldn't validate properly `client_name`.
![image](https://user-images.githubusercontent.com/86965029/176245841-e2eec1e9-0462-428c-be96-809a393f7f69.png)
In the stack trace we can see that it's failing while validating asserts.
```
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotNull(Assert.java:686)
at io.jans.as.client.client.Asserter.assertRegisterResponseClaimsNotNull(Asserter.java:32)
at io.jans.as.client.ws.rs.AuthorizeRestWebServiceHttpTest.requestAuthorizationAccessTokenFail(AuthorizeRestWebServiceHttpTest.java:2096)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
```

**Comment by qbert2k** [comment]
![image](https://user-images.githubusercontent.com/2474616/176288657-74cbc914-3276-446c-ba08-193181b8c058.png)

I will keep checking...

**Comment by yuriyz** [comment]
@qbert2k no need to check. I've debugged it, the root cause was actually in NPE in JwtAuthorizationRequest. I've fixed it, so next re-build should show tests state. So this language ticket has nothing to do with current tests failures. I will keep an eye on tests.

For reference https://github.com/JanssenProject/jans/issues/1641

**Comment by qbert2k** [comment]
great!
