### ISSUE TITLE
NPE in device code flow

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1087]
In Jans server (installation dating Mar 18th) an NPE is thrown (see log attached).

Steps to reproduce:
- In a different host install jans-cli, steps [here](https://github.com/JanssenProject/jans/tree/main/jans-cli#building)
- Run `python3 config-cli.pyz --host "your.jans.host" --client-id "Jans role based client" --client_secret "..."
- Make a query, eg. custom script by inum

The following appears in the console:
```
Access token was not found.
Please visit verification url https://your.jans.host/device-code and enter user code ... in 1800 secods
```

After typing code in the browser, it is redirected to `/jans-auth/error_service.htm`

[jans-auth.log](https://github.com/JanssenProject/jans/files/8315211/jans-auth.log)

**Comment by yuriyz** [comment]
NPE in AS is fixed.
