### ISSUE TITLE
bug(jans-linux-setup): change datatype of `jansReqURI`, `jansClaimRedirectURI` and `jansAuthorizedOrigins` to json of `jansClnt` table in mysql

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1088]
In mysql, multivalued database attributes are mapped to `json` datatype.

**Current Issue**
In `jansClnt` table, `claimRedirectUris`, `authorizedOrigins` and `requestUris` have following datatypes 
`jansReqURI` -->tinytext
`jansClaimRedirectURI` -->tinytext
`jansAuthorizedOrigins` -->varchar(64)

**Expected change**
The `jansReqURI`, `jansClaimRedirectURI` and `jansAuthorizedOrigins` attributes are multivalued. So we need to change the datatype of these columns to `json`.

**Comment by mbaser** [comment]
Implemented
