### ISSUE TITLE
Move the `/fido/u2f` endpoint from auth-server project to the fido project

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1117]
**Describe the bug**
Currently `/fido/u2f` REST endpoint is listed under [auth-server REST API](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-auth-server/docs/swagger.yaml)

**Expected behavior**
`/fido/u2f` REST endpoint should be part of [jans-fido2 project REST API](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-fido2/docs/jansFido2Swagger.yaml). 

**Screenshots**

![image](https://user-images.githubusercontent.com/343411/160336162-ffcdc185-d0dd-4be8-ba41-14d1c23fb38d.png)

**Comment by maduvena** [comment]
TODOs

1. The `.well-known/configuration/fido-configuration` should reflect the correct endpoints
2. Swagger doc for jans-auth should be updated
3. Swagger doc for fido2 server should be updated
