### ISSUE TITLE
Publish javadocs for `jans-config-api`

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1118]
Every run of `fullrebuild` job on https://jenkins.jans.io/, publishes javadocs at https://jenkins.jans.io/javadocs/

For `jans-config-api`, javadocs are not getting published. 

We need to publish these docs.

**Comment by ossdhaval** [comment]
Hi @pujavs 

Would it be possible to prioritize this? Not a lot of effort may be, but helps a lot to community members to understand and use the module. @duttarnab has implemented this for `jans-client-api` in #1095.

Once docs are published, please also add link to [jans wiki](https://github.com/JanssenProject/jans/wiki/API-References)

**Comment by pujavs** [comment]
hi @ossdhaval 
Changes done to generate javadocs and updated the wiki as well

![image](https://user-images.githubusercontent.com/43700552/164449166-42ccbdf2-71e2-4014-822d-ed23e7fdd1d8.png)
