### ISSUE TITLE
refactor(jans-auth-server): refactor RegisterRestWebServiceImpl into multiple services

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1126]
### Description

Over years all registration logic on AS growth in single RegisterRestWebServiceImpl with ~1350 lines of code. It has to be split into different classes (validator, service, json service) and covered by tests. 

Cognitive complexity has to be dropped.

![image](https://user-images.githubusercontent.com/2013070/160488156-0b697890-61d1-4d41-b25d-33874443bd69.png)

**Comment by nynymike** [comment]
I agree

**Comment by yuriyz** [comment]
Implemented. Registration is split into multiple services and single responsibility actions.

![image](https://user-images.githubusercontent.com/2013070/163783261-6a1cbfa7-6fb3-4a90-957d-46785b99fe65.png)
