### ISSUE TITLE
Typo in `jans-cli` interactive mode

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1140]
**Describe the bug**
`Optional` is incorrectly spelt as `Optiaonal` in `jans-cli`

**To Reproduce**
- On a system where Janssen server is installed, try to create a new OIDC client using documentation [here](https://github.com/JanssenProject/jans/blob/main/docs/user/using-jans-cli/im/im-openid-connect-clients.md#create-a-new-openid-client)
- When you select `y` for providing optional fields, it will present the list of optional fields. Title of this list is where the typo is.

**Expected behavior**
- typo should be fixed in code as well as documentation link above.

**Screenshots**
![image](https://user-images.githubusercontent.com/343411/161050124-4d6e7d39-e16d-4325-a6e7-42f395026278.png)

**Comment by ajmengistu** [comment]
Hi @ossdhaval. Can I work on this issue? If so, I've fixed the typo in code and doc :smile:. But, I'm having issues installing the Janssen server in GitHub Codespaces to test it out.

**Comment by moabu** [comment]
@ajmengistu go for it! Lets see that PR 🚀

**Comment by ossdhaval** [comment]
> Hi @ossdhaval. Can I work on this issue? If so, I've fixed the typo in code and doc smile. But, I'm having issues installing the Janssen server in GitHub Codespaces to test it out.

Your contribution would be most welcome.
