### ISSUE TITLE
feat: (config-api) :  Implement PATCH method of Custom Scripts

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#1210]
### Description

- Development target issue
Implement PATCH method of Custom Scripts

- Implementation Details
  A command to enable / disable a custom script. Particularly useful for authentication mechanism, no need to fetch json, and change the enabled flag
-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes `NA`

- [ ] task 1 `NA`

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by pujavs** [comment]
Implemented the change for adding Json PATCH endpoint for Custom script -> /jans-config-api/api/v1/config/scripts/{inum}

Testing

**Comment by pujavs** [comment]
Code merged in main
