### ISSUE TITLE
feat(jans-linux-setup): setup changes for config-api user management plugin  

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#1213]
jans-setup changes for
1) Copy `user-mgt-plugin` in jans-config-api `/opt/jans/jetty/jans-config-api/custom/libs/` folder
2) Append the path of the new plugin to `extraClasspath` element in`/opt/jans/jetty/jans-config-api/webapps/jans-config-api.xml` 
Example :
<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar, /opt/jans/jetty/jans-config-api/custom/libs/user-mgt-plugin.jar</Set></Configure>

**Comment by mbaser** [comment]
Implemented
