### ISSUE TITLE
feat: convert date/boolean values to DB specifc format before calling ORM layer

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#1215]
In `jans-config-api` test there is test which add many custom user attributes. In this customAttributes list the types of next values are conform LDAP format only:
```
{
    "userId": "config_test_user_01",
    "customAttributes": [
        {
            "name": "birthdate",
            "multiValued": false,
            "values": [
                "19830106010101.253Z"
            ],
            "value": "19830106010101.253Z",
            "displayValue": "19830106010101.253Z"
        },
...
        {
            "name": "emailVerified",
            "multiValued": false,
            "values": [
                "TRUE"
            ],
            "value": "TRUE",
            "displayValue": "TRUE"
        },
...
        {
            "name": "phoneNumberVerified",
            "multiValued": false,
            "values": [
                "TRUE"
            ],
            "value": "TRUE",
            "displayValue": "TRUE"
        },
```

Boolean values we can convert to json boolean values. This will conform both LDAP/RDBMS. But date format requires conversion. The current ORM version support only generic `Date` objects and date in string format like this: `2002-04-18 17:22:16.945`. To write code which not depend on DB type application can use `PersistenceEntryManager` methods: 
```
    Date decodeTime(String primaryKey, String date);
    String encodeTime(String primaryKey, Date date);
```

Also this issue led to the question about standardization. Which generic data format will be acceptable for `jans-config-api` in API requests.

**Comment by pujavs** [comment]
@yurem config-api endpoints accept `application/json` and `application/json-patch+json` for PATCH methods.
So for data-type it relies on JSON Data Type.
Which supports types - `number`,  `boolean`, `null`, `object`, `array` and not `Date`
In this case where **customAttributes** return type is String[] how to get the exact type to do the conversion?

**Comment by yurem** [comment]
You need to define custom attributes as Object[] instead of String[]
```
    import io.jans.orm.model.base.CustomObjectAttribute;
    ...
    @AttributesList(name = "name", value = "values", multiValued = "multiValued", sortByName = true)
    private List<CustomObjectAttribute> customAttributes = new ArrayList<CustomObjectAttribute>();
```

Here is example with this custom attributes: https://github.com/JanssenProject/jans/blob/main/jans-orm/sql-sample/src/main/java/io/jans/orm/sql/SqlCustomObjectAttributesSample.java

I think the `jansAttrTyp` in entry above is not right. For this we can use generalizedTime type. Or if you strictly need to know if it's date without time we can define new AttributeDataType for `date` type.

**Comment by yurem** [comment]
To simplify this issue resolution ORM provides new methods: `getCustomAttributesListItemType`, `getAttributeDataListFromCustomAttributesList`, `getCustomAttributesListFromAttributeDataList`

Your interceptor can do next work:
1. Call `getAttributeDataListFromCustomAttributesList` to get `List<AttributeData>`
2. Load `ou=attributes` and process list from point 1 based on types from this table. We need to fix attribute types in this table if needed.
3. Call `getCustomAttributesListFromAttributeDataList` to get custom attributes list
4. Set new list into bean class
5. Call ORM persist/merge
