### ISSUE TITLE
jans-client-api-server healthcheck api returned 404

### ISSUE THREAD

**Issue by Venkatvenstvm** [JanssenProject/jans#1230]
**Describe the bug**
i have installed jans server in vm with vcpu-3 ram-4G , ubuntu 20.04 as OS, 
client Api are not available and thrown 404 http code
ex : https://{{hostname}}/health-check  ->  resulted 404 with html page 

**To Reproduce**
Installed jans server with following wiki document
```
apt update

apt install wget curl

wget http:$(curl -s -L https://api.github.com/repos/JanssenProject/jans/releases/latest | egrep -o '/.*ubuntu20.04_amd64.deb' | head -n 1) -O /tmp/jans.ubuntu20.04_amd64.deb

apt install -y /tmp/jans.ubuntu20.04_amd64.deb

sudo python3 /opt/jans/jans-setup/setup.py
```

**Expected behavior**
Following Clients api to be available  

1. https://{{hostname}}/health-check
2. client registration 
3. get-client-token

**Additional context**
however below configuration url returning configuration json of authserver
https://{{hostname}}/.well-known/openid-configuration

OR  kindly let me know what the actual end point to be used to access api mentioned swagger 

https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-client-api/server/src/main/resources/swagger.yaml#/developers/update-site

**Comment by jmunozherbas** [comment]
> 

Well, you have to install and run jans-client-api service, with next instructions:
https://github.com/JanssenProject/jans/tree/main/jans-client-api#maven-repository
The link to download distribution is: https://maven.jans.io/maven/io/jans/jans-client-api-server/1.0.0-jetty-SNAPSHOT/jans-client-api-server-1.0.0-jetty-SNAPSHOT-distribution.zip

**Comment by Venkatvenstvm** [comment]
Hi @jmunozherbas  - Kindly let us know  which services are required separate installation and part of **jans.ubuntu20.04_amd64.deb** package installation, this will help us to have complete installation

List of below services are mentioned in **https://gluu.org/janssen-project-linux-foundation/**

1. auth-server 
2. fido
3. config-api 
4. scim 
5. jans-cli 
6. client-api 
7. core 
8. orm

**Comment by jmunozherbas** [comment]
> Hi @jmunozherbas - Kindly let us know which services are required separate installation and part of **jans.ubuntu20.04_amd64.deb** package installation, this will help us to have complete installation
> 
> List of below services are mentioned in **https://gluu.org/janssen-project-linux-foundation/**
> 
> 1. auth-server
> 2. fido
> 3. config-api
> 4. scim
> 5. jans-cli
> 6. client-api
> 7. core
> 8. orm

Hi @Venkatvenstvm, these services require separate actions :

5. **jans-cli** is installed with the **package installation** you have used, but to run you have this guide (check Quick Start): https://github.com/JanssenProject/jans/tree/main/jans-cli#virtual-machine-setup

6. **client-api**  have a separate installation as I mentioned before: https://github.com/JanssenProject/jans/issues/1230#issuecomment-1104680303.

The others modules are installed and run with **package installation** you have used.

**Comment by Venkatvenstvm** [comment]
Thanks for you clarification
