### ISSUE TITLE
fix(jans-linux-setup): installation exit with built pyz package

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#1272]
**Describe the bug**

installer exists out with error

```
Proceed with these values [Y|n]
The following packages are required for Janssen Server
mysql-server
Do you want to install these now? [Y/n]
Installing packages mysql-server
FATAL: True
Traceback (most recent call last):
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/jans_setup.py", line 370, in do_installation
    jansAuthInstaller.start_installation()
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/setup_app/installers/base.py", line 51, in start_installation
    self.render_import_templates()
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/setup_app/installers/jans_auth.py", line 112, in render_import_templates
    self.role_scope_mappings()
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/setup_app/installers/jans_auth.py", line 97, in role_scope_mappings
    scope_list = self.get_config_api_scopes()
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/setup_app/installers/jans_auth.py", line 79, in get_config_api_scopes
    data = base.current_app.ConfigApiInstaller.read_config_api_swagger()
  File "/root/.shiv/jans-linux-setup.pyz_18edb9491e261cef13b29bd0df6c16171747b55148eaa52388a0c8bd80a5e6dc/site-packages/jans_setup/setup_app/installers/config_api.py", line 86, in read_config_api_swagger
    yml_str = yml_str.replace('\t', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**To Reproduce**
1. `git clone https://github.com/JanssenProject/jans`
2. `cd jans/jans-linux-setup`
3. `make zipapp`
4. `./jans-linux-setup.pyz` or `python3 jans-linux-setup.pyz`

**Expected behavior**

Completed installation

**Screenshots**

**Desktop (please complete the following information):**
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=20.04
  DISTRIB_CODENAME=focal
  DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

**Additional context**
<details>
  <summary>more!</summary>
Preparing jans-cli package
The following packages are required for Janssen Server
apache2 unzip python3-prompt-toolkit
Do you want to install these now? [Y/n] Y
Installing packages apache2 unzip python3-prompt-toolkit

Installing Janssen Server...

For more info see:
  /opt/jans/jans-setup/logs/setup.log
  /opt/jans/jans-setup/logs/setup_error.log

Profile         :  jans
Detected OS     :  ubuntu 20
Janssen Version :  1.0.0-jetty-SNAPSHOT
Detected init   :  systemd
Detected Apache :  2.4

Do you acknowledge that use of the Janssen Server is under the Apache-2.0 license? [N|y] : Y
Enter IP Address [172.31.40.26] :
Enter hostname [ip-172-31-40-26.eu-central-1.compute.internal] : 1.y.org
Enter your city or locality : Austin
Enter your state or province two letter code : TX
Enter two letter Country Code : US
Enter Organization Name : anssen
Enter email address for support at your organization : jans@ans.io
Enter maximum RAM for applications in MB [13260] :
Chose Backend Type:
  1 Local OpenDj
  2 Remote OpenDj
  3 Local MySQL
  4 Remote MySQL
  5 Remote Couchbase
  6 Cloud Spanner
Selection [1]: 3
Enter Password for Admin User [pr1TGB+XjXy9] : xxxxxxxxx#
Install Jans Auth Config Api? [Yes] :
Install Scim Server? [Yes] :
Install Fido2 Server? [Yes] :
Install Eleven Server? [No] :

hostname                                       1.testingluuk8.org
orgName                                                    anssen
os                                                         ubuntu
city                                                       Austin
state                                                          TX
countryCode                                                    US
Applications max ram (MB)                                   13260
Backends                                                    mysql
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Auth Config Api                                 True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Eleven Server                                       False

Proceed with these values [Y|n]
The following packages are required for Janssen Server
mysql-server
Do you want to install these now? [Y/n]
Installing packages mysql-server
</details>

[setup_error.log](https://github.com/JanssenProject/jans/files/8589422/setup_error.log)
[setup.log](https://github.com/JanssenProject/jans/files/8589423/setup.log)

**Comment by mbaser** [comment]
@moabu This issue will be fixed in refactored version.

**Comment by mbaser** [comment]
Fixed
