### ISSUE TITLE
`jans-cli` showing garbled error message

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1276]
**Describe the bug**
I am encountering garbled error message from `jans-cli` when trying to perform action for which user doesn't have scope.

**To Reproduce**
1. Fresh Janssen installation (MySQL backend)
2. Use jans config cli to get list of OIDC clients ( option 16 and then 1 )
3. Complete device flow and authenticate using default `admin` user
4. cli shows a message a shown below. 
5. Upon checking config API logs, it seemed that admin user doesn't have required scopes. 
6. But error on CLI should say the same. Or may be something logical.

![image](https://user-images.githubusercontent.com/343411/166192455-e06ddaf4-2454-4400-8908-654a2c871b90.png)

- Config API log error: 

```
01-05 23:02:15.156 ERROR [qtp1199673596-15] jans.configapi.filters.AuthorizationFilter AuthorizationFilter.java:95- ======AUTHORIZATION  FAILED ===========================================
jakarta.ws.rs.WebApplicationException: oAuth authorization error Insufficient scopes! , Required scope: [https://jans.io/oauth/config/openid/clients.readonly], however token scopes: [openid]
	at io.jans.configapi.security.service.OpenIdAuthorizationService.validateScope(OpenIdAuthorizationService.java:185) ~[classes/:?]
	at io.jans.configapi.security.service.OpenIdAuthorizationService.processAuthorization(OpenIdAuthorizationService.java:90) ~[classes/:?]


```

**Expected behavior**
Need to fix error message on jans-cli

**Comment by pujavs** [comment]
@mbaser request you to please chk this

**Comment by mbaser** [comment]
@pujavs CLI displays what it gets from server. If server returns "Insuffificent" scope rather than raising "Unauthorzed" response, CLI can display that message. Besides I were not be able to find any endpoint to check if jwt token is valid or not.

**Comment by mbaser** [comment]
This issue was fixed in refactored setup
![image](https://user-images.githubusercontent.com/6398752/166681133-fe658076-f7fe-4200-ac4f-340e842108ca.png)
