### ISSUE TITLE
fix: redesign Gluu xhtml webpages used in janssen

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#1302]
Upgrade/update all xhtml webpages such as the login pages used by different scripts to use a new enhanced design featuring the jans  branding instead of the Gluu branding.
janssen logos:
https://github.com/JanssenProject/jans/tree/main/docs/logo

disgard any `casa` xhtml files

search for all `xhtml` and `html`  [files ](https://github.com/JanssenProject/jans/find/main)

|page|designed|code written|Issue|
|-----|-----------|-------------|----|
| [404](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_404.html) | [x] | [x] |https://github.com/JanssenProject/jans/issues/1956|
| [500](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_500.html) | [x] | [x] |https://github.com/JanssenProject/jans/issues/1956|
| [502](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_502.html) | [x] | [x] |https://github.com/JanssenProject/jans/issues/1956|
| [503](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_503.html) | [x] | [x] |https://github.com/JanssenProject/jans/issues/1956|
| [504](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_504.html) | [x] | [x] |https://github.com/JanssenProject/jans/issues/1956|
| [agama](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/agama.xhtml) | [] | [] ||
| [error](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/error.xhtml) | [] | [] ||
| [login](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/login.xhtml) | [] | [] | #7202 |
| [Device auth](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/device_authorization.xhtml) | [] | [] | #7203 |
| [logout](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/logout.xhtml) | [] | [] ||
| [opiframe](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/opiframe.xhtml) | [] | [] ||
| [redirect](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/redirect.xhtml) | [] | [] ||
| [authorize](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/authorize.xhtml) | [] | [] ||
| [ciba](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/ciba/home.xhtml) | [] | [] ||
| [postlogin](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/postlogin.xhtml) | [] | [] ||
| [error_service](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/error_service.xhtml) | [] | [] ||
| [error_session](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/error_session.xhtml) | [] | [] ||
| [selectAccount](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/selectAccount.xhtml) | [] | [] ||
| [cert-login](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/auth/cert/login.xhtml) | [] | [] ||
| [otp-enroll](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/auth/otp/enroll.xhtml) | [] | [] ||
| [authz-authorize](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/authz/authorize.xhtml) | [] | [] ||

- [ ] #7835

**Comment by moabu** [comment]
![Jassen Sign In](https://user-images.githubusercontent.com/47318409/178486982-63e00f39-3d68-4a7f-9b6d-d60e7fde2941.jpg)
![Jassen Sign Up 1](https://user-images.githubusercontent.com/47318409/178486984-4db23724-104a-4476-9965-6da5e9f6a65a.jpg)
![Jassen Sign Up 2](https://user-images.githubusercontent.com/47318409/178486986-c90c0611-f7b4-4e43-af03-478fcc2037a8.jpg)
![Reset the password](https://user-images.githubusercontent.com/47318409/178486987-6932d510-eb61-4b61-bca0-8a510579ec0e.jpg)
![Forgot Password](https://user-images.githubusercontent.com/47318409/178486989-c2a83c59-b843-4ce8-8856-769ba64857dd.jpg)

**Comment by ossdhaval** [comment]
@moabu Page designs look great !! :+1:

**Comment by ossdhaval** [comment]
@moabu Just came across device authorization page. That also has Gluu branding. One more page to your list.

https://<jans-server>/device-code

**Comment by iromli** [comment]
@moabu we may need to update https://github.com/JanssenProject/jans/tree/main/jans-linux-setup/jans_setup/templates/apache/error_pages as well.

They are used in https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/https_jans.conf#L126-L130

**Comment by moabu** [comment]
yes all `html` and `xhtml` pages will be updated. The above designs are just to give a sense of the general theme.

**Comment by moabu** [comment]
![504](https://user-images.githubusercontent.com/47318409/181564392-7ba5af22-5436-4f26-8a9c-1b097c9eef8d.jpg)
![404](https://user-images.githubusercontent.com/47318409/181564399-76506c48-c491-4dd3-b4bb-1c8de9de8307.jpg)
![500](https://user-images.githubusercontent.com/47318409/181564401-11e04e73-9b42-49ab-bb08-e8e2e6d7a85c.jpg)
![502](https://user-images.githubusercontent.com/47318409/181564403-46957fcb-6591-4cf5-b54f-b548455fe766.jpg)
![503](https://user-images.githubusercontent.com/47318409/181564405-47143250-7488-4b49-ab8f-3d893a751abd.jpg)

**Comment by ossdhaval** [comment]
@moabu #6534 would be covered if we can take this issue to completion. 

Assuming the status in this issue's description is up-to-date, there are many pages to be worked on.

Let me know if I can chip in and take this forward.

**Comment by ossdhaval** [comment]
@kamalb25 We need your expertize in finishing what @moabu started. Specifically the designing of the remaining pages. 

@moabu has listed pages in the table above, but there can be more. Find out the instructions that he has noted:

```
disgard any casa xhtml files

search for all xhtml and html [files](https://github.com/JanssenProject/jans/find/main)
```

Once you are done, I'll take up the coding part.

**Comment by ossdhaval** [comment]
@moabu Now that the Casa is officially part of Janssen Server Project, should we be disregarding it's pages still?

**Comment by kamalb25** [comment]
Hi, I see there is a list of pages https://prnt.sc/Kk3A3lHzuhCx, among those some pages are already designed but need to update to new Gluu branding. If you can provide me the source files (PSD, Figma or XD files which is used to design this pages) that will be helpful otherwise I have to create all these pages from scratch.

For rest of the pages I need to know the flow or function of the website so that I can create new pages, also I need content for these pages (https://prnt.sc/LhFPxkavfHq6) to design properly. Once you provide me the content I can have a basic idea of the page layout structure, relevant graphics and icons to be used.

**Comment by ossdhaval** [comment]
@kamalb25 Just to be clear, we have to remove the Gluu branding and add Janssen branding on the similar lines as what @moabu  has done above.

> also I need content for these pages

I'll get you the content

> But I need design files (For e.x PSD, Figma or Adobe XD files) to make changes or rebranding.

@moabu, do you have these? :point_up:

**Comment by moabu** [comment]
Yes @ossdhaval . I will provide these files in chat.

**Comment by kamalb25** [comment]
@moabu
Hello,
here is the Sign In screens design link:
https://www.figma.com/file/Fu5fhvOmr2gpPFSbHZrElE/Janssen?type=design&node-id=1%3A2&mode=design&t=lzbrecnEcT9SRXuO-1

Please have a look and let me know your thoughts.
![Uploading Sign-In.jpg…]()

**Comment by ossdhaval** [comment]
@moabu 

@kamalb25 has created and shared [figma](https://www.figma.com/file/Fu5fhvOmr2gpPFSbHZrElE/Janssen?type=design&node-id=1%3A2&mode=design&t=lzbrecnEcT9SRXuO-1). Can you please review it and suggest changes if any. 

I could spot a few changes in the details(like the bird in the logo), but not sure if that is critical.

@kamal, can you update the two differences that I mentioned in the figma?

**Comment by moabu** [comment]
Looks good.

**Comment by kamalb25** [comment]
@moabu 

Here is the link of updated sign in page and device code page design.
https://www.figma.com/file/Fu5fhvOmr2gpPFSbHZrElE/Janssen?type=design&node-id=1%3A2&mode=design&t=7Vd0yALPPHK5hWXm-1

Please have a look and let me know your thoughts.
