### ISSUE TITLE
feat(jans-linux-setup): changes to deploy fido2-plugin jar 

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#1303]
jans-setup changes for fido2-plugin jar 

**Prerequisite**: if jans-fido2 module is being deployed
1) Copy fido2-plugin.jar 
Source:  https://maven.jans.io/maven/io/jans/jans-config-api/plugins/fido2-plugin/1.0.0-SNAPSHOT/fido2-plugin-1.0.0-SNAPSHOT-distribution.jar
Destination: /opt/jans/jetty/jans-config-api/custom/libs/fido2-plugin.jar
Note:  jar name in jetty folder should be `fido2-plugin.jar`

2) Append the path of the new plugin to extraClasspath element in/opt/jans/jetty/jans-config-api/webapps/jans-config-api.xml
Note the jars in this xml are comma separated
Example :
/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar, /opt/jans/jetty/jans-config-api/custom/libs/fido2-plugin.jar

3) Ensure  setup downloads all the artifacts for version 1.0.0-SNAPSHOT

**Comment by mbaser** [comment]
Implemented
