### ISSUE TITLE
jans-cli: `Optional fields` should be sorted or categorised so that options are easy to locate

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1349]
This refers to usability issue in jans-cli.

While using certain operations, like for example manually registering new OIDC client, jans-cli takes in few default params and then asks for optional parameters.

Issue one:
`Optional fields` list should be sorted or categorised so that options are easy to locate. As shown in image below,  `optional fields` presents a huge list of optional fields. If you are looking for a particular option, it is not easy to find. For example, if it was sorted in alphabetical order, it would be easy. Or may be categorised in some logical way. 

![image](https://user-images.githubusercontent.com/343411/161562217-ca4efad9-8364-4074-baaa-7c6d87633036.png)

Minor second issue:
 the `Populate optional fields?` doesn't have any suggestions for input.
![image](https://user-images.githubusercontent.com/343411/161561323-fefdf699-68a9-49e5-942b-cf106459d590.png)

_Originally posted by @ossdhaval in https://github.com/JanssenProject/jans/discussions/1158#discussioncomment-2500685_

**Comment by devrimyatar** [comment]
In commit, optional fields are sorted:
![image](https://user-images.githubusercontent.com/6398752/191491479-1cfac8cd-7663-401d-9388-ffd783c4c152.png)
