### ISSUE TITLE
jans-cli: Prompt for `scopes` optional parameter says `array of string separated by _,»` but the example is space separated

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1350]
How to reproduce:
1) install Janssen server
2) Invoke `jans-cli` from command line
3) select option to register new OpenID connect client
4) provide details for all mandatory parameters
5) say yes to providing optional parameters
6) select option to add value for scopes

Prompt for `scopes` optional parameter says `array of string separated by _,»` but the example is space separated

```
«Provide list of scopes granted to the client. Type: array of string separated by _,»
Example: read write dolphin
```

_Originally posted by @ossdhaval in https://github.com/JanssenProject/jans/discussions/1158#discussioncomment-2529385_

**Comment by devrimyatar** [comment]
![image](https://user-images.githubusercontent.com/6398752/191349552-1fc59b31-8b23-4375-8081-269b3b26e915.png)
