### ISSUE TITLE
Help message showing possible prompt responses at jans-cli prompt needs to be fixed

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1352]
**Describe the bug**

Case 1:

![image](https://user-images.githubusercontent.com/343411/168868655-3c6c013e-28d7-430f-9992-2bf472bedbf4.png)

Case 2

![image](https://user-images.githubusercontent.com/343411/168860953-c370e4fe-39d3-4825-b713-1fc83354217c.png)

In above images, help message in grey color has two issues.
1. Format: missing comma after second and third option
2. Missing options: As can be seen in the orange color help message, there are more options, like `w` for case 1 and `y` and `n` for case 2, that are not shown in the grey color help message. All possible options should be listed as part of grey message.

**To Reproduce**
Steps to reproduce the behavior (screenshot 1):
1. Install Janssen server
2. Invoke `config-cli` from command line
3. select option for `health-check` (for case 1) and select option `OAuth - OpenID Connect - Clients` (for case 2)

**Expected behavior**
- [ ] Formatting should be fixed
- [ ] All possible prompts response options should be shown in help messages

**Comment by devrimyatar** [comment]
Fixed

![image](https://user-images.githubusercontent.com/6398752/172150501-5b4bad7d-3ae4-453d-863e-a6b5a14efb8b.png)
