### ISSUE TITLE
fix (jans-config-api):  password encryption/decryption is not required at user-mgt-plugin

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1392]
I was testing `POST` method of `/jans-config-api/mgt/configuser`. 

We do not need password encryption in `user-mgt-plugin`. For example: https://github.com/JanssenProject/jans/blob/main/jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java#L125.

Reason: The password is hashed at jans-orm (https://github.com/JanssenProject/jans/blob/main/jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java#L188)

**Comment by pujavs** [comment]
This was implemented and code merged into main PR #[1393](https://github.com/JanssenProject/jans/pull/1393)
