### ISSUE TITLE
feat(agama): update setup to include agama

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1449]
To add [agama](https://github.com/JanssenProject/jans/tree/main/agama#agama) the folowing is needed:

1. Include Agama script (disabled by default)

```
dn: inum=BADA-BADA,ou=scripts,o=jans
objectClass: jansCustomScr
objectClass: top
description: Agama Script
displayName: agama
inum: BADA-BADA
jansConfProperty: {"value1":"cust_param_name","value2":"customParam1","hide":false,"description":""}
jansEnabled: false
jansLevel: 10
jansModuleProperty: {"value1":"usage_type","value2":"interactive","description":""}
jansModuleProperty: {"value1":"location_type","value2":"ldap","description": ""}
jansProgLng: python
jansRevision: 1
jansScrTyp: person_authentication
```

The source code (`jansScr` attribute) is already [here](https://github.com/JanssenProject/jans/raw/main/jans-linux-setup/jans_setup/static/extension/person_authentication/AgamaBridge.py)

2. Create agama tree (this is used to hold the definition of flows plus the state of flows currently running)

```
dn: ou=agama,o=jans
objectClass: organizationalUnit
objectClass: top
ou: agama

dn: ou=runs,ou=agama,o=jans
objectClass: organizationalUnit
objectClass: top
ou: runs

dn: ou=flows,ou=agama,o=jans
objectClass: organizationalUnit
objectClass: top
ou: flows
```

3. Setup agama folder

Under `/opt/jans/jetty/jans-auth` create the following directory structure:

```
agama
  +-- fl
  +-- ftl
  +-- scripts
```

So by now, there will be 3 empty subdirectories. Also transfer to `agama` directory these [files](https://github.com/JanssenProject/jans/tree/main/agama/misc). Feel free to move them to a place you consider appropriate. They will rarely change

4. Copy xml descriptor

[This](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jetty/agama_web_resources.xml) file should go under `/opt/jans/jetty/jans-auth/webapps`

**Comment by devrimyatar** [comment]
Implemented
