### ISSUE TITLE
fix(jans-cli): getting error when accessing client using inum 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1450]
**Describe the bug**
getting error while accessing openid client using inum

**To Reproduce**
1. open jans_cli client 
2. select 8  option for aouth
3. add 1 for openid 
4. select 4 option to get

**Expected behavior**
should get openid client details

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/170422801-1435360f-2470-475e-a9da-0997e928d970.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version :20.04

**Additional context**
[error.log](https://github.com/JanssenProject/jans/files/8776508/error.log)

**Comment by gluuer** [comment]
Can't replicate

![image](https://user-images.githubusercontent.com/6398752/171152883-4252b5f5-91f0-4170-9b99-bae7ca5dd7b3.png)
