### ISSUE TITLE
fix(jans-cli): getting error while updatig openid client using inum

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1451]
Describe the bug
getting error while accessing openid client using inum

To Reproduce

1. open jans_cli client
2. select 8 option for aouth
3. select 1 for openid
4. select 6 option to get "Update modified properties of OpenId Connect client by Inum"
5. add inum
6. select operation and add path ,value
check error 

**Expected behavior**
should not get error and get modified open client id value.

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/170429945-59fe0d98-0d33-41fd-bf85-acaec5fd1f71.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs 

Please see config-api logs

```
10-06 13:38:41.222 INFO  jans.configapi.filters.LoggingFilter LoggingFilter.java:33- ****Request PATCH /openid/clients/ce5e4043-fa92-4dbb-84e2-405298631e23 from IP 10.146.197.158
2022-06-10 13:38:41.357:WARN :oejs.HttpChannel:qtp762476028-19: handleException /jans-config-api/api/v1/openid/clients/ce5e4043-fa92-4dbb-84e2-405298631e23 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)| at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.jans.as.common.model.registration.Client["clientName"])
```

**Comment by pujavs** [comment]
- Error screenshot:
![image](https://user-images.githubusercontent.com/43700552/195662151-abda44e5-a197-4300-af15-b3e6376ec66a.png)

- Assigning to @qbert2k as It is LocalizedString issue which is being looked into by @qbert2k

**Comment by devrimyatar** [comment]
Not persist in TUI and CLI command line args
