### ISSUE TITLE
fix(jans-cli): SCIM option in jans_cli not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1452]
**Describe the bug**
SCIM option in jans_cli not working

**To Reproduce**
install Janssen server
Invoke jans-cli from command line
select option 12 to check SCIM
select 1 for configuration mgmt
select 1 for  "Retrieves SCIM App configuration"

**Expected behavior**
should show all scim app configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/170442578-2ef3c55b-3897-4bce-80da-6860cf0678a6.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Additional context**

**Comment by gluuer** [comment]
Can't reproduce 
![image](https://user-images.githubusercontent.com/6398752/171159395-7a8dec44-71f6-4f13-9b2a-6b092a106352.png)

**Comment by devrimyatar** [comment]
Tested again

![image](https://user-images.githubusercontent.com/6398752/191339215-0c9c8f76-4528-4a8f-af5e-8ecf614e735d.png)
