### ISSUE TITLE
fix(jans-cli): admin Role in jans_cli is not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1453]
**Describe the bug**
getting  below error while accessing or addAdmin Role in jans_cli 

**To Reproduce**

install Janssen server
Invoke jans-cli from command line
select option 15to check Admin UI
select 1 for Adminrole
select 1 or 2 for Get all admin ui roles or add new role

**Expected behavior**
itshould  provide all role present

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/170443536-e2ea0c59-05d0-4141-a92c-0450622da5d8.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate


https://user-images.githubusercontent.com/6398752/172107521-cea247c1-780f-45e5-8426-ccf5a61a3f50.mp4

**Comment by devrimyatar** [comment]
This works only if admin-ui plugin is available. Now CLI ignores if plugin is not available:

https://github.com/JanssenProject/jans/pull/1478/commits/8f8c6b2a04bdae877707316a6e9ef17612777df1
