### ISSUE TITLE
fix(sonar): code analysis not executing correctly

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#1454]
**Describe the bug**
Thw workflow associated with the sonar code analysis should run based on the files touched ( folders). It seems like it is building all modules for every PR. 

Example:
Here fido2 and config-api  are failling even though both aren't touched.
https://github.com/JanssenProject/jans/pull/1447

**Comment by ossdhaval** [comment]
Probably this issue doesn't exist anymore, but we are still doubtful about correct workflow execution. @moabu will confirm that and close this issue.
