### ISSUE TITLE
feat(jans-linux-setup):Include the jans-client-api in installer

### ISSUE THREAD

**Issue by jmunozherbas** [JanssenProject/jans#1490]
Include the jans-client-api in the installer.
Branch: https://github.com/JanssenProject/jans/tree/jans-client-api-issue-260
Installation, Compile and Run instructions: https://github.com/JanssenProject/jans/blob/jans-client-api-issue-260/jans-client-api/README.md

**Comment by devrimyatar** [comment]
Done
