### ISSUE TITLE
feat(jans-config-api): include agama config in the configuration service

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1493]
There is a new section in the AS configuration: https://github.com/JanssenProject/jans/blob/main/jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java#L319

Bean here: https://github.com/JanssenProject/jans/blob/main/agama/model/src/main/java/io/jans/agama/model/EngineConfig.java

There are no mandatory fields in the configuration. All optional.

Validations:
- `maxItemsLoggedInCollections`  greater than zero

**Comment by pujavs** [comment]
changes implemented related PR [1501](https://github.com/JanssenProject/jans/pull/1501)

**Comment by pujavs** [comment]
@jgomer2001, changes have been merged with main, please validate
