### ISSUE TITLE
feat(jans-auth-server): resolve cycle dependency fido2 <-> jans-auth-server (impacts release process)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1499]
### Description

During last release we run into cycle dependency between fido2 and jans-auth-server. We should avoid it.

**Comment by jgomer2001** [comment]
I'm reopening so we don't lose from sight that  fido2 authn is not working when using the fido2 script due to this fix.

**Comment by yuriyz** [comment]
@jgomer2001 if add `jans-fido2-client` via custom libs, will it work or it needs some cross-dependencies? During release process with @moabu we found out that we have cycle dependency between fido2 and jans-auth. It leads to nighmare during re-build with flipped version. It would be great to get rid of it.

**Comment by jgomer2001** [comment]
I think custom libs should be fine. I created issue https://github.com/GluuFederation/flex/issues/263
