### ISSUE TITLE
feat(jans-config-api): endpoints for agama flows

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1509]
Create a service for agama flows CRUD. Reference bean [here](https://github.com/JanssenProject/jans/blob/main/agama/model/src/main/java/io/jans/agama/model/Flow.java) 

For creation:
- Only `QName` and `source` are required
- With the exception of `enabled`, if any other property is supplied, the operation should be rejected  (http 400 maybe)
- Set `jansRevision` to `-1` by default in the DB.

For retrieval, all attributes should be retrieved. The retrieval must be done by `QName` (it's the flow identifier)

For update (also by `QName`), only the following attributes should be effectively updated (if present):
- revision
- enabled
- source
- metadata.{displayName, author, description, properties}

If the payload comes with any other attribute, we should reject (http 400 maybe)

**Comment by jgomer2001** [comment]
Additional notes:

For updates: if `source` is present and `revision` is absent, the `revision` in the DB should be  incremented by 1. This allows recompilation of the source to take place in the background.

I'm thinking that passing the `source` in both creation and update is not very friendly because it has to be json-escaped previously, e.g. `{ "QName": "test", "source" : "Flow test\n    Basepath \"hello\" \n\nin = { name: \"John\" }\nRRF ... VERY  LARGE STUFF HERE ...`. This fits well when the admin-ui consumes the service, ie. the app creates the payload based on UI elements filled by the user, but not when a developer hits the endpoints directly, say by curl/postman.

I kindly request you to add a couple of extra endpoints:

Flow creation so the `QName` is passed in the URL itself and the payload contains the value of `source`. Here `enabled` should be set to true by default.

This way is easy to consume using curl, like this: `curl -H 'Authorization: Bearer ...access token...' 
  -d @flow.txt https://<host-name>/.../flows/add/QName_here` (`flow.txt` file has the source contents)

Flow update. As in the previous case, the `QName` is part of the URL and the only attribute to update is `source` that goes in the payload.

**Comment by jgomer2001** [comment]
Another request I had forgotten, sorry:

Add an endpoint to retrieve basic data of all flows at once (GET). It should retrieve a list of flows with the following:

- QName
- enabled
- metadata
- codeError

**Comment by pujavs** [comment]
> flow.txt

@jgomer2001, do you have a sample flow.txt that you can share.

**Comment by jgomer2001** [comment]
Here: https://github.com/JanssenProject/jans/blob/main/docs/admin/developer/agama/test

**Comment by pujavs** [comment]
> Here: https://github.com/JanssenProject/jans/blob/main/docs/admin/developer/agama/test

@jgomer2001 shouldn't the flow.txt contain `Qname` and `source` i do not see these in [test file](https://github.com/JanssenProject/jans/blob/main/docs/admin/developer/agama/test)https://github.com/JanssenProject/jans/blob/main/docs/admin/developer/agama/test

**Comment by pujavs** [comment]
@jgomer2001, I have implemented the agama endpoint.
**Implementation Details:**

1) /jans-config-api/api/v1/agama
     GET - Fetches all the flow
     POST - Create a new flow

2) /jans-config-api/api/v1/agama/{qname}
     GET - Fetch flow based on qname
     POST - Create a flow with request payload reading source file
     PUT - Updates a flow based on qname
    DELETE - Deletes a flow

**Testing evidence**
Manual test evidence: [Agama_endpoint_test_issue#1509.xlsx](https://github.com/JanssenProject/jans/files/9190167/Agama_endpoint_test_issue.1509.xlsx)

**Karate test case evidence:**
[src.test.resources.feature.agama.agama.pdf](https://github.com/JanssenProject/jans/files/9190187/src.test.resources.feature.agama.agama.pdf)

**Note:** As communicated Java bean has a field name QName is not working and in the dev branch agama code base i have renamed the field to qname.
**Branch:** https://github.com/JanssenProject/jans/tree/jans-config-api-1509-new
**Please advice if the code needs to be merged with main along with agama change**

**Comment by pujavs** [comment]
as confirmed by @jgomer2001 raised PR [1898](https://github.com/JanssenProject/jans/pull/1898) for the changes including agama service changes for `qname`
