### ISSUE TITLE
jansStatus attribute is not in list still getting error 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1517]
**Describe the bug**
jansStatus attribute is not in list still getting error "attribute jansStatus is required"

**To Reproduce**
install jans server
open jan-cli.py
goto 4th option
then go to 5 th option ie user managment
select 2 to create new user
add all details 

**Expected behavior**
user should be create with details

**Screenshots**
![Screenshot from 2022-06-07 16-39-41](https://user-images.githubusercontent.com/5729240/172378370-9a4f8755-f0b3-425e-80b3-c91596452b2d.png)

**Desktop (please complete the following information):**
  - OS: Ubuntu 20.04
  - Browse
  - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
Fixed this with PR [1519](https://github.com/JanssenProject/jans/pull/1519)

**Comment by devrimyatar** [comment]
User is created, but when we receive users, the following error raises

```
Please wait while posting data ...

Error retreiving data

Invalid value for `user_password`, must not be `None`

b: back, q: quit, x: logout and quit

```

This issue is mentioned at https://github.com/JanssenProject/jans/issues/418#issuecomment-1149713951
