### ISSUE TITLE
FEAT: Backchannel Authentication Scripts

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1528]
Much desired by the community is a way to enable domains to render the username/pw login form, avoiding the redirect to the IDP-hosted login page. Many SSO solutions offer a proprietary endpoint to accomplish this. However, I think this can be accomplished with the OAuth/OpenID framework by using a combination of calling the `/token` endpoint using the OAuth password flow, and then redirecting to browser to the `/authorization` endpoint, but auto-submitting the form. 

Ideally, there would be no code change needed to Jans Auth Server--this solution would just consist of two scripts (ROPW and Person Authn).

![BF Authn API Sequence Diagram](https://user-images.githubusercontent.com/3717101/172693034-80b65d4a-b1bb-4011-abc9-681336fc686b.png)

```
Title password Grant with State

Person->Browser: Navigate to website
Browser->Website:
Website->Browser:Display login page
Person->Browser: Enter Username / PW
Browser->Website: (creds)
Website->IDP: /token?uid=_&pw=&browser_ip=_
IDP->Website: {"redirect": "/authz/state=1F2D41A", ...}
Website->Browser:
Browser->IDP: /authz?state=1F2D41A
IDP->IDP: check IP address is\n same as state
IDP->Browser: write cookie / send redirect_uri
Browser->Website: redirect_uri
```

**Comment by Milton-Ch** [comment]
I'm working on this solution, so far I added the initial approach, work in progress.
https://github.com/JanssenProject/jans/wiki/Backchannel-authentication-scripts

**Comment by Milton-Ch** [comment]
Just updated that wiki page with the final solution, please take a look.

**Comment by Milton-Ch** [comment]
Closing this ticket cause solution is already published.
