### ISSUE TITLE
unable to instll jans using install.py

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1547]
**Describe the bug**
unable to install jans using install.py

**To Reproduce**

curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py
python3 install.py

**Expected behavior**
should install jans without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/173288073-0e53fc55-5f35-495d-b7e3-988a54506348.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser:
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate. May be it is temporary or issue with your network.

![Screenshot_2022-06-13_11-04-11](https://user-images.githubusercontent.com/6398752/173308030-ad63bb9f-139d-46b4-b899-fc2b3b310494.png)

**Comment by manojs1978** [comment]
this was VM issue
