### ISSUE TITLE
feat (jans-auth-server) : need api to provide how long each transaction on auth-server taking(admin-ui request)

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1579]
**Is your feature request related to a problem? Please describe.**
On admin-ui, we need to show how long each transaction to/from auth server is taking.

**Describe the solution you'd like**
Jans auth server can provide an endpoint to provide transaction details in the response.

**Comment by Milton-Ch** [comment]
What represents a "transaction"? is this since the first `/authorize` request AS receives until a final response AS returns? or what is the idea about this time interval that you are talking?

**Comment by duttarnab** [comment]
This feature request has been raised on the basis of the suggestions made for the data to be displayed on admin-ui (see Image). I am also not sure about the details expected to be shown, so raised this feat can be discussed and doubts are resolved.

@nynymike @mo-auto could you please answer the questions asked by @Milton-Ch .

![image](https://user-images.githubusercontent.com/32794267/175990523-0b53ef52-b2c4-4eb9-9899-f8e7621cd25b.png)

**Comment by nynymike** [comment]
This issue is too vague. There are many transactions in the Gluu Server. And I'm not sure that adding tracing into something like the code flow would be worth the potential performance impact.
