### ISSUE TITLE
Only log file YYYY_MM_DD.jetty.log is generated when fido2 client lib is added

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#1603]
**Describe the bug**
When we add fido2 client lib to jans-auth as described in https://github.com/GluuFederation/flex/issues/263 , only log file file YYYY_MM_DD.jetty.log is generated.

**To Reproduce**

1. Install jans server
2. Download https://maven.jans.io/maven/io/jans/jans-fido2-client/1.0.1-SNAPSHOT/jans-fido2-client-1.0.1-SNAPSHOT.jar to `/opt/jans/jetty/jans-auth/custom/libs/jans-fido2-client.jar`
3. Add path `/opt/jans/jetty/jans-auth/custom/libs/jans-fido2-client.jar`  to **extraClasspath** in `/opt/jans/jetty/jans-auth/webapps/jans-auth.xml`
4. Stop jans-auth and remove log files
5. Start jans-auth

**Expected behavior**
All log files should be created, but only YYYY_MM_DD.jetty.log is created

**Comment by pujavs** [comment]
@yurem fixed this by excluding log4j file from client jar to fix the conflict of log4j files
**PR:** [3636](https://github.com/JanssenProject/jans/pull/3636)
