### ISSUE TITLE
unable to install jans using properties file

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1612]
**Describe the bug**
we have created setup.properties file 
and tried to install jans using properties file but it is failing with below error

**To Reproduce**
1. create setup.properties file
2. run command 
python3 install.py --args="-f setup.properties -c -n"

4. getting error

FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 382, in do_installation
    jansAuthInstaller.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 29, in start_installation
    self.dbUtils.bind()
  File "/opt/jans/jans-setup/setup_app/utils/db_utils.py", line 80, in bind
    self.ldap_conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 521, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 145, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(datetime.datetime(2022, 6, 26, 8, 8, 30, 533734), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('::1', 1636, 0, 0)), (datetime.datetime(2022, 6, 26, 8, 8, 30, 534019), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('127.0.0.1', 1636))])

**Expected behavior**
installation should be successful with setup.properties file

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/175805682-29e8fae0-5cda-4e8a-9707-de7e09fa4e6f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser :
  - Version:

**Additional context**
setup properties file content is like below

ip=104.248.203.59
hostname=gluubuntu
orgName=glu
admin_email=manojsurya78@gmail.com
city=pune
state=MH
countryCode=IN
ldapPass=pass@123

**Comment by devrimyatar** [comment]
Fixed
