### ISSUE TITLE
docs(agama): make docs conform to structure

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1617]
About commit https://github.com/JanssenProject/jans/pull/1608/commits/b73fb10a655bbf9439bb35fe57f8114566fed207

- It is not clear how to make these contents fit in the new Janssen docs outline. I am requesting someone to make this conform if necessary
- It was pushed because I need other team members to get access to this content ASAP
- So far the content is designed to make readers start at index.md and then follow the links in a natural way
- The structure is flat (all md files in the same top level)
- Beware there are lot of cross references in pages, links will be broken if files are not in the same directory

Additionally, some proofreading is welcome. My text editor does not know English :)

Also “Agama” should be capitalized

**Comment by shmorri** [comment]
This is now in its final home, with proofreading incoming.
