### ISSUE TITLE
test(jans-client-api):fix jenkins job jans-client-api loading test.properties

### ISSUE THREAD

**Issue by jmunozherbas** [JanssenProject/jans#1629]
### What is failing?
Fullrebuild -> jans-client-api Jenkins job is not working.

### Where is it failing?
https://jenkins.jans.io/jenkins/job/jans-client-api/60/console

### Relevent logs
https://jenkins.jans.io/jenkins/job/jans-client-api/60/console

### Possible root cause
unused file is filtered

**Comment by yuriyz** [comment]
@jmunozherbas I guess build is good now. Can we close it?

**Comment by jmunozherbas** [comment]
Right, is ready to close
