### ISSUE TITLE
unable to authenticate using admin  username and passwd

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1631]
**Describe the bug**
unable to authenticate using admin  username and passwd

**To Reproduce**
1. download install.py 
2. install jans 
3. after open config_cli.py
4. click on device-code
5. add 4-4 char code on UI side and submit
6. add admin username and passwd (which is set at the time of installation)
7. 
**Expected behavior**
should able to authenticate admin and give permissions

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/176357773-5907b898-6a7e-494c-ad71-4a3d64816990.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Browser chrome
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**
[error.zip](https://github.com/JanssenProject/jans/files/9007579/error.zip)

**Comment by devrimyatar** [comment]
It is due to scirpt F**orgot_Password_2FA_Token** (inum=B270-381E), when this script is disabled, it works

**Comment by devrimyatar** [comment]
This isssue is related to https://github.com/JanssenProject/jans/issues/1601

**Comment by manojs1978** [comment]
issue is fixed
