### ISSUE TITLE
Jans setup.py error in SUSE .rpm

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1654]
I tried installing the latest release on SUSE Leap `jans-1.0.0-suse15.x86_64.rpm`, but I get the following error when running setup:

![image](https://user-images.githubusercontent.com/3717101/177016308-32c4ee83-edba-4fc1-8a37-27dd7d355b58.png)

```
# cat  /etc/os-release

NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
```

**Comment by devrimyatar** [comment]
We are not using gsc anymore, hence not proper
