### ISSUE TITLE
BUG: Jans CLI error.log file permission error

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1655]
I installed the server as `root`. I copied `.config/jans-cli.ini` to my local user, but when I try to run the CLI, I get the following error: 

```
Traceback (most recent call last):
  File "./config-cli.py", line 2271, in <module>
    main()
  File "./config-cli.py", line 2265, in main
    with open(error_log_file, 'a') as w:
PermissionError: [Errno 13] Permission denied: '/opt/jans/jans-cli/error.log'
```

Shouldn't I be able to put the error log location in my `.ini` ?

**Comment by devrimyatar** [comment]
@yes it should be configurable. I will do on refactored version https://github.com/JanssenProject/jans/tree/jans-cli-no-swagger-client
