### ISSUE TITLE
BUG: CLI does not return list of custom scripts

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1656]
When I navigate:
* 6 Custom Scripts
* 1 Gets a list of custom scripts

I get this error message:

![image](https://user-images.githubusercontent.com/3717101/177058535-bba6e4f2-6b13-4626-b55f-1b25c8223b8e.png)

**Comment by devrimyatar** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/6398752/177207131-7dd663a5-ceed-404f-8361-bba00a4808f7.png)
