### ISSUE TITLE
Bug:  No way to escape from config-cli.py prompt

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1657]
You should be able to "escape" from something. For example, if I try to update a script, it asks for `inum`... but what if I don't know it. There is no way to get out... I had to ctrl-c

For example:

* 6 Custom Scripts
* 3 Updates a custom script

```
«inum. Type: string»
inum:

```

How do I get back?

**Comment by devrimyatar** [comment]
@nynymike In commit https://github.com/JanssenProject/jans/commit/d501b21c999e635ef0fad04a0d2676ed2c354d98, I implemented escaping prompt, enter `_b` any time to return to back.
