### ISSUE TITLE
FEAT: CLI: Improve Interactive OpenID Connect Client Creation 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1658]
When you create an OpenID Connect client, there is actually only one required field: `redirect_uri`

The default for `client_type` should be `web`

The default for include_claims_in_id_token should be `false`

The most common parameters for an OpenID Connect client are 
* grant_type
* response_type
* scopes
* Display name

It would also be nice to group all the encryption options... people normally accept the defaults. In fact, it may make sense to group other claims too into logical groups.

**Comment by maduvena** [comment]
A separate mention should be included of the following case - When the client creation request is an encoded JWT
