### ISSUE TITLE
fix(jans-auth-server): google login button not loading

### ISSUE THREAD

**Issue by kdhttps** [JanssenProject/jans#1663]
**Describe the bug**
I found a bug in [Social-Login-with-Google](https://github.com/JanssenProject/jans/wiki/Social-Login-with-Google). After auth request on the login page is not showing the `Login with Google` button.

**To Reproduce**
1. Configure Google Jans auth using [Social-Login-with-Google](https://github.com/JanssenProject/jans/wiki/Social-Login-with-Google) guide
2. Initiate a request from your RP app with `acr_values=google` 
3. After the login page loads, there is no option or google login button for login with google

**Expected behavior**
The login page should show the `Login with Google` button.

**Screenshots**
![login-page-without-google-login-button](https://user-images.githubusercontent.com/39133739/177133846-f4146adb-e465-4efb-b031-6f3468083e48.png)

**Desktop (please complete the following information):**
  - OS: Ubuntu 20
  - Browser: chrome, safari

**Additional context**

We need to add the [latest Google API JS](https://developers.google.com/identity/gsi/web/guides/client-library) at [.../google/login.xhtml](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/webapp/auth/google/login.xhtml). I have a solution available, please assign an issue to me. I will make a PR

**Comment by ossdhaval** [comment]
Hi @kdhttps, since this issue has been open for a long time, can you check if this is still relevant and need to be fixed?

**Comment by kdhttps** [comment]
it fixed. closing, thanks @ossdhaval!
