### ISSUE TITLE
feat: create pipeline job which can cleanly re-compile all projects with new version (new release)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1723]
feat: create pipeline job which can cleanly re-compile all projects with new version (new release)

AS failed due to agama
```
[ERROR] Failed to execute goal on project jans-auth-model: Could not resolve dependencies for project io.jans:jans-auth-model:jar:1.0.1: Failed to collect dependencies at io.jans:agama-model:jar:1.0.1: Failed to read artifact descriptor for io.jans:agama-model:jar:1.0.1: Could not transfer artifact io.jans:agama-model:pom:1.0.1 from/to bouncycastle 
```

Agama fails due to missed jans-auth-model
```
[ERROR] Failed to execute goal on project agama-engine: Could not resolve dependencies for project io.jans:agama-engine:jar:1.0.1: Could not find artifact io.jans:jans-auth-model:jar:1.0.1 in jans (https://maven.jans.io/maven) -> [Help 1]
```

**Comment by yuriyz** [comment]
We got another cycle dependency between agama and jans-auth-model. We had similar issue between fido and jans. We have to refactor code and extract common code out of AS.

**Comment by yuriyz** [comment]
There are also problems between jans-client-api and jans-config-api. We have cross-dependency here as well.
@jmunozherbas why do we rely on `jans-config-api` in jans-client-api ?

**Comment by jmunozherbas** [comment]
> There are also problems between jans-client-api and jans-config-api. We have cross-dependency here as well. @jmunozherbas why do we rely on `jans-config-api` in jans-client-api ?

I could remove `jans-config-api` dependency from `jans-client-api`.
It was used in previous version, but now could be removed.

**Comment by yuriyz** [comment]
@jmunozherbas please remove

**Comment by yuriyz** [comment]
Dependency issues during build/release were resolved. Closing this ticket.
