### ISSUE TITLE
unable to get openID client list

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1740]
**Describe the bug**
unable to list openID client list
error:

Gets list of OpenID Connect clients
-----------------------------------

«Search size - max size of the results to return. Type: integer»
limit  [50]:                                                                                                                                    

«Search pattern. Type: string»
pattern:                                                                                                                                        

«The 1-based index of the first query result. Type: integer»
startIndex  [1]:                                                                                                                                

«Attribute whose value will be used to order the returned response. Type: string»
sortBy  [inum]:                                                                                                                                 

«Order in which the sortBy param is applied. Allowed values are "ascending" and "descending". Type: string, Valid values: ascending, descending»
sortOrder  [ascending]:                                                                                                                         
Calling Api with parameters: {'limit': 50, 'start_index': 1, 'sort_by': 'inum', 'sort_order': 'ascending'}
Please wait while retreiving data ...

Error retreiving data

Invalid value for `redirect_uris`, must not be `None`

b: back, q: quit, x: logout and quit

Selection:  

**To Reproduce**
1. run /opt/jans/jans-cli/config-cli.py
2. select 8 for Oauth
3. select 1 for openid connect - clients
4. 1 to get list
5 select limit, pattern, start index ,sortby , sortorder with default value

**Expected behavior**
should show list of open id clients

**Screenshots**
![Screenshot from 2022-07-08 17-12-48](https://user-images.githubusercontent.com/5729240/177985879-3daa1044-b268-43b1-ac03-b36fdea63f6f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed in https://github.com/JanssenProject/jans/pull/1730
