### ISSUE TITLE
jans-cli :unable to create UMA resource with given mendatory properties

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1752]
**Describe the bug**
jans-cli :unable to create UMA resource with given mendatory properties
getting attached error

**To Reproduce**
1. install jans
2. open jans-cli
3. select 8 for OAuth
4. select 2 for UMA
5. select 2 to create new UMA resource
6. add mendatory properties
as below:
![image](https://user-images.githubusercontent.com/5729240/178211479-ad87731d-75fa-402b-ac3a-2061ad3cda5d.png)

**Expected behavior**
should able create UMA resource with given mendatory properties

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178211584-c20bacaa-fa8b-4a69-8a21-e21a6d91e51d.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**UMA resource name and description are mendatory properties without that cant create UMA resource**

**Comment by devrimyatar** [comment]
@pujavs 
**name** and **description** are should be required, as error given by jans-config-api

**Comment by devrimyatar** [comment]
If name and description is provided, it creates
![image](https://user-images.githubusercontent.com/6398752/178565778-fd8b650b-81bc-4a59-9718-4017a1cbd81e.png)

**Comment by pujavs** [comment]
@devrimyatar @manojs1978 , fixed Mandatory fields via https://github.com/JanssenProject/jans/pull/1805

![image](https://user-images.githubusercontent.com/43700552/179271924-73f4bfb0-982b-4709-97da-1571134783da.png)

**Comment by pujavs** [comment]
Assigning it to @manojs1978 to test the fix

**Comment by moabu** [comment]
Hey @manojs1978,

So you have a  status update on this ?

**Comment by manojs1978** [comment]
Hi @moabu ,
i ll check with latest build and update this ticket

**Comment by manojs1978** [comment]
verified on latest build
i was not able to reach to that step ,getting below error when added description .
@pujavs 
![image](https://user-images.githubusercontent.com/5729240/181159592-7fcb5b36-c0ec-47f3-bdf8-ca8be12cfdb6.png)

**Comment by pujavs** [comment]
I had tested this earlier as well and communicated via DM that am not able to replicate. I have retested again today. and still not able to replicate. Request you to please see attached video and confirm if you are still facing issue. 
Note i have tested on LDAP setup.[Uma_Resource_Creation_09Sep2022.zip]n(https://github.com/JanssenProject/jans/files/9536782/Uma_Resource_Creation_09Sep2022.zip)

**Comment by manojs1978** [comment]
ok
checking

**Comment by manojs1978** [comment]
issue is not reproducible in latest build
![1752_latestbuild](https://user-images.githubusercontent.com/5729240/189680861-e01f4940-daeb-4d30-87b3-4819246019eb.png)


actually i have retested long back in july month but now its working fine with latest build.

thank you.
