### ISSUE TITLE
unable to udated UMA resource

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1753]
**Describe the bug**

**To Reproduce**
 install jans
open jans-cli
select 8 for OAuth
select 2 for UMA
select 6 to update  UMA resource

**Expected behavior**
shoulde able udated UMA resource

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178214169-bb271e20-70db-4f82-8ecc-14e03b1338a7.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs see error log
```
12-07 18:30:57.777 INFO  jans.configapi.filters.LoggingFilter LoggingFilter.java:33- ****Request PATCH /uma/resources/b2b33dde-6dc7-49e3-b600-15c7001392a1 from IP 10.146.197.201
2022-07-12 18:30:57.785:WARN :oejs.HttpChannel:qtp1793436274-17: handleException /jans-config-api/api/v1/uma/resources/b2b33dde-6dc7-49e3-b600-15c7001392a1 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('["1201.c510dedb-2496-468c-b053-340d6131d07d"]')| at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.jans.as.model.uma.persistence.UmaResource["clients"])
```

**Comment by pujavs** [comment]
@devrimyatar, i tested this and the endpoint is working fine when invoking via rest http request. 

Seems a generic problem with jans-cli where in ArrayList attribute patch is not working. I tested both UMA Resource with `clients` property and UMA Scope with `umaAuthorizationPolicies` property. Both these properties are ArrayList and not working via jans-cli PATCH.
I tried all permutations to pass ArrayList but it's failing. Request you to please check and revert.

**1. UMA Resource PATCH Testing**
`1.1. Http request - Working`
![image](https://user-images.githubusercontent.com/43700552/179237357-546e4500-a546-40c4-be77-b49158b8e932.png)

`1.2. jans-cli - Error`
![image](https://user-images.githubusercontent.com/43700552/179239222-23bf79af-318c-4745-a138-01d32dc4ff44.png)
![image](https://user-images.githubusercontent.com/43700552/179239447-773c76b0-33be-484f-aba8-f4646db928d5.png)
![image](https://user-images.githubusercontent.com/43700552/179239644-67ea3fcf-f9cc-4c81-b681-04289a7575b3.png)
![image](https://user-images.githubusercontent.com/43700552/179240010-44b9395c-d74e-4112-a3be-b1bf0c14da82.png)


**2. Scope  PATCH Testing**
`2.1. Http request - Working`
![image](https://user-images.githubusercontent.com/43700552/179238625-9bd0c5d2-c2e4-4aae-820f-cb671edf217e.png)

`2.2. jans-cli - Error`
![image](https://user-images.githubusercontent.com/43700552/179237766-f7c733ee-1b9c-497a-8a2f-ebb7a4df967e.png)

**Comment by pujavs** [comment]
Assigning it to @devrimyatar for handling ArrayList in PATCH request

**Comment by devrimyatar** [comment]
Fixed in commit https://github.com/JanssenProject/jans/pull/2429/commits/71067cdbed06fa5c481c843ad9eb883130cfe693

![image](https://user-images.githubusercontent.com/6398752/191575711-d848928c-9562-4976-84a5-c8d8e30d1b65.png)

**Comment by devrimyatar** [comment]
List values should be seperated by `_,` as usual
