### ISSUE TITLE
feat(jans-config-api): Search custom script by name

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#1754]
### Description

- Development target issue
Develop `get-config-script-by-name` on the same lines as [this](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans-config-api/master/docs/jans-config-api-swagger.yaml#/operations/Custom%20Scripts/get-config-scripts-by-inum)
<br/> This feature is more likely to be used than get-by-inum
- Implementation Details
on the same lines as [this](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans-config-api/master/docs/jans-config-api-swagger.yaml#/operations/Custom%20Scripts/get-config-scripts-by-inum)
Note: script name is a unique field

-------------------

### Document the changes

- [ ] Update developer documentation

**Comment by pujavs** [comment]
@maduvena , this has been implemented in https://github.com/JanssenProject/jans/pull/1802
**Implemented:** GET /jans-config-api/api/v1/config/scripts/name/{name}

**Example:** GET /config/scripts/name/resource_owner_password_credentials_example

**Testing:**
![image](https://user-images.githubusercontent.com/43700552/179016689-fae5c5fa-7e36-4fe3-bba3-37672fbadb95.png)

**Comment by pujavs** [comment]
Closing this issue as the feature as been implemented
