### ISSUE TITLE
unable to launch jans-cli on centOS8

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1755]
**Describe the bug**

**To Reproduce**
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum module enable mod_auth_openidc
yum install curl
yum install -y https:$(curl -s -L https://api.github.com/repos/JanssenProject/jans/releases/latest | egrep -o '/.*el8.x86_64.rpm' | head -n 1)
sudo python3 /opt/jans/jans-setup/setup.py
/opt/jans/jans-cli/config-cli.py.

**Expected behavior**
should able to launch jans-cli on 

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178230298-a8cbb9bf-d84e-4930-b943-c82b92461c81.png)

**Desktop (please complete the following information):**
  - OS: centOS 8
  - Browser 
  - Version 8

**Smartphone (please complete the following information):**

**Additional context**
[error.log](https://github.com/JanssenProject/jans/files/9082525/error.log)

**Comment by devrimyatar** [comment]
Can't replicate


https://user-images.githubusercontent.com/6398752/178248939-5b234e85-87b9-4af5-9d3b-0b9260d3d05d.mp4
