### ISSUE TITLE
unable to add custom scripts without SimpleCustomProperty property

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1764]
**Describe the bug**
unable to add custom scripts without SimpleCustomProperty property 
we are gettign attached error

**To Reproduce**
1.open jans-cli
select 5 for custom scripts
select 2 to add new script
add name,script, scripttype, programmingLanguage,
add SimpleCustomProperty? n
Populate optional fields? n 
Continue? 

**Expected behavior**
should add custom script without SimpleCustomProperty property

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178428610-8482e1bd-1c37-4897-9b22-e7eb2635f946.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
It is actually adding, but due to swagger client, it raises error.
See adding client with current version
![Screenshot_2022-07-12_20-57-02](https://user-images.githubusercontent.com/6398752/178561228-371e145b-392d-4011-8adf-be4d3faa305c.png)

And retreving with new version
![Screenshot_2022-07-12_20-57-56](https://user-images.githubusercontent.com/6398752/178561339-145e13a7-eddf-4e9b-8b47-831740da46ee.png)

**Comment by devrimyatar** [comment]
@pujavs Is **moduleProperties** mandatory? Seems not, config-api can create without **moduleProperties** If not mandatory please remove this line https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L3958

**Comment by pujavs** [comment]
Removed non-mandatory field from mandatory attribute list for Custom Script via [2480](https://github.com/JanssenProject/jans/pull/2480)

**Comment by devrimyatar** [comment]
New swagger file fixed this issue
```
Custom Scripts
--------------
1 Gets a list of custom scripts
2 Adds a new custom script
3 Updates a custom script
4 Fetch custom script by name
5 Deletes a custom script
6 Partially update custom script
b: back, q: quit, x: logout and quit

Selection: 2

«Custom script name. Should contain only letters, digits and underscores. Type: string»
name: testscript

«Actual script. Type: string»
script: _file /tmp/test.py

«Type of script. Type: string, Valid values: PERSON_AUTHENTICATION, INTROSPECTION, RESOURCE_OWNER_PASSWORD_CREDENTIALS, APPLICATION_SESSION, CACHE_REFRESH, CLIENT_REGISTRATION, ID_GENERATOR, UMA_RPT_POLICY, UMA_RPT_CLAIMS, UMA_CLAIMS_GATHERING, CONSENT_GATHERING, DYNAMIC_SCOPE, SPONTANEOUS_SCOPE, END_SESSION, POST_AUTHN, SCIM, CIBA_END_USER_NOTIFICATION, REVOKE_TOKEN, PERSISTENCE_EXTENSION, IDP, DISCOVERY, UPDATE_TOKEN, CONFIG_API»
scriptType: CONFIG_API

«Programming language of the custom script. Type: string, Valid values: PYTHON, JAVA»
programmingLanguage: PYTHON

«Script level. Type: integer»
level: 10

Populate optional fields? n
Obtained Data:

{
  "dn": null,
  "inum": null,
  "name": "testscript",
  "aliases": null,
  "description": null,
  "script": "print(\"A test script\")",
  "scriptType": "CONFIG_API",
  "programmingLanguage": "PYTHON",
  "moduleProperties": null,
  "configurationProperties": null,
  "level": 10,
  "revision": 0,
  "enabled": false,
  "scriptError": null,
  "modified": false,
  "internal": false,
  "locationPath": null,
  "baseDn": null
}
b: back, n: no, y: yes, q: quit, x: logout and quit

Continue? y
Please visit verification url https://snap.gluu.org/device-code and enter user code MBZG-XTTQ in 1800 secods
Please press «Enter» when ready
Please wait while posting data ...

{
  "dn": "inum=1fdf42db-82b0-46e9-a7b8-7a375f2447ec,ou=scripts,o=jans",
  "inum": "1fdf42db-82b0-46e9-a7b8-7a375f2447ec",
  "name": "testscript",
  "aliases": null,
  "description": null,
  "script": "print(\"A test script\")",
  "scriptType": "CONFIG_API",
  "programmingLanguage": "PYTHON",
  "moduleProperties": null,
  "configurationProperties": null,
  "level": 10,
  "revision": 0,
  "enabled": false,
  "scriptError": null,
  "modified": false,
  "internal": false,
  "locationPath": null,
  "baseDn": "inum=1fdf42db-82b0-46e9-a7b8-7a375f2447ec,ou=scripts,o=jans"
}
b: back, q: quit, x: logout and quit

Selection:
```
