### ISSUE TITLE
fix (jans-config-api) : some url fields have object value for oidc clients `GET` response

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1765]
**Describe the bug**
For [/jans-config-api/api/v1/openid/clients](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml#/operations/OAuth%20-%20OpenID%20Connect%20-%20Clients/post-oauth-openid-clients) `GET` following url fields have object value.

- clientUri
- logoUri
- policyUri
- tosUri

**Expected behavior**
The `string` values are expected for url fields.

**Comment by pujavs** [comment]
`LocalizedString` changes under discussion with @yuriyz @yurem and @qbert2k

**Comment by pujavs** [comment]
@qbert2k, request you to please confirm once the  LocalizedString as suggested by @yurem are implemented so that we can verify and test the impacted functionality.

**Comment by pujavs** [comment]
@duttarnab, @qbert2k seems to have fixed this. I tested locally and getting these values as string now. request you to please verify.
![image](https://user-images.githubusercontent.com/43700552/200832319-fb181262-a3a8-4a34-92c4-a429f005278b.png)

**Comment by pujavs** [comment]
Fixed see https://github.com/JanssenProject/jans/issues/2946
