### ISSUE TITLE
unable to update openid connect client

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1770]
**Describe the bug**
unable to update openid connect client
new value is not reflecting in openid configuration

**To Reproduce**
1. open jans-cli
2. select 8 for Oauth
3. select 1for open id connect
4. select 3 to update oepnid 
5. selelccdt 25 to update displayName
6. continue and save

**Expected behavior**
should able to update property

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178454518-32120fc7-21ea-4b56-aeb4-7f859ccf1c08.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**
unable to update throguh using 3 and 6 option in  interactive mode

**Comment by devrimyatar** [comment]
This is known issue
https://github.com/JanssenProject/jans/issues/1724

**Comment by devrimyatar** [comment]
Closing due to duplication.
