### ISSUE TITLE
jans-cli: Janssen Server dynamic install give success message even after failure

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#1776]
**Describe the bug**
I was trying to install Janssen Server using dynamic install. 

During the step where it tries to install `jans-auth-server` by downloading jans-auth.war, it timed out. As shown in image below shows time-out message. 
But still, before terminating, it gives a message that install was successful.

**Expected behavior**
If the install process timed out then it should not say that install was a success.

**Screenshots**
![image](https://user-images.githubusercontent.com/343411/178485299-91e01aa3-17c6-4197-bfb7-e235c25164f1.png)

**Desktop (please complete the following information):**
  - OS: Ubuntu 20.04

**Comment by devrimyatar** [comment]
Not sure, I need log files to understand what happened.

**Comment by nynymike** [comment]
This is not an error. You need to copy the properties over from `/root/.config/jans-cli.ini` because you probably installed as root.
