### ISSUE TITLE
feat(jans-config-api): update swagger and client endpoint according to registration parameters

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1778]
### Description

Swagger spec must match to what AS supports as well as Client Endpoint.

https://github.com/JanssenProject/jans/blob/26e576a5be90ac9597ed37e0d3629a2701008fcf/jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java#L19

**Comment by yuriyz** [comment]
@pujavs once swagger is updated please let @duttarnab know so he can check UI has all properties.

**Comment by duttarnab** [comment]
Hi @yuriyz @pujavs 

fyi, @nynymike has asked Admin UI team to arrange oidc client registration fields as per the below wiki.

https://github.com/JanssenProject/jans/wiki/CLI_V2

**Comment by pujavs** [comment]
Assigning to @duttarnab to test and confirm

**Comment by duttarnab** [comment]
I have raised a bug found during testing. This bug is closed.
https://github.com/JanssenProject/jans/issues/1861

**Comment by pujavs** [comment]
Thanks @duttarnab for confirmation. Closing this issue now
