### ISSUE TITLE
feat: sonar must ignore java:S5979 or otherwise recognize @Listeners(MockitoTestNGListener.class)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1785]
### Description

Sonar shows blocker for `java:S5979`. It does not recognize "@Listeners(MockitoTestNGListener.class)" at the top of the class and thinks that mocks are not initialized while it is. Sonar has to be upgraded to recognize it or otherwise we have to disable this particular scan.

![image](https://user-images.githubusercontent.com/2013070/178728530-1b0135ef-ced7-4d60-b1e8-17a537289fef.png)

**Comment by ossdhaval** [comment]
Hi @yuriyz, I am closing this issue as most latest scans on the main branch don't report this as a problem. [Here](https://sonarcloud.io/code?id=JanssenProject_jans-auth-server&selected=JanssenProject_jans-auth-server%3Aserver%2Fsrc%2Ftest%2Fjava%2Fio%2Fjans%2Fas%2Fserver%2Ftoken%2Fws%2Frs)

![image](https://github.com/JanssenProject/jans/assets/343411/a9eecdf8-533e-4978-9cee-9ed31edcb4f8)
