### ISSUE TITLE
feat: remove OX properties from Auth Server

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1791]
I see these properties in the Admin UI and it makes me wonder if the property names need to be updated in Jans.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/3717101/178859077-82292be8-be1b-4c9c-98fb-564446621ab1.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/3717101/178859129-3393d367-f85b-4689-8b4c-71527a5f287c.png">

**Comment by villcabo** [comment]
Hey @nynymike,

If I rename Ox to Jans? The names of the properties look like this:
```
- Jans Eleven Generate Key Endpoint: ...
- Jans Eleven Sign Endpoint: ...
- Jans Eleven Verify Signature Endpoint: ...
- Jans Eleven Delete Key Endpoint: ...

- Jans Open Id Connect Version: ...
- Jans Id: ...
```

Or should I remove Ox? and they look like this:
```
- Eleven Generate Key Endpoint: ...
- Eleven Sign Endpoint: ...
- Eleven Verify Signature Endpoint: ...
- Eleven Delete Key Endpoint: ...

- Open Id Connect Version: ...
- Id: ...
```

Which option works for you?

**Comment by Milton-Ch** [comment]
Should I rename Ox to Jans? I mean something like this:

- Jans Eleven Generate Key Endpoint: ...
- Jans Eleven Sign Endpoint: ...
- Jans Eleven Verify Signature Endpoint: ...
- Jans Eleven Delete Key Endpoint: ...

- Jans Open Id Connect Version: ...
- Jans Id: ...


Or should I remove Ox? and they look like this:

- Eleven Generate Key Endpoint: ...
- Eleven Sign Endpoint: ...
- Eleven Verify Signature Endpoint: ...
- Eleven Delete Key Endpoint: ...

- Open Id Connect Version: ...
- Id: ...


Which option works for you?

**Comment by nynymike** [comment]
Although it's not a component we talk about alot, [Jans Eleven](https://github.com/JanssenProject/jans/tree/main/jans-eleven) was ported to the Janssen Project. So best to rename "Jans Eleven"
