### ISSUE TITLE
jans-auth service is failing to start

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1794]
**Describe the bug**
jans-auth service is failing to start
when tried to run sudo  systemctl restart jans-auth
getting below error.

manoj@opensuse:~> sudo  systemctl status jans-auth
● jans-auth.service - Janssen OAauth service
     Loaded: loaded (/etc/systemd/system/jans-auth.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-07-14 15:19:15 IST; 19s ago
    Process: 8734 ExecStart=/opt/dist/scripts/jans-auth start (code=exited, status=1/FAILURE)

Jul 14 15:18:12 opensuse systemd[1]: Starting Janssen OAauth service...
Jul 14 15:18:15 opensuse jans-auth[8734]: Starting Jetty:
Jul 14 15:18:15 opensuse jans-auth[8766]: 2022-07-14 15:18:15.114:INFO :oe.jetty:main: Console stderr/stdout captured to|        /opt/jans/jetty>
Jul 14 15:19:14 opensuse jans-auth[8734]: . . . . . . . . . . . . . . . FAILED Thu 14 Jul 2022 03:19:14 PM IST
Jul 14 15:19:14 opensuse systemd[1]: jans-auth.service: Control process exited, code=exited, status=1/FAILURE
Jul 14 15:19:15 opensuse systemd[1]: jans-auth.service: Failed with result 'exit-code'.
Jul 14 15:19:15 opensuse systemd[1]: Failed to start Janssen OAauth service.

**To Reproduce**

1. not any specific steps 
2.  adhoc testing or create some invalid property or clients

**Expected behavior**
service should up and running

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178959239-25810220-47ae-4052-a230-81e580024fd5.png)

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version 15 leap

**Smartphone (please complete the following information):**

**Additional context**
[log.zip](https://github.com/JanssenProject/jans/files/9110944/log.zip)

**Comment by yuriyz** [comment]
@manojs1978 sounds like it's not valid anymore, please re-open if needed.
