### ISSUE TITLE
unable to fetch  user statistics

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1812]
**Describe the bug**
unable to fetch server stat report

**To Reproduce**
1. launch config-cli.py
2. select 9 for statistics
3. select 1 for fetch user statistics
4. select 1 for Provides server with basic statistic
5. add months as in screenshot given format
6. see error in screenshot

**Expected behavior**
should get user stats report for month

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/179450352-4092e67f-0c44-46a2-afc4-3e9b62cb66ab.png)
![image](https://user-images.githubusercontent.com/5729240/179450494-e1e49db2-01cc-4baa-91fe-ded81756db92.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Swagger client fixed and uploaded.

@manojs1978 all months are should be in format **YYYYMM**, see this example:

![user-stat](https://user-images.githubusercontent.com/6398752/192097477-9bb0d802-bb33-45f8-b535-b1594a11c529.png)
