### ISSUE TITLE
feat: load update token script in persistence

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#1820]
Load from [scan ](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/scan/static/extension/update_token/UpdateToken.py)folder the token update script.

**Comment by moabu** [comment]
@iromli I think thats a good idea as long as we name it appropriately

**Comment by maduvena** [comment]
@iromli -  its good to put it here - https://github.com/JanssenProject/jans/tree/main/jans-linux-setup/jans_setup/static/extension/update_token

**Comment by devrimyatar** [comment]
@maduvena It is good for Linux Setup
