### ISSUE TITLE
feat(jans-auth-server): Extend Client Schema - add jansClientGroup

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1824]
* In the UI, it would be nice if we had an attribute like `jansClientGroup` so we could "group" clients in the UI.
 * Perhaps we should add an extra client claim for `o` (organization). 
 * We should maybe also consider some of the claims found in [UK Open Banking Software Statement](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/36667724/OpenBanking+OpenID+Dynamic+Client+Registration+Specification+-+v1.0.0-rc2#OpenBankingOpenIDDynamicClientRegistrationSpecification-v1.0.0-rc2-SSAPayload)... for example `software_roles`

**Comment by yuriyz** [comment]
`o` is mapped to SSA `org_id`. `jansClientGroup` sounds as good fit for `software_roles`. I will add it on AS side.
