### ISSUE TITLE
unable to access openbanking after installation

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1828]
**Describe the bug**
unable to access openbanking after installation,getting attached screenshot error

**To Reproduce**
1. download  installer wget https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py
2. run install.py  : sudo python3 install.py --profile openbanking
3. add information required for certification generation
![openbanking](https://user-images.githubusercontent.com/5729240/179899379-ddecd8af-0caf-4d09-9cb8-34692f5c9fce.png)

**Expected behavior**
should able to launch jans-cli for  open banking 

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/179899228-3ef90310-e3d5-4e1e-8daf-40763a91d60a.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser
  - Version20.04

**Smartphone (please complete the following information):**

**Additional context**

[error.log](https://github.com/JanssenProject/jans/files/9146628/error.log)

**Comment by devrimyatar** [comment]
Tested. No such issue. He had chosen `N` to the following question.

 @manojs1978 Follow this guide https://github.com/JanssenProject/jans/wiki/Gluu-OB-Testing-Installation

Please enter defaults for the following questions (press just enter key), it will download certificate from jwksUri
```
 Use external key? [Y|n] : y
  Openbanking Key File [/opt/jans/jans-setup/openbanking/static/ob-gluu-test.key] : 
  Openbanking Certificate File [/root/obsigning.pem] : 
  Openbanking Key Alias [ob-gluu-test] : 
```
