### ISSUE TITLE
fix(jans-auth): Scopes used by the jans-cli do not reflect after client creation 

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#1833]
**Describe the bug**
Scopes used by the jans-cli do not reflect after client creation 

**To Reproduce**
1. Execute the curl command
```
curl -X POST -k -H 'Content-Type: application/json' -i 'https://jans-ui.jans.io/jans-auth/restv1/register' --data '{
"redirect_uris": [
    "https://client.example.org/cb"
  ],
"grant_types":["client_credentials"],
scope:["openid","https://jans.io/oauth/config/scripts.write","https://jans.io/oauth/config/scripts.readonly","https://jans.io/oauth/config/openid/clients.write","https://jans.io/oauth/config/openid/clients.readonly","https://jans.io/oauth/config/openid/clients.delete"]
}'
```
3. Check the `scope`
4. Notice that `openid` has been added, but not the others
5. If you change the json attrib to `scopes` in the request,  you get another result (sample result - `"scope": "openid permission uma_protection jans_client_api offline_access",`), but it still doesnt include the above scopes like `https://jans.io/oauth/config/scripts.readonly`

**Expected behavior**
All scopes should reflect

**Comment by yuriyz** [comment]
Scopes are represented as space delimited string. Correct curl request should have `"scope": "openid https://jans.io/oauth/config/scripts.write https://jans.io/oauth/config/scripts.readonly"`.

I guess it was coded like that in early AS days to keep it compatible with OAuth and authz request where scope is space delimited string.

Closing ticket as not an issue on AS side.
