### ISSUE TITLE
fix: [Snyk] Security upgrade org.seleniumhq.selenium:selenium-remote-driver from 3.141.59 to 4.0.0 -autocreated 

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#1856]
This issue was created because no open issues were referenced in your PR (#1855).

**Comment by yuriyz** [comment]
Snyk proposes breaking change, upgrade to selenium 4.x. We are on 3.x. Latest is `[4.3.0](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-remote-driver/4.3.0)`.
@jmunozherbas check whether upgrade to 4.x requires a lot of changes in our client tests.
