### ISSUE TITLE
fix: unable to access openbanking profile with bleeding edge linux install

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1860]
**Describe the bug**
unable to access openbanking after installation,getting attached screenshot error

**To Reproduce**
download installer wget https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py
run install.py : 
python3 install.py --profile=openbanking --args="-ob-key-fn=/opt/jans/jans-setup/openbanking/static/ob-gluu-test.key -static-kid=ob-gluu-test -jwks-uri=https://ox.gluu.org/icrby8xcvbcv/ob/ob-gluu-test.jwks --disable-ob-auth-script -ob-alias=ob-gluu-test"

add information required for certification generation as in screenshot.

**Expected behavior**
should able to access open banking profile using jans-cli

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/180705468-9f387af3-1e9d-4b59-a8a3-4efdbc0c59e2.png)

![image](https://user-images.githubusercontent.com/5729240/180705429-e989bf70-6a5d-4091-8448-46437255dda3.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**
please check attached errors
[error_openbanking.log](https://github.com/JanssenProject/jans/files/9178299/error_openbanking.log)
[jans-auth.log](https://github.com/JanssenProject/jans/files/9178300/jans-auth.log)

**Comment by devrimyatar** [comment]
There was an issue for CentOS/RHEL installation, resolved by https://github.com/JanssenProject/jans/pull/1987
Can't replicate the issue on Ubuntu20
