### ISSUE TITLE
bug (jans-config-api) : some of the new added fields are not saving for oidc client 

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1861]
**Describe the bug**
The bug has been found in following endpoints
- `/jans-config-api/api/v1/openid/clients` `POST`
- `/jans-config-api/api/v1/openid/clients` `PUT`

Following fields are not saved when using the above config-api endpoints.

- defaultPromptLogin
- authorizedAcrValues
- attributes.authorizationSignedResponseAlg
- attributes.authorizationEncryptedResponseAlg
- attributes.authorizationEncryptedResponseEnc

**Comment by pujavs** [comment]
Fixed, issue was due mismatch of field and json property of the attribute

![image](https://user-images.githubusercontent.com/43700552/181267910-142d2e87-ea42-40ba-a58d-f62d9762ed1d.png)

**Comment by pujavs** [comment]
Implemented via PR [1912](https://github.com/JanssenProject/jans/pull/1912)

**Comment by pujavs** [comment]
Closing the issue as changes merged into main
