### ISSUE TITLE
feat(jans-config-api): include latest attributes added to scim configuration

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1875]
Include in the config api these two recently-added attributes so that they can be managed via CLI:
https://github.com/JanssenProject/jans/blob/main/jans-scim/service/src/main/java/io/jans/scim/model/conf/AppConfiguration.java#L37-L39

Ref issue #1819

**Comment by pujavs** [comment]
@jgomer2001, I have implemented the agama endpoint.
**Implementation Details:**
1) /jans-config-api/api/v1/agama
    GET - Fetches all the flow
    POST - Create a new flow

2) /jans-config-api/api/v1/agama/{qname}
    GET - Fetch flow based on qname
    POST - Create a flow with request payload reading source file
    PUT - Updates a flow based on qname
    DELETE - Deletes a flow

**Testing evidence"**
Manual test evidence: [Agama_endpoint_test_issue#1509.xlsx](https://github.com/JanssenProject/jans/files/9190167/Agama_endpoint_test_issue.1509.xlsx)

Karate test case evidence: 
[src.test.resources.feature.agama.agama.pdf](https://github.com/JanssenProject/jans/files/9190187/src.test.resources.feature.agama.agama.pdf)


**Note:** As communicated Java bean has a field name `QName` is not working and in the dev branch `agama` code base i have renamed the field to `qname`.
**Branch**: https://github.com/JanssenProject/jans/tree/jans-config-api-1509-new
**Please advice if the code needs to be merged with main along with agama change**

**Comment by pujavs** [comment]
Implemented: 
![image](https://user-images.githubusercontent.com/43700552/181752556-e795b70d-8b1c-4978-b951-265950ab6809.png)

![image](https://user-images.githubusercontent.com/43700552/181764866-6122d8b8-f352-4cb9-b851-812abb68a4b1.png)

**Comment by pujavs** [comment]
Related PR [1940](https://github.com/JanssenProject/jans/pull/1940)
