### ISSUE TITLE
fix:(jans-config-api) (openbanking profile) getting error "Index 0 out of bounds for length" while fetching list of user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1878]
**Describe the bug**
getting error "Index 0 out of bounds for length" while getting list of user in user management.

**To Reproduce**
download installer wget https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py
run install.py :
python3 install.py --profile=openbanking --args="-ob-key-fn=/opt/jans/jans-setup/openbanking/static/ob-gluu-test.key -static-kid=ob-gluu-test -jwks-uri=https://ox.gluu.org/icrby8xcvbcv/ob/ob-gluu-test.jwks --disable-ob-auth-script -ob-alias=ob-gluu-test"

access openbanking profile using jans-cli
select 4 for configuration  then select 5 for user management
select 1 to get list of users
select default values for filters

**Expected behavior**
should able to get list of available users

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/180949145-75b01417-5682-4e22-b5ae-d755fd46fff8.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
User operations hsould be hidden for openbanking profile. There won't be a user, openbanking will act as proxy

![no-user-operations](https://user-images.githubusercontent.com/6398752/192101988-732caf96-6113-4ae9-8468-ab67066ed777.png)
