### ISSUE TITLE
feat (jans-config-api) : need endpoint to fetch uma resource by client_id

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1879]
**Is your feature request related to a problem? Please describe.**

As per the new oidc client view screen designs we need to show the UMA resources created by the client along with other client details.

For this functionality need to add endpoints in config-api to fetch uma resources by client_id. 

`GET` `[/jans-config-api/api/v1/uma/resources/{clientId}`

ref; https://github.com/JanssenProject/jans/wiki/CLI_V2

![image](https://user-images.githubusercontent.com/32794267/180948742-e22c07bb-a788-43a2-950e-7df21c54889b.png)

**Comment by yuriyz** [comment]
You can use AS code for reference to add it
https://github.com/JanssenProject/jans/blob/6c1caa1c4c92d28571f8589cd701e6885d4d85ef/jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaResourceService.java#L132

**Comment by pujavs** [comment]
thanks @yuriyz for the reference

**Comment by pujavs** [comment]
Implemented via PR [1912](https://github.com/JanssenProject/jans/pull/1912) 
UmaResource : New endpoint /jans-config-api/api/v1/openid/clients/{clientid}
Note you need to pass clientid and not DN

Testing Evidence:
![image](https://user-images.githubusercontent.com/43700552/181303097-6bca14b6-6faa-4652-8a35-be97a7f21e66.png)

**Comment by pujavs** [comment]
Closing the issue as changes merged into main
