### ISSUE TITLE
Fix:(jans-cli)(open banking) Error "invalid value for jans_status"

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1881]
**Describe the bug**
getting An Unhandled error raised: Invalid value for `jans_status` (active)

**To Reproduce**
download installer wget https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py
run install.py :
python3 install.py --profile=openbanking --args="-ob-key-fn=/opt/jans/jans-setup/openbanking/static/ob-gluu-test.key -static-kid=ob-gluu-test -jwks-uri=https://ox.gluu.org/icrby8xcvbcv/ob/ob-gluu-test.jwks --disable-ob-auth-script -ob-alias=ob-gluu-test"

access openbanking profile using jans-cli
select 4 for configuration then select 5 for user management
select 2 to create new user.
select jansstatus value by valid values (Valid values: active, inactive, expired, register are given )
add any values as given in screenshot.

**Expected behavior**
should not give any error or add valid jansstatus  value in capital letter

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/180951153-f1a80242-5191-47c5-90a7-386fd7b18d9c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
User creation is hided for openbanking profile
