### ISSUE TITLE
Fix:(jans-cli)(open banking) Unable to create UMA resource

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1882]
**Describe the bug**

**To Reproduce**

1)b download installer wget https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py
2) run install.py :
python3 install.py --profile=openbanking --args="-ob-key-fn=/opt/jans/jans-setup/openbanking/static/ob-gluu-test.key -static-kid=ob-gluu-test -jwks-uri=https://ox.gluu.org/icrby8xcvbcv/ob/ob-gluu-test.jwks --disable-ob-auth-script -ob-alias=ob-gluu-test"

3) access openbanking profile using jans-cli
4) select 8 for OAuth then select 2 for UMA  resource
5) select 2 to create new user.

add any values as given in screenshot.

**Expected behavior**
should able to create UMA resource

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/180974067-dd964a50-f410-42ab-a115-882db1d4a9e2.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This issue was fixed before

![image](https://user-images.githubusercontent.com/6398752/192102129-6a44ccf5-5c72-4d7b-a563-e6a337108dca.png)
