### ISSUE TITLE
fix:(fido2) (open banking) unable to get Fido2 configuration properties

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1911]
**Describe the bug**
unable to get Fido2 configuration properties using jans-cli openbanking profile

**To Reproduce**
1. access openbanking profile using jans-cli
select 5 for FIDO2 then select 1 for get list of fido configuration

**Expected behavior**
should get fido configuration 

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/181279160-edea144d-a1e5-4713-b5f4-73afc3fc085f.png)

**Desktop (please complete the following information):**
  - OS: [ubuntu
  - Browser
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fido2 is not available for openbanking, fido2 menu should be hided.
