### ISSUE TITLE
UMA: Add Created Time / Creator to UMA scope

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1934]
It would be helpful to know when the UMA scope was created. Also, if there is a person associated with its creation, if that could be recorded too, it would be great. Maybe information about the person as a JSON object, because a link to a person may not be as useful if the person leaves the organization.  With this information, we could add this information to the TUI like so:

![image](https://user-images.githubusercontent.com/3717101/181673475-d1956e11-9ac5-4bc5-aa6b-8906ace6cb2c.png)

**Comment by yuriyz** [comment]
@pujavs ticket is implemented on AS side. Please check whether all works good on jans-config-api side and then re-assign to Arnab to cover UI part.

**Comment by pujavs** [comment]
Swagger changes done for the same 
![image](https://user-images.githubusercontent.com/43700552/183083996-10877a74-1399-4a25-a123-bb7028670e68.png)

Related config-api PR# [2033](https://github.com/JanssenProject/jans/pull/2033)
