### ISSUE TITLE
feat:remove rpm/deb package using install.py

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1955]
**Is your feature request related to a problem? Please describe.**
when we run "**python3 install.py -uninstall**" command , it is not deleting package from VM.
so we are not able to completely remove jans from VM

**Describe the solution you'd like**
we should delete rpm/deb package  when we run "**python3 install.py -uninstall**" command 

**Describe alternatives you've considered**
currenlty we need to remove package seperately.
sudo apt remove jans
sudo yum remove jans

**Additional context**
![image](https://user-images.githubusercontent.com/5729240/182077032-7d5856a4-3fb1-4a47-9314-c539a7503157.png)

**Comment by devrimyatar** [comment]
If you install Jans RPM/DEB package, remove it via `apt` or `yum`. `install.py` should not hande package removal.
