### ISSUE TITLE
feat(jans-linux-setup): add scopes for agama flows CRUD

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#1975]
The following scopes are used by jans-config-api to do flows management:

- `https://jans.io/oauth/config/agama.readonly`
- `https://jans.io/oauth/config/agama.write`
- `https://jans.io/oauth/config/agama.delete`

Let's add them to the default jans installation and include them as scopes for the jans-config-api client

Descriptions could be: modify agama flows, delete, etc...

**Comment by devrimyatar** [comment]
@jgomer2001 setup.py reads scopes under `components:securitySchemes:oauth2:flows:clientCredentials:scopes` of swagger yaml file:
https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L3530

Can't we add there?

**Comment by jgomer2001** [comment]
@pujavs can you add them?

**Comment by pujavs** [comment]
Yes we can, I will update swagger spec for the same
