### ISSUE TITLE
feat (jans-config-api) : API to delete resource by jansId

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#1986]
On the UMA resource details page we need a button to delete a resource. For this operation, we need API to delete resources by `id`.

[/jans-config-api/api/v1/uma/resources/{id}](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml#/operations/OAuth%20-%20UMA%20Resources/get-oauth-uma-resources-by-id) `DELETE`

![image](https://user-images.githubusercontent.com/32794267/182310436-17ea60ab-4023-4286-a1c5-1b6590144286.png)

**Comment by pujavs** [comment]
working on this

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/182614417-b55a89e6-2431-483e-8348-efdfc86e5a20.png)
