### ISSUE TITLE
feat (jans-config-api) : authorization alg supported values field should be added in jans configuration api

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2018]
**Describe**

We need to following fields (new) in `GET` [/jans-config-api/api/v1/jans-auth-server/config](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml#/operations/Configuration%20%E2%80%93%20Properties/get-properties).

- authorizationSigningAlgValuesSupported
- authorizationEncryptionAlgValuesSupported
- authorizationEncryptionEncValuesSupported
![image](https://user-images.githubusercontent.com/32794267/182792676-798614fa-6ca1-4abb-af3b-aadccb21824a.png)

**Comment by pujavs** [comment]
@duttarnab, these fields are already fetched by config endpoint and hence no change required for this.
Attaching the test report for your reference.
[src.test.resources.feature.config.properties.properties.pdf](https://github.com/JanssenProject/jans/files/9268713/src.test.resources.feature.config.properties.properties.pdf)
