### ISSUE TITLE
fix:unable to do device-code verification for ipaddress in hostname

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2045]
**Describe the bug**
unable to do device-code verification for long or containing ipaddress in hostname

**To Reproduce**
1. create VM with ipaddress in hostname ex. 65.20.68.48.vultrusercontent.com
2. install jans server
3. do device-code verification

**Expected behavior**
should able to do device-code verification

**Screenshots**
![de](https://user-images.githubusercontent.com/5729240/183369470-00a2ff85-baeb-4a44-9101-c3d5d3099940.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moabu** [comment]
I really don't think you are testing the latest. Here is the 503 error page link https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/apache/error_pages/custom_503.html


Here is how it looks:
https://user-images.githubusercontent.com/47318409/182088667-f460a614-9961-4a78-8078-909b59bdc3c4.png

**Comment by nynymike** [comment]
Also, if you are getting a 503, we'd want the web server log and oxauth log. That's a valid FQDN, but I don't see anyone doing that.

**Comment by manojs1978** [comment]
i have run below 2 commands
curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py
python3 install.py

please chek below VDO
https://user-images.githubusercontent.com/5729240/183573767-1642ea1f-0234-4062-8954-6c3d41ff8528.mp4

**in setup_error.log i found below ,  is it causing this failure?**

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/filter does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/dir.conf does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/deflate.conf does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/authz_user does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/dir does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/authn_file does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/status.conf does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/auth_basic does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/status does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/negotiation does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/deflate does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/autoindex.conf does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/negotiation.conf does not exist!

05:38:46 08/09/22 ERROR: Module /etc/apache2/mods-enabled/autoindex does not exist!

**please find attached log zip.**

[hostissue.zip](https://github.com/JanssenProject/jans/files/9287433/hostissue.zip)

**Comment by devrimyatar** [comment]
Unable to replicate

![ip1](https://user-images.githubusercontent.com/6398752/192730935-215fe768-8ddd-43e1-9a63-62cb8ed55dd6.png)
![ip2](https://user-images.githubusercontent.com/6398752/192730968-8602b390-873f-4dd8-9d1d-86fcd844a117.png)
![ip3](https://user-images.githubusercontent.com/6398752/192730995-7fbfe33d-1724-40f1-a433-78ef19451b17.png)
![ip4](https://user-images.githubusercontent.com/6398752/192731024-489dafdd-0c09-4a64-bd71-20093d2f929f.png)
