### ISSUE TITLE
feat (jans-config-api) : apis to view and revoke sessions on auth server

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2090]
Parent issue# https://github.com/GluuFederation/flex/issues/331

- We need API in config-api to view sessions sorted by date.
- We need API in config-api to revoke all sessions by userId.

**Comment by pujavs** [comment]
Implemented session endpoints
1) GET /jans-config-api/api/v1/jans-auth-server/session - 
Note: 
- This return all the sessions sorted by `creationDate` in descending order
-  Both authenticated and unauthenticated are returned
![image](https://user-images.githubusercontent.com/43700552/185149497-eba23a57-14e0-4fb1-abd4-6b330aa93d51.png)


2) POST /jans-config-api/api/v1/jans-auth-server/session/**{userDn}**
Note: 
- path param is userDn you get this is GET method example `inum=290a9cba-d605-42b3-abd5-dcacb87eb9e7,ou=people,o=jans`
- only **authenticated** session for the user will be delete
![image](https://user-images.githubusercontent.com/43700552/185146116-76ec2fd8-1c55-4241-bbda-8e82c8794de9.png)
