### ISSUE TITLE
feat (jans-config-api) : get spontaneous scopes by client_id

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2091]
We need API in `jans-config-api` to get all spontaneous scopes by oidc client_id.

`GET` /jans-config-api/api/v1/scopes/spontaneous/{clientId}

Parent ticket# https://github.com/GluuFederation/flex/issues/357

**Comment by yuriyz** [comment]
It should be generic API : 
1) get scope by creatorId -> `GET /jans-config-api/api/v1/scopes/creator/{creatorId}`
2) get scope by type -> `GET /jans-config-api/api/v1/scopes/type/{type}`

Getting spontaneous scopes by client id falls into `GET /jans-config-api/api/v1/scopes/creator/{clientId}`.

**Comment by pujavs** [comment]
Looking into this

**Comment by pujavs** [comment]
1) Get scope by creatorId -> GET /jans-config-api/api/v1/scopes/creator/{creatorId}) 
![image](https://user-images.githubusercontent.com/43700552/184118737-82d2897d-30e3-4be9-ad2c-875a3b9c500e.png)
![image](https://user-images.githubusercontent.com/43700552/184119006-ef79af73-88db-4d85-b39d-9b03bba3ef4d.png)

2) Get scope by type -> GET /jans-config-api/api/v1/scopes/type/{type}
![image](https://user-images.githubusercontent.com/43700552/184118890-33f46b75-aac2-4cdb-8b96-4c5c4174007f.png)
![image](https://user-images.githubusercontent.com/43700552/184118967-b557466b-7f21-41b4-aa92-dbfa14f01476.png)

**Comment by pujavs** [comment]
jans-cli test

1)Get scope by creatorId -> GET /jans-config-api/api/v1/scopes/creator/{creatorId})
![image](https://user-images.githubusercontent.com/43700552/184142532-0b1c45e8-f105-4838-95cd-65d7134cf38b.png)
![image](https://user-images.githubusercontent.com/43700552/184142644-16990173-0bd6-4986-89e3-979ff593b0e2.png)


2) Get scope by type -> GET /jans-config-api/api/v1/scopes/type/{type}
![image](https://user-images.githubusercontent.com/43700552/184140833-74b6ad2c-c2d7-4245-acae-003ca7e88ae5.png)
![image](https://user-images.githubusercontent.com/43700552/184142742-cac01cab-d8b8-46ca-ac19-98f78bacb15c.png)

**Comment by pujavs** [comment]
https://github.com/JanssenProject/jans/pull/2098
