### ISSUE TITLE
feat(jans-cli): create StyleSheet

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2125]
prompt-ttolkit supports style-sheet for coloring display. We need it for nice view, we may support styling so it should be in different file

**Comment by AbdelwahabAdam** [comment]
related commits: 
https://github.com/JanssenProject/jans/commit/1303317a6168ce0f64874e6fe9fe7f4a9510de71
https://github.com/JanssenProject/jans/commit/82296fed43c700274b2c7596a1ae088b2258a1df
https://github.com/JanssenProject/jans/commit/a85cea45b565ebdfaf831e5bd813cc061a1b5084

missing styles for new features or pages
