### ISSUE TITLE
feat(jans-cli): device flow for authentication for the TUI

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2129]
Only users with the admin role should be allowed to use the TUI.

Here are the roles we defined in the Admin UI:

![image](https://user-images.githubusercontent.com/3717101/197552987-644f3404-6be7-4c2a-bdbe-3047e78bc4bb.png)

Here is the mapping to OAuth Scopes:

![image](https://user-images.githubusercontent.com/3717101/197553168-11a0b763-4875-4c6e-aba2-3f36eaf27af4.png)

**Comment by devrimyatar** [comment]
Implemented in commit https://github.com/JanssenProject/jans/commit/1177165c3eb6adc2415d7c0b6f99e8b5ee80f045
![image](https://user-images.githubusercontent.com/6398752/197795805-9601b12c-8613-4016-9475-711ade7ea976.png)
