### ISSUE TITLE
fix:unable to start jans-cli interactive mode and run in CLI mode

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2135]
**Describe the bug**
unable to start jans-cli interactive mode when run "/opt/jans/jans-cli/config-cli.py"

**To Reproduce**
1. install jans-server 
2. curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py
3. python3 install.py
4. run config-cli using  /opt/jans/jans-cli/config-cli.py
5. See error

**Expected behavior**
should able to run jan-cli in interactive and CLI mode

**Screenshots**

**Desktop (please complete the following information):**
  - OS: centos8/ ubuntu
  - Browser 
  - Version 8 /20

**Smartphone (please complete the following information):**

![image](https://user-images.githubusercontent.com/5729240/184589523-93cbf3d9-a56d-412d-b072-ad446ccb6050.png)

**Additional context**

[root@glucentos8 ~]# /opt/jans/jans-cli/config-cli.py --operation-id get-attributes
An Unhandled error raised: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 15 Aug 2022 06:47:44 GMT', 'Server': 'Apache', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'WWW-Authenticate': 'Basic realm="jans-auth"', 'Content-Type': 'application/json;charset=iso-8859-1', 'Content-Length': '651', 'Set-Cookie': 'X-Correlation-Id=c0f5962c-12fb-476a-973e-94daa87a28d6; Secure; HttpOnly;HttpOnly', 'Connection': 'close'})
HTTP response body: b'{\n    "error_description": "Client authentication failed (e.g. unknown client, no client authentication included, or unsupported authentication method). The authorization server MAY return an HTTP 401 (Unauthorized) status code to indicate which HTTP authentication schemes are supported. If the client attempted to authenticate via the Authorization request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code, and include the WWW-Authenticate response header field matching the authentication scheme used by the client. CorrelationId: c0f5962c-12fb-476a-973e-94daa87a28d6",\n    "error": "invalid_client"\n}'
**centos 8 log**
[centos.zip](https://github.com/JanssenProject/jans/files/9335566/centos.zip)

**ubuntu20 log**
[ubuntu.zip](https://github.com/JanssenProject/jans/files/9335599/ubuntu.zip)

**Comment by devrimyatar** [comment]
Can't replicate 

https://user-images.githubusercontent.com/6398752/187440847-10e62c91-4d5b-4bd2-8a52-999e227f7c79.mp4

**Comment by devrimyatar** [comment]
Unable to replicate. CLI works well on both OS
