### ISSUE TITLE
feat (jans-config-api) : need to add pagination parameters in request and response of jans-config-api apis

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2156]
**Is your feature request related to a problem? Please describe.**

The server-side pagination is the performance efficient technique when amount of data is large.

**Describe the solution you'd like**

In order to implement server-side pagination on applications (like admin-UI, jans-cli etc) using jans-config-api, we need to add the following pagination parameters in all `GET` apis (fetching multiple records).

_**In Request (query parameters to be added)**_ 

`startIndex` - This is the page index

`limit` - This is the number of rows that will be displayed per page.

_**Response (parameters to be added)**_

`totalItems` - This is the number of records/rows in the database.

**Example**

Request: 
`curl -X GET -i 'http://<hostname>/jans-config-api/api/v1/openid/clients?startIndex=1&limit=10'
`

Response:
```
{
data: [{}, {}, {}, ...],
totalItems: 345
}
```

cc: @yuriyz @devrimyatar

**Comment by pujavs** [comment]
Implemented the change for Attribute endpoint `/jans-config-api/api/v1/attributes`. Kindly review and confirm if good to be repeated to other endpoints
### params:
1.  `limit`: Search size - max size of the results to return. 
2.  `pattern`: Search pattern.
3.  `string` : Status of the attribute
4. `startIndex`: The 1-based index of the first query result.
5. `sortBy`: Attribute whose value will be used to order the returned response.
6. `sortOrder`: Order in which the sortBy param is applied. Allowed values are "ascending" and "descending".

### Response structure:
```{
  "totalItems": 0,
  "entriesCount": 0,
  "data": [
    {}
]
}```

Testing:

[Issue_2156_Pagination.xlsx](https://github.com/JanssenProject/jans/files/9446343/Issue_2156_Pagination.xlsx)

**Comment by pujavs** [comment]
Attributes changes for paginations has been verified and confirmed to be as expected. Re-opening as need to incorporate the pagination for other endpoints.
