### ISSUE TITLE
bug(jans-auth): Authorize.xhtml UI rendering

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#2169]
**Describe the bug**
1. Missing image - URL shows as - https://my-jans-server/jans-auth/%7B%7D
2. Place holder needs to be fixed - {=Jans Role Based Client}

**To Reproduce**
1. Add a new user
2. Login
3. Consent screen is displayed after username, password screen

**Expected behavior**
Image and placeholder should be rendered correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/12072533/185314091-0d3e1f5b-45ed-47c8-a012-732994afa000.png)

**Comment by yuriyz** [comment]
Assigning to @qbert2k . It should automatically work once issue with logoUri is fixed as propose by @yurem (LocalizedString).

See https://github.com/JanssenProject/jans/issues/1765

**Comment by yuriyz** [comment]
Closing this as fixed because issue with logoUri was fixed by Javier.
