### ISSUE TITLE
fix: device code authentication is failing when jans installed with couchbase server

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2192]
**Describe the bug**
device code authentication is failing when jans installed with couchbase server

**To Reproduce**
1. download install.py 
2. curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py
3. python3 install.py
4. /opt/jans/jans-cli/config-cli.py
5. perform device authentication
6. add admin username and passwd

**Expected behavior**
admin should able to login and allow all access.

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/185880620-78af7f66-54ae-43e7-a0d8-884a1eef4860.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 
  - couchbase version 6.6.5

**Additional context**
log added
[logs.zip](https://github.com/JanssenProject/jans/files/9392791/logs.zip)

**Comment by devrimyatar** [comment]
Can't replicate. May be due to a fixed orm issue
