### ISSUE TITLE
Fix: unable to connect Google cloud spanner while installing jans with cloud spanner

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2195]
**Describe the bug**
unable to connect Google cloud spanner while installing jans with cloud spanner

**To Reproduce**
1. download and start cloud spanner with below steps
2. VERSION=1.4.2
wget https://storage.googleapis.com/cloud-spanner-emulator/releases/${VERSION}/cloud-spanner-emulator_linux_amd64-${VERSION}.tar.gz
tar zxvf cloud-spanner-emulator_linux_amd64-${VERSION}.tar.gz
chmod u+x gateway_main emulator_main
./emulator_main --host_port localhost:1234
./gateway_main --hostname localhost --grpc_port 1234 --http_port 1235
 download install.py 
 python3 install.py
3. select cloud spanner as db

**Expected behavior**
should able to connect cloud spanner and install jans

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/185964126-77e1734d-3c4a-4092-bd91-0ecff1997bd3.png)
![image](https://user-images.githubusercontent.com/5729240/185964241-f504ec20-046f-4408-981f-fd869837e72b.png)

![image](https://user-images.githubusercontent.com/5729240/185963687-3f06c42a-af1b-4756-af4b-5df7e0c0db64.png)

**Desktop (please complete the following information):**
  - OS: [centos8
  - Browser 
  - Version : 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 @moabu This is not an issue, but lack of knowledge. I prepared a doc for using spanner emulator

https://github.com/JanssenProject/jans/wiki/Using-Spanner-Emulator-for-Testing
