### ISSUE TITLE
bug (jans-auth-server) : field to save `claims gathering script` missing from oidc client table in database

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2218]
As per the oidc client wireframe (ref: https://github.com/JanssenProject/jans/wiki/CLI_V2) we need to add/display `Claims Gathering Script` associated with client in OIDC client form. 
![image](https://user-images.githubusercontent.com/32794267/186444108-c90c27b5-81b6-40fc-9910-8ec3c20f9626.png)

But the oidc client table in the database has no field to save selected `claims gathering scripts` from oidc clients form. Please let us know if this field is required to be added to the database.

![image](https://user-images.githubusercontent.com/32794267/186444169-488f7d7e-76c1-4218-8715-43e57e7e69ed.png)

**Comment by yurem** [comment]
yes, in Jans server there is no code which allow to use specific `Claims Gathering Script` per client. But in scope entry there is list umaAuthorizationPolicies. In this field we can specify list of script.

**Comment by duttarnab** [comment]
Thanks for providing this information. Closing this issue.
