### ISSUE TITLE
docs: rename the two developer guides for clarity

### ISSUE THREAD

**Issue by shmorri** [JanssenProject/jans#2277]
We currently have two different developer guides in documentation, and both could use clearer names.

For the one inside the Admin Guide, `Customization Guide` is more accurate for what it contains.

For the top level, `Contribution Guide` is more descriptive.

**Comment by ossdhaval** [comment]
Yes, I think the term `developer` is overloaded. Let's name the top-level item `Developer` -> `Contributing` and then we can leave the `developer` under admin guide as it is.
