### ISSUE TITLE
fix: device authentication failed with couchbase server 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2285]
**Describe the bug**
admin authentication failing when we add username and passwd after entering device code 

**To Reproduce**
1. insall jans with couchbase server
2. select couchbase as db while installation
3. run /opt/jans/jans-cli/config-cli.py
4. open device code page and add code
5. enter username and passwd
6. 

**Expected behavior**
should able to authenticate user

**Screenshots**

https://user-images.githubusercontent.com/5729240/187888735-53702327-c243-41fd-ab7a-537c675fc036.mp4

**Desktop (please complete the following information):**
  - OS: UBUNTU
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate, may be due to a fixed orm issue
