### ISSUE TITLE
feat(jans-auth-server): rename `enabledComponents` conf property -> `featureFlags`

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#2290]
### Description

Rename `enabledComponents`  conf property  -> `featureFlags`

Mike: enabledComponents sounds like big stuff, like auth-server, fido, scim
YuriyZ: we need better name for it
Mike: featureFlags would help us with security audit… then we can say we have “feature flags”

**Comment by nynymike** [comment]
Can you give some examples of what the values are here?
