### ISSUE TITLE
feat(jans-auth-server): automate swagger and doc generation

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#2291]
### Description

We need automate swagger and doc generation. Question what is the easiest way to do it?

Primary goal is to automate it for jans-config-api since beans are changing often there. jans-auth-server API is more conservative.

[springfox ](https://github.com/springfox/springfox)is nice tool to automatically generate swagger and documentation. Problem is that we don't use spring. What alternatives can we use with Weld ? R&D is needed.

**Comment by yuriyz** [comment]
Actually it seems we already have ticket for jans-config-api [here](https://github.com/JanssenProject/jans/issues/2217). Thus targeting by this ticket jans-auth-server.

**Comment by ossdhaval** [comment]
Hi @yuriyz, can you confirm if this is still a need?

**Comment by yuriyz** [comment]
AS swagger is based on spec and it not changed frequently. And config-api is automated. We can close it. Lets re-open when needed.
