### ISSUE TITLE
fix:jans-cli : getting AttributeApi error when accessed list of attribute

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2294]
**Describe the bug**

**To Reproduce**
1. install jans server with openDJ database
2. access list of attributes
3. run /opt/jans/jans-cli/config-cli.py --operation-id get-attributes or access through jans-cli Interactive Mode

**Expected behavior**
able to get list of attributes

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188101396-d6ba53a3-bc7c-4ec2-ba3d-670d03f97ee0.png)
![image](https://user-images.githubusercontent.com/5729240/188102748-f8de4c24-43d1-4896-b90f-60f024b8deb0.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04

**Smartphone (please complete the following information):**
  - Device: 
  - OS: 
  - Browser 
  - Version 

**Additional context**
[error.log](https://github.com/JanssenProject/jans/files/9476513/error.log)

**Comment by devrimyatar** [comment]
Interactive mode is working
![image](https://user-images.githubusercontent.com/6398752/189292509-4afc22ba-1f0b-4936-9c06-7a5b6c261e9d.png)

**Comment by devrimyatar** [comment]
For command line, operation id is changed in swagger to `get-all-attribute`:
```
# /opt/jans/jans-cli/config-cli.py --info Attribute

Operation ID: get-all-attribute
  Description: Gets all attributes. Optionally max-size of the result, attribute status and pattern can be provided.
  Parameters:
  limit: Search size - max size of the results to return. [integer]
  pattern: Search pattern. [string]
  status: Status of the attribute [string]
  startIndex: The 1-based index of the first query result. [integer]
  sortBy: Attribute whose value will be used to order the returned response. [string]
  sortOrder: Order in which the sortBy param is applied. Allowed values are "ascending" and "descending". [string]
Operation ID: post-attributes
  Description: Adds a new attribute.
  Schema: /components/schemas/GluuAttribute
Operation ID: put-attributes
  Description: Updates an existing attribute.
  Schema: /components/schemas/GluuAttribute
Operation ID: get-attributes-by-inum
  Description: Gets an attribute based on inum.
  url-suffix: inum
Operation ID: delete-attributes-by-inum
  Description: Deletes an attribute based on inum.
  url-suffix: inum
Operation ID: patch-attributes-by-inum
  Description: Partially modify a GluuAttribute.
  url-suffix: inum
  Schema: Array of /components/schemas/PatchRequest

To get sample schema type /opt/jans/jans-cli/config-cli.py --schema <schma>, for example /opt/jans/jans-cli/config-cli.py --schema /components/schemas/PatchRequest
```

![image](https://user-images.githubusercontent.com/6398752/189293389-c650c242-35ee-4529-9a91-75046c4ca83f.png)

Doc is modified accordingly.
