### ISSUE TITLE
fix:( jans-cli) unable to get current session management

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2296]
**Describe the bug**
unable to get current session management
getting attached error

**To Reproduce**
1. laucnh jans-cli
2. select 12 then select 1 and then 1 to return current session 
3 See error

**Expected behavior**
should not get any error and show proper result

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188195539-ffeb1a9e-91ee-429c-b87f-29021a1ca704.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

error in log
Traceback (most recent call last):
  File "/opt/jans/jans-cli/config-cli.py", line 2273, in main
    cli_object.runApp()
  File "/opt/jans/jans-cli/config-cli.py", line 2260, in runApp
    self.display_menu(self.menu)
  File "/opt/jans/jans-cli/config-cli.py", line 1854, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1854, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1852, in display_menu
    self.display_menu(menu.parent)
  File "/opt/jans/jans-cli/config-cli.py", line 1852, in display_menu
    self.display_menu(menu.parent)
  File "/opt/jans/jans-cli/config-cli.py", line 1854, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1854, in display_menu
    self.display_menu(menu.get_child(menu_numbering[int(selection)]))
  File "/opt/jans/jans-cli/config-cli.py", line 1857, in display_menu
    getattr(self, 'process_' + m.method)(m)
  File "/opt/jans/jans-cli/config-cli.py", line 1134, in process_get
    api_caller = self.get_api_caller(endpoint)
  File "/opt/jans/jans-cli/config-cli.py", line 1428, in get_api_caller
    client = getattr(swagger_client, self.get_api_class_name(endpoint.info['tags'][0]))
AttributeError: module 'jca.swagger_client' has no attribute 'AuthSessionManagementApi'

**Comment by devrimyatar** [comment]
Swagger client was updated after this issue was created. Rather I got `Insufficient scopes`:
```
Unauthorized
b'oAuth authorization error Insufficient scopes! , Required scope: [https://jans.io/oauth/jans-auth-server/session.readonly], however token scopes: [https://jans.io/oauth/config/attributes.readonly, https://jans.io/oauth/config/attributes.write, https://jans.io/oauth/config/attributes.delete, https://jans.io/oauth/config/acrs.readonly, https://jans.io/oauth/config/acrs.write, https://jans.io/oauth/config/acrs.delete, https://jans.io/oauth/config/scopes.readonly, https://jans.io/oauth/config/scopes.write, https://jans.io/oauth/config/scopes.delete, https://jans.io/oauth/config/scripts.readonly, https://jans.io/oauth/config/scripts.write, https://jans.io/oauth/config/scripts.delete, https://jans.io/oauth/config/openid/clients.readonly, https://jans.io/oauth/config/openid/clients.write, https://jans.io/oauth/config/openid/clients.delete, https://jans.io/oauth/config/smtp.readonly, https://jans.io/oauth/config/smtp.write, https://jans.io/oauth/config/smtp.delete, https://jans.io/oauth/config/logging.readonly, https://jans.io/oauth/config/logging.write, https://jans.io/oauth/config/uma/resources.readonly, https://jans.io/oauth/config/uma/resources.write, https://jans.io/oauth/config/uma/resources.delete, https://jans.io/oauth/config/database/ldap.readonly, https://jans.io/oauth/config/database/ldap.write, https://jans.io/oauth/config/database/ldap.delete, https://jans.io/oauth/config/jwks.readonly, https://jans.io/oauth/config/jwks.write, https://jans.io/oauth/config/fido2.readonly, https://jans.io/oauth/config/fido2.write, https://jans.io/oauth/config/cache.readonly, https://jans.io/oauth/config/cache.write, https://jans.io/oauth/config/database/couchbase.readonly, https://jans.io/oauth/config/database/couchbase.write, https://jans.io/oauth/config/database/sql.readonly, https://jans.io/oauth/config/database/sql.write, readonly, https://jans.io/oauth/config/stats.readonly, jans_stat, https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly, https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write, https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.readonly, https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write, https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly, https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write, https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly, https://jans.io/oauth/jans-auth-server/config/adminui/license.write, https://jans.io/scim/bulk, https://jans.io/scim/users.write, https://jans.io/scim/fido.read, https://jans.io/scim/all-resources.search, https://jans.io/scim/fido2.read, https://jans.io/scim/groups.write, https://jans.io/scim/users.read, https://jans.io/scim/groups.read, https://jans.io/scim/fido2.write, https://jans.io/scim/fido.write, https://jans.io/oauth/jans-auth-server/config/properties.write, https://jans.io/oauth/jans-auth-server/config/properties.readonly, https://jans.io/oauth/config/database/sql.delete, https://jans.io/oauth/config/database/couchbase.delete, https://jans.io/oauth/config/agama.readonly, https://jans.io/oauth/config/agama.write, https://jans.io/oauth/config/agama.delete, https://jans.io/oauth/config/stats.readonly jans_stat, https://jans.io/oauth/jans-auth-server/session.readonly revoke_session, https://jans.io/oauth/jans-auth-server/session.delete, https://jans.io/oauth/config/user.readonly, https://jans.io/oauth/config/user.write, https://jans.io/oauth/config/user.delete, https://jans.io/scim/config.readonly, https://jans.io/scim/config.write, https://jans.io/oauth/config/organization.readonly, https://jans.io/oauth/config/organization.write, https://jans.io/oauth/jans-auth-server/config/adminui/user/role.read, https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.read]'
```
@pujavs Although `https://jans.io/oauth/jans-auth-server/session.readonly` in token scopes, config-api riases insufficient scope.

**Comment by devrimyatar** [comment]
There is extra `revoke_session` in swagger file, once this is fixed. This issue will extinct. 
![image](https://user-images.githubusercontent.com/6398752/189309102-de12f223-bac9-49c3-9a53-bc6ca0fa01f0.png)

Here is result:

![image](https://user-images.githubusercontent.com/6398752/189308933-2cf4a1cb-bfb9-4e96-b05a-137e570bcb63.png)
