### ISSUE TITLE
fix:(jans-cli) unable to update cache configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2300]
**Describe the bug**
unable to update cache configuration 

**To Reproduce**
1. install jans server
2. /opt/jans/jans-cli/config-cli.py
3. goto cache configuration 
4. modify cache configuration (for ex: maxOperationQueueLength)
5. see error 

**Expected behavior**
we should able to update cache configuration 

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188393111-bd92ae9c-fcdc-4584-9bab-2fd97e207300.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser
  - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 Path is wrong, it should be `/memcachedConfiguration/maxOperationQueueLength`


![image](https://user-images.githubusercontent.com/6398752/189298589-9de99ad8-5080-446f-a24b-df050fe67ba4.png)
