### ISSUE TITLE
fix:(jans-cli) unable to get list of jwk used by server

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2301]
**Describe the bug**
unable to get list of jwk used by server

**To Reproduce**
1. launch jan-cli interactive mode
2. go to json web key configuration 
3. select 1 option to get list of JWK used by server

**Expected behavior**
should able to get list of JWK used by server

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188404230-73404bc8-ad83-49e6-a4cf-fd57ff05da22.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate

![image](https://user-images.githubusercontent.com/6398752/189336222-b42dd862-1975-49f8-ac3a-2c0b67624259.png)
