### ISSUE TITLE
fix:(jans-cli) unable to Fido2 configuration properties

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2304]
**Describe the bug**
 unable to Fido2 configuration properties in jans-cli IM

**To Reproduce**
1. isntall jans server
2. start jans-cli in IM mode
3. select 5 for FIDO2 
4. select 1 for fido properties
5. See error

**Expected behavior**
should able to get fido properties

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188424251-532b8e0e-34a5-424d-8997-4006a778e667.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Version 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate

![image](https://user-images.githubusercontent.com/6398752/188846105-4144971b-2017-4b3d-b452-78d9bab60e0d.png)
