### ISSUE TITLE
fix: scim : unable to get user list users

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2312]
**Describe the bug**
run below command
/opt/jans/jans-cli/scim-cli.py --operation-id get-users

**To Reproduce**
1. run below command to get users
2. /opt/jans/jans-cli/scim-cli.py --operation-id get-users
3. See error

**Expected behavior**
should get list of users

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/188657671-1ea3770d-d248-4985-a352-d00120ff6b85.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**
[error.log](https://github.com/JanssenProject/jans/files/9497846/error.log)

**Comment by devrimyatar** [comment]
Unabel to replicate

![image](https://user-images.githubusercontent.com/6398752/192742574-29c24691-1a1e-44e0-b26f-8463281e0870.png)
