### ISSUE TITLE
feat (jans-config-api) : allow multiple pattern search in apis 

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2325]
**Is your feature request related to a problem? Please describe.**

In config-api APIs, we have a `pattern` query parameter allowing a single pattern search. We need multiple pattern search feature in APIs.

For example https://admin-ui-test.gluu.org/jans-config-api/api/v1/attributes?pattern=birthDate|jansAdminUIRole|c

**Comment by pujavs** [comment]
Implemented in Attributes resource via PR  [2491](https://github.com/JanssenProject/jans/pull/2491).
Note, delimiter used is comma(,). Please confirm if as expected inorder to implement in rest of the GET api

**Testing on MySQl Server:**

![image](https://user-images.githubusercontent.com/43700552/192772166-f25804ab-6fdf-4007-ae95-33e7980d6d87.png)

**Testing on LDAP:**
![image](https://user-images.githubusercontent.com/43700552/192771956-c54ecea0-8888-4308-add5-264f8a292b24.png)

**Comment by duttarnab** [comment]
Reopening this issue. 
- For attributes API the multiple pattern search works for only displayName. It will be useful for clients like admin-ui, tui if it works for inum.

- We need to implement multiple pattern searches for all apis. (Need  this in scopes apis to fix https://github.com/GluuFederation/flex/issues/502)

**Comment by pujavs** [comment]
Implemented via PR [2590](https://github.com/JanssenProject/jans/pull/2590)

- Attribute: implemented pattern search in inum as well
![image](https://user-images.githubusercontent.com/43700552/195078900-9acd9b9a-120b-486e-9e49-4407686793e1.png)

- Scope: implemented multiple pattern search along with inum
![image](https://user-images.githubusercontent.com/43700552/195088962-2a41224e-b2b9-4e5a-bbfa-08c345d5ae6d.png)

- Client: implemented multiple pattern search along with inum
![image](https://user-images.githubusercontent.com/43700552/195090157-dbd757f3-4827-49af-b304-898a44543193.png)

- UMA Resource: implemented multiple pattern search along with inum
![image](https://user-images.githubusercontent.com/43700552/195138397-da0a7536-7141-4efd-ac55-631e90ed2149.png)

- User: implemented multiple pattern search along with inum
![image](https://user-images.githubusercontent.com/43700552/195140842-2ca98b31-5ade-4f18-a35b-3936cd7e0894.png)
