### ISSUE TITLE
fix: (jans-cli) unable to get  list of couchbase configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2331]
**Describe the bug**
 unable to get  list of couchbase configuration

**To Reproduce**
1. install jans server with couchbase
2. run /opt/jans/jans-cli/config-cli.py
3. select 7 for database
4. 2 for couchbase configuratoin 
5. 1  to get list of couchbase configuration
6. See error

**Expected behavior**
should get couchbase configuration list

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189096045-7b847213-c7c5-4cc4-8a7e-6c1759ba534e.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
CB endpoint is removed https://github.com/JanssenProject/jans/pull/2480
