### ISSUE TITLE
fix:(jans-cli) unable to update openid client

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2332]
**Describe the bug**

**To Reproduce**
1.run /opt/jans/jans-cli/config-cli.py
2. select 8 for oauth
3. 1 for openid and 3 or 6 to update openid client
4. add update information 
5. See error

**Expected behavior**
should able to update openid client
please check display name it is not updated

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189134806-a6e963d4-88c7-446b-b064-a47df3540c30.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
@manojs1978 & @devrimyatar not able to replicate this issue on LDAP. 
![image](https://user-images.githubusercontent.com/43700552/189380133-8723b4ad-0d3d-483e-b4f8-e65f9dc01433.png)

**Comment by devrimyatar** [comment]
@pujavs I were be able to replicate. It can't update **displayName** unless we do within **customAttribute**
![image](https://user-images.githubusercontent.com/6398752/189483150-cdc60fcc-463d-45ea-add1-d10687367525.png)

![image](https://user-images.githubusercontent.com/6398752/189483221-7f75b6f4-de69-43eb-b0ab-0bbdc182463b.png)

**Comment by pujavs** [comment]
- Error screenshot:
![image](https://user-images.githubusercontent.com/43700552/195661304-b5afeb7a-3e98-478e-85cf-285054ba3907.png)

- Assigning to @qbert2k as It is **LocalizedString** issue being looked into by @qbert2k

**Comment by devrimyatar** [comment]
IM is depreciated
