### ISSUE TITLE
fix:(jans-cli) unable to get current session in Auth : session management

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2335]
**Describe the bug**
unable to get current session in Auth : session management

**To Reproduce**
1. launch jans-cli by running /opt/jans/jans-cli/config-cli.py
2. select 12 > 1 > 1 to get current session
3. See error

**Expected behavior**
should get current session details

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189290913-4c93290d-2186-4e9a-adee-b5d824f26c43.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB : couchbase

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This was fixed, you have to re-install jans
