### ISSUE TITLE
fix: (jans-cli) unable to create group

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2338]
**Describe the bug**
unable to create group

**To Reproduce**
1. /opt/jans/jans-cli/scim-cli.py
2. select 2 then 2 to create new group
3. add mendatory information 

**Expected behavior**
should able to create group

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189304895-940aeae3-36f7-4193-9a9e-627b6a9111c2.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20
  - couchbase

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/6398752/192743111-c1d2b4b7-366a-416e-9e73-0b95a74deb59.png)
