### ISSUE TITLE
Fix error in swagger pecification

### ISSUE THREAD

**Issue by syntrydy** [JanssenProject/jans#2344]
**Is your feature request related to a problem? Please describe.**
The authorizationRequestCustomAllowedParameters property is defined as an array of strings instead of an array of objects as you can see below the reason why we are receiving the objects as strings. 

`authorizationRequestCustomAllowedParameters:[{"paramName":"customParam1","returnInResponse":false},{"paramName":"customParam3","returnInResponse":false},{"paramName":"customParam5","returnInResponse":true},{"paramName":"customParam4","returnInResponse":true},{"paramName":"customParam2","returnInResponse":false}]
`

![image](https://user-images.githubusercontent.com/7513418/189351171-97e461bf-e0e5-48aa-bcfd-651ba934748c.png)

**Describe the solution you'd like**
To sort this out change the string to pass an object instead.

**Comment by pujavs** [comment]
@syntrydy, this has been fixed, request you to please check if any issue.

- https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger-auto.yaml#L8165
![image](https://user-images.githubusercontent.com/43700552/198563217-743c03ac-8b22-4b7a-85d9-685c37e5e3e8.png)


- https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L4724
![image](https://user-images.githubusercontent.com/43700552/198563087-e4cd6b48-bbcc-4e3a-b1a1-1063dfe2eee5.png)
