### ISSUE TITLE
fix (jans-config-api) : incorrect response field type in swagger specs

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2345]
**API:** `GET` [/jans-config-api/api/v1/jans-auth-server/config](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml#/operations/Configuration%20%E2%80%93%20Properties/get-properties)

**Current behavior**

In swagger specs, the`authorizationRequestCustomAllowedParameters` field in the response is an array of string.
![image](https://user-images.githubusercontent.com/32794267/189353600-da948482-b5c7-4b60-ba37-b400b55ae740.png)

**Expected behavior**

The `authorizationRequestCustomAllowedParameters` field in response should be array of objects.

```
"authorizationRequestCustomAllowedParameters":[{"paramName":"customParam1","returnInResponse":false},{"paramName":"customParam3","returnInResponse":false},{"paramName":"customParam5","returnInResponse":true},{"paramName":"customParam4","returnInResponse":true},{"paramName":"customParam2","returnInResponse":false}]
```

**Comment by pujavs** [comment]
fixed: 
![image](https://user-images.githubusercontent.com/43700552/189392475-d84ccd9a-6783-4fbd-9465-bd3995cdec17.png)


[src.test.resources.feature.config.properties.properties.pdf](https://github.com/JanssenProject/jans/files/9537024/src.test.resources.feature.config.properties.properties.pdf)

**Comment by pujavs** [comment]
@duttarnab, change implemented via PR [2348](https://github.com/JanssenProject/jans/pull/2348), please verify
