### ISSUE TITLE
fix:(jans-cli) getting error ID token expired

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2346]
**Describe the bug**
getting error ID token expired

**To Reproduce**
1. install janssen server
2. access /opt/jans/jans-cli/config-cli.py and do device code verification 
3. access jans-cli after some time may be 1-2 days
4. getting error token expired
5. See error

**Expected behavior**
should able to access jans-cli

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189370079-2d8417bf-1cb9-4ba7-beb3-56940300a6f6.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed
![image](https://user-images.githubusercontent.com/6398752/189482028-50baa5e3-ea85-4d90-8238-fd75333b4cdb.png)
