### ISSUE TITLE
chore(jans-config-api): use scim configuration from `jans-scim-model` module

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#2349]
Issue #1944 is closed. Now we can proceed with re-using the scim configuration  classes in jans-config-api:

Please add this dep to your config-api scim plugin:
```
		<dependency>
			<groupId>io.jans</groupId>
			<artifactId>jans-scim-model</artifactId>
		</dependency>
```

And replace these two classes:
`io.jans.configapi.plugin.scim.model.config.ScimAppConfiguration` -> `io.jans.scim.model.conf.AppConfiguration`
`io.jans.configapi.plugin.scim.model.config.ScimConf` -> `io.jans.scim.model.conf.Conf`

Since setters/getters of `ScimAppConfiguration` don't match the same names in `AppConfiguration`, you'll have to adjust existing calls accordingly

**Comment by pujavs** [comment]
implemented via PR [2348](https://github.com/JanssenProject/jans/pull/)
