### ISSUE TITLE
docs(jans-auth-server): add json payload examples to the generated swagger

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2355]
### Description

The swagger documentation should include example payloads to help development and execution of calls manually or via scripting clear.

https://swagger.io/docs/specification/adding-examples/
### Prepare

- [x] Read contribution guidelines
- [x] Read license information

- Development target issue #2353

**Comment by ossdhaval** [comment]
Hi @yuriyz 

Can you confirm the status of this issue that it is still an open item that we need to work on? I see examples in the Swagger documentation but I can't see relevant commits in `jans-auth-server/docs/swagger.yaml`. 

Let me know if this is done and I can close it.

**Comment by ossdhaval** [comment]
Closing this based on the previous comment.
