### ISSUE TITLE
docs(jans-client-api): add json payload examples to the generated swagger

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2356]
### Description

The swagger documentation should include example payloads to help development and execution of calls manually or via scripting clear.

https://swagger.io/docs/specification/adding-examples/
### Prepare

- [x] Read contribution guidelines
- [x] Read license information

- Development target issue #2353

**Comment by yuriyz** [comment]
Scheduled jans-client-api removal https://github.com/JanssenProject/jans/issues/2582
