### ISSUE TITLE
fix: (jans-cli) unable to add new couchbase configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2360]
**Describe the bug**
unable to add new couchbase configuration

**To Reproduce**
1. launch /opt/jans/jans-cli/config-cli.py
2. select 7 for database and 2 for couchbase
3.select 2 to add new configuration
 4. add mendator fields
 5.  See error

**Expected behavior**
should able to create couchbase configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/189629801-773ad9ba-16f5-4a56-bdcf-80ebb4d03cbb.png)

**Desktop (please complete the following information):**
  - OS: ubuntu/centos8
  - Browser
  - Version  20/8
  - DB- mysql

**Smartphone (please complete the following information):**

**Additional context**
[configapi.log](https://github.com/JanssenProject/jans/files/9547061/configapi.log)

**Comment by devrimyatar** [comment]
CB endpint is removed https://github.com/JanssenProject/jans/pull/2480
