### ISSUE TITLE
fix:(scim-cli) multiple option with same name (Query User resources)

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2382]
**Describe the bug**
multiple option with same name (Query User resources)

**To Reproduce**
please check below screenshot 1 and 7 option are same in scim-cli user menu 
and both have same functionality which is not working

**Expected behavior**
there should be only one option with "Query User resources" functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/190082195-017fcfe0-4ea9-4aa3-986c-7a2b5803adab.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@jgomer2001 May be we can change this description:
https://github.com/JanssenProject/jans/blob/main/jans-scim/server/src/main/resources/jans-scim-openapi.yaml#L1493

**Comment by devrimyatar** [comment]
Option 7 is removed in commit https://github.com/JanssenProject/jans/commit/98ac92023bd2c0603fb825bbc436b6e0aa336ceb
