### ISSUE TITLE
fix:(jans-cli) get scope by type/ get scope by creatorID not working 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2399]
**Describe the bug**
get scope by type/ get scope by creatorID not working 

**To Reproduce**
1. run /opt/jans/jans-cli/config-cli.py
2. select 8 then select 2 for scope
3.select 8 to get scope by type

**Expected behavior**
should get scope details when we access by scope type

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/190580458-2eea7757-62c9-433d-a9ca-1572314c79e2.png)

**Desktop (please complete the following information):**
  - OS: opensuse
  - Version 15
  - -DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate,  fixed by swagger client update

![image](https://user-images.githubusercontent.com/6398752/193269813-b2cb0566-0ac4-433e-a2f5-516bd2cc8770.png)
