### ISSUE TITLE
fix:(jans-cli) unable to return current session management

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2402]
**Describe the bug**

**To Reproduce**
launch jans-cli by running /opt/jans/jans-cli/config-cli.py
select 12 > 1 > 1 to return current session

**Expected behavior**
should get some session details

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/190599750-d17ffd7e-60e3-4ed0-ad88-dfa263f2ee0d.png)

**Desktop (please complete the following information):**
  - OS: opensuse
  - Version 15
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate. Probably fixed by swagger client update.

![image](https://user-images.githubusercontent.com/6398752/193261571-70eab879-5331-4ab2-9f9d-4b7a7c578329.png)
