### ISSUE TITLE
fix: (jans-cli) unable to update organisation info

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2405]
**Describe the bug**

**To Reproduce**
1. launch jans-cli by running /opt/jans/jans-cli/config-cli.py
select 14 > 2  to update org info

**Expected behavior**
should able to update org info

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/190602407-a8b5b96f-c4df-42ec-ab7b-426f73323467.png)

**Desktop (please complete the following information):**
  - OS: opensuse
  - Browser 
  - Version 15
  - FB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 This was answered before. Please do not re-open issue that is answered before.

You should use **add** operation for properties having value `null`

![image](https://user-images.githubusercontent.com/6398752/193260858-9963acb0-6710-424c-bb63-83a7e3946c9a.png)
