### ISSUE TITLE
Web Authentication: An API for accessing Public Key Credentials Level 2

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#241]
https://www.w3.org/TR/2020/CR-webauthn-2-20201222/

Level 2 adds an Apple attestation, some management features, enterprise attestation, and does some clean-up

**Comment by tailnet-h-usky-io** [comment]
Is this why I cannot get Passkeys working on Safari or iOS?

**Comment by yackermann** [comment]
@moabu this can be closed.
