### ISSUE TITLE
fix(docs): new option added to setup.py needs to be documented

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#2416]
**Describe the bug**
This [PR](https://github.com/JanssenProject/jans/pull/2413) recently added a new option to reset DB, but PR doesn't have any accompanying documentation changes. This option needs to be documented to make it useful.

**Expected behavior**
Documentation describing when and how to use this option

**Comment by maduvena** [comment]
- [ ] fix(docs) : Post install setup
