### ISSUE TITLE
feat (jans-auth-server) : issue spontaneous scope  creation

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2418]
**Steps to reproduce the issue**

1. Register a oidc client with `allowSpontaneousScopes` to `true` and `spontaneousScopes` field containing scope regex expression (like `^transaction:.+$`).
2.  Using authz_url try to create spontaneous scopes (eg: `transaction:100`, `transaction:101`).
3. Spontaneous scopes will not be created in database.

**Current Result**
Spontaneous scopes will not be created in database.

**Expected Result**
Spontaneous scopes should not be created in database.

**Comment by yuriyz** [comment]
@duttarnab Today's build shows that it works. See https://jenkins.jans.io/jenkins/job/jans-auth-server/7441/testngreports/io.jans.as.client.ws.rs/SpontaneousScopeHttpTest/

Test source code here: https://github.com/JanssenProject/jans/blob/a7013f33404b2f0e0e61f4a87b1665dbe2883927/jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SpontaneousScopeHttpTest.java#L42

Give me full AS log in TRACE log level when it didn't work for you.

**Comment by yuriyz** [comment]
Closing as not reproducible. @duttarnab please attach full TRACE log if it's still reproducible for you.
