### ISSUE TITLE
feat: introduce endpoint to manage custom assets

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2419]
## Usecase

There should be a clear non filesystem (volume) based solution for possible user customization's such as login pages, CSS, libraries ..etc. Managed clearly by an API endpoint then further optimized by drag and drop in a parent admin ui.

## Possible Solutions:
1. Support different cloud buckets such as S3, Google bucket ...etc
2. We use persistence and come up with a method to store the objects efficiently 

My personal recommendation is to support this directly in our persistence and remove all file based requirements.

**Comment by jgomer2001** [comment]
Potentially related
https://github.com/GluuFederation/oxCore/issues/223
https://github.com/GluuFederation/oxCore/issues/188

**Comment by nynymike** [comment]
What should we call this endpoint? `/agama-assets` ?

**Comment by jgomer2001** [comment]
I'd say `/jans-assets` because it applies to several projects

**Comment by pujavs** [comment]
**Requirement breakdown:**
1. Centrally managing assets(html,css,js,lib, etc) and leveraging existing DocumentStore for the same.
2. Managing assets(html,css,js,lib, etc) in jetty classpath will require to use Jetty API.

**Comment by ossdhaval** [comment]
@pujavs It looks like this change may require a documentation update as well. Please evaluate the documentation aspect and make the change along with the code change within this PR itself.

**Comment by pujavs** [comment]
Implemented change via PR [8096](https://github.com/JanssenProject/jans/pull/8096)
