### ISSUE TITLE
fix: unable to insert oidc client

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2455]
##### OidcClient
error:

```
Caused by: 
com.querydsl.core.QueryException: Caught SQLException for insert into jansdb.jansClnt (jansAccessTknAsJwt, jansAccessTknSigAlg, jansAppTyp, jansAttrs, inum, displayName, jansClntSecret, jansClntURI, del, jansDisabled, jansLogoutSessRequired, jansLogoutURI, jansGrantTyp, jansInclClaimsInIdTkn, jansLogoURI, jansPersistClntAuthzs, jansPolicyURI, jansRedirectURI, jansRptAsJwt, jansScope, jansSubjectTyp, jansTknEndpointAuthMethod, jansTosURI, jansTrustedClnt, objectClass, dn, doc_id)|values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
...
Caused by: 
java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'displayName' at row 1
```

The payload is the following:

```json
{
  "dn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans",
  "inum": "1201.d52300ed-8193-510e-b31d-5829f4af346e",
  "displayName": "test-client",
  "clientSecret": "SEw7VOX8m9ah",
  "frontChannelLogoutUri": "null",
  "redirectUris": [
    "https://moabu-21f13b7c-9069-ad58-5685-852e6d236020.gluu.info/.well-known/scim-configuration"
  ],
  "grantTypes": [
    "client_credentials"
  ],
  "applicationType": "native",
  "subjectType": "pairwise",
  "tokenEndpointAuthMethod": "client_secret_basic",
  "scopes": [
    "inum=9e4d1b6a-a978-4457-bc16-cda74309ee04,ou=scopes,o=jans"
  ],
  "accessTokenSigningAlg": "RS256",
  "attributes": {
    "parLifetime": 600
  },
  "authenticationMethod": "client_secret_basic",
  "baseDn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans"
}
```

**Comment by moabu** [comment]
Related https://github.com/JanssenProject/jans/issues/2288

**Comment by pujavs** [comment]
Working fine in LDAP but throwing the above error in MySQL. Attached logs and testing details.
Seems  common issue with MySQL  -> incorrect-string-value
Added extra logs for debug and captured logs, assigning to @yurem for guidance
**LDAP Testing with latest code:**
![image](https://user-images.githubusercontent.com/43700552/192833776-80c4ebc0-8129-4dee-8f27-bb738e205922.png)

**MySQL Testing with latest code:**
![image](https://user-images.githubusercontent.com/43700552/192833850-c561b77d-d4f7-4a21-80a0-e2d9e79fed06.png)

**Logs:**
[logs_mysql_logs_2455.zip](https://github.com/JanssenProject/jans/files/9667042/logs_mysql_logs_2455.zip)

**Comment by pujavs** [comment]
assigning to @yurem for verification

**Comment by yurem** [comment]
@pujavs can you share sample displayName which led to this issue?

**Comment by pujavs** [comment]
**sample data**
curl -X POST -k -H 'Content-Type: application/json' -H 'Authorization: Bearer f701d576-28cb-46d0-a8a0-61dab4ce0dac' -i 'https://jenkins-build.jans.io/jans-config-api/api/v1/openid/clients/' --data '{"dn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans","inum": "1201.d52300ed-8193-510e-b31d-5829f4af346e","displayName": "test-client","clientSecret": "SEw7VOX8m9ah","frontChannelLogoutUri": "null","redirectUris": ["https://moabu-21f13b7c-9069-ad58-5685-852e6d236020.gluu.info/.well-known/scim-configuration"],"grantTypes": ["client_credentials"],"applicationType": "native","subjectType": "pairwise","tokenEndpointAuthMethod": "client_secret_basic","scopes": ["inum=03F8-EDD7,ou=scopes,o=jans"],"accessTokenSigningAlg": "RS256","attributes": {"parLifetime": 600},"authenticationMethod": "client_secret_basic","baseDn": "inum=1201.d52300ed-8193-510e-b31d-5829f4af346e,ou=clients,o=jans"}'

**Comment by yurem** [comment]
This issue related to https://github.com/JanssenProject/jans/issues/1482

**Comment by yurem** [comment]
displayName in DB defined as text type. But in code it's LocalizedString. ORM is trying to convert object to String and send value to server. And we see in logs results of this HashMap->String conversion:
```
Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'displayName' at row 1
```

![изображение](https://user-images.githubusercontent.com/6104200/194008106-b85b4549-5870-4b4b-9353-f96cede5ff38.png)

**Comment by yurem** [comment]
I added quick fix to instruct ORM to work with LocalizedString as with multivalued attribute: https://github.com/JanssenProject/jans/pull/2542/files

**Comment by yurem** [comment]
We need to fix: https://github.com/JanssenProject/jans/issues/1482 to avoid such issues in future
