### ISSUE TITLE
feat(jans): OpenID Client and Users CustomAttribute should return appropriate attribute type 

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#2483]
Currently CustomAttributes for OpenID Client and Users return type as String.
Need changes to return appropriate CustomAttribute type

This would involve change in various modules including config-api

**Comment by moabu** [comment]
Created from a chat thread internally

**Comment by yuriyz** [comment]
I will change Client on AS side to use `CustomObjectAttribute`.
