### ISSUE TITLE
fix(jans-scim): discrepency in `ServiceProviderConfig`

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2484]
## ServiceProviderConfig

- According to API, attribute `authenticationSchemes` is a single object, backend returns an array of objects.

**Comment by jgomer2001** [comment]
it's an array of objects: https://github.com/JanssenProject/jans/blob/main/jans-scim/server/src/main/resources/jans-scim-openapi.yaml#L1883-L1885
