### ISSUE TITLE
fix(jans-client-api): update swagger documentation

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2486]
The swagger https://github.com/JanssenProject/jans/blob/6fa53eb63f3f08a217c137575052ef11a6a560ce/jans-client-api/server/src/main/resources/swagger.yaml does **not** contain all the endpoints the backend declares such as `/get-rp` . This needs to get updated and documented.

**Comment by yuriyz** [comment]
Scheduled jans-client-api removal https://github.com/JanssenProject/jans/issues/2582
