### ISSUE TITLE
fix (jans-config-api) : the associated-clients is missing in scope api response

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2517]
**Steps to reproduce**

1. Execute `GET` `/api/v1/scopes` api with query parameter `withAssociatedClients` set to `true`.
    eg: `http://<op_host>/jans-config-api/api/v1/scopes?withAssociatedClients=true`

2. In response, the scopes are missing the `clients` field even if the scopes have associated-clients.

**Expected Result**
In response, the scopes should have the `clients` field.

![image](https://user-images.githubusercontent.com/32794267/193315195-adf95818-8867-40a2-9f6e-e60ab6c60607.png)

**Comment by pujavs** [comment]
Found  issue only for `uma` scope type.  Pls. find screenshots post fix

1. scopeType: oauth
![image](https://user-images.githubusercontent.com/43700552/193584767-9a7a6ade-d60b-4410-a89d-a3cb65d3d3d9.png)

2. scopeType: openid
![image](https://user-images.githubusercontent.com/43700552/193586663-6a2210f0-4a62-40b8-9631-bfffaccd415f.png)

3. scopeType: dynamic
![image](https://user-images.githubusercontent.com/43700552/193587929-80edbdc0-aedb-42ed-84d7-c2e5e0ec7791.png)

4. scopeType: uma
![image](https://user-images.githubusercontent.com/43700552/193636826-591c45d0-306b-4e1d-80fe-be7a892cdc99.png)

5. scopeType: spontaneous
![image](https://user-images.githubusercontent.com/43700552/193637082-b8ac160c-3c93-40e1-a8c0-af56f1258fae.png)
