### ISSUE TITLE
FEAT(jans-auth-server): Support OpenID Connect Native SSO for Mobile Apps

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#2518]
This customer challenge is just getting worse. While supporting draft specs is normally not encouraged, I think this would be helpful sooner rather then later.

https://openid.net/specs/openid-connect-native-sso-1_0.html

See video from Identiverse: https://www.youtube.com/watch?v=8BkblIYjegk
And blog on the challenges of cookie sharing: https://developer.okta.com/blog/2022/01/13/mobile-sso

**Comment by yuriyz** [comment]
I will take over it
