### ISSUE TITLE
fix(jans-config-api): Error in custom script schema

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#2583]
**Describe the bug**
When adding a custom script, the [documentation](https://docs.jans.io/head/admin/developer/interception-scripts/#basic-schema-of-a-custom-script) tells us to get a basic custom script schema and modify it before sending it as a payload to the custom scripts POST endpoint. Using this schema, the auth server throws an LDAP exception and returns a 500 error as such:
```
{
"cause2":"LDAPException(resultCode=20 (attribute or value exists), diagnosticMessage=&apos;The provided LDAP attribute jansConfProperty contains duplicate values&apos;, ldapSDKVersion=6.0.0, revision=524c20f3bbcc0d83fb56b9e136a2fd3a7f60437d)",
"cause1":"io.jans.orm.exception.EntryPersistenceException: Failed to persist entry: inum=bf0057ef-be41-48ff-977d-c9c316882d69,ou=scripts,o=jans",
"servlet":"io.jans.configapi.rest.ApiApplication",
"cause0":"org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to persist entry: inum=bf0057ef-be41-48ff-977d-c9c316882d69,ou=scripts,o=jans",
"message":"org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to persist entry: inum=bf0057ef-be41-48ff-977d-c9c316882d69,ou=scripts,o=jans",
"url":"/jans-config-api/api/v1/config/scripts",
"status":"500"
}
```
According to [batch mode documentation](https://docs.jans.io/head/admin/config-guide/jans-cli/cli-custom-scripts/#adds-a-new-custom-script), `moduleProperties` and `jansConfProperty` **must** be set to lists. The basic schema should reflect this.

**To Reproduce**
1. Install Jans on Ubuntu 20
2. Get the basic custom script schema by executing `/opt/jans/jans-cli/config-cli.py --schema /components/schemas/CustomScript > schema.json`
3. Edit the JSON file and put in dummy details, but leave `moduleProperties` and `jansConfProperty` unmodified.
4. Send the JSON as payload for the POST endpoint as such: `/opt/jans/jans-cli/config-cli.py --operation-id post-config-scripts --data schema.json`
5. The endpoint should return the 500 error mentioned above.

**Expected behavior**
The custom script should be added normally.

**Desktop (please complete the following information):**
  - Device: DigitalOcean VM
  - OS: Ubuntu 20.04
  - Browser: Mozilla Firefox

**Additional context**
By wrapping the dicts in a list, the error is fixed..

```
"moduleProperties": [{
  "value1": null,
  "value2": null,
  "description": null
}],
"configurationProperties": [{
  "value1": null,
  "value2": null,
  "description": null,
  "hide": false
}]
```

**Comment by devrimyatar** [comment]
@SafinWasi This is neither config-api nor cli issue. It works well with this json

```
{
  "name": "testscript",
  "aliases": [
    "string"
  ],
  "description": "string",
  "script": "print('Hello World')",
  "scriptType": "ciba_end_user_notification",
  "programmingLanguage": "python",
  "level": 166,
  "revision": 179,
  "enabled": false,
  "modified": false,
  "internal": true,
  "locationPath": "string",
  "locationType": "file",
  "baseDn": "string"
}
```

![image](https://user-images.githubusercontent.com/6398752/220050471-d44f4804-3181-4d17-99be-44e3904ba8e3.png)
