### ISSUE TITLE
Documentation regarding configuration

### ISSUE THREAD

**Issue by nathmo** [JanssenProject/jans#259]
Hi, I'm looking for some documentation regarding the configuration of the server such that it use my IAM (LemonLDAP in that case) like what am i supposed to set up to make it works. So far i can't find much. i tried to replicate the config of my working OXD server as both are really close but i don't see the settings regarding the Gluu server in it. like the keys, scope etc. (and i have no idea what right i should give to the OXD serer from my IAM 

thanks in advance for any help.

**Comment by yuriyz** [comment]
Scheduled jans-client-api removal https://github.com/JanssenProject/jans/issues/2582
