### ISSUE TITLE
Re-design oxd Connect part to work inside user-agent instead of as backchannel app.

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#260]
Refer : https://github.com/GluuFederation/oxd/issues/462

**Comment by yuriyz** [comment]
Latest dropwizard still sticks to jetty 9 (`<jetty.version>9.4.45.v20220203</jetty.version>`).
It can be right time to drop dropwizard and migrate to weld/resteasy and get it works exactly in same way as AS and config-api work.

https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-dependencies/pom.xml#L52

**Comment by yuriyz** [comment]
Yes, it is good amount of work. Also deployment scripts has to be corrected. Instead of standalone run it would be deployment of war to jetty (same story as with AS and jans-config-api).

**Comment by yuriyz** [comment]
Done within https://github.com/JanssenProject/jans/pull/1319
