### ISSUE TITLE
Modify oxd-spring, oxd-java-sample and python client script to test jans-client-api

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#261]
Modify oxd-spring, oxd-java-sample and python client script to test jans-client-api.

https://github.com/GluuFederation/oxd-spring
https://github.com/GluuFederation/oxd-java-sample
https://www.gluu.org/docs/oxd/tutorials/python/

**Comment by yuriyz** [comment]
Scheduled jans-client-api removal https://github.com/JanssenProject/jans/issues/2582
