### ISSUE TITLE
feat: implement prompt=create: Initiating User Registration via OpenID Connect 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#2616]
[Initiating User Registration via OpenID Connect 1.0 - draft 06](https://openid.net/specs/openid-connect-prompt-create-1_0.html)

Several years of deployment and implementation experience with [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-prompt-create-1_0.html#OpenID.Core) [[OpenID.Core](https://openid.net/specs/openid-connect-prompt-create-1_0.html#OpenID.Core)] has uncovered a need, in some circumstances, for the client to explicitly signal to the OpenID Provider that the user desires to create a new account rather than authenticate an existing identity.

This specification allows the client to indicate to the OpenID Provider that the user desires to create an account improving the user experience by reducing the friction for the user of finding the sign-up link on the default login page.

This specification defines a new value for the prompt parameter.

**Comment by ossdhaval** [comment]
Thanks @gustavovalverde for your feedback about this feature and for highlighting the duplicate. :+1: 

This feature is on our roadmap and we will share more details when it is planned for release.

**Comment by nynymike** [comment]
Frankly, this should be done in an Agama flow. Perhaps we could do something as simple as redirect to `acr=agama&agama_flow=____`

**Comment by yuriyz** [comment]
Implemented within duplicated issue https://github.com/JanssenProject/jans/issues/7899

PR https://github.com/JanssenProject/jans/pull/8035
