### ISSUE TITLE
docs: "Kubernetes" docs names should be generalized to "Cloud Native"

### ISSUE THREAD

**Issue by shmorri** [JanssenProject/jans#2658]
Currently, our documentation is divided along Cloud Native and Virtual Machine administration, since these are the two broad categories. So far, we've been using "Kubernetes" instead of "Cloud Native" for those docs names, but Kubernetes is just one deployment method in a broader category of administration.

**Comment by moabu** [comment]
Right but the documentation that is renamed is not cloud native its Kubernetes. It should probably be under a bigger umbrella under cloud-native but it shouldn't be renamed to cloud-native.

**Comment by ossdhaval** [comment]
@shmorri @moabu This is an issue created long back. Are we ok with what we presently have? Do we have any action items here? If not, then let's close this issue.
