### ISSUE TITLE
fix: jans-cli: duo scripts showing script  error when accessed using  custom script

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2680]
**Describe the bug**
duo scripts showing stack trace error when accessed using using custom script

**To Reproduce**
1. install jans
2. start jans-cli in ineractive mode
3. goto custom script  and search for duo script

**Expected behavior**
should not get any script error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/196903487-00fbe9ab-bbde-4734-89d5-163bf4da5084.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**
Add any other context 
[jans-auth.log](https://github.com/JanssenProject/jans/files/9828154/jans-auth.log)
[2022_10_20.jetty.log](https://github.com/JanssenProject/jans/files/9828155/2022_10_20.jetty.log)
.

**Comment by devrimyatar** [comment]
1) Works with cli-tui
![image](https://user-images.githubusercontent.com/6398752/205692304-083fda0b-641f-44c2-a00f-f37610f66771.png)

2) works with cli command line
![image](https://user-images.githubusercontent.com/6398752/205692676-5e7afb3b-aad1-4184-bbfb-96b34f01adf5.png)
