### ISSUE TITLE
fix(jans-config-api): incorrect https status for GET requests

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2689]
When requesting any AdminUI entities that do not exist, the expected behavior would be to get a 404 response from the server. However, currently I'm getting either a 400 bad request (for `role` and `permission`) or 500 server error (for `rolePermissionMapping`)

**Comment by pujavs** [comment]
Fixed via PR [2697](https://github.com/JanssenProject/jans/pull/2697)
**Note correct URL:**
- /jans-config-api/admin-ui/adminUIRoles
- /jans-config-api/admin-ui/adminUIPermissions
- jans-config-api/admin-ui/adminUIRolePermissionsMapping

**Testing:**
- /jans-config-api/admin-ui/adminUIRoles
![image](https://user-images.githubusercontent.com/43700552/197254309-62b9cec0-7a1a-4a2c-8c6a-bb8d94447ff6.png)

- /jans-config-api/admin-ui/adminUIPermissions
![image](https://user-images.githubusercontent.com/43700552/197254361-e9ddd159-7c4f-4842-9852-52d0486d7386.png)

- jans-config-api/admin-ui/adminUIRolePermissionsMapping
![image](https://user-images.githubusercontent.com/43700552/197254434-f8794fdc-26d2-4af1-a578-dccd10b963ca.png)

**Comment by moabu** [comment]
@pujavs 

CRUD operations all work correctly. However, the response you get when trying to GET an entity that actually doesn't exist. So the proper response code should be 404, instead I get 400 or 500.

**Comment by pujavs** [comment]
Fixed
**1.adminUIRoles**
-Before Fix:
![image](https://user-images.githubusercontent.com/43700552/199689309-54ddf1ec-0bb3-4a02-a29f-814c3c359587.png)
-After Fix:
![image](https://user-images.githubusercontent.com/43700552/199697820-5d3e3f6f-dacb-4666-bc64-0b1c34be80d4.png)

**2.adminUIPermissions**
-Before Fix:
![image](https://user-images.githubusercontent.com/43700552/199694202-21978444-83e8-4a54-bede-4139c8566ce1.png)
-After Fix:
![image](https://user-images.githubusercontent.com/43700552/199697944-4ab05433-3fbb-453d-a3ec-74630cad3099.png)

**3.adminUIRolePermissionsMapping**
-Before Fix:
![image](https://user-images.githubusercontent.com/43700552/199694800-730e8783-7f41-47eb-aa3f-dd10870e7ef4.png)
-After Fix:
![image](https://user-images.githubusercontent.com/43700552/199723973-2a303912-fb93-4cf9-b314-5e147221d4b6.png)

**Comment by pujavs** [comment]
Fixed via [2854 ](https://github.com/JanssenProject/jans/pull/2854)
