### ISSUE TITLE
fix: jans-linux-setup auto generated yaml for config-api scopes

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#2695]
**Describe the bug**
Since yaml file is auto-generated, jans-setup should use it for gathering scopes.

**Comment by iromli** [comment]
@devrimyatar do we still need to generate scopes from yaml? because jans-config-api will create missing scopes and also adding those scopes to jca client.

**Comment by pujavs** [comment]
yes we need this, jans-linux-setup should create required scopes on installation. Its a feature and not a bug. 
**jans-linux-setup** creates the scopes during installation for existing functionality and assigns it to internal client as well as test client.
**config-api** start-up checks and creates scopes for any new endpoints that are added post installation.

**Comment by devrimyatar** [comment]
Implemented
