### ISSUE TITLE
SCIM user extension schema URI not updatable

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#271]
Ensure the two fields highlighted in the image can be managed through the API

![Screenshot from 2022-01-07 07-30-53](https://user-images.githubusercontent.com/5444180/148545126-81fa5995-afe7-4a99-8b8c-b189474c6a69.png)

Reference ticket 10239

**Comment by pujavs** [comment]
Implemented following two endpoints - /jans-config-api/scim/config
1) GET
2) PATCH

[src.test.resources.feature.scim.config.scim-config.pdf](https://github.com/JanssenProject/jans/files/7913704/src.test.resources.feature.scim.config.scim-config.pdf)

**Comment by pujavs** [comment]
Feature merged with main branch
