### ISSUE TITLE
test(jans-linux-setup): load agama test data

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#2733]
When the installer loads test data (`-t` switch), the following is required:

1. Import [this ldif](https://github.com/JanssenProject/jans/files/9871130/agama-test-data.ldif.txt) file.  Preliminar rendering is required, i.e. fill the `%(hostname)s` placeholder
2. Copy all files and folders found at https://github.com/JanssenProject/jans/tree/main/agama/engine/src/test/resources/templates into `/opt/jans/jetty/jans-auth/agama/ftl/`
3. Modify json content of attribute `jansConfDyn` in `ou=jans-auth,ou=configuration,o=jans` so that Agama configuration section looks like:

```
"agamaConfiguration": {
    "disableTCHV": true,
    "enabled": true,
    ... the rest as is
}
```
4. Create a file `/opt/jans/jans-setup/output/test/jans-auth/config-agama-test.properties` based on this template:

```
#The URL of your Jans installation
server=https://%(hostname)s

clientId=BADA-BADA

custParamName=customParam1
```

**Comment by jgomer2001** [comment]
All perfect but I forgot one step:

5. Set `jansEnabled=TRUE` for agama script: `inum=BADA-BADA,ou=scripts,o=jans`

**Comment by devrimyatar** [comment]
Done https://github.com/JanssenProject/jans/pull/2749/commits/ebc80d430b22470e748ce81e580b56bc19875019

**Comment by jgomer2001** [comment]
Hi @devrimyatar , recently we had to move agama inside jans-auth-server folder, can you please update the code so that files are grabbed now from `https://github.com/JanssenProject/jans/tree/main/jans-auth-server/agama/engine/src/test/resources/templates`

This is regarding point no. 2 of this issue description

**Comment by jgomer2001** [comment]
Hi @devrimyatar , there is a new requirement:

we need to copy the directories found under
https://github.com/JanssenProject/jans/tree/main/jans-auth-server/agama/engine/src/test/resources/lib to `/opt/jans/jetty/jans-auth/agama/scripts`
