### ISSUE TITLE
fix(jans-config-api): problems with handling custom attributes

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2752]
Custom attributes currently cannot be handled properly, as they can have any value type (string, number, boolean, or an array thereof). Since most upstream clients can only support fixed primitive types, the type of an attribute must be well defined.

**Comment by pujavs** [comment]
@yurem, request you to please suggest how to handle this request.

**Comment by yurem** [comment]
@pujavs Is this issue related to LDAP ORM only?

**Comment by yurem** [comment]
Here is result with LDAP ORM after update:
![изображение](https://user-images.githubusercontent.com/6104200/202481750-a7572cdb-b2d3-45fc-b5f5-42ec3b4a2c01.png)

Now LDAP ORM uses schema to determine if attribute has integer/boolean/date type to convert value to corresponding java data type from string.

**Comment by moabu** [comment]
@yurem it was a general observation. I was using MySQL when I was investigating.

**Comment by yurem** [comment]
Can you provide real example to reproduce this issue?

**Comment by yurem** [comment]
Same example which I run with MySQL DB:
![изображение](https://user-images.githubusercontent.com/6104200/202711537-b050eb21-c7d3-485e-8e91-5105752be4b2.png)

**Comment by yurem** [comment]
I've checked ORM + PostgreSQL/Spanner/CB.
According to my testing ORM with LDAP/CB/Spanner/MySQL/PostgreSQL correctly store/return values with next types: Boolean/Integer(Long)/Date. Multivalued attributes we store:
1. As generic attributes in LDAP
2. As JSON in MySQL/PostgreSQL
3. As array in Spanner/CB.

**Comment by moabu** [comment]
This can be closed as resolved
