### ISSUE TITLE
fix(jans-config-api): max connections for LDAP database

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2754]
The LDAP database configuration has an attribute `maxConnections`. This attribute is considered during creation of a new configuration, however, updates are always disregarded and the original value, provided during creation is kept.

**Comment by pujavs** [comment]
Note able to replicate the issue. Am able to update `maxConnections` successfully.

**Video:**
[LDAP_MaxConnections_Update_Issue_2754.zip](https://github.com/JanssenProject/jans/files/9920723/LDAP_MaxConnections_Update_Issue_2754.zip)

**Screenshot:**
![image](https://user-images.githubusercontent.com/43700552/199497680-c6552f2b-9778-4b1a-8b2b-a2f574c2b6e8.png)
![image](https://user-images.githubusercontent.com/43700552/199499775-8cec83bc-ae90-4b45-a1e6-f26660785dc1.png)
![image](https://user-images.githubusercontent.com/43700552/199500894-e6b00696-9bd2-4acf-950c-f0928b22d123.png)
![image](https://user-images.githubusercontent.com/43700552/199501143-c2c48a5d-2c80-484c-a159-e2468f020afc.png)
