### ISSUE TITLE
fix(jans-config-api): error when creating oidc clients

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2755]
Whenever a request is made to create an oidc client, an uncaught exception occurs, resulting in a 500 server error. Easiest request to test is the following:

```json
{"redirectUris":["https://moabu-diverse-tiger.gluu.info"]}
```

**Comment by pujavs** [comment]
fixed the issue;
![image](https://user-images.githubusercontent.com/43700552/199454622-0cbf6622-68db-42be-8974-e8ba1d71e954.png)
