### ISSUE TITLE
fix(jans-config-api): organization attributes not updated

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2756]
When updating the organization, the organization title, as well as the DN/BaseDN are not updated.

**Comment by pujavs** [comment]
@moabu, `dn` and `baseDn` are internally generated and can be updated to only applicable schema values to avoid  *schema class violation* and the config-api endpoints conforms to it. Same is applicable to `dn` and `baseDn` update for any schema object.

**Video:**
[SMTP_dn_baseDN_Issue_2756.zip](https://github.com/JanssenProject/jans/files/9912574/SMTP_dn_baseDN_Issue_2756.zip)

**Screenshots:**
![image](https://user-images.githubusercontent.com/43700552/199295520-d4f5ec5f-26ba-4237-9961-91b22d8f7f3f.png)
![image](https://user-images.githubusercontent.com/43700552/199295593-cbab28c8-bd7e-4a31-abba-9be34dee0a3d.png)
![image](https://user-images.githubusercontent.com/43700552/199295722-dab0f223-fe28-410c-99d3-c5d3fbc11928.png)
![image](https://user-images.githubusercontent.com/43700552/199295817-c56c0d9d-f394-4c22-a9b0-d5bc46cf454f.png)

**Comment by moabu** [comment]
OK, understood about the `Dn`/`BaseDn`, however, I'm not always getting an error from the API when using an incorrect value. For example following request returns a 200 OK response:

```json
[
	{"op":"add","path":"/dn","value":"ou=groups,o=jans"},
	{"op":"add","path":"/baseDn","value":"o=janssen"}
]
```

If the API doesn't return an error, it's hard to handle it properly on the provider side. 

Also what about the `OrganizationTitle`? Should I be able to change that?

**Comment by pujavs** [comment]
on verifying the code found that we have `organizationTitle` only getter without any setter or corresponding attribute in model class. 
@yuriyz request your advice.
https://github.com/JanssenProject/jans/blob/main/jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/GluuOrganization.java#L92
![image](https://user-images.githubusercontent.com/43700552/200849286-9d9219dc-e6d0-47cf-99c0-9850eb0bc340.png)

**Comment by yuriyz** [comment]
@pujavs removed this method in https://github.com/JanssenProject/jans/pull/2948/files

We don't need it, I removed it. There is already getter/setter for title.

**Comment by pujavs** [comment]
thankyou @yuriyz 
cc @moabu

**Comment by moabu** [comment]
Ok I'll confirm and close the ticket if everything goes as expected . Thanks @yuriyz and @pujavs

**Comment by moabu** [comment]
Confirmed.
