### ISSUE TITLE
fix(jans-config-api): smtp configuration not updated

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2757]
When trying to update the SMTP configuration, following attributes are ignored/not updated:

- RequiresSSL
- TrustHost
- FromName
- FromEmailAddress
- RequiresAuthentication
- UserName

**Comment by pujavs** [comment]
@moabu , i am able to update SMTP conf details. I tested with latest build  on jenkins-build env 
**Screenshot**
![image](https://user-images.githubusercontent.com/43700552/198685361-8e445942-f2ba-4114-a298-fd7f346b4dbc.png)

**Comment by moabu** [comment]
Can you do a get after this and check it actually got updated @pujavs

**Comment by pujavs** [comment]
Rechecked - its working, screenshot and video for reference. Again tested this on jenkins-build env today with latest build. The DB this time was spanner.

**Screenshot:**
![image](https://user-images.githubusercontent.com/43700552/199199452-78ded5ba-cccd-4bd3-b175-81457d4902d1.png)

**Video:**
[SMTP_Config_Update_Issue_2757.zip](https://github.com/JanssenProject/jans/files/9908494/SMTP_Config_Update_Issue_2757.zip)

**Comment by moabu** [comment]
Issue can be closed as it is solved.
