### ISSUE TITLE
docs: VM Operations Guide

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#2770]
Top level issues to track progress on the VM Operations guide (`jans/docs/admin/vm-ops`):

- [x] backup
- [x] Certificates
- [x] Checking Server Status
- [x] Logs
- [ ] Key Rotation
- [ ] Key Creation
- [x] Restarting Services
- [ ] Web Services

**Comment by SafinWasi** [comment]
Partly addressed in #2832

**Comment by ossdhaval** [comment]
Closing this issue as we are now tracking documentation completion by raising individual GH issues for each document.
