### ISSUE TITLE
docs: errata in mkdocs

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#2835]
**Describe the bug**
There are some errors in `mkdocs.yml`, leading to the nav configuration not finding some files and resulting in 404s.

**To Reproduce**
1. Check out latest codebase from Github
2. Use `mkdocs serve` to serve the documentation locally
3. A number of files will not be found in the nav configuration, leading to 404s from the sidebar.

**Additional context**
The errata is as follows:
- Line 248: `'admin/auth-server/ssa.md'` should be `'admin/auth-server/endpoints/ssa.md'`
- Line 276: `'admin/auther-server/openid-features/native-sso.md'` should be `'admin/auth-server/openid-features/native-sso.md'`

**Comment by ossdhaval** [comment]
@shmorri @SafinWasi I reviewed and tested the changes. They are good to go. 
At the same time, current commits will fix the items mentioned in `additional context` in the description.

Point `3` in the description refers to another set of errors in the configuration. I'll have to tackle them one by one in the next few days. I will merge this PR after adding fixes for those errors.
