### ISSUE TITLE
feat(jans-auth-server): Return unmet_authentication_requirements if no person authn script matches acr requested by RP

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#2845]
https://openid.net/specs/openid-connect-unmet-authentication-requirements-1_0.html

This specification augments OpenID Connect Core 1.0 by defining an additional error code unmet_authentication_requirements to allow the OpenID Provider to signal

**Comment by yuriyz** [comment]
Already implemented as part of https://github.com/JanssenProject/jans/issues/7900
