### ISSUE TITLE
fix: duplicate configapi scopes in cn update

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2851]
**Describe the bug**
Upon upgrading jans cn setup from `1.0.2` to the latest currently `1.0.4_dev` multiple duplicate scopes are created.

config-api replicas: `1`

persistence and config jobs were ran on upgrade

```
Config API scope https://jans.io/oauth/config/jwks.delete
Config API scope https://jans.io/oauth/config/agama.delete
Config API scope https://jans.io/oauth/config/agama.readonly
Config API scope https://jans.io/oauth/config/agama.write
Config API scope https://jans.io/oauth/jans-auth-server/session.delete
Config API scope https://jans.io/oauth/jans-auth-server/session.readonly
```

**Expected behavior**
Existing scopes should be skipped

**Comment by iromli** [comment]
I was unable to replicate the issue when using 1 replica, but it does occurs when using 2 replicas.

There was race condition when multiple replicas trying to create new scopes. 
Each of them assume there are missing scopes in persistence hence each of config-api creates new scopes which eventually are persisted into persistence.

**Comment by iromli** [comment]
I tested by reverting back scopes creation to old scopes.ldif template (created statically before running config-api), but after that multiple jans-config-api replicas are creating missing scopes at the same time.

Eventually, multiple scopes with same jansId are created.

**Comment by iromli** [comment]
to summarize the multiple scopes issue:

1. multiple scopes creation (where DN prefix is 1800.mmmmmm-nnnnnn) can be avoided if we revert back to static scopes.ldif (v1.0.2 and lower)
2. multiple scopes creation (where DN prefix is UUID4 format) need to be investigated in jans-upstream jans-config-api

**Comment by iromli** [comment]
Point no. 1 is tracked in #2869
