### ISSUE TITLE
fix (jans-auth-server) : the auth server logs are not updating

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#2860]
**Describe the bug**
After doing the VM installation of jans-auth-server, noticed that auth server logs at `/opt/jans/jetty/jans-auth/logs` are not updating.

**To Reproduce**
1. Instal jans-auth-server using VM installer.
2. Check the size of log files (eg: jans-auth.log, jans-auth_script.log etc) at  `/opt/jans/jetty/jans-auth/logs`
3. Perform different operations on auth server (like authorization code flow)
4. Check the size of the log files. The log files are not updated.

**Expected behavior**
The logs should be updated with logs of recent operations.

**Comment by yuriyz** [comment]
Just checked out FullRebuild jenkins server and see logging is working there correctly. Closing as not reproducible.
![image](https://user-images.githubusercontent.com/2013070/200009309-a3434570-326c-4c53-b7fe-93e43d41e57d.png)
