### ISSUE TITLE
fix(jans-config-api): incorrect server response for missing agama resources

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2924]
When trying to fetch an agama flow that does not exist, instead of a 404 response, the server return 500. This was introduced with the latest deployment. 

The request is run against `/jans-config-api/api/v1/agama/QNAME` where QNAME is the name of a flow that is not defined in the system.

**Comment by pujavs** [comment]
@moabu, this is on jenkins build env
![image](https://user-images.githubusercontent.com/43700552/200639575-205a5f8a-2f30-4ebb-bb33-969c27cf5155.png)

**Comment by moabu** [comment]
@pujavs the issue still seems to exist.This is with the latest on MySQL.
I'm still getting a 500 for the request. 
<img width="1117" alt="202416094-3d36947c-e3d9-41a6-85d4-e71ac5acc18e" src="https://user-images.githubusercontent.com/47318409/202426100-ee3c3c9c-20b8-451b-857b-d242f5ce7d97.png">

**Comment by pujavs** [comment]
handled Exception , fix via PR [3028 ](https://github.com/JanssenProject/jans/pull/3028)

**Comment by pujavs** [comment]
Fixed and tested on mysql env
[Agama_404.zip](https://github.com/JanssenProject/jans/files/10275648/Agama_404.zip)

**Comment by moabu** [comment]
Tests and is working as expected
