### ISSUE TITLE
fix:(jans-config) getting error while create openid client

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2946]
**Describe the bug**
getting error while create openid client

**To Reproduce**
1. download schema  /opt/jans/jans-cli/config-cli.py --operation-id post-oauth-openid-clients --data /tmp/Client.json
2. modify Client.json add
 "customAttributes": null,
  "customObjectClasses": null,
4.run 
/opt/jans/jans-cli/config-cli.py --operation-id post-oauth-openid-clients --data /tmp/Client.json
5. See error

**Expected behavior**
should able to create openid client

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/200853519-ac93a905-967c-4dae-825b-cebc3f5facd5.png)

**Desktop (please complete the following information):**
  - OS: [ubuntu
  - Version 20.0
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**
[openidlog.zip](https://github.com/JanssenProject/jans/files/9971865/openidlog.zip)

**Comment by manojs1978** [comment]
[Client.json.txt](https://github.com/JanssenProject/jans/files/9972584/Client.json.txt)

**Comment by yurem** [comment]
You need to update your client.json

```
  "clientName": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "logoUri": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "clientUri": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "policyUri": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "tosUri": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  ```
  
Now we store in `clientName/logoUri/clientUri/policyUri/tosUri` values as before in plain text values
While for localized we added additional attributes where we store values in JSON

The localized attributes has same names + `Localized` at the end

**Comment by pujavs** [comment]
@manojs1978 were you able to test the fix?

**Comment by pujavs** [comment]
Assigning to @qbert2k for inputs.
@qbert2k, we are not able to pass LocalizedString in json it is giving error. If we pass it as empty string it gives no error. 
Can you please share how LocalizedString can be passed
Details:
**DBType:** LDAP

**Error:** ```com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (org.eclipse.jetty.server.HttpInput); line: 25, column: 23] (through reference chain: io.jans.as.common.model.registration.Client[&quot;logoUriLocalized&quot;])```

**Screenshot:**
![image](https://user-images.githubusercontent.com/43700552/202728119-85ac055b-b7d9-47bb-a00c-e38eba72cfab.png)

**Json:**
```{
  "dn": null,
  "expirationDate": null,
  "deletable": true,
  "clientSecret": "password",
  "frontChannelLogoutUri": null,
  "frontChannelLogoutSessionRequired": true,
  "registrationAccessToken": null,
  "clientIdIssuedAt": null,
  "clientSecretExpiresAt": null,
  "redirectUris": ["http://myserver.com"],
  "claimRedirectUris": [],
  "responseTypes": [],
  "grantTypes": [],
  "applicationType": "native",
  "contacts": [],
  "idTokenTokenBindingCnf": null,
  "clientName": "Puja_Test_1",
  "logoUri": null,
  "clientUri": null,
  "policyUri": null,
  "tosUri": null,
  "clientNameLocalized": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "logoUriLocalized": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "clientUriLocalized": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "policyUriLocalized": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "tosUriLocalized": {
    "values": null,
    "value": null,
    "languageTags": []
  },
  "jwksUri": null,
  "jwks": null,
  "sectorIdentifierUri": null,
  "subjectType": "public",
  "idTokenSignedResponseAlg": null,
  "idTokenEncryptedResponseAlg": null,
  "idTokenEncryptedResponseEnc": null,
  "userInfoSignedResponseAlg": null,
  "userInfoEncryptedResponseAlg": null,
  "userInfoEncryptedResponseEnc": null,
  "requestObjectSigningAlg": null,
  "requestObjectEncryptionAlg": null,
  "requestObjectEncryptionEnc": null,
  "tokenEndpointAuthMethod": null,
  "tokenEndpointAuthSigningAlg": null,
  "defaultMaxAge": null,
  "defaultAcrValues": [],
  "initiateLoginUri": null,
  "postLogoutRedirectUris": [],
  "requestUris": [],
  "scopes": [],
  "claims": [],
  "trustedClient": true,
  "lastAccessTime": null,
  "lastLogonTime": null,
  "persistClientAuthorizations": true,
  "includeClaimsInIdToken": true,
  "refreshTokenLifetime": null,
  "accessTokenLifetime": null,
  "customAttributes":null,
  "customObjectClasses": null,
  "rptAsJwt": true,
  "accessTokenAsJwt": false,
  "accessTokenSigningAlg": null,
  "disabled": true,
  "authorizedOrigins": [],
  "softwareId": null,
  "softwareVersion": null,
  "softwareStatement": null,
  "attributes": {
    "tlsClientAuthSubjectDn": null,
    "runIntrospectionScriptBeforeJwtCreation": true,
    "keepClientAuthorizationAfterExpiration": false,
    "allowSpontaneousScopes": true,
    "spontaneousScopes": [],
    "spontaneousScopeScriptDns": [],
    "updateTokenScriptDns": [],
    "backchannelLogoutUri": [],
    "backchannelLogoutSessionRequired": true,
    "additionalAudience": [],
    "postAuthnScripts": [],
    "consentGatheringScripts": [],
    "introspectionScripts": [],
    "rptClaimsScripts": [],
    "ropcScripts": [],
    "parLifetime": null,
    "requirePar": false,
    "jansAuthSignedRespAlg": null,
    "jansAuthEncRespAlg": null,
    "jansAuthEncRespEnc": null,
    "jansSubAttr": null,
    "redirectUrisRegex": null,
    "jansAuthorizedAcr": [],
    "jansDefaultPromptLogin": false,
    "idTokenLifetime": null
  },
  "backchannelTokenDeliveryMode": "poll",
  "backchannelClientNotificationEndpoint": null,
  "backchannelAuthenticationRequestSigningAlg": "ES384",
  "backchannelUserCodeParameter": false,
  "description": null,
  "organization": null,
  "groups": [],
  "ttl": null,
  "displayName": null,
  "tokenBindingSupported": true,
  "authenticationMethod": "self_signed_tls_client_auth",
  "baseDn": null,
  "inum": null
}```

**Comment by qbert2k** [comment]
Hi @pujavs

I can see the problem is deserializing the Localized String in Client class:

![image](https://user-images.githubusercontent.com/2474616/203116014-4d579fab-7169-4d8f-b3a1-59fc8fee2ca3.png)

I can suggest using a ClientDto instead and a mapper.

**Comment by qbert2k** [comment]
Why jans-config-api-server is not consuming the dynamic client registration endpoint from jans-auth-server?

**Comment by pujavs** [comment]
@qbert2k config-api has been using [Client.class ](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java) since beginning and was working without any issue.  
Which i understand you were aware because when the LocalizedString changes happen and related issues starting cropping up and being reported;
 - https://github.com/JanssenProject/jans/issues/1482#issuecomment-1150403068
- https://github.com/JanssenProject/jans/issues/1724
- https://github.com/JanssenProject/jans/issues/1765

Do you think you can rectify the issue in `https://github.com/JanssenProject/jans/blob/main/jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java` rather than intorducing another Dto and Mapper?
cc @yuriyz for suggestion and advice

**Comment by qbert2k** [comment]
1. The way LocalizedString is being persisted was changed as requested. Let me explain in more detail why I think we need to introduce a DTO and mapper:
- Let's consider the example in the specs: https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest

 ```JSON
{
// ...
"client_name": "My Example",
"client_name#ja-Jpan-JP":  "クライアント名"
// ...
}
```

- As we can see in the example, the format of the param is special and cannot be deserialized directly, that's why I am purposing to use another mechanism. So instead of trying to receive a Client object directly at the rest controller level, I suggest using a DTO and mapping the values to the Client object.

2. I was just curious about why not use Dynamic Client Registration because it could be another option to solve the problem.

**Comment by pujavs** [comment]
@qbert2k, i am also just as curious that would the DTO and mapper resolved the issue long back rather than waiting for changes to the [Client.class](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java)

**Comment by yuriyz** [comment]
@qbert2k @pujavs jans-config-api has access to internal AS structure which is not exposed outside by AS via dynamic registration endpoint. There reason is that jans-config-api must have ability to change any data (e.g. client secret or expiration). We of course can solve `Client` serialization/deserialization problem by introducing DTO and mapping but it introduce another point of maintaining in code and as result another point of failure. 

I'm going to investigate and fix deserialization problem. 
```
Error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`) at [Source: (org.eclipse.jetty.server.HttpInput); line: 25, column: 23] (through reference chain: io.jans.as.common.model.registration.Client[&quot;logoUriLocalized&quot;])
```

**Comment by pujavs** [comment]
Confirmed the fix is working, @yuriyz  thankyou
Testing: tested with json shared by @yuriyz  as well as others
![image](https://user-images.githubusercontent.com/43700552/203746163-8ff83af7-faa3-4268-b699-cb98dfed19a6.png)

**Comment by pujavs** [comment]
@manojs1978 to test and confirm

**Comment by manojs1978** [comment]
checking

**Comment by manojs1978** [comment]
Hi @pujavs ,
please check below error, getting while running post method ,

``` /opt/jans/jans-cli/config-cli.py --operation-id post-oauth-openid-client --data /tmp/client.json com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String &quot;string&quot;: not a valid representation (error: Failed to parse Date value &#x27;string&#x27;: Unparseable date: &quot;string&quot;)
 at [Source: (org.eclipse.jetty.server.HttpInput); line: 1, column: 36] (through reference chain: io.jans.as.common.model.registration.Client[&quot;expirationDate&quot;])```

**Comment by pujavs** [comment]
@manojs1978 i am not getting this error, request you to please re-test and post exact request json in-case of error or else close the issue

**Comment by pujavs** [comment]
assigning to @manojs1978 for testing and closure

**Comment by manojs1978** [comment]
with modfied client.json able to create open id client using API
