### ISSUE TITLE
Allow to inject endpoints calls to janssen services

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#296]
### User Story Title.

Allow to inject endpoints calls to janssen services

#### Risk Level. 

1

#### Effort.

1

#### Priority.

MEDIUM

### Description.

Allow to inject the two endpoints, token api for access token validations, and openid-configuration via `application.properties`

#### Acceptance Criteria. This section contains every condition under which the feature should operate for the end-user to consider the feature to be accepted or marked complete. The criteria also serve as a guideline for writing unit tests for the feature. For example:

```
When the application is run it needs to be able to only communicate to neighboring service via an inject service protocol://address:port/path
```
.

**Comment by pujavs** [comment]
Closing this issue since as per @iromli this has been handled in CN, refer https://github.com/JanssenProject/jans/issues/687
