### ISSUE TITLE
fix:(jans-cli) unable to create new agama flow 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2960]
**Describe the bug**

**To Reproduce**
1. launch /opt/jans/jans-cli/config-cli.py
2.go to 4 5 then 2 to create agama flow
3. add qname and press y

**Expected behavior**
should able to create agama flow from mendatory fields

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/201288244-e77269c3-8adc-420f-9256-4e4aa4a5bec8.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Browser
  - Version 20.04
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Not relevant for IM, workinf for cm

![image](https://user-images.githubusercontent.com/6398752/207559875-bb402898-25c0-4cce-9805-414537c638c8.png)
