### ISSUE TITLE
fix:(jans-cli) unable to create user using jan-cli

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2961]
**Describe the bug**
 unable to create user from jans-cli
**To Reproduce**
1. launch /opt/jans/jans-cli/config-cli.py
2. go to 4 then 6 then 2 to create user
3. See error

**Expected behavior**
should able to create user

**Screenshots**

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**
[error.log](https://github.com/JanssenProject/jans/files/9988096/error.log)

**Comment by devrimyatar** [comment]
Not relevant for cli-tui, tested with command line, it worked
![image](https://user-images.githubusercontent.com/6398752/205674225-6e3b64d9-c2e8-41fc-9804-199da321c0ee.png)
