### ISSUE TITLE
fix:(jans-cli) getting Error 503 and scim is not getting up

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2962]
**Describe the bug**
getting Error 503 and scim is not getting up

**To Reproduce**
1.See attached log

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/201317167-77bf225d-8843-4eaa-abe3-956f255e418f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20.04

**Smartphone (please complete the following information):**
  - Device: [ubuntu

**Additional context**
[logs.zip](https://github.com/JanssenProject/jans/files/9989335/logs.zip)

**Comment by devrimyatar** [comment]
This is no  CLI issue. SCIM is working fine on 1.0.5
