### ISSUE TITLE
fix:(jans-cli) healthcheck return null state

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2966]
**Describe the bug**

**To Reproduce**
1. run health check command using config-cli.py
  /opt/jans/jans-cli/config-cli.py --operation-id get-config-health-live
 /opt/jans/jans-cli/config-cli.py --operation-id get-config-health
2. return below output
5See error

**Expected behavior**
should get proper healthcheck staus

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/201464878-57f03a4a-5b80-487b-b241-bd9077771d0e.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
1) This is duplication of https://github.com/JanssenProject/jans/issues/3008
2) Working
![image](https://user-images.githubusercontent.com/6398752/205663304-d60457ec-2fee-4236-a5b4-81c69a28129d.png)
