### ISSUE TITLE
fix:(jans-cli) unable to update exisiting scope

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#2973]
**Describe the bug**
 unable to update exisiting scope using jans-cli

**To Reproduce**
1. launch /opt/jans/jans-cli/config-cli.py
2. goto 8 then 3 then 2 then 3
3. add inum then select attribute field to update

**Expected behavior**
able to update attribute

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/201637743-b2a7acf9-4d5e-4368-9fc7-bccdcbb6325b.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20.04
- DB openDJ
- 
**Smartphone (please complete the following information):**

**Additional context**
[error_1.log](https://github.com/JanssenProject/jans/files/10002128/error_1.log)

**Comment by devrimyatar** [comment]
Not relevant for cli-tui. Checked with command line, it worked
![image](https://user-images.githubusercontent.com/6398752/205662789-a66896bd-b513-4e43-906e-b380ebf2e358.png)
