### ISSUE TITLE
Jans Config api client changes for scim endpoints

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#300]
**Requirement:**  Scim endpoints changes

1) yaml for new endpoints. 
Attached is the yaml that i have synched with exact changes
[jca.zip](https://github.com/JanssenProject/jans-cli/files/7291847/jca.zip)

2) Issue: Patch for scim -user management not working as expected. It does not take the request object as specified.

**Comment by mbaser** [comment]
@pujavs Do you think we can close this issue?

**Comment by pujavs** [comment]
Yes, SCIM user patch is working 
![image](https://user-images.githubusercontent.com/43700552/150108222-54aae4b5-4cfe-411d-9036-b372876197ba.png)
