### ISSUE TITLE
An option to see server's status

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#301]
![Screenshot from 2021-06-23 01-02-15](https://user-images.githubusercontent.com/7156097/123043998-b642a500-d3be-11eb-8de6-eebb30496efe.png)

Is it possible to add another button like "Server Properties" which will show disk space, memory, installed database ( ldap / CB or anything there )?

**Comment by mbaser** [comment]
@pujavs Any work for this?

**Comment by pujavs** [comment]
@mbaser, as discussed earlier can you please upload the script for getting the server status in folder from where jans-config-api can query it

**Comment by mbaser** [comment]
@pujavs This is the script we use with Gluu oxtrust ui 
https://raw.githubusercontent.com/GluuFederation/gluu-snap/master/facter/facter

**Comment by pujavs** [comment]
Jans-config-api  implementation complete, refer issue 275 [Implementation sofr](https://github.com/JanssenProject/jans/issues/275)

**Comment by mbaser** [comment]
Implemented

![Screenshot_2022-02-16_21-12-23](https://user-images.githubusercontent.com/6398752/154329144-d974238c-039e-4626-bb7a-deb1e2fd4822.png)
