### ISSUE TITLE
Post-Installation script for installation, enable and disable plugins in admin-ui frontend

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#302]
## Description
To install, enable and disable plugins in the admin-ui frontend we need a post-installation script. 

- `Install Plugin`  - Users can develop frontend plugins for Admin UI. The newly developed frontend plugin can be installed in Admin UI application.

- `Enable Plugins` - The plugins installed in Admin UI need to be enabled so that they are included when the project is built.

- `Disable Plugins` - The plugins in Admin UI can be disabled so that they are not included when the project is built.

## **Steps to install, enable and disable plugins in admin-ui frontend using post-installation script :**

a. Extract `/opt/dist/jans/gluu-admin-ui.zip`
b. Change directory to extracted `gluu-admin-ui`
c. The post-installation script will show the following message
```
Select option
1. Install new Admin-UI Plugin
2. Enable plugins (include them in built)
3. Disable plugins (do not include in built)
```
**Install Plugin**
d. If the user selects `1` then the script will display the following message
```
Enter the path of the plugin directory (from disk)
```
e. After the path is entered script should check if the path is preset. Then execute the following command to install the plugin
```
npm run plugin:install <path_of_the_plugin_directory_on_disk>
```
**Enable Plugin**
f. If the user selects `2` then the script will first execute below command to display a list of all available disabled plugins.
```
npm run plugin:showDisabled
```

g. Then it will display the following message
```
Enter the plugin keys from the above list separated by _, delimiter. (eg: admin_,schema_,services)
```

h. After the user enters plugin keys, the script should run below command
```
npm run plugin:enable <plugin_keys_separated_by_delimeter>
```
i. Then script should run `npm run build:prod` and copy the built from <gluu-admin-ui_home>/dist and overwrite to /var/www/html/admin.

**Disable Plugin**
j. If the user selects `3` then the script will first execute the below command to display a list of all available enabled plugins.

```
npm run plugin:showEnabled
```

k. Then it will display the following message
```
Enter the plugin keys from the above list separated by _, delimiter. (eg: admin_,schema_,services)
```
l. After the user enters plugin keys, the script should run below command
```
npm run plugin:disable <plugin_keys_separated_by_delimeter>
```
m. Then script should run `npm run build:prod` and copy the built from <gluu-admin-ui_home>/dist and overwrite to /var/www/html/admin.

**Finally**

n. The script should zip back the extracted contents of `/opt/dist/jans/gluu-admin-ui.zip`.

**Comment by duttarnab** [comment]
## Overview

There will be only following commands in post-install script

1. `Add Plugin` - Users can develop frontend plugin for Admin UI. The newly developed frontend plugin can be added to Admin UI application.

2. `Remove Plugin` -  Users can remove a plugin from admin-ui .

## Steps to add/remove plugin

**Initial Installation**

1. If user selects `yes` for Admin UI installation during `jans-auth-server` set-up then run below command before executing `npm run build:prod`.

```
npm run plugin:clean
```

**Add Plugin**

1. To add plugin user should execute below command.
```
npm run plugin:add <path_of_the_plugin_directory_on_disk>
``` 

2. Then script should execute `npm run build:prod` and copy the built from <gluu-admin-ui_home>/dist and overwrite to /var/www/html/admin.

**Remove Plugin**

1. To remove plugin user should execute below command.
```
npm run plugin:remove <plugin_key>
```

2. Then script should execute `npm run build:prod` and copy the built from <gluu-admin-ui_home>/dist and overwrite to /var/www/html/admin.

**Finally**

n. The script should zip back the extracted contents of /opt/dist/jans/gluu-admin-ui.zip.

**Comment by mbaser** [comment]
@duttarnab Do you think we can close this issue?

**Comment by duttarnab** [comment]
Done
