### ISSUE TITLE
fix: (jans-cli) unable to launch jans-cli after installtion

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3021]
**Describe the bug**
unable to launch jans-cli after installtion in centos8

**To Reproduce**
1. install RHEL rpm from release
2. launch /opt/jans/jans-cli/config-cli.py
3. See error

**Expected behavior**
should able to launch jans-cli

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/202460805-2a427c06-2486-4dbc-a42c-dbeef8459979.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 8

**Smartphone (please complete the following information):**

**Additional context**
[error_centos8.l
[logs.zip](https://github.com/JanssenProject/jans/files/10032172/logs.zip)
og](https://github.com/JanssenProject/jans/files/10032043/error_centos8.log)

**Comment by nynymike** [comment]
Are we supporting CENTOS 8? I thought we were just supporting RHEL, SUSE, and Ubuntu.

**Comment by devrimyatar** [comment]
> Are we supporting CENTOS 8? I thought we were just supporting RHEL, SUSE, and Ubuntu.

Officially we don't, but we test on CentOS8 to estimate RHEL8 issues.

**Comment by devrimyatar** [comment]
Can't replicate.
