### ISSUE TITLE
docs: Endpoints

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#3035]
- [x] #3495
- [x] #3454
- [ ] Backchannel Authentication endpoint documentation
- [x] #3518
- [x] #3036
- [x] #3511
- [x] #3037
- [x] #3535
- [x] #3607
- [x] #3591
- [x] #3445
- [ ] registration endpoint documentation
- [x] #3492
- [x] #3561

**Comment by ossdhaval** [comment]
Closing this issue as we are now tracking documentation completion by raising individual GH issues for each document.
