### ISSUE TITLE
fix(jans-cli-tui): getting window too small error in edit user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3041]
**Describe the bug**
getting window too small error in edit user

**To Reproduce**
1. launch jans -tui
2. goto edit user
3. edit existing user

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203004984-4f783d8d-f2b9-4950-8452-e3205d0d86e8.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser :
  - Version 20.04
  - DB openDJ

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
I can't replicate, even with very small window, it can display edit user dialog

![image](https://user-images.githubusercontent.com/6398752/203027224-c420af12-a0b3-4bf8-b017-1372cb11504f.png)

**Comment by manojs1978** [comment]
hello @devrimyatar,
 please select "jans auth test user" from list
![image](https://user-images.githubusercontent.com/5729240/203245412-7c3c3792-1e4d-46fb-a707-9452330c5474.png)

**Comment by manojs1978** [comment]
when we add multiple claims while add/edit user this issue is reproducible.

![image](https://user-images.githubusercontent.com/5729240/204282464-8b42eea3-f82a-4c6e-86c3-08c0de6d34a5.png)

**Comment by AbdelwahabAdam** [comment]
## Solved
https://user-images.githubusercontent.com/63171603/204314742-6177e98d-9c03-4268-b034-3ef9858f1537.mp4
