### ISSUE TITLE
Getting Unhandled exception on scopes list when clicking on next.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#3048]
**Describe the bug**
Not able to get the scopes list after clicking next button three times.

**To Reproduce**
1. Go to jans-tui
2. Go to Auth Server
3. Go to scope
4. click on get scopes
5. click on next button two or three times.

**Expected behavior**
scopes list must be shown.

**Screenshots**
![Screenshot from 2022-11-21 17-41-23](https://user-images.githubusercontent.com/34593983/203052444-401eb474-fa69-48d5-81ac-110eac4a05b3.png)
![Screenshot from 2022-11-21 17-41-31](https://user-images.githubusercontent.com/34593983/203052742-3319e838-8890-4da1-aae2-71a2f5e06e42.png)

**Desktop (please complete the following information):**
  - OS: [ubuntu20.04]
  - Browser [ chrome ]
  - Version [1.0.5 ]

**Comment by devrimyatar** [comment]
Uploading vokoscreenNG-2022-11-21_18-51-57.mp4…

I were not be able to replicate

**Comment by devrimyatar** [comment]
Closing, since we were unable to replicate

**Comment by AbdelwahabAdam** [comment]
I think I faced similar issue before, Maybe you need to upgrade `jans-config-api` and  `jans-auth server`
