### ISSUE TITLE
feat(agama): deploy flows from `.gama` files

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#3052]
ADS tool will generate `.gama` files which contain one or more flows and related assets. A deployment functionality is needed

This should be exposed in the config-api through an endpoint, where a `.gama` file is presented
- A status value of 202 (accepted) should be returned in addition to some identifier to later track the status of the operation
- A status value of 200 should be returned when the operation has completed. A summary of the status deployment for every sub-task should be returned in the body

**Comment by jgomer2001** [comment]
An "undeploy" feature is desirable too, so maybe there has to be an endpoint to list the currently deployed projects in the AS

For simplicity, the deploying endpoint may contain the project identifier in the URL itself. The same endpoint would be then used to get the deployment status via GET

**Comment by nynymike** [comment]
Needs a scope too for read and write
