### ISSUE TITLE
fix(jans-tui): getting multiple device auth message 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3059]
**Describe the bug**

**To Reproduce**
launch jans-tui
goto jan-cli at right corner and press enter
press enter on"configure jans cli"
do not modify content press enter on save button
you will get message like below screenshot
![image](https://user-images.githubusercontent.com/5729240/203512142-3129b604-5ff1-4369-85b8-dca6c627cee5.png)
press enter
complete device authentication and press enter

**Expected behavior**
should not get any multiple device auth popup

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203513592-bdf5ada6-c6f8-4898-a492-15c291ed63e0.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Version 20.04
-DB mysql
**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed in commit https://github.com/JanssenProject/jans/commit/a5e92ad43438edb0ea20a5ebdbcf31506dc548cd


https://user-images.githubusercontent.com/6398752/203623168-fdc361a0-eb1c-40e9-b418-f2b9ef3496cd.mp4
