### ISSUE TITLE
fix(jans-tui): screen hang in scim 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3061]
**Describe the bug**

**To Reproduce**
goto scim dont modify anything click on save button ,
you will get message like “ no changes made” then click on ok

 then screen hangs

**Expected behavior**
screen should not hang

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203528940-affd89de-9ce5-40e4-8f39-0be161b64e7f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20.04
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed in commit 07202152735491de4db9127c9c56aa280d05a506


https://user-images.githubusercontent.com/6398752/203614582-501cd1fd-163d-4b17-a11a-a35a8be97163.mp4
