### ISSUE TITLE
fix: jans-cli nested list in Properties

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#3062]
**Describe the bug**
Editing a nested list in Properties, for example, **responseTypesSupported** in the following screenshot

![image](https://user-images.githubusercontent.com/6398752/203539726-1a10c67d-a5b1-476b-8419-898a04c6ed6f.png)

raises error:
```
  File "/mnt/data/projects/Janssen/jans/jans-cli-tui/cli_tui/plugins/010_oxauth/view_property.py", line 204, in prepare_properties
    value='\n'.join(self.value),

Exception sequence item 0: expected str instance, list found
```

**To Reproduce**
1. Execute TUI
2. Navigate to **Properties** tab of **Auth Server**, 
3. Click **Next** couple of times untill  you see property **responseTypesSupported**, press Enter

**Comment by AbdelwahabAdam** [comment]
## Solved and revised all `array` type properties:


| Property Name | Type |  Output type |  Widget implemented | Editable |
| ----------- | ----------- | ----------- |----------- |----------- |
| subjectIdentifiersPerClientSupported | Array       | List of values |  TexrArea |  ✔️  |
| **responseTypesSupported** | Array       | List of Lists |  checkboxlist | ✔️  |
| responseModesSupported| Array       | List of values| checkboxlist |✔️  |
| grantTypesSupported| Array       | List of values | checkboxlist |  ✔️  |
| subjectTypesSupported| Array       |  List of values| TexrArea |✔️  |
| authorizationSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| authorizationEncryptionAlgValuesSupported| Array |List of values | TextArea|✔️  |
| authorizationEncryptionEncValuesSupported|Array |List of values | TextArea|✔️  |
| userInfoSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| userInfoEncryptionAlgValuesSupported| Array |List of values | TextArea|✔️  |
| userInfoEncryptionEncValuesSupported| Array |List of values | TextArea|✔️  |
| idTokenSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| idTokenEncryptionAlgValuesSupported| Array |List of values | TextArea|✔️  |
| idTokenEncryptionEncValuesSupported| Array |List of values | TextArea|✔️  |
| accessTokenSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| requestObjectSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| requestObjectEncryptionAlgValuesSupported|Array |List of values | TextArea|✔️  |
| requestObjectEncryptionEncValuesSupported|Array |List of values | TextArea|✔️  |
| tokenEndpointAuthMethodsSupported|Array |List of values | TextArea|✔️  |
| tokenEndpointAuthSigningAlgValuesSupported| Array |List of values | TextArea|✔️  |
| displayValuesSupported| Array |List of values | TextArea|✔️  |
| claimTypesSupported|Array |List of values | TextArea|✔️  |
| jwksAlgorithmsSupported|Array |List of values | TextArea|✔️  |
| claimsLocalesSupported|Array |List of values | TextArea|✔️  |
| idTokenTokenBindingCnfValuesSupported|  Array |List of values | TextArea|✔️  |
| uiLocalesSupported| Array |List of values | TextArea|✔️  |
| requestUriBlockList|  Array |List of values | TextArea|✔️  |
| personCustomObjectClassList| Array |List of values | TextArea|✔️  |
| authenticationFilters| Array       | List of Dicts | tabs| ✔️ |
| clientAuthenticationFilters|Array       | List of Dicts | tabs| ✔️ |
| corsConfigurationFilters|Array       | List of Dicts | tabs| ✔️ |
| dynamicGrantTypeDefault|  Array       | List of values| checkboxlist |✔️  |
| clientWhiteList|Array |List of values | TextArea| ✔️  |
| clientBlackList|Array |List of values | TextArea| ✔️  |
| authorizationRequestCustomAllowedParameters|Array       | List of Dicts | tabs| ✔️ |
