### ISSUE TITLE
docs: OpenAPI docs point to wrong version of docs

### ISSUE THREAD

**Issue by shmorri** [JanssenProject/jans#3067]
The OpenAPI links on this page: https://docs.jans.io/head/admin/reference/openapi/ always point at the Main branch, even in older versions. We need to make them match the version of the docs that we're currently on.

Normally we accomplish this with relative linking, but in this case they're generated and require full links, as shown in this screenshot.

<img width="1196" alt="Screen Shot 2022-11-23 at 11 04 06 AM" src="https://user-images.githubusercontent.com/36208047/203606668-0a2ed6c2-8735-4f25-944b-c1827bbd3f62.png">

Is this something we can add to the release automation, to update these links? We also need to update older releases to be correct.

**Comment by ossdhaval** [comment]
@shmorri This got fixed with #3355. The current behavior seems to be pointing to the correct version. Hence I am closing this issue.
