### ISSUE TITLE
fix(jans-tui):  error while getting client list

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3069]
**Describe the bug**
error while getting client list

**To Reproduce**
1. launch tui
2. goto auth server then clients and press getclients
3. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203709471-f8832315-71ec-4cc5-816a-1b97299e3f37.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser
  - Version 20
  - DB -pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate


https://user-images.githubusercontent.com/6398752/203849791-ed069a9d-5081-4011-bcfc-b518fdf9d33e.mp4
