### ISSUE TITLE
fix(jans-tui): getting "window too small" error while adding user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3070]
**Describe the bug**
getting "window too small" error while adding user

**To Reproduce**
1. launch tui
2.go to user the add user
3. insert information and press add claim select some claims
4. press save button
5. See error

**Expected behavior**
should no get error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203716227-191818bd-6121-4242-8b7d-e7f11cc9b8b5.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB pgsql
**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
Related to 
https://github.com/JanssenProject/jans/issues/3041

Solved with commit 
https://github.com/JanssenProject/jans/commit/b2fc89878fb8dd3078f7a488810278ff3291a58a
