### ISSUE TITLE
fix(jans-tui): getting error "not found" when click one get user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3071]
**Describe the bug**

**To Reproduce**
1. launch  tui
2. create one user
3. press  get user

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203721544-07981729-c9ae-490a-979b-266267ca3fd6.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate

https://user-images.githubusercontent.com/6398752/203849549-699415ee-d462-47d1-8ad5-238f09aafd24.mp4

**Comment by manojs1978** [comment]
hello @devrimyatar ,
please check this one .today i installed but facing same issue
steps i followed:
curl https://raw.githubusercontent.com/JanssenProject/jans/main/jans-linux-setup/jans_setup/install.py > install.py
python3 install.py --args="-t"
pip3 install shiv
wget https://github.com/JanssenProject/jans/archive/refs/heads/jans-cli-tui-works.zip
unzip jans-cli-tui-works.zip
cd jans-jans-cli-tui-works/jans-cli-tui/
make zipapp
./config-cli-tui.pyz
then completed device verification 
get users
search user
then try to add user

https://user-images.githubusercontent.com/5729240/203907343-1b8f6300-8fb2-46bf-b459-96146504bfc1.mp4
