### ISSUE TITLE
fix(jans-ui): "not fount" error while adding new user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3072]
**Describe the bug**

**To Reproduce**
launch tui
create one user , add information for new user and press save button
See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/203725199-93e27eaa-b556-4165-ab03-8314729308df.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version  20
  - DB pgsqql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate


https://user-images.githubusercontent.com/6398752/203854578-e72eaaf6-d9dc-4bd8-98ca-6b387385aee4.mp4
