### ISSUE TITLE
fix(jans-tui): unable to move backword in auth server column

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3073]
**Describe the bug**
unable to move backword in auth server column

**To Reproduce**
1. launch tui
2. go to auth server then go to different columns like client,scopes keys properties default loggin
3. move forward and backword
4. when we reach properties tab unable to move forware or backword

**Expected behavior**
should able to move forward and backward in all tab option

**Screenshots**

https://user-images.githubusercontent.com/5729240/203749745-ee196ab2-02f9-47cf-ad5d-e012747d6b7e.mp4

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
Fixed with commit https://github.com/JanssenProject/jans/commit/aaf691

https://user-images.githubusercontent.com/63171603/203815203-7f5953e3-d764-4b0d-b113-de089ffd1ce2.mp4

7091b1a9e53c236c35bc39e58ff52069e4
