### ISSUE TITLE
feat(linux-setup): config-api scope creation with static inum

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#3097]
**Issue:** When multiple config-api instances are deployed then multiple scopes are created with same name.
**Solution:**  Simplest and effective solution as proposed by @yuriyz is to use use same inum and rely on DB. All DBs provides unique identifier and enforce it.
![image](https://user-images.githubusercontent.com/43700552/204337335-31e00964-7fcb-46b0-bbd8-1ab5237df508.png)

-------------------

### Description
1. linux setup will have to refer [config-api-rs-protect.json ](https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/resources/config-api-rs-protect.json) for config-api scope creation rather than swagger spec .
`config-api-rs-protect.json` will have three sets of scopes per endpoint scope, groupScope and superScope with inum and name.
linux-setup will have to create these scopes in DB with specified inum
2.  Scope name and inum will be repeated so code should be able to get the unique sets of scope and create accordingly.
3.  Refer `config-api-rs-protect.json` from dev branch for development -> https://github.com/JanssenProject/jans/tree/jans-config-fixes
4. If inum or name of the scope is null or empty then do not create that scope
5. config-api and setup code will have to be merged in main together.
6. Related config-api issues [2937](https://github.com/JanssenProject/jans/issues/2937) and [2882](https://github.com/JanssenProject/jans/issues/2882) 

- Development target issue

- Implementation Details
  

-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes
linux setup config-api scope creation

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by devrimyatar** [comment]
Implemented
