### ISSUE TITLE
docker-jans-monolith: Janssen server doesn't come up when installing through docker monolith quick start instructions

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#3132]
**Describe the bug**
When installing Janssen Server following [docker quick start](https://docs.jans.io/head/admin/install/docker-install/quick-start/) instructions, the Janssen Server doesn't come up. And stays in `unhealthy` state forever.

**To Reproduce**
1. Have a fresh Ubuntu 22.04 VM on VMWare player (4 CPU, 8 GB RAM, 40 GB HDD)
2. Follow instructions at https://docs.jans.io/head/admin/install/docker-install/quick-start/
3. As shown in screenshot, the container stays in `unhealthy` state for more than 30 mins and doesn't come up even after that.

**Expected behavior**
Installation should end successfully.

**Screenshots**

Container unhealthy for more than 30 mins ( and still not up afterwards )
![image](https://user-images.githubusercontent.com/343411/204998333-306564e6-adc3-469f-8247-630116f1662f.png)

**Comment by misba7** [comment]
Now docker monolithic is working
![Screenshot (409)](https://github.com/JanssenProject/jans/assets/49232835/fbf11519-0bce-4140-9913-8cad4e749ec1)

**Comment by moabu** [comment]
We can close this
