### ISSUE TITLE
docs: docker quick start guide uninstall section uses docker compose

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#3133]
**Describe the bug**

While `docker compose` is not listed as a prerequisite, the [quick start guide](https://docs.jans.io/head/admin/install/docker-install/quick-start/#uninstall-remove-the-janssen-server) uses `docker compose` command for uninstallation. This causes the uninstall instruction to fail on VMs where `docker compose` is not installed.

**Comment by misba7** [comment]
The startjanssenmonolithdemo script actually [installs](https://github.com/JanssenProject/jans/blob/737eb9067b5688ecba861d75cc49c0f94def4fdc/automation/startjanssenmonolithdemo.sh#L36) docker-compose plugin, and that's how jannsen is [installed](https://github.com/JanssenProject/jans/blob/737eb9067b5688ecba861d75cc49c0f94def4fdc/automation/startjanssenmonolithdemo.sh#L65)

And thus docker-compose will be present, as in the screenshot

![image](https://github.com/JanssenProject/jans/assets/49232835/72c26b64-8e00-4091-a115-b12eee5b0455)
