### ISSUE TITLE
docs: Janssen Server installation with docker compose runs into errors

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#3146]
**Describe the bug**
Installation fails with an error as shown in screenshot

**To Reproduce**
1. VMWare player VM with Ubuntu 22.04 (4 CPU, 8 GB RAM, 40 GB HDD)
2. Follow instructions at [Docker compose](https://docs.jans.io/head/admin/install/docker-install/compose/)

**Expected behavior**
Install should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/343411/205025409-013aecdf-9b70-4cc4-ab2b-f09779a12acb.png)

**Comment by moabu** [comment]
Tested and its working. This looks like you had an issue with your docker installation

**Comment by ossdhaval** [comment]
Hi @moabu, Thanks for checking. In my case, it was a fresh Ubuntu 22.04 VM on VMWare workstation Player. When you tried, was it a fresh VM?

I installed docker using [these instructions](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository), and it was installed without any hiccups. So, it is hard to imagine there is a problem with the docker install. Anyway, Let me try this one more time next week and then close it with whatever the finding may be.

**Comment by ossdhaval** [comment]
Closing this issue as it seems to be a docker install-related issue.
