### ISSUE TITLE
CI: host Janssen artifacts on maven central

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#316]
-------------------

### Description

- Development target issue
  This development item doesn't have any parent issue as this is a pure tech enhancement

  Enhancement:
  Janssen currently hosts all its deployment artifacts on its own servers. Like `https://ox.gluu.org/` and `https://maven.jans.io`.
  Standard practice in majority of open source projects is to make these artifacts available through maven central. There multiple advantages of hosting on maven central:
  - Easy discovery. Maven central is well known in developer community and it is the first place where people look for dependencies and OSS distributions
  - Leveraging CDN: Unlike our own servers where we host our artifacts, maven central delivers artifacts across the world using CDN. This will significantly improve timings for first installs where almost all dependencies are downloaded.
  - Javadoc hosting: All open source artifacts hosted on maven central get free javadoc hosting on `javadoc.io`.

- Implementation Details

High level code changes are listed in section below. 

-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes

- [ ] Onboarding to sonatype
  - [ ] Register `io.jans` group id
- [ ] POM.xml changes to all repositories
  - [ ] create GPG key for used in all jans repositories
  - [ ] add or change `distributionManagement`
  - [ ] add or change `release` profile
  - [ ] configure `javadoc`, `source`, `gpg`, `sonatype` plugins
  - [ ] remove `https://ox.gluu.org/` and `https://maven.jans.io` from POM
- [ ] Jenkins configuration for deploying artifact on central
  - [ ] envirnment variables for passphrase, sonatype user-id, sonatype password
  - [ ] add or change existing job to release on maven central

-------------------

### Test and rollout

- [ ] TBD
- [ ] TBD

-------------------

### Document the changes

- [ ] changes in Developer documentation
  - [ ] need to mention where to find janssen artifacts on central
  - [ ] need to mention new javadoc location on `javadoc.io`

**Comment by moabu** [comment]
We are likely publishing automatically to GitHub packages. Javadocs can be automatically hosted with our github pages.

**Comment by ossdhaval** [comment]
@moabu Let's close this issue if integration with GH packages is being tracked separately.

**Comment by ossdhaval** [comment]
Closing this issue since we will not go the Maven central route to publish javadoc. Instead, we have created a CI flow to have javadocs created automatically and be checked into the GH repo.
