### ISSUE TITLE
docs: arrange navigation in order of relevance

### ISSUE THREAD

**Issue by shmorri** [JanssenProject/jans#3197]
Now that docs content is starting to fill in, we're seeing that the order of documentation could be fine-tuned. The documentation topics, mostly categories, should be arranged in order from most widely relevant to most niche.

**Comment by shmorri** [comment]
Additionally, let's comment out the sections that aren't MVP for right now.

So far, that's:
VM Operations Guide:
 - Web Services
 -  Faq

**Comment by ossdhaval** [comment]
Hi @shmorri, As you know docs went through a lot of restructuring in the last 6 months. Do we need this issue anymore? The most recent of your PR #4317 has also addressed this issue. 

Please close this issue if not required anymore.

**Comment by shmorri** [comment]
You're absolutely right, this is the work we've been doing.
