### ISSUE TITLE
fix:(jans-cli-tui) getting service unavailable error after launch cli-tui

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3207]
**Describe the bug**
getting service unavailable error after launchi cli-tui

**To Reproduce**
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum module enable mod_auth_openidc
yum install curl wget
yum install -y https:$(curl -s -L https://api.github.com/repos/JanssenProject/jans/releases/latest | egrep -o ‘/.*el8.x86_64.rpm’ | head -n 1)
sudo python3 /opt/jans/jans-setup/setup.py
/opt/jans/jans-cli/[config-cli-tui.py

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/205602965-4ffa1bb3-5549-4723-9f19-30a87e0e8262.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 8
  - DB openDJ
  - 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate
