### ISSUE TITLE
fix(jans-cli-tui) error when installing  janssen server with quick start way

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3217]
**Describe the bug**
error when installing  janssen server with quick start
getting error "Access token was not found."

**To Reproduce**
1.run command 
wget https://raw.githubusercontent.com/JanssenProject/jans/main/automation/startjanssenmonolithdemo.sh && chmod u+x startjanssenmonolithdemo.sh && sudo bash startjanssenmonolithdemo.sh demoexample.jans.io MYSQL
2. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/205844251-b06e4cb8-c6d3-4d1e-8246-5fc8399a4c36.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - -DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moabu** [comment]
fixed in https://github.com/JanssenProject/jans/commit/e312e9e09db8dbc461c82820b9f5093bbcac5795
