### ISSUE TITLE
fix(jans-cli-tui) : unable to add claims whille creating new user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3219]
**Describe the bug**

**To Reproduce**
1. launch jans-cli-tui
2. goto add user
3. fill mendatory information and press add claim
4. select multiple claims
5. press save button
6. See error

**Expected behavior**
should not get any error while adding claims to  user

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/205861239-ef79b43a-38d5-4a97-8638-412e5ed18055.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
-DB pgsql
-jans server 1.0.5

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
does this Error happen for any field?
have you filled the selected claims with data?
can you list the claims you test for?
@manojs1978

**Comment by manojs1978** [comment]
Hi @AbdelwahabAdam ,
 i selected multiple fields,might be some of from below field causing issue
![image](https://user-images.githubusercontent.com/5729240/206702887-bf8c9ae0-1df8-4e99-9477-9675bd939bda.png)

**Comment by AbdelwahabAdam** [comment]
The problem in `Last Updated` feild

**Comment by devrimyatar** [comment]
We  removed **updatedAt** in commit https://github.com/JanssenProject/jans/pull/3287/commits/a5c51ef06da3fe175f0b899cf4ecdc526286a85d
