### ISSUE TITLE
Token Exchange

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#323]
We get a lot of requests for token exchange. MITRE has developed some documents that provide some use cases for token exchange that might be helpful for implementation of this feature:

- https://www.mitre.org/publications/technical-papers/token-and-identity-chaining-between-protected-resources-in-a-single-icam-ecosystem-using-oauth-token-exchange
- https://www.mitre.org/publications/technical-papers/token-and-identity-chaining-between-protected-resources-in-a-multiple-icam-ecosystem-using-oauth-token-exchange

**Comment by yuriyz** [comment]
Token Exchanges was implemented during Native SSO development https://github.com/JanssenProject/jans/issues/2518 .
