### ISSUE TITLE
Feat: update both enc and sign algorithms on the server

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#326]
## Describe the issue
Feat: update both enc and sign algorithms on the server

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

authorization_encryption_alg_values_supported | RSA1_5,RSA-OAEP,RSA-OEAP-256,ECDH-ES,ECDH-ES+A128KW,ECDH-ES+A192KW,ECDH-ES+A256KW,A128KW,A192KW,A256KW,dir,A128GCMKW,A192GCMKW,A256GCMKW,PBES2-HS256+A128KW,PBES2-HS384+A192KW,PBES2-HS512+A256KW
-- | --
authorization_encryption_enc_values_supported | A128CBC-HS256,A192CBC-HS384,A256CBC-HS512,A128GCM,A192GCM,A256GCM
authorization_signing_alg_values_supported | PS384,RS384,HS256,HS512,RS256,HS384,PS256,PS512,RS512
backchannel_authentication_request_signing_alg_values_supported | RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
dpop_signing_alg_values_supported | RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
id_token_encryption_alg_values_supported | RSA1_5,RSA-OAEP,RSA-OEAP-256,ECDH-ES,ECDH-ES+A128KW,ECDH-ES+A192KW,ECDH-ES+A256KW,A128KW,A192KW,A256KW,dir,A128GCMKW,A192GCMKW,A256GCMKW,PBES2-HS256+A128KW,PBES2-HS384+A192KW,PBES2-HS512+A256KW
id_token_encryption_enc_values_supported | A128CBC-HS256,A192CBC-HS384,A256CBC-HS512,A128GCM,A192GCM,A256GCM
id_token_signing_alg_values_supported | PS384,RS384,HS256,HS512,RS256,HS384,PS256,PS512,RS512
introspection_endpoint_auth_signing_alg_values_supported | HS256,HS384,HS512,RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
request_object_encryption_alg_values_supported | A192GCMKW,RSA-OAEP,dir,A192KW,A128GCMKW,PBES2-HS256+A128KW,PBES2-HS384+A192KW,RSA-OEAP-256,A128KW,A256GCMKW,A256KW,RSA1_5,PBES2-HS512+A256KW
request_object_encryption_enc_values_supported | A128CBC-HS256,A192CBC-HS384,A256CBC-HS512,A128GCM,A192GCM,A256GCM
request_object_signing_alg_values_supported | HS256,HS384,HS512,RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
revocation_endpoint_auth_signing_alg_values_supported | HS256,HS384,HS512,RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
token_endpoint_auth_signing_alg_values_supported | HS256,HS384,HS512,RS256,RS384,RS512,PS256,PS384,PS512,ES256,ES384,ES512,ES256K,EdDSA
userinfo_encryption_alg_values_supported | RSA1_5,RSA-OAEP,RSA-OEAP-256,ECDH-ES,ECDH-ES+A128KW,ECDH-ES+A192KW,ECDH-ES+A256KW,A128KW,A192KW,A256KW,dir,A128GCMKW,A192GCMKW,A256GCMKW,PBES2-HS256+A128KW,PBES2-HS384+A192KW,PBES2-HS512+A256KW
userinfo_encryption_enc_values_supported | A128CBC-HS256,A192CBC-HS384,A256CBC-HS512,A128GCM,A192GCM,A256GCM
userinfo_signing_alg_values_supported | PS384,RS384,HS256,HS512,RS256,HS384,none,PS256,PS512,RS512

</body>
</html>

**Comment by ossdhaval** [comment]
@yuriyz 

I think this can be closed with all PRs from @smansoft now merged. Can confirm and close?

**Comment by yuriyz** [comment]
@ossdhaval can you point me to merged PRs ? I see only big PRs which were not merged because of abnormal size and many refactoring changes. We can't merge such PRs.

**Comment by ossdhaval** [comment]
@yuriyz Maybe I was wrong in thinking all PRs have been merged. I added this comment 2 months back and now I don't remember what it was based on :confused: 

Anyway, @smansoft did a lot of work but unfortunately, the PRs were not of reviewable size. I can see that he also attempted to break it down to smaller PRs. Based on my search, the complete work is spread across below PRs:

https://github.com/JanssenProject/jans-auth-server/pull/210 - Full work is in this PR I believe. Too bit to review.
#383 - This seems to be a small PR, 7 changed files. Can this be reviewed and merged independently?
#385 - This seems to be a small PR, 7 changed files. Can this be reviewed and merged independently?
#669 - Merged already
#670 - Merged already

Do you think we can find a way forward from here?

**Comment by yuriyz** [comment]
383 and 385 are setup changes only. I don't see PRs to AS side for such changes. We can't change setup and declare something is supported if it is not supported. I guess main changes are in that big 210 PR. I'm closing 383 and 385 PRs for now. Also since 210 is not in reviewable state I think we can close this ticket even if it is not done. And open specific ticket for exact algorithm(s) that we think are useful for AS and which must be added. It will keep scope narrow and will not lead to huge PRs.

**Comment by ossdhaval** [comment]
@yuriyz Thank you for your actions on these issues. :handshake: 

About `exact algorithm(s) that we think are useful for AS and which must be added.`

You are the best judge here I believe. Can you please list out algorithms that you think should be our priority? I'll create issues for only those. Once these new issues are in place, I'll close JanssenProject/jans-auth-server#210
