### ISSUE TITLE
sha256sum  checksum command failing

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3274]
**Describe the bug**
sha256sum  checksum command failing while checking  package checksum

**To Reproduce**
1. download jans ubuntu package
2.  Download sha256sum file for the package
3. sha256sum -c jans_1.0.5.ubuntu20.04_amd64.deb.sha256sum

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/206636550-d074b99e-1730-44fa-95e0-7ef38aafd3d9.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser
  - Version 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nikdavnik** [comment]
Fixed this filename in checksum create script. In next build we can verify the fix and close this ticket

**Comment by manojs1978** [comment]
working fine now
able to complete checksum
