### ISSUE TITLE
feat(jans-config-api): add agama flow code syntax check endpoint

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#3277]
Add to existing agama endpoints one for syntax  check. This will help expedite development in ADS avoiding successive deployment attempts

**Comment by jgomer2001** [comment]
@duttarnab here's how you can use the endpoint:

|Endpoint|`/jans-config-api/api/v1/agama/syntax-check/{qname}`|
|-|-|
|Purpose|Determine if the text passed is valid Agama code|
|Method|POST|
|Path param|`qname` - the qualified  name of the flow to analyse. Example: `co.acme.MyFlow`|
|Body|The code. This payload is expected to be `Content-Type: text/plain`|
|Output|A JSON object. If it contains a `message` property, it means the code is invalid, and the object follows [this](https://github.com/JanssenProject/jans/blob/main/agama/transpiler/src/main/java/io/jans/agama/dsl/error/SyntaxException.java#L9) struture. This is helpful to show errors in the UI|
|Status|Always 200|

**Comment by jgomer2001** [comment]
@pujavs can you add the required swagger annotations to this endpoint please?

**Comment by pujavs** [comment]
Added spec via PR 3369 [https://github.com/JanssenProject/jans/pull/3369]
