### ISSUE TITLE
fix(jans-cli-tui): getting config api error on centos8

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3288]
**Describe the bug**
getting config api error with cloud spanner 

**To Reproduce**
1. install jans with cloud spanner backend
2. launch jans-cli-tui
3. See error

**Expected behavior**
shold able to launch jans-cli-tui and access it

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/206997611-8e54a6fd-5880-4afd-a6f0-1f8a00e6fba4.png)

**Desktop (please complete the following information):**
  - OS: centos8
  - Browser 
  - Version 8
  - DB cloud spanner/ mysql
  - jans 1.0.5

**Smartphone (please complete the following information):**

**Additional context**
[logs.zip](https://github.com/JanssenProject/jans/files/10206130/logs.zip)

**Comment by devrimyatar** [comment]
Can't replicate


https://user-images.githubusercontent.com/6398752/207317972-adea0955-3150-4a06-867f-a799ebe1457a.mp4
