### ISSUE TITLE
fix(jans-cli-tui) newly added client/user is not showing in one list

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3297]
**Describe the bug**
newly added client is not showing in one list

**To Reproduce**
1. install jans 1.0.5
2. launch jans-cli-tui
3. add new client/user
4. press get client/user
5. check for newly added client/user in list

**Expected behavior**
newly created client should show in client list

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/207239704-ca6259e2-cbbb-4385-8bd5-50b03983b4f3.png)
![image](https://user-images.githubusercontent.com/5729240/207239930-5242b9e1-74f7-4631-a862-5140f7756410.png)

**Desktop (please complete the following information):**
  - OS: opensuse
  - Browser 
  - Version 15
  - DB openDJ

**Smartphone (please complete the following information):**
 
**Additional context**
whe we search for client in search box then only newly created client is showing

**Comment by devrimyatar** [comment]
@manojs1978  We can't replicate it. How did you create cleint and user?

**Comment by manojs1978** [comment]
hello @devrimyatar ,
i installed jans without test data on suse environment
then created user/client with required mendatory data and searched for it

**Comment by devrimyatar** [comment]
This was due to 0-index base. Not happens in latest code
