### ISSUE TITLE
Test with FIPS Verified version of BouncyCastle

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#330]
We should create a test branch that uses one of the FIPS-2 verified Bouny Castle distributions. 

https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&ModuleName=Bouncy&CertificateStatus=Active&ValidationYear=0

**Comment by ossdhaval** [comment]
Hi @yuriyz 

It seems there were a few fixes that we merged that targeted this issue. Can this be closed?

**Comment by yuriyz** [comment]
According to last Mike's comment we can close it. Lets re-open if we need it.
