### ISSUE TITLE
Add person entry methods schould call idGenerator script

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#331]
This will allow to generate smart inum for people like `inum=hash(lower(user_name))`. This inum in combination with custom person script can help with DB optimization when there are many users. Instead of execution query to DB we can execute simple lookup operation which is in many times faster and requires less CPU DB resources.

**Comment by yurem** [comment]
The main idea of this issue is to allow replace random `inum` with smart based on authentication context `inum`. This will allow us to replace search operation with lookup by primary key. This will dramatically decrease AuthZ flow time. Now this operation do major load in our benchmark.

To implement this we can add new authentication method to person authentication script to get `inum` based on current authentication context. Also we need to call this method in version if this script will be bigger than current one.

**Comment by ossdhaval** [comment]
@Milton-Ch 

I am reviewing this old issue. I see a PR merged references this issue and says `Part of the work to be done for issue`. 

Few questions:
- Is this issue/request still relevant?
- Does the PR above has everything needed and this issue can be closed?

Please suggest.

**Comment by Milton-Ch** [comment]
@ossdhaval 

With the PR I uploaded above, I think the required issue was solved, but maybe @yuriyz could give us one more opinion, to close it for sure.

**Comment by yuriyz** [comment]
Yes, id generation now can use custom script which allows to customize id. Closing ticket.
