### ISSUE TITLE
fix(jans-cli-tui): should able to search anything from any column value in auth server client

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3351]
**Describe the bug**
should able to search anything from any column value in auth server client
we should able to search any value form any column (clientid, client name, grant types, subject type) from client

**To Reproduce**
1. install jans-cli-tui 
2. search in auth server > client > search box
3. search for any value from any column
4. unable to search from any column other than client name and  unable to search some word from client name as well, check screenshot attached

**Expected behavior**
should able to search any value from any column
**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/208365557-db8f3e75-ed8e-42fd-9896-68ed539f8e17.png)
![image](https://user-images.githubusercontent.com/5729240/208365591-2b33fae4-735c-4267-ad21-ea8d6682df5f.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
### can't replicate it

OS: ubuntu20
DB: mysql

https://user-images.githubusercontent.com/63171603/208427934-a0dfb478-838c-467f-bc14-f2b75cd16f75.mp4

**Comment by manojs1978** [comment]
we should able to search any value from any column in search text box

**Comment by devrimyatar** [comment]
Search is server side, **config-api-server** searches `displayName`, `description` and `inum`
