### ISSUE TITLE
fix(jans-cli-tui) unable to search value in script search 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3352]
**Describe the bug**
unable to search value in script search , we should able to search with any column value in search list

**To Reproduce**
install jans-cli-tui
go to scripts> search box
search for any value from any column
unable to search from any column other than description

**Expected behavior**
should able to search any value from any column

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/208371657-6e4bf5bb-96b0-42dc-b7a3-84293765c5cc.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Search is server side, **config-api-server** searches `displayName`, and `description`
