### ISSUE TITLE
fix(jans-cli-tui) unable to search user in search box

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3353]
**Describe the bug**
 unable to search user in search box

**To Reproduce**
install jans-cli-tui
go to users>add new user
go to search box >search for any value from any column

**Expected behavior**
should able to search newly created user in list
as showin in screenshot i have created manoj user and trying to search manoj user in search box bug getting screenshot error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/208376582-bace2bf7-b54a-43ef-b7b4-ce49c5c8fe75.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
### can't replicate it

OS: ubuntu20
DB: mysql

https://user-images.githubusercontent.com/63171603/208429015-8be6e1aa-7e4a-49a0-8526-e40813b7635d.mp4

### NOTE @manojs1978 
- maybe you can try to add some users
- Search for `username` only

**Comment by manojs1978** [comment]
@AbdelwahabAdam,
please check below , i already added one user

https://user-images.githubusercontent.com/5729240/208430659-b3a8be0b-4293-4f46-baaf-57d30e895359.mp4

**Comment by AbdelwahabAdam** [comment]
Fixed
