### ISSUE TITLE
Key History

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#336]
_nynymike commented on Apr 19, 2017_
How would an old signature be validated after key rotation happens? While the private key can be disposed of, we need to keep a history of the public keys. It would be best if this information was stored in the database, something like this:

```
dn: id=d07668b9d367,ou=keyhistory,o=(org-inum),o=gluu
objectclass: top
objectclass: oxKeyHistoryEntry
oxAuthConfWebKeys: {keyInfo}
oxAuthCreation: 20170129120000.0Z
oxAuthExpiration: 20170131120000.0Z
oxAuthKeyType: tls 
oxAuthIssuer:  https://idp.example.com
```

Note: `oxAuthKeyType` could have values either `tls` (normal key used for `jwks_uri`) or `signing` (used for OpenID Federation).

**Comment by ossdhaval** [comment]
@yuriyz 

I am reviewing this old issue. Do you think this is still relevant and should be on our roadmap? Please comment.

Based on relevance and importance, can you review and update the priority and effort labels?

**Comment by yuriyz** [comment]
We introduced archived jwks in this ticket https://github.com/JanssenProject/jans/issues/6437

I'm closing this one as done
