### ISSUE TITLE
fix(jans-cli-tui)(casa): services are not starting after reboot

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3362]
**Describe the bug**
all services are not starting after reboot

**To Reproduce**
1. install jans 
2. install admin,casa
3. check all jans and casa services are up
4. reboot VM
5. See all services are up or not

**Expected behavior**
All jans and casa services should be up

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/208615425-620d3e68-796c-4bee-b8e2-51edbf450e78.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Browser 
  - Version 20
  - DB postgresSql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This is not jans-cli-issue.
