### ISSUE TITLE
fix (jans-config-api): Not getting user records from user-mgmt apis

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#3368]
User records are missing in `GET` `/mgt/configuser` response.

![image](https://user-images.githubusercontent.com/32794267/208672887-a02ec0df-4fd5-4df6-874e-fe104c968ea6.png)

**Comment by pujavs** [comment]
Fixed via PR 3369 [https://github.com/JanssenProject/jans/pull/3369]

**Comment by pujavs** [comment]
![image](https://user-images.githubusercontent.com/43700552/208852496-10dd51ac-db28-48cc-8dbd-73c26ae0179b.png)
