### ISSUE TITLE
feat: update TUI to use SCIM for User Management

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3380]
The TUI currently calls the Config API `/configuser` endpoint for data. It would be better if it called the SCIM `/user` endpoint instead. This would leverage existing interceptions scripts for SCIM, and reduce the surface area for user update auditing.

**Comment by devrimyatar** [comment]
SCIM is optional, if not installed we can't use it.

**Comment by nynymike** [comment]
@jgomer2001 reports that:

```
SCIM could work, but you would have to manually add all attributes which are missing and take into
 account that attributes handled OOTB by SCIM do not match with physical attribute names of database.

This means we would have to add around 80 attributes to the extension, which makes the extension 
itself semantically wrong…

Also there is need to append new attributes as they are coming.

```
