### ISSUE TITLE
ID token's audience claim should be a string when there is only one value

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#339]
_bhammond604 commented on Apr 23, 2018_
The value of the ID token's audience claim is currently represented as an array (['AUDTOKEN']), even if there is only one value, which has been causing errors when testing against OpenID's certification testing tool (https://github.com/openid-certification/oidctest).

Instead of an array, the value of the audience token should be a string ('AUDTOKEN') when there is only one value.

_qbert2k commented on Jan 16, 2020_
The specs says:

> In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

We can make this **configurable** to allow select the desired behavior because it can be complicated for some customers to make an implementation that handles both response cases.

**Comment by Milton-Ch** [comment]
@yuriyz Looks like this feature was already implemented here: https://github.com/JanssenProject/jans/blob/546b1c23becbf9d00cdb4aaaeb086a44a9fb518b/jans-auth-server/model/src/main/java/io/jans/as/model/jwt/JwtClaims.java#L98
I validated this in my tests:
![aud2](https://user-images.githubusercontent.com/86965029/160022646-5025fb7c-1804-4434-8cd7-c728b19d737c.jpeg)
![aud1](https://user-images.githubusercontent.com/86965029/160022662-6f335e7a-20d0-448e-b519-20a0e0b8523d.jpeg)

**Comment by yuriyz** [comment]
It is correct, it was corrected some time ago here: https://github.com/GluuFederation/oxAuth/commit/bf0a87a69f31c3042d066aa819aca1ff51cd3f64

Closing this ticket.
