### ISSUE TITLE
Feat: filter JSON keys returned from .well-known/openid-configuration

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3406]
Issue [599](https://github.com/JanssenProject/jans/issues/599) filters just the `claims_supported`. What was actually needed was a way to filter all the keys returned from the `.well-known/openid-configuration` JSON response. It would be great if we could add an Auth Server Property like this:

```
 "opConfigMetadataAllowList" : ["issuer", "authorization_endpoint", "token_endpoint", "acr_values_supported", ...]  
 ```

If the value is either `None` or `disable`, it should be ignored.

**Comment by yuriyz** [comment]
In AS configuration we have two configuration properties which controls what is returned by discovery:
- `discoveryAllowedKeys` - all allowed keys
- `discoveryDenyKeys` -- all json key that must be denies

Filter method looks like [this](https://github.com/JanssenProject/jans/blob/bc1a8ca8b2c7e3b286f2762d9e84205f402cce4a/jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java#L294):
```
    public static void filterOutKeys(JSONObject jsonObj, AppConfiguration appConfiguration) {
        final List<String> denyKeys = appConfiguration.getDiscoveryDenyKeys();
        if (!denyKeys.isEmpty()) {
            for (String key : new HashSet<>(jsonObj.keySet())) {
                if (denyKeys.contains(key)) {
                    jsonObj.remove(key);
                }
            }
        }

        final List<String> allowedKeys = appConfiguration.getDiscoveryAllowedKeys();
        if (!allowedKeys.isEmpty()) {
            for (String key : new HashSet<>(jsonObj.keySet())) {
                if (!allowedKeys.contains(key)) {
                    jsonObj.remove(key);
                }
            }
        }
    }
```

@mmrraju would you please check docs has these properties described correctly ? I see `@DocProperty` for auto-docs generation are added (cc @ossdhaval ) 

Closing this ticket as completed.
