### ISSUE TITLE
feat(jans-auth-server): specify minimum ACR for clients

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#343]
_nynymike commented on Oct 10, 2018_
Customers want to be able to force a certain level of authentication to access certain clients. Is it possible to look at the `client_id`, and if the current session does not match the required acr, to force authentication with the requisite acr.

_yuriyz commented on Oct 10, 2018_
Session tracks all clients that take part in SSO. So indeed we can check whether required level of acr is set per client or not. Do we want to have it as relative level number as defined by `auth_level_mapping` (on well-known json), e.g. `50` or set acr e.g. `otp`?

```
"auth_level_mapping": {
        "-1": ["auth_ldap_server"],
        "50": ["otp"],
        "100": ["basic"],
        "10": ["u2f"],
        "15": ["super_gluu"]
    }
```
I can take over it if needed.

_qbert2k commented on Oct 12, 2018_
There is already an array of default requested Authentication Context Class Reference values (`default_acr_values`) per client that can be overridden/forced by the request parameter `acr_values`.

_nynymike commented on Oct 12, 2018_
But only in the authentication phase. So if a person is already logged in, these are ignored. What we want to do is force reauthentication. For example, before a code is sent back to the client

**Comment by yuriyz** [comment]
There is going to be new client properties: 
- `minimumAcrLevel` - integer value which sets minimum acr level.
- `minimumAcrLevelAutoresolve` - boolean value, if `false` and `minimumAcrLevel` is higher then current `acr_values` then reject request. If `true` - find nearest acr and continue authorization request processing.

Lets say acr to level map is as following
```
"auth_level_mapping": {
        "-1": ["auth_ldap_server"],
        "50": ["otp"],
        "100": ["basic"],
        "10": ["u2f"],
        "15": ["super_gluu"]
    }
```

and `minimumAcrLevel`: 14, then:
- if `acr_values=u2f` and `minimumAcrLevelAutoresolve=false` -> request is rejected
- if `acr_values=u2f` and `minimumAcrLevelAutoresolve=true` -> acr_values is replaced with nearest value `acr_values=super_gluu` and request continue processing
- if `acr_values=super_gluu` -> current acr is higher then minimum. Thus nothing to do.

Feedback on the above is welcome.

**Comment by nynymike** [comment]
The client should ideally have more control over this priority. I updated your example above.

**Comment by yuriyz** [comment]
@nynymike I like it, agreed.
