### ISSUE TITLE
New installation argument to modify the context /jans-auth

### ISSUE THREAD

**Issue by Milton-Ch** [JanssenProject/jans#3430]
During certification there is a discovery validation test, where AS is required to be installed on root context `/`, currently when a new installation is done, by default it is installed on context `/jans-auth`.

To comply with this, it is suggested to add a new installation argument `-jans-auth-api-prefix` which will be default to `/jans-auth`.

Test plan url
https://www.certification.openid.net/plan-detail.html?plan=BMrUE6MqnNRzM&public=true

**Comment by ossdhaval** [comment]
@devrimyatar @Milton-Ch 

I am reviewing aging issues in our backlog.

Is this issue still valid? 

If yes, then please add labels for priority and effort.

If not, then please close the issue/PR.

**Comment by devrimyatar** [comment]
I think we don't need this issue, test was passed. I tried implementing this before but I had issue with apache configuration. @Milton-Ch , please confirm.

**Comment by Milton-Ch** [comment]
@ossdhaval @devrimyatar 

This issue is no longer necessary, it was solved using a configuration that already brought jans-auth in apache2.
You can close this issue, thank you

**Comment by Milton-Ch** [comment]
@ossdhaval @devrimyatar 

This issue is no longer necessary, it was solved using a configuration that already brought jans-auth in apache2.
You can close this issue, thank you
