### ISSUE TITLE
TUI: enabledcomponents list needs to be checked if component is enabled

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#3438]
**Describe the bug**
As in the screenshot below, currently when we open enabledComponents list for modification, none of them comes with `check mark`. All of them are unchecked. 

![image](https://user-images.githubusercontent.com/343411/209819866-b2f68c19-bc4d-4b4d-b84e-2744eaa746f1.png)

expected behaviour is that if the components are enabled, they should come `checked` in the list. Assumption is that in Janssen, by default, all components are enabled.

It would be beneficial to check if the same behaviour is present in other places in TUI where similar list is displayed.

**Comment by devrimyatar** [comment]
Implemented in https://github.com/JanssenProject/jans/pull/3504/commits/3bb54d140a042f42efe45eff0a8c7cf1939653e9
