### ISSUE TITLE
fix: jans-cli-tui missing properties

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#3448]
**Describe the bug**
Jans config-api server does not return all configuration properties. For example  `mtlsUserInfoEndpoint` is missing

- [x] on TUI we need to have Add Properties button on **Auth Server:Properties** Screen, when pressed display a popup with key and value and use `patch, op:add` in cli operation (@AbdelwahabAdam)
- [x] in command line we use `--patch-add` argument which requires colon delimited **key:value** pairs, but we cant set for example `mtlsUserInfoEndpoint:https://example.jans.io/mtlsuserinfo` because value also contains colon (@devrimyatar)

**Comment by devrimyatar** [comment]
Second part is implemented in commit  7bd8d26bb2343acb171417cf87f7b28520c4fc8e , we can use escape character `\` for colons, for example
```
/opt/jans/jans-cli/config-cli.py --operation-id=patch-properties --patch-add="mtlsUserInfoEndpoint:https\://example.jans.io/muserinfo"
```

**Comment by ossdhaval** [comment]
@devrimyatar 
Above fix will enable addition of `mtlsUserInfoEndpoint` **explicitly**. But the question is that, like other listed properties, why does this property not get loaded in the properties list automatically? And maybe there are more such missing properties.

**Comment by devrimyatar** [comment]
@ossdhaval TUI displays what it get from config-api server. So the first fix for TUI (add property button) will fix it.

**Comment by devrimyatar** [comment]
Implemented

**Comment by devrimyatar** [comment]
Missing properties are listed in dialog when you press **Add Property** button

![image](https://user-images.githubusercontent.com/6398752/213654258-ce7ab897-f23e-45bc-ad31-ac48f50a1ddb.png)
