### ISSUE TITLE
TUI: Improve Scope Management for OpenID Client

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3460]
![image](https://user-images.githubusercontent.com/3717101/210007976-c70c70d8-605b-4e15-b426-e07a476d186c.png)

- [x] 1. I'd expect the scopes to show the name of the scope, e.g.  `openid` or `profile`, not the DN of the scope.

- [x] 2. Also, it's not obvious that there are more then three scopes... if you tab to the scopes you can arrow-down to see more... but a person might not realize this. I wonder if there is some more compact way to display the scopes. For example, could we display each scope like this:
 ![image](https://user-images.githubusercontent.com/3717101/210008548-8fe0d829-2000-413f-bff5-64af5d04b6d9.png)
And if you navigate to a scope and hit return, it is removed (or you get a modal window to confirm removal).
- [ ] 3. We need a modal window to add scopes, which enables the admin to search through the existing scopes. No admin will know the DN of the scope entry.

**Comment by AbdelwahabAdam** [comment]
![image](https://user-images.githubusercontent.com/63171603/210381350-17855476-3446-41a5-8e95-4c59844fa160.png)

**Comment by devrimyatar** [comment]
For Scopes, let's do it as a list, so that we can delete as Mike proposing in (2).
@nynymike in part (2) we can only use listbox like we did for scopes

![image](https://user-images.githubusercontent.com/6398752/210406582-73482542-99f5-4b4e-96cd-bb46cb9a93e3.png)

In this way we can delete by pressing `delete` on keyboard

**Comment by AbdelwahabAdam** [comment]
![image](https://user-images.githubusercontent.com/63171603/210629194-d2edfaba-3e5f-424d-b336-a49f808d2561.png)
