### ISSUE TITLE
fix(jans-cli-tui): getting error "no script found for this search"

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3468]
**Describe the bug**
 getting error "no script found for this search

**To Reproduce**
1. launch jan-cli-tui
2. goto scripts then press get scripts
3. press next ,next to navigate through list
4. press previos button multiple times
5. See error

**Expected behavior**
should not get any error and first page should not have prev button. 

**Screenshots**

https://user-images.githubusercontent.com/5729240/210063194-99677972-cb1c-4559-ae19-f147a632e6a9.mp4

**Desktop (please complete the following information):**
  - OS: centos8
  - Version 8
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdelwahabAdam** [comment]
## Fixed
