### ISSUE TITLE
feat(jans-auth-server): add flexible date formatter handler to AS (required by certification tools)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#3600]
### Description

feat(jans-auth-server): add flexible date formatter handler to AS (needed by certification)

We have different places in AS where date is formatted in one way while certification tools may expect another format (depending on tool). We have to provide flexible way to return dates in different formats.

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

**Comment by Milton-Ch** [comment]
@yuriyz I checked this new feature, but it only works for `/userinfo` endpoint.
I made an extension to make it work on `/authorize` endpoint.

**Comment by yuriyz** [comment]
@Milton-Ch right, we should use this generic service in places where we need it to pass certification and where we need custom formatter. Approved and merged.

**Comment by Milton-Ch** [comment]
@yuriyz  @nynymike 
This birthdate formatting fix must be taken to `oxAuth`.
I get the same error that I got in `Jans`.

![image](https://user-images.githubusercontent.com/86965029/217983529-e04a2ae5-a49c-4f16-a4b6-d4e6c52fa81b.png)
