### ISSUE TITLE
fix(jans-tui): unable to edit auth server properties

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3628]
**Describe the bug**
unable to edit auth server properties

**To Reproduce**
1. install jans 1.0.6
2. launch tui
3. edit auth server properties

**Expected behavior**
shold not  get any error while editing

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/212628545-904b55f1-79c9-4a38-9712-b46865fa7835.png)

**Desktop (please complete the following information):**
  - OS: ubuntu 20
  -  DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate with recent code

https://user-images.githubusercontent.com/6398752/213686081-d95522f5-0795-4a80-9c9c-5ae39ba4a674.mp4
