### ISSUE TITLE
fix: issue with OxAuthPersistentJwt attribute in custom users

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#3651]
When creating a new custom user and setting an array of values for the `OxAuthPersistentJwt` attribute, the new object that is created and returned by the backend has a different structure:

Input: 
```
"oxAuthPersistentJwt":["jwt1","jwt2"]
```

Output:
```
"oxAuthPersistentJwt":["{\"v\":[\"{\\\"v\\\":[\\\"jwt1\\\",\\\"jwt2\\\"]}\"]}"]
```
The structure doesn't seem to be correct. This is similar to the issue we opened in regards of the claim passed having the same returned structure . At the moment this is not happening here .

**Comment by pujavs** [comment]
Tested in LDAP and MySQL, getting issue in MySQL, shared details with @yurem 
[vokoscreenNG-2023-01-24_17-31-31.zip](https://github.com/JanssenProject/jans/files/10506714/vokoscreenNG-2023-01-24_17-31-31.zip)

**Comment by yurem** [comment]
`jansPersistentJWT` isn't defined as multivalued in [schema](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/schema/jans_schema.json#L788). But in Bean it's defined as multivalued (String[]). We need to add to this attribute definition in schema:
```
      "multivalued": true,
```

After reinstalling we can check if this resolved the issue

**Comment by pujavs** [comment]
@moabu, this issue has been fixed. Request you to please verify

https://user-images.githubusercontent.com/43700552/216623214-7153b843-0ca9-49b3-9b4a-8d2ab3ff888a.mp4

**Comment by moabu** [comment]
verified
