### ISSUE TITLE
feat(jans-auth-server): Enable JWT response at introspection point 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3658]
```
   The introspection response, as specified in OAuth 2.0 Token
   Introspection [RFC7662], is a plain JSON object.  However, there are
   use cases where the resource server requires stronger assurance that
   the authorization server issued the token introspection response for
   an access token, including cases where the authorization server
   assumes liability for the content of the token introspection
   response.  An example is a resource server using verified person data
   to create certificates, which in turn are used to create qualified
   electronic signatures.

```

https://datatracker.ietf.org/doc/draft-ietf-oauth-jwt-introspection-response/12/

**Comment by yuriyz** [comment]
It was implemented in oxauth and exists in jans-auth as well, ticket https://github.com/GluuFederation/oxAuth/issues/947

There is new request parameter
```
response_as_jwt - OPTIONAL. Boolean value with default value false. If true, returns introspection response as JWT (signed based on client configuration used for authentication to Introspection Endpoint).
```

doc commit: https://github.com/GluuFederation/docs-ce-prod/commit/160fb4c2f3dce1b7b4b72d3c040e91b611a49edc#diff-620375772b9fe2e79f764c4c30b81cdc58f6d2a7cf16ce1537dfd36e71e21423

Closing as implemented.

**Comment by yuriyz** [comment]
Re-opened, spec is not fully covered.

Not sure how it got missed but AS picks up signing algorithm from `defaultSignatureAlgorithm` configuration property while spec clearly saying about client specific (not global):
- introspection_signed_response_alg
- introspection_encrypted_response_alg
- introspection_encrypted_response_enc  

Also supported algs has to be introduced by discovery endpoint.
