### ISSUE TITLE
BUG: TUI should not copy | for server property

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3659]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/3717101/213901820-e46eb781-3792-4f8a-8fc2-0ff2e9fdcb32.png">

What is copied is  `|endsessionWithAccessToken` ... maybe we need to add a space to the left so it doesn't copy the `|` ?

**Comment by AbdelwahabAdam** [comment]
all lists have been spaced by one space to the right
