### ISSUE TITLE
Remove token_revocation_endpoint key from discovery response

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#367]
Token revocation endpoint should be advertised on on discovery page as `revocation_endpoint`. In oxAuth this was `token_revocation_endpoint` left for backwards compatibility but in Auth Server, we should remove it.

https://tools.ietf.org/html/rfc8414

**Comment by jmunozherbas** [comment]
There is a commit fixing it: 
https://github.com/JanssenProject/jans/commit/a9cd7a5a4751fbdc3eda46d4febf3a354e71705e
"token_revocation_endpoint" was removed in this commit.

**Comment by yuriyz** [comment]
Got it, thanks. It seems I forgot to close this ticket.
