### ISSUE TITLE
feat(jans-config-api): add endpoints for users' consent management

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#3672]
In summary, implement a REST API that offers the same functionality of this plugin for the case of Jans: https://gluu.org/docs/casa/plugins/consent-management/

So for a given userId:
1. Retrieve the authorizations the user has granted, eg. what clients/scopes 
1. Revoke the authorizations the user granted to a given client

You'll get some idea taking a look at this [class](https://github.com/GluuFederation/flex/blob/main/casa/plugins/client-authorizations/src/main/java/org/gluu/casa/plugins/consent/service/ClientAuthorizationsService.java) and probably using casa-flex with that plugin installed

Also, you might reuse some logic from the `/revoke` [endpoint](https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/java/io/jans/as/server/revoke/RevokeRestWebService.java#L37) of AS for point 2, however this requires prior knowledge of the client/token pair

**Comment by pujavs** [comment]
Looking into this

**Comment by jgomer2001** [comment]
thx. The plugin for the flex version of casa is this one: https://maven.gluu.org/maven/org/gluu/casa/plugins/authorized-clients/5.0.0-SNAPSHOT/authorized-clients-5.0.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by pujavs** [comment]
- GET jans-config-api/api/v1/clients/authorizations/{userId}

![image](https://user-images.githubusercontent.com/43700552/225702252-a7c4411a-aad0-4457-aa2d-d053b4b95c23.png)

**Comment by pujavs** [comment]
- GET jans-config-api/api/v1/clients/authorizations/{userId}
- DELETE jans-config-api/api/v1/clients/authorizations/{userId}/{clientId}/{username}

![image](https://user-images.githubusercontent.com/43700552/229118719-19145f11-723e-43c4-9f48-a9f1827de83d.png)
