### ISSUE TITLE
fix(jans-config-api) :  error getting in jans configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3679]
**Describe the bug**
error getting in jans configuration

**To Reproduce**
1. install jans 1.0.6 with  couchbase
2. device authentication
4. See error for jans configuration and fido 2 configuration

**Expected behavior**
should not get any configuration error

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/214242740-d6d71d08-258a-4ae8-82f0-d59013b026d6.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20
  - couchbase 7.1.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This is config-api issue not TUI issue. @pujavs please close after you fix the issue

**Comment by pujavs** [comment]
Fixed via PR [3697](https://github.com/JanssenProject/jans/pull/3697)

**Comment by pujavs** [comment]
@manojs1978 request you to please test the fix
