### ISSUE TITLE
Set public subject identifier per client

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#368]
It's possible that one application would want email as the public identifier for subject, while another might want username. We should enable the public subject identifier to be set on a per client basis.

**Comment by qbert2k** [comment]
1. In the configuration, set publicSubjectIdentifierPerClientEnabled to true.
2. Configure the supported attributes.

![image](https://user-images.githubusercontent.com/2474616/153494202-bca2a208-d49c-4655-8e7f-200389520ea9.png)

**Comment by yuriyz** [comment]
@qbert2k we got test failures after PR merge (https://github.com/JanssenProject/jans/pull/800)
Would you please check? 

![image](https://user-images.githubusercontent.com/2013070/153859059-3a6ab128-6e34-4c2a-9dec-fe66ff8e95fb.png)

https://jenkins.jans.io/jenkins/job/jans-auth-server/5512/

**Comment by yuriyz** [comment]
Restored Javier's commits which was removed during jans-linux-setup refactoring by Mustafa.
https://github.com/JanssenProject/jans/pull/835

Closing this ticket as solved.
@qbert2k Please re-open if needed.
