### ISSUE TITLE
fix(jans-linux-setup) progress bar showing after installation as well

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3689]
**Describe the bug**

**To Reproduce**
1. install jans using install.py
2. while installing check progress bar

**Expected behavior**
progress bar should close after installation 

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/214487119-d165d9d2-2bb5-4bc9-8d0c-96754b3965ef.png)

**Desktop (please complete the following information):**
  - OS: ubuntu1
  - Version 20
  - -DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
![image](https://user-images.githubusercontent.com/6398752/216265840-08328cca-adf4-4494-ae3a-06ad21eddd32.png)

 @manojs1978 this progress bar is not jans-setup. It seems it is apt's progress bar. I don't know why it is there.

**Comment by devrimyatar** [comment]
Closing this issue, since it is not setup progress bar
