### ISSUE TITLE
Support new localizations without modifying faces-config.xml

### ISSUE THREAD

**Issue by martynaslawinska** [JanssenProject/jans#369]
We need to find a way how to avoid editing: https://github.com/GluuFederation/oxAuth/blob/version_4.1.1/Server/src/main/webapp/WEB-INF/faces-config.xml#L7

And use instead of this list: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxauth-config.json#L175
which it's possible to change in oxTrust GUI.

**Comment by Milton-Ch** [comment]
@yuriyz @martynaslawinska @yurem About this ticket, I checked in Janssen and oxAuth, however last version of both repos don't have list of values in `faces-config.xml` and I'm thinking it was implemented as part of https://github.com/GluuFederation/oxAuth/commit/effb15822de0acadee48a6647ede47aa07bf8cb2

**Comment by yuriyz** [comment]
Right, it seems to be implemented as part of https://github.com/GluuFederation/oxAuth/issues/1275

Check whether all is done in jans and if yes, close this ticket.

**Comment by Milton-Ch** [comment]
Yes, confirmed, it's all done.
