### ISSUE TITLE
Add client claim to enable explicit configuration of id_token lifetime

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#373]
Currently, the lifetime of the id_token is configured globally at the OP level--i.e. the idTokenLifetime attribute in the JSON configuration, applies to all clients available. It would be nice if id_token lifetime could be configured per client. If a client does not have this configuration, it should use the default OP lifetime. 

Impacts: ORM, config-API, documentation.

**Comment by ossdhaval** [comment]
Hi @yuriyz 

This is an old issue. Could there be any changes in the status?

**Comment by yuriyz** [comment]
It was implemented as part of this ticket https://github.com/JanssenProject/jans/issues/2656
