### ISSUE TITLE
feat(jans-auth-server): /ssa endpoint must use key_ops=ssa keys

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#3746]
### Description

feat(jans-auth-server): /ssa endpoint must use key_ops=ssa keys
ssa keys does not expire for long time (e.g. 10 years).

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by Milton-Ch** [comment]
To complete this issue I have a question:
- Should I work to make it `backwards compatible`? By this I mean, if I cannot find keys of type `ssa`, then I should use keys of type `connect`.

**Comment by yuriyz** [comment]
I would say throw exception if `ssa` key is not found, so we got both error in log and error response. We should indicate that we have problem instead of hiding it. If we sign SSA with `connect` keys and it gets rotated then SSA validation will fail which is exactly what we want to avoid.

cc @nynymike 

@Milton-Ch you can use newly added cryptoProvider method to get key with keyOps as parameter, pass `KeyOps.SSA` into that method.
```
public String getKeyId(JSONWebKeySet jsonWebKeySet, Algorithm algorithm, Use use, KeyOps keyOps) throws CryptoProviderException
```
https://github.com/JanssenProject/jans/blob/2be2a0346d7ed0541bb540e3c2ff32aa3a04dcf7/jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AbstractCryptoProvider.java#L71

**Comment by Milton-Ch** [comment]
To generate the `JWT` should I also use the `ClientSecret` in case I have the client configured?
Or is this field only for `OIDC`?

**Comment by yuriyz** [comment]
No, we should use asymetric algorithm for SSA, so no client secret.
