### ISSUE TITLE
test(agama): some agama tests are not passed on jenkins but works on newly spinned vm

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#3754]
### Description

![image](https://user-images.githubusercontent.com/2013070/216021336-1fc192c5-8785-4c3c-986a-9c483c445c8d.png)

![image](https://user-images.githubusercontent.com/2013070/216022927-7bf4675c-435d-47c9-98ea-1faef3b2ada4.png)

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by jgomer2001** [comment]
it's weird, here's some evidence that tests can effectively pass on `jenkins-build.jans.io` (ldap container). This was run on 2023-02-03 18:40:26-18:41:03 UTC. The closest job to this timeframe is jans-auth-server-ldap/1637 (same day at 13:39:33) which shows them all failed!

[agama-tests-Feb03-0140pm.txt](https://github.com/JanssenProject/jans/files/10581872/agama-tests-Feb03-0140pm.txt) (timezone of file is UTC -5)

**Comment by jgomer2001** [comment]
https://github.com/JanssenProject/jans/commit/9bd598b446b172f74f3daa5ac31d9ed380ae8638

We are OK now, see last row:

![Screenshot from 2023-02-10 06-46-59](https://user-images.githubusercontent.com/5444180/218085022-0c7fae3b-5b67-4d29-aac7-f220e55709e0.png)
