### ISSUE TITLE
Implement FF4J: Feature Flags for Java

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#381]
Feature Toggle is the capability for an application, a system or a product to enable and/or disable features through configuration (files, databases,…) and possibly at runtime. FF4J, stands as Feature Flipping for Java, is an implementation of this pattern for the Java platform.

https://ff4j.github.io/

**Comment by ossdhaval** [comment]
Closing this issue since FF4J implementation is not required anymore as we have decided on continuing with JSON flag based approach.
