### ISSUE TITLE
fix(casa): unable to set primary authenticatin method

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3868]
**Describe the bug**
unable to set primary authenticatin method in casa

**To Reproduce**
1. configure 2 authentication methods to enable 2fa
2. enable 2fa
3. Click on "set primary method"
4. save and logout
5. 

**Expected behavior**
should able to login with set primary authentication method while relogin.
![image](https://user-images.githubusercontent.com/5729240/219316898-033875b1-6659-4d13-9f98-4341423aa163.png)

**Screenshots**
still using bydefault (fido usb)  method to login to casa and when inserted fido usb ,getting error.html 
oops unexpected encoutered page.

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser chrome
  - Version 20.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
@manojs1978 fido2 is not working well, see https://github.com/GluuFederation/flex/issues/759

that explains why it fails for you

Please open casa issues under GluuFederation/flex not JanssenProject/jans

I will transfer this issue

**Comment by manojs1978** [comment]
ok moving this issue  to  flex
