### ISSUE TITLE
fix(jans-config-api): unable to create client using API

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3872]
**Describe the bug**
unable to create client using API

**To Reproduce**
1. download schema json using command /opt/jans/jans-cli/config-cli.py --schema Client >/tmp/Client.json
2. modify client.json 
3. add client name and redirect url mendatory fields  only
4. /opt/jans/jans-cli/config-cli.py --operation-id post-oauth-openid-client --data /tmp/Client.json
5. See error
getting below error
{
  "server_error": "com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String &quot;string&quot;: not a valid representation (error: Failed to parse Date value &#x27;string&#x27;: Unparseable date: &quot;string&quot;)\n at [Source: (org.eclipse.jetty.server.HttpInput); line: 1, column: 36] (through reference chain: io.jans.as.common.model.registration.Client[&quot;expirationDate&quot;])"
}

**Expected behavior**
should able to create client with mendatory fields

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/219387639-33fb6242-f3a8-4509-a4af-48100287dca1.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 20
-DB openDJ
**Smartphone (please complete the following information):**

**Additional context**
[Clientjson.txt](https://github.com/JanssenProject/jans/files/10764614/Clientjson.txt)

**Comment by devrimyatar** [comment]
@manojs1978 This is neither config-api nor cli issue, `expirationDate` should be in ISO format, for example, `2024-07-30T23:40:21`. The following basic `client.json` works well 

```
{
	"disabled": false,
	"clientName": "testclient",
	"clientSecret": "TopSecret",
	"description": "Test Client",
	"subjectType": "public",
	"grantTypes": ["client_credentials"],
	"responseTypes": ["token"],
	"applicationType": "native",
	"redirectUris": ["https://jans.io/cb"],
	"expirationDate": "2024-07-30T23:40:21",
	"displayName": "testclient"
}
```
Result:



![image](https://user-images.githubusercontent.com/6398752/220044144-86b5b6fc-f19f-4523-b337-3e8285e5d656.png)
