### ISSUE TITLE
fix: script **GithubAuthenticatorForADS.py** should not be installed automatically.

### ISSUE THREAD

**Issue by smansoft** [JanssenProject/jans#3883]
**Describe the bug**
Script [**GithubAuthenticatorForADS.py**](https://github.com/JanssenProject/jans/blob/main/docs/script-catalog/person_authentication/github-external-authenticator/GithubAuthenticatorForADS.py) should not be installed automatically.

**Comment by nynymike** [comment]
Agreed! ADS is a third party commercial SaaS. We publish lots of them, like Duo and BioID, but they should not be automatically installed.
