### ISSUE TITLE
fix: bug in setting `acr_values` in clients

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#3888]
**Describe the bug**
1. If a script is set in the client as a default acr to be used it doesn't work. It will assign it correctly in the url i.e `&acr_values=inum.....` but it won't work showing a white screen
2. the default server acr somehow was empty upon a fresh setup.

**Comment by jgomer2001** [comment]
just in case -  you pass script display name, not inum

**Comment by yuriyz** [comment]
re: 1, @jgomer2001 is right, we must use name of the script, not inum.

re: 2, reassigned to @devrimyatar to check installation.

**Comment by devrimyatar** [comment]
Fixed in PR https://github.com/JanssenProject/jans/issues/4356

![image](https://user-images.githubusercontent.com/6398752/231700142-c7b6ff7f-2cc2-4440-a2de-1201ae41f9da.png)
