### ISSUE TITLE
fix:(jans-cli-tui) unable to add user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#3895]
**Describe the bug**
unable to add user

**To Reproduce**
1. install jans nightly build  jans--nightly-build_1.0.6.ubuntu20.04_amd64.deb
2. launch jans-cli-tui
3. add user
4. search for newly added user

**Expected behavior**
should able to search and edit user

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/220285910-88c8d470-75ea-410a-8850-b1c6091df63a.png)

![image](https://user-images.githubusercontent.com/5729240/220285771-435f2191-1dc7-46ab-bdf0-303e95332736.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Browser 
  - Version 20.04
  - dB couchbase

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs , jans-config-api creates user with **jansCustomPerson** rahter than **jansPerson**

![image](https://user-images.githubusercontent.com/6398752/223157775-e4409896-6461-42be-bee6-17658aab6c79.png)

**Comment by pujavs** [comment]
When checked the creation via curl the user is successfully created and returned 
However when tested via tui, user is created and response returned by config-api as per logs but TUI does not display the same on screen. Does not seem to be config-api issue.
Request you please verify once

**Comment by pujavs** [comment]
@devrimyatar , @manojs1978 - request you to please check and revert
