### ISSUE TITLE
fix(jans-fido2): Exception handling for endpoints

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#3902]
Steps to reproduce:
1. visit - https://my.jans.server/jans-fido2/restv1/assertion/authentication
2. Exception 
![image](https://user-images.githubusercontent.com/12072533/220367991-6fc5d545-3522-4abb-a3ca-3f3cf103256f.png)
3. Exception handling should be on the same lines of `https://my.jans.server/jans-auth/restv1/authorize` and here is a reference - https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java

**Comment by yurem** [comment]
When I try to execute `curl -X POST <server>/jans-fido2/restv1/attestation/registration` I get stack trace in client response

**Comment by yurem** [comment]
For reference you can take a look on jans auth how it handle such excpetions
