### ISSUE TITLE
feat(tui): add support for view/edit agama project's flows configurations

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#4041]
let's add a "button" for every row in agama projects table labeled "Configurations". Upon clicking on it, show a window offering access to 3 functionalities:

1. Show current configurations 
2. Modify configurations
3. Show example configurations

For 1, retrieve the configurations using the `/agama-deployment/configs` GET endpoint passing the project name in the query string. This will retrieve a json object. You can either show the contents on the screen or dump the contents to disk and show the output path, or both things... If the retrieved json is empty, ie. `{ }`,  just show a message like "No configurations defined".

For 2, a json object must be supplied. How to input data? I'm not sure (through file upload maybe?). The contents must be sent to same endpoint of 1 via PUT

For 3, the sample configurations are found in the json you already obtained via GET `/agama-deployment` for the project in question. More specifically, in the `configs` key. If it is missing or has an empty json, show a message like "No sample configurations defined", otherwise, show the contents in the screen or dump them to disk, or both - it's up to you.

I'll add a comment to this issue when the endpoints for 1 and 2 are ready. I'm still working on them

**Comment by devrimyatar** [comment]
@jgomer2001 For 1 and 3, is this enough?
![image](https://user-images.githubusercontent.com/6398752/223162447-d36ee3c5-d667-4442-a6e9-e95e8c27f8e6.png)

When you press key **d** on keyboard, TUI displays deployment in json, you can save by pressing **Export** button

**Comment by jgomer2001** [comment]
yes @devrimyatar  a window like that is fine. Of course, We have to show only the "configs" section in this case

The idea is the user will see & export the sample configurations to a file, then edit & save them, and finally PUT those. These "real" configurations don't come in the deployment json (only the sample)

Also I would like to see the errors (if any) in its own window - not json. That is, show only the string error because this data  can be quite long and criptic  hence it is hard to interpret it in the middle of a bulky json content. This is a topic for a separate issue though

**Comment by jgomer2001** [comment]
closing this one, needs thorough refactoring
