### ISSUE TITLE
fix(jans-config-api): agama deployment endpoints not conforming with the projects API style

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#4048]
There is two main nonconformities in the agama deployment endpoints: 

1. All other API endpoints have the ID as a path parameter, here it is a query parameter. If there is no hard evidence that can lead to this style change this should be changed to path as well. The effected endpoints are : 
- `/api/v1/agama-deployment` `GET` `POST` `DELETE`
- `/api/v1/agama-deployment/list` `GET`

2. According to the openAPI definition, getting a deployment requires  three different scopes: `agama.readonly`, `agama.write`, `read-all`. Every other API call has a one scope to one operation mapping . Why is this different ?

**Comment by pujavs** [comment]
1. Modified endpoints to replace query parameter with replace parameter for 
/api/v1/agama-deployment/ GET POST DELETE PUT
/api/v1/agama-deployment/configs GET PUT

2. Rectified the scope change

Note: /api/v1/agama-deployment/list GET not modified

Changes not yet merged to main
