### ISSUE TITLE
chore(jans-linux-setup): fix typo in attribute name: `county`

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#4058]
should be `country` right? (object class `jansOrganization`):

![Screenshot from 2023-03-08 11-05-36](https://user-images.githubusercontent.com/5444180/223765718-16d06498-4054-438c-9be6-8d07ea422fae.png)

Actually I don't think we need this attribute, `c` has historically existed in ldap schema

**Comment by devrimyatar** [comment]
@yurem please comment
