### ISSUE TITLE
letsencrypt certitficate verification failed on jans-tent

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans#4126]
jans-tent couldn't be able to verify the certificate of letsencrypt enabled jans-server.

##  Error

```
SSLError
requests.exceptions.SSLError: HTTPSConnectionPool(host='jans-latest.gluu.info', port=443): Max retries exceeded with url: /jans-auth/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

```

**To Reproduce**
1. install jans-server with self-sgined certificate
2. setup jans-tent
3. create client and connect with jans-tent
4. test sso (it should work)
5. now upgrade certificate of jans-server (letsencrypt)
6. import updated certificate at jans-tent (`python certifi`)
7. check sso again (it should failed due to SSL verification error)

**Expected behavior**

jans-tent should work with letsencrypt certificate as well.

## Config
- janssen server (1.0.9)
- jans-tent client app
- ubuntu

**Comment by christian-hawk** [comment]
Are you running jans-tent on ubuntu and Jansen server too? what ubuntu version are you running `jans-tent` @imShakil ?

**Comment by christian-hawk** [comment]
Talked to @imShakil and he is running Mac OS native python. Is specific to his environment. 

I requested the following
- Install `pyenv` 
- `pyenv install 3.11` to install python 3.11
- Clone the latest `jans-tent`
- head to jans-tent folder
- `pyenv local 3.11`
-  create a virtual environment: `python -m venv venv`
- Activate venv: `source venv/bin/activate`
- Install packages: `pip install -r requirements.txt`
- **Skip** modifications on `certifi` as lets encrypt authorities should already be in cacerts.

**Comment by imShakil** [comment]
Thanks @christian-hawk It's working fine with your suggestions.
