### ISSUE TITLE
Feat [config-api][tui]: Agama Project Deployment based on URL

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#4214]
![image](https://user-images.githubusercontent.com/3717101/225741667-f4611e65-bc43-4971-80dc-00cf2d15492d.png)

If we know the URL of the repo Release section, the software name, and software version... we could download the release and verify the sha256 hash.

**Comment by pujavs** [comment]
@jgomer2001 request you please share more details, what needs to be done in config-api for the same

**Comment by nynymike** [comment]
We need to re-think this. Might re-open...
