### ISSUE TITLE
test: add device flow test

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#4238]
I think we should have a full test covering the device flow to confirm the functionality before releasing as its a vital point of failure for the TUI.

https://github.com/JanssenProject/jans/issues/4237

**Comment by ossdhaval** [comment]
@moabu are you talking about manual tests? If so, let's assign this to @manojs1978.

**Comment by manojs1978** [comment]
already we have covered device flow login, login using password authentication,login using agama flow.
https://github.com/JanssenProject/jans/wiki/Jans-VM-Pre-Release-Test-Plan
