### ISSUE TITLE
fix(tui) : showing default acr as agama

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4256]
**Describe the bug**

**To Reproduce**
1. install jans 1.0.10 
2. go to defalt in auth server

**Expected behavior**
it should contain other option as well , but there is only one value ie agama
that eans default_acr is set to agama

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/226818255-0f9cffeb-31cb-4c52-bb16-7e28622fbacd.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - -opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yuriyz** [comment]
@devrimyatar default AS acr is saved in `jansAuthMode`. Check whether you use value from this attribute. In setup currently value is `simple_password_auth` (which is about to be renamed to `default_password_auth`).
