### ISSUE TITLE
fix(jans-fido2): 2-step verification using fido is failing 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4257]
**Describe the bug**
2-step verification is failing getting registration failed error for fido2 device

**To Reproduce**
1.install jans 1.0.10 
2. launch tui
3. create auth server client 
4. enable fido script
5. use this client for 2-step verification 

**Expected behavior**
should be able complete 2-step verification

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/226822893-63692a81-5132-4d38-a2db-5287d4cc32d7.png)

**Desktop (please complete the following information):**
  - OS:ubuntu
  - Version 22
  - -opendj/mysql/pgsql

**Smartphone (please complete the following information):**

**Additional context**
[jans-auth.log](https://github.com/JanssenProject/jans/files/11037170/jans-auth.log)
[fido2.log](https://github.com/JanssenProject/jans/files/11037171/fido2.log)
[2023_03_22.jetty.log](https://github.com/JanssenProject/jans/files/11037172/2023_03_22.jetty.log)

**Comment by ossdhaval** [comment]
Hi @manojs1978, since this issue is open since long time, can you check if this is still reproducible and is still relevant?

**Comment by manojs1978** [comment]
fido2 device is not working on chrome browser  
already we have raised issue for it
https://github.com/JanssenProject/jans/issues/5594.
so closing this issue
