### ISSUE TITLE
fix(jans-cli-tui) client search  is case sensitive

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4264]
**Describe the bug**
client search  is case sensitive

**To Reproduce**
1. install jans
2. goto auth server > client
3. search for scim

**Expected behavior**
search should not be case sensitive

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/226857338-03506362-5460-4dde-9eaf-3ccf8932eb0c.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - couchbase

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nynymike** [comment]
This is a nice-to-have feature. Actually, client_id's are case sensitive.

**Comment by AbdelwahabAdam** [comment]
Not a Tui issue, but it is solved.

https://user-images.githubusercontent.com/63171603/230531433-89fa5e83-aa9b-48d7-b78f-b5ff0efb3b4d.mp4
