### ISSUE TITLE
feat(jans-config-api): ldap authentication management

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#4268]
This is follow up issue for https://github.com/JanssenProject/jans/issues/4265
We need an endpoint for managaging/testing ldap authentication.

**Comment by yuriyz** [comment]
@devrimyatar do you mean `/api/v1/config/database/ldap` or you need something else ?

https://github.com/JanssenProject/jans/blob/e20f399249055d7b0a65f2c807867c0678e0c787/jans-config-api/docs/jans-config-api-swagger.yaml#L4747
