### ISSUE TITLE
fix(jans-linux-setup) unable to install jans with opendj on suse15sp4

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4289]
**Describe the bug**
unable to install jans with ldap on suse15sp4

**To Reproduce**
1. download install.py 
2.  curl https://raw.githubusercontent.com/JanssenProject/jans/v1.0.11.nightly/jans-linux-setup/jans_setup/install.py > install.py
3. install jans  with opendj

**Expected behavior**
should able to install

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/227496933-4cabf3a4-656f-4843-91cc-04b0263b174a.png)

**Desktop (please complete the following information):**
  - OS: suse linux
  - Version 15 sp 4 
  - -opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
I were not be able to replicate.

**Comment by manojs1978** [comment]
same issue  i encountered in RHEL8 on new aws VM today.

![image](https://user-images.githubusercontent.com/5729240/236212363-cbd8f701-87f2-4a9f-84e0-7189b1dea672.png)

**Comment by devrimyatar** [comment]
This is aws suse15sp4 instance

![image](https://github.com/JanssenProject/jans/assets/6398752/120c1f0e-9137-4952-8062-f9ae77f4963d)

**Comment by devrimyatar** [comment]
Before executing setup, install the followings, since SLE15 standard repo is missing some rpms
```
zypper install python3-pip
pip3 install pymysql
pip3 install ruamel.yaml
```
