### ISSUE TITLE
fix(jans-auth-server) - Client registration request should default to code flow

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#4296]
>>> `response_types`
>>> OPTIONAL. JSON array containing a list of the OAuth 2.0 response_type values that the Client is declaring that it will restrict 
>>> itself to using. **If omitted, the default is that the Client will use only the `code` Response Type.**

>>> `grant_types ` 
>>> ...
>>> **If omitted, the default is that the Client will use only the `authorization_code` Grant Type.**

I believe this is a bug because there is no SHOULD here... it says the "default is". Also, these are listed as "Optional" params, so with no default they are "Requried".

**Comment by christian-hawk** [comment]
Information about default values found at section 2 from [OpenID Connect Registration Specs](https://openid.net/specs/openid-connect-registration-1_0.html)
