### ISSUE TITLE
feat [auth-server]: Device Flow needs configurable acr

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans#4305]
We need a way to specify the acr (and potentially other params, like `agama_flow=...`) for device flow. Otherwise when you enable two acr's, it's unpredictable which one may run.  Perhaps we can add two Auth Server configuration JSON properties : `device_flow_default_acr` and `device_flow_extra_authn_params` ?

**Comment by yuriyz** [comment]
It was already reported and fixed in 1.0.11 https://github.com/JanssenProject/jans/issues/4278

**Comment by yuriyz** [comment]
Re-opening and assinging to @devrimyatar to check whether cli sets default acr correctly.

**Comment by nynymike** [comment]
I repaced the original content of this message with the root cause--there is no way in Auth Server to specify the acr for device flow.
