### ISSUE TITLE
[Tent] Dynamic client registration leaving `grant_types` and `response_types` blank

### ISSUE THREAD

**Issue by christian-hawk** [JanssenProject/jans#4307]
# Bug description

When using the dynamic client registration feature from `jans-tent`, the client is created without the (openId specs) defaults `grant_types` (`authorization_code`) and `response_types` (`code`).

**To reproduce**
1. Start server as specified in jans-tent readme
2. submit a `POST` request to `/register` endpoint (replace `OP_HOSTNAME` with the actual op host)
```bash
curl --location --request POST 'https://localhost:9090/register' \
--header 'Content-Type: application/json' \
--data-raw '{
    "op_url": "https://OP_HOSTNAME",
    "client_url": "https://localhost:9090"
}'
```

Client is created without `grant_type` and `response_types`:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/59786962/227724586-125f931a-43d3-4ef0-9e5c-ae9252462b82.png">

**Comment by christian-hawk** [comment]
After investigation, we realized that the lib `Flask-OIDC` does the registration request as expected. But Jansen don't populate `grant_types` and `response_types` default values as specified in [OpenID Specs](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).

**Comment by nynymike** [comment]
It would be better to write a custom client reg class anyway in Tent. I don't think Flask-OIDC will support OAuth software statements, or some of the other custom client registration tricks we may want to try.

**Comment by christian-hawk** [comment]
The related problem, regarding to Tent, is client not being registered as expected, as explained in bug description. 
Client register customization is an enhancement and need to be better defined (probably in the respective issue). 

For now, this issue is focused in **making the current auto-register feature work as expected**. In matter of fact, it does (according to OpenID specs), but as Jans Server presented the bug reported in #4296 , it doesn't. This is why, regarding the scope of this issue, is a fix. 

I'm creating an issue for the customizing enhancement and will update this one right after.

**Comment by christian-hawk** [comment]
Created feature request #4336
