### ISSUE TITLE
fix(jans-linux-setup) unable to install jans with opendj on RHEL 8

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#4312]
**Describe the bug**
unable to install jans with opendj on RHEL8

**To Reproduce**
1. download install.py 
2. curl https://raw.githubusercontent.com/JanssenProject/jans/v1.0.11.nightly/jans-linux-setup/jans_setup/install.py > install.py
3. install jans  with opendj

**Expected behavior**
should able to install

**Screenshots**
![Screenshot (21)](https://user-images.githubusercontent.com/34593983/227922793-0b4c0c77-ecad-4748-93f0-11afb5c46e9f.png)

**Desktop (please complete the following information):**
  - OS: RHEL8
  - opendj

**Comment by devrimyatar** [comment]
@MohitMaliFtechiz Installation was good for me. Perhaps you forget to enable **epel-release** and **mod_auth_openidc**, and make sure selinux is disabled:

```
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum -y module enable mod_auth_openidc 
setenforce 0
```

![rh8-opendj](https://user-images.githubusercontent.com/6398752/228258425-1c5152fe-9362-4e4a-964a-f3e5ec79328c.png)
