### ISSUE TITLE
fix(jans-linux-setup) unable to install jans with mysql on RHEL 8

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#4314]
**Describe the bug**
unable to install jans with mysql on RHEL8

**To Reproduce**
1. download install.py 
2. curl https://raw.githubusercontent.com/JanssenProject/jans/v1.0.11.nightly/jans-linux-setup/jans_setup/install.py > install.py
3. install jans  with opendj

**Expected behavior**
should able to install

**Screenshots**
![Screenshot (22)](https://user-images.githubusercontent.com/34593983/227923669-1fa6ca6d-8225-4fdc-a1b9-a6045b29ebcd.png)

**Desktop (please complete the following information):**
  - OS: RHEL8
  - mysql

**Comment by devrimyatar** [comment]
@MohitMaliFtechiz Worked for me

Perhaps you forget to enable epel-release and mod_auth_openidc, and make sure selinux is disabled:
```
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum -y module enable mod_auth_openidc 
setenforce 0
```
![image](https://user-images.githubusercontent.com/6398752/228263340-c6f38ec9-0dad-4943-9c69-a70ef3790418.png)
