### ISSUE TITLE
fix(jans-scim): Device management using SCIM has to be updated to reflect Super gluu devices. 

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#4318]
**Describe the bug**
- [x] #4320
- [ ] #4319

Previously, SG devices were registered under ou=fido, inum=...., ou=people
![image](https://user-images.githubusercontent.com/12072533/228011098-456b7bc1-8021-4732-a5fc-bfa0945791ea.png)

Now SG devices have been moved under ou=fido2_register, inum= ..., ou=people
![SG_registration](https://user-images.githubusercontent.com/12072533/228011341-041fbdb0-c4a7-402b-a21a-38f54766150c.png)

**Comment by maduvena** [comment]
Yes, this needs to be fixed.

**Comment by jgomer2001** [comment]
Both fido2 and supergluu devices are managed through the fido2 endpoint `/jans-scim/restv1/v2/Fido2Devices`. Only doc updates are required
