### ISSUE TITLE
fix(jans-auth-server): client secret printed on logs.

### ISSUE THREAD

**Issue by mmrraju** [JanssenProject/jans#4323]
**Describe the bug**
We notice that client secret printed on `jans-auth.log`
Here is the class path
https://github.com/JanssenProject/jans/blob/main/jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java

**Expected behavior**
Plain client secret should not be printed on logs.

**Screenshots**
![Screenshot from 2023-03-27 23-54-15](https://user-images.githubusercontent.com/43112579/228032957-b976b1ef-726d-4325-b67b-131c677de186.png)

**Desktop (please complete the following information):**

  - OS: [Ubuntu20.04LTS ]
  - Janssen [v1.0.10]

**Comment by yuriyz** [comment]
It is actual and must be fixed.
