### ISSUE TITLE
docs: fill in all documentation category READMEs

### ISSUE THREAD

**Issue by shmorri** [JanssenProject/jans#4340]
- [ ] Database Guide
- [ ] Auth Server Admin Guide - Tokens
- [ ] Auth Server Admin Guide - Scopes
- [ ] Auth Server Admin Guide - Endpoints
- [ ] Auth Server Admin Guide - Crypto
- [x] Auth Server Admin Guide - OpenID Features
- [ ] Auth Server Admin Guide - OpenID Features - Consent
- [ ] Auth Server Admin Guide - OpenID Features - User Claims
- [ ] Auth Server Admin Guide - OAuth Features
- [x] Auth Server Admin Guide - UMA Features
- [ ] Auth Server Admin Guide - Internationalization
- [ ] Auth Server Admin Guide - Reporting and Metrics
- [ ] Auth Server Admin Guide - Logging
- [ ] Auth Server Admin Guide - Customization
- [ ] Auth Server Admin Guide - Scripts
- [ ] Reference Guide
- [ ] Reference Guide - JSON Config/Properties
- [ ] Reference Guide - JSON Config/Properties - Properties
- [ ] Reference Guide - JSON Config/Properties - Feature Flags
- [x] Janssen Recipes
- [x] Upgrade Guide

**Comment by ossdhaval** [comment]
Closing this issue as now we have individual issues to track the completion of each document.
