### ISSUE TITLE
fix: test(jans-auth-server): IntrospectionWsHttpTest.bearerWithResponseAsJwt fail because it was not adapted to latest JWT changes #4358 -autocreated 

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#4360]
This issue was created because no open issues were referenced in your PR (#4359).

**Comment by yuriyz** [comment]
Bot keeps created tickets automatically however ticket was references in PR https://github.com/JanssenProject/jans/issues/4358
