### ISSUE TITLE
chore(jans-linux-setup) : Populate the description field for mysql / plsql table

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#4368]
When the [sql setup](https://github.com/JanssenProject/jans/blob/main/docker-jans-persistence-loader/scripts/sql_setup.py), is run, please populate the description field for each table.

The aim is to autogenerate this section of the docs - [https://github.com/JanssenProject/jans/blob/main/docs/admin/reference/database/mysql-schema.md](https://github.com/JanssenProject/jans/blob/main/docs/admin/reference/database/mysql-schema.md)

**Comment by yurem** [comment]
To allow use remarks I opened issue https://github.com/JanssenProject/jans/issues/4986 Now MariaDB ORM not uses REMARKS columns. We can proceed with this issue now
