### ISSUE TITLE
[Tent] Enforce localhost installation 

### ISSUE THREAD

**Issue by christian-hawk** [JanssenProject/jans#4373]
**Is your feature request related to a problem? Please describe.**
As **Tent** `register_new_client.py` feature will register `localhost` in `ISSUER`, to avoid wrong setup/usage (such as #4370 ) , enforce localhost installation information may be needed.

**Describe the solution you'd like**
At least docs info and/or runtime console message when starting. (i.e.: **IMPORTANT: Run this client in your local computer**)

**Comment by nynymike** [comment]
I don't think we should *enforce* localhost. If the deployer is using another ethernet interface, they should update the `redirect_uri`.
