### ISSUE TITLE
fix(jans-tui): uploaded agama project name details showing different

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4391]
**Describe the bug**
uploaded agama project name details showing different

**To Reproduce**
1. lautnch tui
2. deploy agama project
3. add some project name and save
4. check deployed project name and other details

**Expected behavior**
should show added project name and other details
**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/228848844-65590248-9e5b-4cfe-a09c-2ec36dad9b23.png)

**Desktop (please complete the following information):**
  - OS: [ubuntu
  - Version 22
  - -pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This was fixed
