### ISSUE TITLE
fix(jans-tent): jans-tent using acr_values=agama ,flow not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4405]
**Describe the bug**
agama flow not working

**To Reproduce**
1. Go to jans tent
2. configure according to steps mentioned
3. https://github.com/JanssenProject/jans/blob/main/demos/jans-tent/README.md#jans-tent
4. modify config.py for ACR for agama add ADDITIONAL_PARAMS = {'agama_flow': 'test'}
5. deploy agam flow 
6. run main.py
7. access https://localhost:9090
8. See error

**Expected behavior**
should able to get agama login page

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/229055422-9c0fe791-65d3-4d21-9461-9adb5ae86141.png)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  

**Smartphone (please complete the following information):**

**Additional context**
[flow.txt](https://github.com/JanssenProject/jans/files/11122853/flow.txt)

**Comment by christian-hawk** [comment]
have you handled it, @manojs1978 ? This is probably not related to `jans-tent`

**Comment by manojs1978** [comment]
realted issue : https://github.com/JanssenProject/jans/issues/4511

@jgomer2001 ,
as per documentation, enabled agama script and it revision is increased automatically  and set enable=true  for agamaconfiguration property.

now getting below error 
![image](https://user-images.githubusercontent.com/5729240/230578591-9152854c-ad47-4e96-be40-7d02394bdf99.png)

**Comment by manojs1978** [comment]
working fine now 
able to complete jans -tent agama flow
![image](https://user-images.githubusercontent.com/5729240/230716452-bee4eb77-beac-4000-84fc-287d14e46d89.png)
