### ISSUE TITLE
feat (jans-tui): Make sure admin can copy device flow URL 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#4419]
![image](https://user-images.githubusercontent.com/3717101/229239379-e5f47988-d323-4ad6-84a6-b11bcd8188de.png)

I hit `ctrl` ... but there is no way to highlight the entire URL because of the carriage return. Perhaps we should put the URL on a line by itself to make sure it fits.

**Comment by devrimyatar** [comment]
Implemented
