### ISSUE TITLE
fix (jans-config-api): we need to restart jans-auth-server to reflect the changes in custom script

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#4428]
**Describe the bug**
We need to restart the `jans-auth-server` to reflect the changes in the custom script done using `jans-config-api`.

**To Reproduce**
1. Make changes in a Custom Script using  `jans-config-api` `PUT` `/jans-config-api/api/v1/config/scripts`
2. Check persistence to verify if the changes are saved. I found the save works perfectly.
3. Test the implementation of the changes in the script. It will not work.
4. Restart `jans-auth-server`
5. The script changes work after restart.

**Comment by pujavs** [comment]
@devrimyatar, is there a script that i can invoke from config-api to restart auth-server safely without disrupting any on-going auth process?

**Comment by yuriyz** [comment]
We don't need to restart whole server. Script is reloaded each 30 seconds if `jansRevision` is changed. 

@pujavs please check whether revision is incremented by jans-config-api on each script change.

**Comment by pujavs** [comment]
revision increment code was not there, added the same, PR [4452](https://github.com/JanssenProject/jans/pull/4452)

**Comment by duttarnab** [comment]
Hi @pujavs , I am still facing this issue in the latest installed jans-auth + jans-config-api.

**Comment by pujavs** [comment]
@pujavs, can you confirm that post script update the script revision was incremented.

**Comment by pujavs** [comment]
> @duttarnab , can you confirm that post script update the script revision was incremented. Maybe there is some cache refresh time
