### ISSUE TITLE
feat (jans-tui): password update feature for active users from TUI

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#4434]
Currently there is no option to update any user's password from TUI as this attribute `userPassword` is not visible. 
![Screenshot from 2023-04-03 23-48-11](https://user-images.githubusercontent.com/7156097/229593244-4d651657-e7d1-4df7-b07a-5e1b3b81b2df.png)

It will be easier for admin to update password if we can provide 'userPassword' attribute with value ( encoded ) from TUI.

**Comment by devrimyatar** [comment]
Press key `p` on keyboard when cursor is on user

![image](https://user-images.githubusercontent.com/6398752/229595303-f27cc4dc-ef86-430e-a4da-753bc7646f04.png)
