### ISSUE TITLE
chore(tui): Fixes for Agama main page (list)

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#4458]
When entering to the Agama page (Alt+m), the table of deployments should appear - more exactly the 1st page of results - based on the response of `/agama-deployment/list` endpoint. 

Currently one is forced to click on <get projects> to see something, let's avoid this because in practice a few deployments will be available in a real environment (it's a short list)

The table should show the following columns in that order. If a value is not available (null), use a hyphen (`-`), not `??` 

- Project name
- Type
- Author
- Status: `Processed` or `Pending` depending on whether `finishedAt` exists or not
- Deployed on: Use hyphen if status=pending, otherwise use the value of `finishedAt` (do not ellide the HH:mm)
- Errors: `No`, `Yes`, or `-`. Use hyphen if status=pending, otherwise use no/yes depending on the whether `details` > `error` is null or not

Notes:
1. The values in the table should be consistent. As an example, yesterday I deployed one project and it appeared as "pending", I switched to another tab (Alt+t) and then returned to Agama and it became `processed` - this is OK. Afterwards I deployed another file and showed "pending",  switched to another tab and returned but it still showed `pending` while in the DB both had  `finishedAt` value set. I repeat the process again and both became "pending":

![Screenshot from 2023-04-04 15-59-16](https://user-images.githubusercontent.com/5444180/229949351-caa79d2a-7725-4c61-8646-79ffe06263f6.png)

![Screenshot from 2023-04-04 16-00-49](https://user-images.githubusercontent.com/5444180/229949383-80f908a7-75bc-43de-9749-d2d082385822.png)

2. Fix this typo (correct is retrieve):

![Screenshot from 2023-04-04 16-00-35](https://user-images.githubusercontent.com/5444180/229949820-6e335811-5542-49ae-81ca-dc1f308c4cb3.png)

3. If possible, enhance the contrast. It is difficult to read the selected row

**Comment by jgomer2001** [comment]
right, I was thinking that

**Comment by devrimyatar** [comment]
> Press d to see deployment details. Press d to view/set projects configurations

Replaced by 

![image](https://user-images.githubusercontent.com/6398752/230983149-d1cb7329-5f99-44b4-8bb8-dbc177c2dea4.png)

**Comment by devrimyatar** [comment]
> Please change the status bar to: "Press d to see deployment details. Press d to view/set projects configurations"
> 
> ![Screenshot from 2023-04-10 07-02-06](https://user-images.githubusercontent.com/5444180/230899320-5a287467-b89c-4a6f-802c-23e53a4bd087.png)

Replaced by 
![image](https://user-images.githubusercontent.com/6398752/230983328-821d92fd-ff06-4650-bdee-ddccc71ce683.png)
