### ISSUE TITLE
feat(tui): Remove Agama project

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#4518]
In the table that lists the deployments, we should offer an option when a row is highlighted for undeployment of the selected project.

An emergent window should appear with a warning like: "This will remove flows, assets, code and libraries belonging to this project".  And buttons to confirm/cancel

If Confirm is pressed, call the `/agama-deployment/{name}` endpoint (DELETE method). Then refresh the table.

**Comment by nynymike** [comment]
Lower priority... let's get deployment working first.

**Comment by devrimyatar** [comment]
There is such feature. To remove project, press **delete** key on keyboard. I just changed confirmation message as follows:

![image](https://user-images.githubusercontent.com/6398752/231580679-f56c0262-91ba-43d2-a2ae-acf78b81c9e5.png)
