### ISSUE TITLE
feat(jans-config-api): project details

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#4531]
We have an issue for displaying project details https://github.com/JanssenProject/jans/issues/4525
Bu config-api does not return these fields:
- Version
- Flows
- Templates
- Type
- Description
- Author

Please provide these information when we call endpoint `/api/v1/agama-deployment/{name}`

**Comment by jgomer2001** [comment]
Most of these info is already returned. Problem is that provided sample gama files are poor in metadata. I will share better versions of `project.json`
