### ISSUE TITLE
fix(jans-config-api): the generated swagger specs showing error

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#4545]
The following swagger specs show errors.
- [ ] https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml
![image](https://user-images.githubusercontent.com/32794267/231087148-fab5ff0f-4404-4ca5-8adb-9cbbbb4a62ee.png)

- [ ] https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml
![image](https://user-images.githubusercontent.com/32794267/231087323-82a9cd3b-0344-446a-99ca-6e0b4b9c09e3.png)

**Comment by pujavs** [comment]
Fix implemented via PR [4595](https://github.com/JanssenProject/jans/pull/4595)
