### ISSUE TITLE
question(jans-config-api): smtp configuration

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#4550]
How can I save `connect_protection` ?
 In yaml

https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L9620-L9625

`connect_protection` can take one of

```
          - None
          - StartTls
          - SslTls
```
But instead server returns `"connectProtectionList": ["NONE", "START_TLS", "SSL_TLS"]` Why? what is purpuse of this property?

**Comment by pujavs** [comment]
@smansoft , request you to please chk this.

**Comment by devrimyatar** [comment]
This issue as fixed
