### ISSUE TITLE
fix(jans-cli-tui): Suppress Authorization not saving

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#4553]
* When you activate `Suppress Authorization` and save, it is not saved (or maybe updated). 
* "Supress" is misspelled 
 
![image](https://user-images.githubusercontent.com/3717101/231342023-dab31992-f216-410f-a764-eea143a6fdf8.png)

**Comment by nynymike** [comment]
FYI, in Gluu 4, this was "Pre Authorization"

![image](https://user-images.githubusercontent.com/3717101/231499627-722a51ee-b404-4fb3-9735-d6b1633d9fa0.png)

**Comment by yuriyz** [comment]
Attribute is `jansTrustedClnt`
