### ISSUE TITLE
docs: need documentation on how to add custom attributes

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4556]
Based on discussion [here](https://chat.gluu.org/group/documentation?msg=4D9TPPWRevahjFshz), 

- we need documentation on how to add a custom attribute
- It’s also important to explain that it may be necessary to add a column to the User table in the RDBMS, or to add an attribute and update the objectclass in LDAP

**Comment by mzico** [comment]
@ossdhaval : i see we have a doc on this already [here](https://docs.jans.io/v1.0.16/admin/config-guide/config-api/attribute/). Want me to modify / update this specific page?

**Comment by ossdhaval** [comment]
@mzico Yes, I think we need to update a different page. [This one](https://docs.jans.io/head/admin/config-guide/cli-attribute.md).

If you refer to the chat link in the issue description, the chat between you and @nynymike , is about how to add custom attributes to the backend directly. In the same chat, @moabu provided a link to the Gluu page [this](https://gluu.org/docs/gluu-server/4.5/admin-guide/attribute/#attributes). I think it is this page that we need to bring to Janssen with the necessary changes.

The link that you shared in your comment above talks about how to add custom attributes via config-API.

**Comment by mzico** [comment]
I see that if we use TUI, we don't need to operate with MySQL / PostGres commands to create custom attribute. Meaning, creating custom attribute with TUI, directly passing all gates and becoming available in claim list. 

However, here is one PR: https://github.com/JanssenProject/jans/pull/5849

**Comment by ossdhaval** [comment]
Closing this issue as resolved by #5849
