### ISSUE TITLE
docs: updates docs to reflect that Agama engine is enabled by default

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4578]
**Describe the bug**
[Agama docs home page](https://docs.jans.io/v1.0.12.nightly/admin/developer/agama/#agama-engine) and [engine config page](https://docs.jans.io/v1.0.12.nightly/admin/developer/agama/engine-config/#engine-availability) needs an update to reflect that Agama engine is enabled by default.

Currently it mentions:

`Account that by default, the engine is disabled in the authentication server. The [quick start](https://docs.jans.io/v1.0.12.nightly/admin/developer/agama/quick-start/) page explains how to enable it.`

**Comment by jgomer2001** [comment]
It is disabled by default @ossdhaval
