### ISSUE TITLE
fix(jans-auth): Unable to fetch SessionId object after authentication

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#4609]
**Describe the bug**
After the authentication / authorization flow has completed, the control goes back to the client (redirect URI).
Now on the client side, we get the following request parameters:
1. code
2. sid
3. session_state.

Now the aim is to obtain the session parameters for the currently "authenticated session".

I try the following in python - all of which yield `None`

1. `CdiUtil.bean(SessionIdService).getSessionIdFromCookie()`
2. `CdiUtil.bean(SessionIdService).getSessionBySid`
3. `CdiUtil.bean(SessionIdService).getSessionId()`

Notes: 
1. I dont see the `sid` value present in persistence either (manual check)
2. `invalidateSessionCookiesAfterAuthorizationFlow` field is false

**Comment by yuriyz** [comment]
@maduvena in what custom script are you trying to run `CdiUtil.bean(SessionIdService).getSessionId()` code ?

It would be helpful to take a look to full script. Can you attach it ?

**Comment by yuriyz** [comment]
This was already discussed and solved. Closing it.

![image](https://github.com/JanssenProject/jans/assets/2013070/6effb6c4-6cf0-4bb7-beb8-4bb19e2dbf25)
