### ISSUE TITLE
fix(jans-auth-server): force clientWhiteList when session is valid for post_logout_redirect_uri (allowPostLogoutRedirectWithoutValidation=true ) #1820

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#4672]
**Describe the bug**

fix(jans-auth-server): force clientWhiteList when session is valid for post_logout_redirect_uri (allowPostLogoutRedirectWithoutValidation=true ) #1820

oxauth counterpart: https://github.com/GluuFederation/oxAuth/issues/1820

**Comment by nynymike** [comment]
Note... we really need to change the term `whiteList` and `blackList` to `allowList` and `denyList`

**Comment by yuriyz** [comment]
Sure, created ticket to track it https://github.com/JanssenProject/jans/issues/4675
