### ISSUE TITLE
jython-installer-2.7.3.jar conflicts between attempted installs of jans-1.0.12-el8.x86_64  and gluu-server-nochroot-4.3.1-el8.x86_64

### ISSUE THREAD

**Issue by dhanan-np** [JanssenProject/jans#4694]
I am following the steps defined at the page: https://docs.jans.io/v1.0.12/admin/install/vm-install/rhel/
And getting the error Error: 

`Transaction test error: file /opt/dist/app/jython-installer-2.7.3.jar conflicts between attempted installs of jans-1.0.12-el8.x86_64 and gluu-server-nochroot-4.3.1-el8.x86_64`

OS: CentOS Stream 8, 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit

**Comment by devrimyatar** [comment]
You should not install jans and gluu server on same machine

**Comment by dhanan-np** [comment]
> You should not install jans and gluu server on same machine

gluu was installed.... Anyway I have moved to jans(1.0.12) now and evaluating it.
