### ISSUE TITLE
fix(jans-cli-tui): smtp configuration  test is failing

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4713]
**Describe the bug**
smtp configuration  test is failing in tui

**To Reproduce**
1. launch tui
2. go to smtp and add smtp configuration details
3. press click 

**Expected behavior**
should get success pop up if configuration is correct

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/234210970-e06d835e-ddce-4f9b-89d6-1495b2bdd82a.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - --jans 1..0.13
  - ldap

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Dupplication of https://github.com/JanssenProject/jans/issues/4713
