### ISSUE TITLE
feat(jans-cache-refresh):Implement Cache refresh functionality in jans

### ISSUE THREAD

**Issue by shekhar16** [JanssenProject/jans#4717]

**Comment by ossdhaval** [comment]
Hi @shekhar16 

A quick request to use the conventional commits style for issue titles. Helps in many ways. [Contribution guide](https://docs.jans.io/head/CONTRIBUTING/#issues) will guide you further. :handshake:

**Comment by shekhar16** [comment]
Code merged closing this ticket.
