### ISSUE TITLE
feat(jans-cache-refresh):Install Cache Refresh Service

### ISSUE THREAD

**Issue by shekhar16** [JanssenProject/jans#4718]
#4717  : Set up install process for Cache Refresh service in CE.
below are the steps :
1) Generate war by maven command : mvn clean install
2) go to target folder and get the war file name with jans-cache-refresh-******.war
3) Deploy that war file in jetty.
4) start the server.

**Comment by devrimyatar** [comment]
@shekhar16 please 
 - write download url for war file
 - what about configuration? Is there any config file or database configuration?

**Comment by yurem** [comment]
@devrimyatar here is link: https://maven.jans.io/maven/io/jans/jans-cache-refresh/1.0.11-SNAPSHOT/jans-cache-refresh-1.0.11-SNAPSHOT.war

**Comment by shekhar16** [comment]
@devrimyatar  here is the config ldif zip file 
[cachefresh.zip](https://github.com/JanssenProject/jans/files/11336905/cachefresh.zip)

**Comment by nynymike** [comment]
What is CE? There is no community edition in Janssen Project. Everything is open source.

**Comment by devrimyatar** [comment]
@moabu Currently CR uses `/var/gluu/identity/cr-snapshots` for snapshots. Is this drectory good? Or should we change it something like `/var/jans/cr-snapshots` ?

**Comment by moabu** [comment]
Hey @devrimyatar ,

Yes since the that word is more of a gluu term in that respect the location you suggested is good.
