### ISSUE TITLE
fix(config-api): filtering script is not working when backend is MySQL

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#4743]
**Describe the bug**
CustomScript filtering script is not working when backend is MySQL and PgSQL.

This query returns all person_authentication scripts, not filtering if it is enabled or not
`# /opt/jans/jans-cli/config-cli.py --operation-id=get-config-scripts --endpoint-args="fieldValuePair:scriptType=person_authentication,fieldValuePair:enabled=true"
Please wait while retrieving data ...
{
  "start": 0,
  "totalEntriesCount": 13,
  "entriesCount": 13,
  "entries": [
    {
      "dn": "inum=09A0-93D6,ou=scripts,o=jans",
      "inum": "09A0-93D6",
      "name": "twilio_sms",
      "description": "Twilio SMS authentication module",
      "script": "# Janssen Project software is availabl
....
....
Get similar response when I user curl

`# curl -k -H @token.txt  "https://gluu-server/jans-config-api/api/v1/config/scripts?fieldValuePair=scriptType=person_authentication&enabled=true"
{"start":0,"totalEntriesCount":13,"entriesCount":13,"entries":[{"dn":"inum=09A0-93D6,ou=scripts,o=jans","inum":"09A0-93D6","name":"twilio_sms","description":"Twilio SMS authentication module","script":"# Janssen Project software is available under the Apache 2.0 License (2004). See http://www.apache.org/licenses/ for full text.\n# Copyright (c) 2020, Janssen Project\n#\n# Author: Gasmyr `
Same query returns only enabled person_authentication when backend is OpenDJ

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to jans auth server
2. Execute `/opt/jans/jans-cli/config-cli.py --operation-id=get-config-scripts --endpoint-args="fieldValuePair:scriptType=person_authentication,fieldValuePair:enabled=true`
3. All scripts are returned.

**Expected behaviour**
Only enabled `person_authentication` scripts should be returned.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
DB is MySQL and PgSQL

**Comment by pujavs** [comment]
Two parts to the issues;
1. @devrimyatar, query param `fieldVauePair` takes comma separated field=value pairs example -> field1=value1,field2=value2
Try /jans-config-api/api/v1/config/scripts?fieldValuePair=level=10 
Thus `# curl -k -H @token.txt  "https://gluu-server/jans-config-api/api/v1/config/scripts?fieldValuePair=scriptType=person_authentication**&**enabled=true" `
should be
`# curl -k -H @token.txt  "https://gluu-server/jans-config-api/api/v1/config/scripts?fieldValuePair=scriptType=person_authentication**,**enabled=true"`

2. All field params working fine expect boolean
**@yurem need your advice** as when i check the query filter in logs i don't any issue
2023-04-28 14:06:21,192 INFO  [qtp762476028-15] [io.jans.service.custom.CustomScriptService] (CustomScriptService.java:128) - Searching CustomScript Flow with filter:(&(|(|((lower("description")=*)((lower("displayName")=*)))(&(&(jansEnabled=true))(&(jansScrTyp=person_authentication))))

- 2.1. Rest Response screenshots: Should return 3 records but is returning 10
![image](https://user-images.githubusercontent.com/43700552/235196803-00ec66af-8219-433e-b66f-8b2bb4b566a3.png)

- 2.2.  DB Query response: Correct response 
![image](https://user-images.githubusercontent.com/43700552/235197059-79b970cf-50ff-470d-96d7-65c23a805b82.png)

**Comment by yurem** [comment]
I think the issue in string values which we pass into ORM in filter in boolean fields. With PR above filter will convert string value to small int for such columns.

With this update next code sample return always same result which conform SQL query:
```
    	for (Object enabledValue : new Object[] {true, 1, "true", "1"} ) {
	    	Filter filter = Filter.createANDFilter(
	    			Filter.createORFilter(
	    					Filter.createORFilter(
	    							Filter.createSubstringFilter(Filter.createLowercaseFilter("description"), null, new String[] { "" }, null)),
	    							Filter.createSubstringFilter(Filter.createLowercaseFilter("displayName"), null, new String[] { "" }, null)),
	    			Filter.createANDFilter(
	    					Filter.createANDFilter(Filter.createEqualityFilter("jansEnabled", enabledValue)), Filter.createANDFilter(Filter.createEqualityFilter("jansScrTyp", "person_authentication"))));
	    	List<SimpleCustomScript> res = manager.findEntries("ou=scripts,o=jans", SimpleCustomScript.class, filter);
	    	System.out.println(res.size());
    	}
```

**Comment by pujavs** [comment]
@devrimyatar, issue has been fixed by @yurem. Request you to please take latest and test the same.

Following are testing by connecting to MySql env
1. person_authentication => Total 13
- DB
![image](https://user-images.githubusercontent.com/43700552/235645978-81326011-0761-47f3-ac52-84c6f4d04e03.png)
- Rest service
![image](https://user-images.githubusercontent.com/43700552/235644395-4753bc7e-a350-4998-8a0b-4f574733711d.png)

3. person_authentication which are enabled => 3
- DB
![image](https://user-images.githubusercontent.com/43700552/235646385-4598df25-e829-43d0-aeba-f46e78848214.png)
- Rest service
![image](https://user-images.githubusercontent.com/43700552/235646534-46668d99-190d-4233-ac98-ef5d26e0a61c.png)

5. person_authentication which are disabled => 10
- DB
![image](https://user-images.githubusercontent.com/43700552/235646872-d8e79a24-bded-472b-a4ae-a8ec2efc68e6.png)
- Rest service
![image](https://user-images.githubusercontent.com/43700552/235646695-31e8a2c3-d304-4a18-83b8-0b6300691d00.png)
