### ISSUE TITLE
fix(docker-jans): resolve all possible google credentials

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#4774]
Currently if the env `GOOGLE_APPLICATION_CREDENTIALS` is not provided the setup will wait for `etc/jans/conf/google-credentials.json` .  In some setups the container would be already authenticated with Google and hence the json file would be redundant as the container would be already authenticated.

**Comment by iromli** [comment]
The following steps need to applied into all images:

1. Remove `GOOGLE_APPLICATION_CREDENTIALS` env from images. Let users pass the environment if they choose to use it for authn
2. Create new directory `$HOME/.config/gcloud` so users can mount their [application_default_credentials.json](https://cloud.google.com/docs/authentication/application-default-credentials#personal)
3. Allow users to mount [service account key](https://cloud.google.com/docs/authentication/provide-credentials-adc#local-key) pointed by `GOOGLE_APPLICATION_CREDENTIALS` env
