### ISSUE TITLE
docs(jans-auth): Custom claims RDBMS

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#4784]
In LDAP, we advised customers to create an objectclass, like `acmePerson` for their custom user claims. On user creation (e.g. SCIM `POST /users`) , this objectclass is appended.  @yurem  has suggested just adding claims to the `jansPerson` table.  Is this the easiest approach? We still need attribute metadata for each claim.

**Comment by ossdhaval** [comment]
Hey @maduvena 

@duttarnab [believes](https://chat.gluu.org/group/documentation?msg=cFuLZGwZo3bHF3RKL) that [this](https://docs.jans.io/v1.0.19/admin/auth-server/openid-features/user-claims/custom-claims/) document addresses this issue. Do you agree? Should we close this issue?

**Comment by maduvena** [comment]
yes!
