### ISSUE TITLE
fix(docs): benchmarking document mistakenly refers to 'vCPU' as 'CPU'

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4792]
### Discussed in https://github.com/JanssenProject/jans/discussions/4789

<div type='discussions-op-text'>

<sup>Originally posted by **dhanan-np** May  3, 2023</sup>
Hello @ossdhaval,

The tables in the Benchmarking contains CPU. I need to know if they are **vCPU** or **CPU**. If CPU can I please know the specification of the CPUs used.

</div>

[Document to be updated](https://docs.jans.io/v1.0.12/admin/recipes/benchmark/)

As discussed with @moabu , it should be vCPU at all places in the document.

**Comment by TaseerAhmad** [comment]
Please assign this task to me. This is my first good issue.

**Comment by KyleChaukccs** [comment]
Hi everyone, I am new to this project. I have just created my first pull request. Feel free to let me know if I am following the guidelines and the best practices correctly throughout the contribution process. Thank you.

**Comment by ossdhaval** [comment]
Hi @KyleChaukccs Thank you for creating this PR. :+1:  We are reviewing. :hourglass_flowing_sand:
