### ISSUE TITLE
fix(jans-tui): getting error while navigating through tui tabs

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4837]
**Describe the bug**
getting error while navigating through  different tabs in jans-tui

**To Reproduce**
1. launch jans-tui
2. navigate through upper tabs
3. 

**Expected behavior**
should not get break tui

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/236743202-3c3c5f0f-95ae-457f-a0ab-f202a51e2b45.png)

![image](https://user-images.githubusercontent.com/5729240/236742222-57a7aff4-8511-4f6c-b5db-b2e1ab28eb7f.png)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-DB opendj
- jans 1.0.13. nightly build
**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 This is not TUI issue, but config-api issue:

![image](https://user-images.githubusercontent.com/6398752/236774561-b8d0f1bb-8944-468a-8e8e-e53a65d8dc54.png)
