### ISSUE TITLE
docs(OIDC feature): create documentation for user claims

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4851]
## General Guidelines

- Start by covering the general definition of the feature in a few lines and then point to the appropriate section of the SPEC. Please refrain from repeating what is there in the SPEC already.
- Try to make the content Janssen Server specific ( e.g. what are the related Janssen Server properties or feature flags, how to change relevant settings using TUI/command line (use the screenshots), recommendations around recommended values, use-cases)
- Follow the [documentation contribution guidelines](https://docs.jans.io/head/CONTRIBUTING/).
- Feel free to refer to content available in Gluu documentation (or any other IDP) if the content doesn't need to be customized for Janssen Server

## Document Location

https://docs.jans.io/head/admin/auth-server/openid-features/user-claims/

## Suggested sections

- Built-in claims
- Adding custom claims
- Claim uniqueness and validation

**Comment by ossdhaval** [comment]
@nynymike I suggest consolidating the [user claims](https://docs.jans.io/head/admin/auth-server/openid-features/user-claims/) section with sub-documents becoming sub-sections in one document. Please share your views.

**Comment by nynymike** [comment]
Related : https://github.com/JanssenProject/jans/issues/4556 
Perhaps the same person should do both.

**Comment by ossdhaval** [comment]
Hi @duttarnab Assigning this to you as you are working on #4556. As per Mike's comment above.
