### ISSUE TITLE
fix(jans-tent): test agama  project deployment flow is failing 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4875]
**Describe the bug**
test agama  project deployment flow is failing 

**To Reproduce**
1. launch agama
2. enable agama properties and script using tui
3. deploy agama project
4. make changes in config.py for agama acr
5. run main.py
6. See error
```
Traceback (most recent call last):
  File "/home/manoj/Documents/janssen/git/jans/demos/jans-tent/main.py", line 1, in <module>
    from clientapp import create_app
  File "/home/manoj/Documents/janssen/git/jans/demos/jans-tent/clientapp/__init__.py", line 25, in <module>
    from . import config as cfg
  File "/home/manoj/Documents/janssen/git/jans/demos/jans-tent/clientapp/config.py", line 20, in <module>
    ACR_VALUES = agama
NameError: name 'agama' is not defined
```
**Expected behavior**
agama flow should work

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/236996771-0280bc69-9fd8-4909-a115-d798255b31ad.png)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - DB opendj
  - jans 1.0.13 nightly build

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
sorry its my mistake

**Comment by christian-hawk** [comment]
Hey Manoj. You forgot to use quotes in `agama` word. `ACR_VALUES = "agama"`

Em ter., 9 de mai. de 2023 às 06:14, manoj suryawanshi <
***@***.***> escreveu:
