### ISSUE TITLE
docs(persistence): remove cb schema document placeholders from docs and docs navigation

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4953]
## Document Location

https://docs.jans.io/head/admin/reference/database/cb-schema/

**Comment by yurem** [comment]
There is no schema in Couchbase

**Comment by ossdhaval** [comment]
> There is no schema in Couchbase

True. I'll convert this issue into removal of cd-schema doc placeholder from codebase and doc navigation
