### ISSUE TITLE
docs(persistence): create documentation for MySQL operations

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4958]
## Document Location

https://docs.jans.io/head/admin/reference/database/mysql-ops/

**Comment by yurem** [comment]
Added

**Comment by ossdhaval** [comment]
Based on [this chat](https://chat.gluu.org/group/documentation?msg=yv6BfFpwY5rYiNqz2), changing the assignment to @mzico

**Comment by mzico** [comment]
@ossdhaval : Please approve: 

 - https://github.com/JanssenProject/jans/pull/5846
 - https://github.com/JanssenProject/jans/pull/5847

**Comment by ossdhaval** [comment]
@mzico done. But #5847 has merge conflict.

**Comment by mzico** [comment]
OK, resolved conflict. Please confirm.
