### ISSUE TITLE
docs(persistence): create documentation for PostgreSQL operations

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#4964]
## Document Location

https://docs.jans.io/head/admin/reference/database/postgres-ops.md

**Comment by ossdhaval** [comment]
Based on [this chat](https://chat.gluu.org/group/documentation?msg=yv6BfFpwY5rYiNqz2), changing the assignment to @mzico

**Comment by mzico** [comment]
@ossdhaval : https://github.com/JanssenProject/jans/pull/5866

More coming....

**Comment by ossdhaval** [comment]
Addressed in #5912
