### ISSUE TITLE
feat(config-api):  plugin for cache refresh 

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#4974]
Cache refresh plugin endpoints to be exposed via endpoint.

Creating Cache refresh plugin in config-api to fetch and update **[jans-cache-refresh-config.json]** (https://github.com/JanssenProject/jans/blob/jans-linux-setup-cr/jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json)

**1. Two endpoints:**
- GET /jans-config-api/cacherefresh/cache-refresh-config: Retrieves Cache Refresh configuration
- PUT /jans-config-api/cacherefresh/cache-refresh-config: Updates Cache Refresh configuration

**2. New scopes:** https://jans.io/oauth/config/cacherefresh.readonly and https://jans.io/oauth/config/cacherefresh.write

**3. Related issues:** 
https://github.com/GluuFederation/flex/issues/1003
https://github.com/JanssenProject/jans/issues/4999

**4. Dependency:**  
- linux setup changes for cache-refresh war  branch [jans-linux-setup-cr](https://github.com/JanssenProject/jans/tree/jans-linux-setup-cr)
- linux setup changes for config-api jetty plugin change as mentioned in issue [4999](https://github.com/JanssenProject/jans/issues/4999) 

**References:**
-  [jans-cache-refresh-config.json] (https://github.com/JanssenProject/jans/blob/jans-linux-setup-cr/jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json)
- [configuration.ldif] (https://github.com/JanssenProject/jans/blob/jans-linux-setup-cr/jans-linux-setup/jans_setup/templates/jans-cache-refresh/configuration.ldif)

**Comment by devrimyatar** [comment]
@pujavs Please ask @shekhar16 for `sourceConfigs`

**Comment by devrimyatar** [comment]
Here is sampe `sourceConfig`
```
    {
      "configId": "UBUNTULDAP1",
      "bindDN": "cn=directory manager",
      "bindPassword": "gluu2022",
      "servers": [
        "127.0.0.1:16361"
      ],
      "maxConnections": 2,
      "useSSL": true,
      "baseDNs": [
        "ou=people,o=gluu"
      ],
      "primaryKey": null,
      "localPrimaryKey": null,
      "useAnonymousBind": false,
      "enabled": false,
      "version": 0,
      "level": 0
    }
```

**Comment by pujavs** [comment]
Anu config from persistence for any modules like, auth-server, scim, fido2, user-mgt are loaded into their respective config model classes.
Example;
- AuthServer -> https://github.com/JanssenProject/jans/blob/main/jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- FIDO2-> https://github.com/JanssenProject/jans/blob/main/jans-fido2/model/src/main/java/io/jans/fido2/model/conf/AppConfiguration.java
-SCIM -> https://github.com/JanssenProject/jans/blob/main/jans-scim/model/src/main/java/io/jans/scim/model/conf/AppConfiguration.java

Thus config-api ideally reuses the respective module classes. creating these in config-api will create duplicate classes and every change in config will have to be replicated in two places.
  
In case of cache-refresh module also this needs to be there and looking at the description `The oxTrust Cache Refresh service was recently migrated by Shekhar to Jans as a standalone service.` of Gluu issue [1003 ](https://github.com/GluuFederation/flex/issues/1003)  i assume the java code for `jans-cache-refresh` has been done.

 @shekhar16, request  please share details of java model class for `jans-cache-refresh` module

**Comment by pujavs** [comment]
Creating Cache refresh plugin in config-api to fetch and update **[jans-cache-refresh-config.json]** (https://github.com/JanssenProject/jans/blob/jans-linux-setup-cr/jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json)

Two endpoints;
- GET /jans-config-api/cacherefresh/cache-refresh-config: Retrieves Cache Refresh configuration
- PUT /jans-config-api/cacherefresh/cache-refresh-config: Updates Cache Refresh configuration
