### ISSUE TITLE
chore(jans-tarp): update extension description

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#5037]
It would good to change "My Chrome Extension" to something more meaningful

![Screenshot from 2023-05-18 14-00-28](https://github.com/JanssenProject/jans/assets/5444180/4c9c0d9c-f4f7-423a-ad33-928bd9b290f3)

**Comment by duttarnab** [comment]
done
![image](https://github.com/JanssenProject/jans/assets/32794267/3623ea7f-1f5a-4fbd-8827-3080bbf13a52)
