### ISSUE TITLE
fix(admin-ui): Storing ACR value is inserting inum instead of displayName

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#5198]
We can select DefaultACR value for each client separately from Admin-UI. Selecting ACR value should insert displayName of that ACR into data source ( i.e. LDAP / mysql ). Instead it's storing DN of that ACR / Person Authentication Script inside Client's data. 
Which is resulting error like: 

```
2023-06-09 13:40:27,186 ERROR [qtp2131670196-20] 872064e4-43f8-4fbe-8e69-92e01acf0184 [as.server.authorize.ws.rs.AuthorizeAction] (AuthorizeAction.java:308) - Failed to get CustomScriptConfiguration. auth_step: 1, acr_values: inum=8BAF-80D7,ou=scripts,o=jans
```

I have recorded a full video what is happening and what is the workaround... 
In this video you can see that, we are trying to select Fido2 as default ACR for "modauth.gluu.org" client. 
But Admin-UI saving "inum" of that "Fido2" instead of displayName. 

Workaround is: manually modify that DefaultACR value. 

Here is the recorded video: https://youtu.be/_vLu5f6KY2Q

This issue is similar to another one: https://github.com/GluuFederation/oxTrust/issues/2323

**Comment by duttarnab** [comment]
shifted to flex repo 
https://github.com/GluuFederation/flex/issues/1079
