### ISSUE TITLE
feat(agama): prefix log statements generated by Agama flows with the qualified name

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#5201]
add any comment you may have @moabu

**Comment by moabu** [comment]
The usecase here is to be able to filter out logs based on the agama flow. This is especially useful when the IDP is shared and showing logs become a security concern

**Comment by jgomer2001** [comment]
I think it is not very useful to filter log statements by flow name in a shared environment because:

- Different customers can reuse the same agama projects, and thus share the same flow names
- Several customers can coincidentally use the same flow names, like "test", "myflow", ...
- Messages logged via the `Log` statement are only partially relevant because Agama flows don't carry much business logic - just structure - so in practice, the really interesting log statements come from Java classes invoked by  `Call` statements or from deeper invocations, eg. Call in flow -> Class A -> Class B -> Class C (logging ocurring here) . However, there is no way to know if an arbitrary Java log statement is originated by an Agama flow.

**Comment by nynymike** [comment]
In the shared environment, we are automatically prefixing the QN with the user's github id. As this is an ephemeral enviornment, the only scripts they test will be their own.

**Comment by jgomer2001** [comment]
@moabu Messages logged via the `Log` statements are now prefixed with `|flow qname|` in AS script log. Example:

`|me.gluu.basic_authn| Hello world`

Besides jans-auth war update, existing flows need to be redeployed for the change to take effect
