### ISSUE TITLE
fix(cache-refresh): module class to be exposed as jar

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#5274]
**Issue:** Current structure of cache-refresh is flat making reuse of its model, util and service classes impossible.

**Requirement:** cache-refresh expose  its model, util and service classes as module making it possible to reuse.

**Note:** Rename [AppConfiguration.java ](https://github.com/JanssenProject/jans/blob/main/jans-cache-refresh/src/main/java/io/jans/cacherefresh/model/config/AppConfiguration.java)to cache-refresh specific class  to avoid conflict in Module class name with other modules

Current `cache-refresh` structure makes reuse of its classes imposible as a result these have to be duplicated in other modules 
that wants to use them.
Any config from persistence for any modules like, auth-server, scim, fido2, user-mgt are loaded into their respective config model classes.
Example;

- AuthServer -> https://github.com/JanssenProject/jans/blob/main/jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- FIDO2-> https://github.com/JanssenProject/jans/blob/main/jans-fido2/model/src/main/java/io/jans/fido2/model/conf/AppConfiguration.java
- SCIM -> https://github.com/JanssenProject/jans/blob/main/jans-scim/model/src/main/java/io/jans/scim/model/conf/AppConfiguration.java

Thus config-api ideally reuses the respective module classes, creating these in config-api will create duplicate classes and every change in config will have to be replicated in two places.

**Comment by shekhar16** [comment]
https://github.com/JanssenProject/jans/issues/5468

**Comment by shekhar16** [comment]
closing this ticket as complete as part of ticket https://github.com/JanssenProject/jans/issues/5468
