### ISSUE TITLE
fix(jans-cli-tui): sometime getting error when launch jans-cli-tui

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5341]
**Describe the bug**
sometime getting error when launch jans-cli-tui

**To Reproduce**
1. install flex.5.0.0-15.nightly
2. launch jans-cli-tui
3. See error

**Expected behavior**
should not gett any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/8b29bc2f-aeed-405b-a84a-3f2aa76741c9)

**Desktop (please complete the following information):**
  - OS: RHEL8
  - Version 8
  - DB-mysql
  - flex5.0.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 This is not TUI issue. Error message is clear: It can't connect to config-api server.
So closing.
