### ISSUE TITLE
fix(jans-cli-tui) unable to copy ssa properly

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5357]
**Describe the bug**
unable to copy ssa properly

**To Reproduce**
1. create SSA in tui
2. copy SSA
3. See error

**Expected behavior**
unable to copy SSA properly getting other char in copy
should able to copy SSA only

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/f4e2883b-6215-4117-a737-03a087f457e2)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp4
  - DB mysql
  - Flex/jans 5.0.015.nightly/ 1.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 This is not an issue.
Export and use that file. We can't do anything on partial copy from konsole screen
