### ISSUE TITLE
fix(jans-cli-tui) : getting error while launching tui

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5365]
**Describe the bug**
getting error while launching tui

**To Reproduce**
1.install jans 1.0.15.nightly
2. launch tui

**Expected behavior**
should not get any error and able to launch tui

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/01cf7a2e-ba9f-4188-a825-56d355a27be3)

**Desktop (please complete the following information):**
  - OS: rhel8
  - Version 8
  - DB pgsql
  - jans 1.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 TESTED NO ISSUES

ENSURE YOU DISABLE SELINUX
