### ISSUE TITLE
feat(jans-auth-server): Mobile Authn with DPoP and FIDO

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#5403]
This is the current list of issues we'd have to address to support this feature.

* [ ] Authorization endpoint: add support for `display=fido`
* [ ] Add OAuth Grant Type: `fido2`
* [ ] token endpoint: Add support for `grant_type=fido2`. In this flow, the as should validate the JWT sent via the `id_token` param. If the id_token is not valid, the AS should return `401/Unauthorized ... WWW-Authenticate: fido`

**Comment by nynymike** [comment]
Better to align with new OAuth drafts: 
https://www.ietf.org/archive/id/draft-parecki-oauth-first-party-native-apps-00.html
https://datatracker.ietf.org/doc/draft-tschofenig-oauth-attested-dclient-reg/
