### ISSUE TITLE
fix: docs(cli): add agama CLI to nav -autocreated 

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#5427]
This issue was created because no open issues were referenced in your PR (#5426).

**Comment by maduvena** [comment]
Using Agama cli to do the following :
1. Setting Configuration Properties in the agama flow, e.g - third party api creds, config parameters etc
2. Deploying a project
3. Checking logs - ensuring that jans-auth server's logs are in debug mode.

**Comment by imShakil** [comment]
It seems a lot of changes happened, I see a few options only. In `AgamaConfiguration` there is only one operation which is: `agama-syntax-check`. Please check the attached image. 

<img width="696" alt="Screenshot 2023-07-12 at 8 30 44 AM" src="https://github.com/JanssenProject/jans/assets/20867846/164429ce-de0e-4c67-9202-d326eb0dcbaa">
