### ISSUE TITLE
docs(installer): add SELinux policy recommendations in installation docs

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#5428]
As concluded in [this chat](https://chat.gluu.org/group/documentation?msg=kAizaBoBdzM7tWkEv)

- [x] need to decide what SELinux policies should we recommend to be in-force on the installation environment
- [x] need to document SELinux policy recommendations in the installation documentation
- [x] Is it applicable to CN setups as well?

**Comment by devrimyatar** [comment]
Executing this command 
`setsebool httpd_can_network_connect 1 -P`
on Ubuntu20, CentOS8 and RHEL makes Jans services work.
I am chaning setup accordingly.

**Comment by ossdhaval** [comment]
> Executing this command `setsebool httpd_can_network_connect 1 -P` on Ubuntu20, CentOS8 and RHEL makes Jans services work. I am chaning setup accordingly.

@devrimyatar So is there a need to document anything or due to the change in setup, it'll be transparent to the person running the installer?

**Comment by ossdhaval** [comment]
Closed with the above PRs
