### ISSUE TITLE
docs(agama): suggestions for additional content for Agama CLI document

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#5443]
Following content can be useful addition to Agama CLI docs, as suggested by @maduvena [here](https://github.com/JanssenProject/jans/issues/5427#issuecomment-1623213691)

See if it is appropriate and can be added.

**Comment by imShakil** [comment]
It seems a lot of changes happened, I see a few options only. In `AgamaConfiguration`
![Uploading Screenshot 2023-07-12 at 8.30.44 AM.png…]()
 there is only one operation which is: `agama-syntax-check`. Please check the attached image.

**Comment by ossdhaval** [comment]
I think we will need @devrimyatar and @jgomer2001's inputs here.

**Comment by imShakil** [comment]
It seems these are the final changes for now:

![Screenshot 2023-08-13 at 10 48 44 PM](https://github.com/JanssenProject/jans/assets/20867846/909d16ea-b872-4b9a-b22d-488c584dd1db)

I will update the docs with these changes.
