### ISSUE TITLE
fix(CLI-TUI): remove references to Agama Developer Studio in CLI and possibly in TUI

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#5445]
CLI should remove references to Agama Developer Studio (as in command below) as ADS is not part of the Janssen Project. Instead, refer to `agama` projects. There might be possible instances of ADS in TUI as well. 

```
/opt/jans/jans-cli/config-cli.py --operation-id get-agama-dev-studio-prj-by-name
```

This also means that config-API also has to adopt the same naming as discussed [here](https://chat.gluu.org/group/documentation?msg=ZmvvhaPJLoJtyJRTa). Added @pujavs for this task.

**Comment by pujavs** [comment]
Changes made in Agama spec via PR [5449](https://github.com/JanssenProject/jans/pull/5449)
![image](https://github.com/JanssenProject/jans/assets/43700552/43d2d0a8-0003-40c8-a69d-42c6d3651b5a)

**Comment by devrimyatar** [comment]
Implemented in https://github.com/JanssenProject/jans/pull/5466

**Comment by ossdhaval** [comment]
Closing this issue since changes for CLI and config-api has been completed as commented by @devrimyatar and @pujavs above.
