### ISSUE TITLE
refactor(jans-linux-setup): order of services to start

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#5447]
In jans, services are started in this order:
1) opendj
2) jans-auth
3) jans-config-api, jans-fido2, jans-cache-refresh, jans-eleven, jans-scim

As it can be guessed, in step (3) five services are started at the same time. This makes high load on system. If VM resources are not good enough, some services are not started due to timeout. We have to make an order to start services. My idea is

1) opendj
2) jans-auth
3)  jans-config-api
4) jans-fido2, jans-cache-refresh
5) jans-eleven, jans-scim

**Comment by yuriyz** [comment]
Proposed order looks good to me.
