### ISSUE TITLE
fix(jans-linux-setup): gettting file not found error (jans-cache-refresh.war)

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5536]
**Describe the bug**
gettting file not found error (jans-cache-refresh.war)

**To Reproduce**
1. install jans 1.0.15
2. select cache-refresh during installation
3. during instalation See error

**Expected behavior**
should not get error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/9ac99a00-efbe-4981-917d-d4c9beb61dc9)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15
  - jans 1.0.15
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This was fixed by https://github.com/JanssenProject/jans/pull/5474
