### ISSUE TITLE
fix (jans-config-api): /jans-config-api/jans-link/link-config `GET` throwing error

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#5537]
`/jans-config-api/jans-link/link-config`  `GET` throwing `500` error on latest jans-auth installation.

![image](https://github.com/JanssenProject/jans/assets/32794267/68e3a8dd-1dea-4ede-b32f-b0b91dfa2d4b)

**Comment by devrimyatar** [comment]
@duttarnab It is working, please retry after this PR https://github.com/JanssenProject/jans/pull/5539 merged, if you still get error, re-open.

![image](https://github.com/JanssenProject/jans/assets/6398752/c70fd686-ccbc-4aa1-ba42-6f582da317b7)
