### ISSUE TITLE
feat (agama): Write CLI packager script that generates a .gama file

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#5549]
### Description

If a developer is writing an Agama project using only the file system and texts editor, there needs to be a way to build a `.gama` Agama project archive file and SHA256 signature. For example:

```
$ gamarchive ./my_project_folder --excludeExtension .tmp --excludeFile secrets.txt --excludeFolder .git

```

Running this script could also perform some validation to warn the Agama develop of problems.

- Development target issue
NA

- Implementation Details

-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes

- [ ] task 1
- [ ] task 2
- [ ] task 3

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by jgomer2001** [comment]
Beyond packaging and validation, the tool might help you bootstrap a project by creating the necessary folders and including a readme, a minimal flow file, and a template. It would prompt the flow name for instance.
