### ISSUE TITLE
fix(jans-cli) unable to create attribute using cli

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5604]
**Describe the bug**
unable to create attribute using cli

**To Reproduce**
1.install jans 1.0.16.nightly
2. download attribute schema file
3. modfiy downloaded json file to create attribute
4. run command `sudo /opt/jans/jans-cli/config-cli.py --operation-id post-attributes --data /tmp/postAttribute.json
5. 
6. See error

**Expected behavior**
should able to create attribute using jans-cli using downloaded schema json file
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/4083ecb7-731e-480b-abcf-42795de835cd)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  - DB opendj
  - jans1.0.16.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
@manojs1978, the attribute `seeAlso` should contain valid existing attribute DN 
**Screenshots:**
- **Error case:** Invalid value for `seeAlso` attribute
![image](https://github.com/JanssenProject/jans/assets/43700552/044d88c1-fb5b-4673-979b-75882664b0d3)

- **Success case:** Valid value for `seeAlso` attribute
![image](https://github.com/JanssenProject/jans/assets/43700552/2efa411b-91a1-4f91-bfa7-41c859e5074b)

**Comment by devrimyatar** [comment]
@manojs1978 If you are using CLI for adding/modifying information, you have to know what you are doing. CLI returns complete schema and you have to populate properly. Here is minimal json:

```
root@ubuntu:~# cat /tmp/test2.json
{
    "name": "test2",
    "saml1Uri": "",
    "saml2Uri": "",
    "displayName": "test2",
    "dataType": "string",
    "editType": [],
    "viewType": [],
    "oxMultiValuedAttribute": false,
    "claimName": "",
    "scimCustomAttr": false,
    "description": "",
    "status": "active",
    "urn": "",
    "origin": "jansCustomPerson"
}
```

When we execute CLI with this json

![attribute](https://github.com/JanssenProject/jans/assets/6398752/b991616d-c152-40e8-b95d-209a2612acad)

Closing, becaue this is not actually issue.
