### ISSUE TITLE
feat: add support to load test data to an external jans setup

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#5625]
Load the test data such as https://github.com/JanssenProject/jans/blob/4d17cbcdab3272653f2cf547bcef1d8181353ffd/jans-linux-setup/jans_setup/templates/test/jans-auth/data/oxauth-test-data.ldif to an external jans setup. It can be a setup extension to load data to an external database providing the mysql credentials and it would just inject it there.

**Comment by ossdhaval** [comment]
@moabu can you please check if this is a duplicate of #1155 ? If so, please mark 1155 as a duplicate and close it.

**Comment by moabu** [comment]
> @moabu can you please check if this is a duplicate of #1155 ? If so, please mark 1155 as a duplicate and close it.

Yes it's a duplicate . Both will be closed once the PR is closed. Can you add the documentation to the pr branch so we merge it ?
