### ISSUE TITLE
fix(jans-tui): getting exception janslinkconfiguration when launching tui

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5647]
**Describe the bug**
getting exception janslinkconfiguration when launching tui

**To Reproduce**
1. install jans 1.0.16.nightly
2. launch cli-tui
3. See error

**Expected behavior**
should not get any error
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/e9d3b497-abc1-49a4-94b4-561cbf9e3555)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - jans 1.0.16.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Duplication of https://github.com/JanssenProject/jans/issues/5652 and closed by https://github.com/JanssenProject/jans/pull/5653
