### ISSUE TITLE
fix: apache does not serve the jwks.json on Janssen installation with test data

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#5655]
**Describe the bug**
After installing Janssen Server using test load option (`-t`), expectation is that URL below should be available:

```
https://host-name/jans-auth-client/test/resources/jwks.json
```
But this is not the case. This URL returns 404.

As #5634 is fixed, the expectation is that this URL will work. Just like it works for `jenkins-build.jans.io`

**Possible solution or workaround**
While trying to find a solution, I noted in the `/etc/apache2/vhosts.d/_https_jans.conf` file the entry of
`DocumentRoot "/srv/www/htdocs"`. Upon unzipping the `jans_test_client_keys.zip` at location pointed by DocumentRoot, it has started serving the JSON. I am not sure of this can become the solution.

**To Reproduce**
1. install Jans with `-t` option
2. Try to access URL above

**Expected behavior**
URL should serve JSON

**Comment by devrimyatar** [comment]
@ossdhaval I can't reproduce this issue, may be you are using installer before this commit https://github.com/JanssenProject/jans/commit/4b00a3a17cae115cea31af8e099953666d14bc8d

![image](https://github.com/JanssenProject/jans/assets/6398752/b598c46c-be29-4cae-a14e-44273ab31271)

**Comment by devrimyatar** [comment]
It happens on SUSE installation.

**Comment by moabu** [comment]
Also happened on ubuntu 22.04. I'll check and see if  this is resolved.
