### ISSUE TITLE
fix(jans-link): getting sql error in jans-link

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5695]
**Describe the bug**

**To Reproduce**
1. install jans 1.0.16.nightly
2. configure jans-link and AD server
3. See error in jank-link logs

**Expected behavior**
jans-link should work

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/5f8b8345-296a-408c-a113-581bddf33ee1)

**Desktop (please complete the following information):**
  - OS: suse15
  - Version sp4
  - jans 1.0.16.nightly
  - DB mysql/pgsql

**Smartphone (please complete the following information):**

**Additional context**
[cacherefresh.log](https://github.com/JanssenProject/jans/files/12213541/cacherefresh.log)
[2023_07_31.jetty.log](https://github.com/JanssenProject/jans/files/12213542/2023_07_31.jetty.log)

**Comment by shekhar16** [comment]
code merged closing this ticket.
