### ISSUE TITLE
feat: don't modify dirAllowed option in jetty global config

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#5697]
New jetty versions support `dirAllowed` option in `web.xml`. As result we don't need to modify global `dirAllowed` option in `/opt/jetty/etc/webdefault.xml`

- [ ] Check if all apps war files in web.xml has option `dirAllowed`
- [ ] Remove part in setup which modify global `dirAllowed` option in `web.xml`

**Comment by iromli** [comment]
CN version is implemented in [PR-5699](https://github.com/JanssenProject/jans/pull/5699)
