### ISSUE TITLE
feat (jans-tarp): display access_token and id_token generated during authentication flow

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#5804]
Display access_token and id_token generated during the authentication flow.

**Comment by nynymike** [comment]
Maybe this should be optional ... not all users would want to splash the AT

**Comment by duttarnab** [comment]
Hi @nynymike 
Ok. I will add a checkbox in the client registration form allowing users to decide if they would like to see AT and ID_TOKEN after authentication.
![image](https://github.com/JanssenProject/jans/assets/32794267/15873441-701f-4da3-ae64-20e2f04fec25)
