### ISSUE TITLE
fix(jans-auth-server) : add exclusion to authentication filter for "/token" and "public client" when PKCE is used 

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#5878]
**Describe the bug**

fix(jans-auth-server) : add exclusion to authentication filter for "/token" and "public client" when PKCE is used

Support: 11402

oxauth counterpart: https://github.com/GluuFederation/oxAuth/issues/1861

**Comment by Milton-Ch** [comment]
This issue was reviewed in detail, and a configuration was found and commented on in the support ticket.
https://support.gluu.org/feature-request/11402/pkce-flow-enable/#at85295

**Comment by yuriyz** [comment]
Exact detail is:

Generate "access token" without sending the "client_secret"
1. Create a client with `tokenEndpointAuthMethod: none`
2. Set the global parameter `clientAuthenticationFiltersEnabled: false` (default is true).
3. Run the PKCE flow again.
