### ISSUE TITLE
docs(jans-link): Docs for jans-link

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#5896]
1. How to get started (install on jans)
2. How to map users
3. Details about functionalities
4. Timer task - Configuring the frequency
5. How to Test
6. Usecases
7. Unidirectional / Bi-directional?

**Comment by ossdhaval** [comment]
@maduvena This can be assigned to @shekhar16 or are you planning to write these yourself?

**Comment by shekhar16** [comment]
closing this ticket as docs PL has been merged.
