### ISSUE TITLE
ci: update java used in workflows

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#5911]
![image](https://github.com/JanssenProject/jans/assets/47318409/9e334ac3-4502-4851-ad6f-7aa1207bd969)

Update java versions across workflows

**Comment by ossdhaval** [comment]
@moabu 

As it stands now, the Java version in two workflows, `build-wars` and `central-code-quality-check` is 17 already.

I couldn't find any other workflow using Java.

With that, can we close this issue?

PS: the distribution used by the workflows mentioned above are different. `zulu` and `adopt`. Should we move to using any one of them? Which is the preferred one?

**Comment by moabu** [comment]
We can close this one as I updated those a while ago
