### ISSUE TITLE
doc(jans-auth-server): update swagger for /register endpoint

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#5920]
### Description

doc(jans-auth-server): update swagger for /register endpoint

- For example currently `lifetime` is currently missed in swagger. However it's present in docs description.

**Comment by nynymike** [comment]
Where in the docs? It's not clear that this is the client lifetime, because there are so many potential lifetimes...

**Comment by yuriyz** [comment]
@nynymike In docs it's described here:
https://github.com/JanssenProject/jans/blob/4e167a1faa33de854de7eaa3555561c224980ea3/docs/admin/auth-server/endpoints/client-registration.md?plain=1#L36

And I've just added missed parameters to swagger. Lifetime line point:
https://github.com/JanssenProject/jans/blob/880bede9f2fdca1e4891d310534d621c2e11a227/jans-auth-server/docs/swagger.yaml#L1463

Should I maybe rename it `lifetime` -> `client_lifetime` for clarity ?
