### ISSUE TITLE
docs(installation): add note about uninstall of persistence 

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#5939]
Based on #5863 comments, we have to add a note to the documentation about persistence not being removed when Janssen Server is uninstalled.

This note has to be added to the `Uninstallation` section of [Installation Guides](https://docs.jans.io/head/admin/install/)

**Comment by ossdhaval** [comment]
@devrimyatar 

Based on comments on #5863, I understand that existing persistence infra that got installed during the Janssen Server installation is not removed when Janssen Server is uninstalled.

Question is: If I reinstall Janssen Server with same persistence options, what happens to the previous persistence that still exists? Will the installation process overwrite existing data in the persistence? 

For example:
- I install a Janssen Server on a VM with MySQL as persistence and default values
- I then uninstall Janssen Server which will leave MySQL untouched with all my data still in it.
- Now if I run install process again with the same options that I selected in first install, then what will happen?

**Comment by devrimyatar** [comment]
You have to remove mysql manually.

**Comment by ossdhaval** [comment]
Hi @devrimyatar I observe that I don't have to uninstall Local LDAP manually after I uninstall Janssen Server. The installer could successfully reinstall Janssen Server. Does the uninstaller remove Local LDAP? If so, which other persistence options would have the same behavior?

**Comment by devrimyatar** [comment]
Only Local LDAP is uninstalled, other databases are left untouched.
