### ISSUE TITLE
feat: fido2 needs to search cache for session instead of persistent storage when its caching is enabled

### ISSUE THREAD

**Issue by aliaksander-samuseu** [JanssenProject/jans#5975]
**Description**
As reported in support ticket 11386, Fido doesn't seem to search appropriate storage for sessionId when "sessionIdPersistInCache" property is set to "True".  As @yuriyz wrote:
>It refers to https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/persist/UserSessionIdService.java#L125
> Sounds like there no check in cache for session

Also, according to @Milton-Ch :
> Fido2 does not have a cache implemented at the time of obtaining a session by id.

**Comment by yurem** [comment]
Implemented
