### ISSUE TITLE
feat (Auth-Server): Support RFC 9470: OAuth 2.0 Step Up Authentication Challenge Protocol

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#6015]
[RFC 9470 - OAuth 2.0 Step Up Authentication Challenge Protocol](https://www.rfc-editor.org/rfc/rfc9470.txt) is final:

```
Abstract
   It is not uncommon for resource servers to require different
   authentication strengths or recentness according to the
   characteristics of a request.  This document introduces a mechanism
   that resource servers can use to signal to a client that the
   authentication event associated with the access token of the current
   request does not meet its authentication requirements and, further,
   how to meet them.  This document also codifies a mechanism for a
   client to request that an authorization server achieve a specific
   authentication strength or recentness when processing an
   authorization request.
```

I don't think there is anything to do here in Auth Server, because the `insufficient_user_authentication` error is returned from the resource server.

**Comment by yuriyz** [comment]
Right, RS returns 401 with `acr_values`, so RP can construct correct authorization request.
```
 HTTP/1.1 401 Unauthorized
   WWW-Authenticate: Bearer error="insufficient_user_authentication",
     error_description="A different authentication level is required",
     acr_values="myACR"
```

Also `acr` claim is returned from Introspection Endpoint and encoded into AT JWT according to spec, so these parts are good as well.

**Comment by yuriyz** [comment]
Closing it as done since nothing to do on AS side. Please re-open if I missed some point.
