### ISSUE TITLE
feat(agama): add ability to launch flows when there is an existing session

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#6018]
Launching a given agama flow when the user is already logged in (by means of another agama flow) can be useful. This is similar to stepped up authentication but simpler - no need to deal with permissions, scopes, etc. 

Just sending a new authn request with a different flow name does not suffice because the acr (_agama_) stays the same, and the AS will bypass the flow execution

**Comment by jgomer2001** [comment]
https://github.com/JanssenProject/jans/issues/6017 required

**Comment by nynymike** [comment]
It's not the acr that determines re-authentication, but the `prompt=login` param of the authn request. Also, one idea is to add a claim into the id_token called `agama_flow` with the QN of the agama flow.
