### ISSUE TITLE
fix(jans-setup): FileNotFoundError error when installating jans

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6078]
**Describe the bug**
FileNotFoundError error when installating jans

**To Reproduce**
1. install jans 1.0.17.nightly package
2. run setup.py file
3. See error
```
ec2-user@ip-172-31-30-182:~> sudo python3 /opt/jans/jans-setup/setup.py
The following packages are required for Janssen Server
openssl
Do you want to install these now? [Y/n] y
Installing packages openssl
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 202, in <module>
    jansInstaller.initialize()
  File "/opt/jans/jans-setup/setup_app/installers/jans.py", line 119, in initialize
    oxauth_client_jar_zf = zipfile.ZipFile(Config.non_setup_properties['oxauth_client_jar_fn'])
  File "/usr/lib64/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dist/jans/jans-auth-client-jar-with-dependencies.jar
```
**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/17d8156a-7f1c-4c17-bf94-fc2ee5ed9f9e)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15sp4
  - jans 1.0.17.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate
![image](https://github.com/JanssenProject/jans/assets/6398752/9b1b05bf-8243-4927-b3ef-52441663f6c8)
