### ISSUE TITLE
fix(jans-tui):unable to configure jans-link

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6084]
**Describe the bug**
unable to configure jans-link

**To Reproduce**
1. install jans 1.0.17
2. launch tui
3. goto jans-link
4. check for all tabs and buttons in jans-link

**Expected behavior**
should able to configure jans-link

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/8ae2913f-063d-41bd-adfa-e9c6e057063b)

**Desktop (please complete the following information):**
  - OS: suse
-jans 1.0.17
-DB opendj
**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Cant't replicate
![image](https://github.com/JanssenProject/jans/assets/6398752/ad35d49f-a61d-4de0-88ff-a41d6b1b2b07)
