### ISSUE TITLE
Instructions to install Helm on Rancher fails

### ISSUE THREAD

**Issue by HankTheCrank** [JanssenProject/jans#6090]
**Describe the bug**
The instructions located at
https://docs.jans.io/head/admin/install/helm-install/rancher/
do not work. I've tried on a couple of different systems and I get the same error

**To Reproduce**
1. In Rancher Marketplace, use the Gluu chart to install
2. Select the "Customize Helm options before install" option
3. Click next
4. In the "Optional Services" section, I clear the "Boolean flag to enable/disable the admin-ui...". This is supposed to remove the parts that are not open source and allow an install of the open source version.
5. Click next
6. Clear the "Wait" option
7. Click the "Install" button
8. The result is "Error: INSTALLATION FAILED: execution error at (gluu/charts/config/templates/license-secrets.yaml:17:10):global.licenseSsa is required in chart values. This is a base64 string provided by Gluu to activate your license."

**Expected behavior**
I expected the chart to install the open source (i.e. Janssen) components in Rancher cluster

**Desktop (please complete the following information):**
  - OS: openSUSE Leap 15.4
  - Browser: Chrome 116.0.5845.189
  - Rancher Version: 2.6
  - Kubernetes Version: v.1.24.4+ke2r1

**Additional context**
I'm trying to install the open source version of the software so I do not have a "License SSA"

**Comment by nynymike** [comment]
Hank, don't forget to star Janssen Projct: https://jans.io :-)

**Comment by moabu** [comment]
Hey @HankTheCrank ,

Better to import the Janssen chart into the Rancher UI which we will update the documentation with . Also, to get over this just place a dummy base64 string there but make sure to disable the admin ui service and things should run.

**Comment by HankTheCrank** [comment]
Hi @moabu 

I put in a fake SSA value and it worked. Thanks for the help!
