### ISSUE TITLE
feat(jans-linux-setup): jans-keycloak-storage-api related changes

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#6142]
### 3. Create new SCIM client in jans DB to be used for Keycloak.  New Keycloak SCIM KC client should have

- 3.1. `grantType`
     authorization_code
     client_credentials
     password
     refresh_token
- 3.2. `authorization_method`
   client_secret_basic 
  client_secret_post
- 3.3. `Scopes` 
inum=F0C4,ou=scopes,o=jans (openid)
inum=1200.56C243,ou=scopes,o=jans (https://jans.io/scim/users.write)
inum=1200.8E1EE6,ou=scopes,o=jans (https://jans.io/scim/users.read)

### 4. Create log folder and give appropriate permission for the KC component to be able to write to the log folder. 
        example: mkdir -p /opt/keycloak/logs

### 5. Create `jans-keycloak-storage-api.properties` in `/opt/keycloak/providers/`
Template uploaded here https://github.com/JanssenProject/jans/blob/jans-config-5148/jans-keycloak/storage-api/src/main/resources/jans-keycloak-storage-api.properties
Place holder values for ${keycloak.server.url}, ${auth.server.url}, ${keycloak.scim.client.id},${keycloak.scim.client.password}

### 6. jans-keycloak-storage-api steps
- 6.1 Copy `jans-keycloak-storage-api` jar from maven to installation Keycloak provider folder -> `https://maven.jans.io/maven/io/jans/jans-keycloak-storage-api/<version>/`
to `/opt/keycloak/providers/`
Example: `https://maven.jans.io/maven/io/jans/jans-keycloak-storage-api/1.0.19-SNAPSHOT/` 
  
- 6.2. Copy jans-scim-model.jar from maven to installation Keycloak provider folder -> `https://maven.jans.io/maven/io/jans/jans-scim-model/<version>/`
to `/opt/keycloak/providers/`

-  6.3. Copy Extract jars from following dependency zip `jans-keycloak-storage-api.zip` from maven to installation Keycloak provider folder -> `https://maven.jans.io/maven/io/jans/jans-keycloak-storage-api/<version>/jans-keycloak-storage-api.zip`
to `/opt/keycloak/providers/`
example: https://maven.jans.io/maven/io/jans/jans-keycloak-storage-api/1.0.19-SNAPSHOT/jans-keycloak-storage-api.zip
![image](https://github.com/JanssenProject/jans/assets/43700552/e6b02678-fcd7-4104-bfaf-2049eb702c2b)

-  6.4. When Keycloak server is started need to pass the log folder and properties file param
Example: `sudo JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 /opt/keycloak/bin/kc.sh start-dev --http-port 8083 --log="console,file" --log-file="/opt/keycloak/logs/keycloak.log" -Dlog.base="/opt/keycloak/logs/jans-keycloak.log" -Djans.config.prop.path="/opt/keycloak/providers"
`
- 
- 6.5. Admin will have to install the new `jans-keycloak-storage-api` as federated identity provider using Keycloak admin console

- Related issue [6177](https://github.com/JanssenProject/jans/issues/6177)

**Comment by devrimyatar** [comment]
Implemented
