### ISSUE TITLE
fix: add agama inbound lib to jans auth default jar

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#6170]
Add to https://github.com/JanssenProject/jans/blob/main/docker-jans-auth-server/Dockerfile#L82 https://jenkins.jans.io/maven/io/jans/agama-inbound/1.0.19-SNAPSHOT/agama-inbound-1.0.19-SNAPSHOT-jar-with-dependencies.jar

**Comment by ossdhaval** [comment]
@moabu 

I think this has been taken care already:

https://github.com/JanssenProject/jans/blob/0bee351256d84b1cc958303d0aebaf741705ae28/docker-jans-auth-server/Dockerfile#L90

Can we close this issue?
