### ISSUE TITLE
feat(jans-auth-server): add lifetime to SSA claims

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#6171]
-------------------

### Description

When a customer requests an SSA from the server, they should be allowed to define a `lifetime` claim in the SSA. This will define lifetime of a client, after which the client will be expired on AS. The value for this claim is number of seconds in integer. 

-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes

- [ ] Add `lifetime` claim

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by Milton-Ch** [comment]
@SafinWasi

Could you give me more details on this issue?
SSA currently has a field that indicates if it will be single use.

**Comment by SafinWasi** [comment]
Yes. Basically we want a new claim, `lifetime`, in SSA.
```json
{
  "software_id": "",
  "grant_types": [
    "client_credentials"
  ],
  "org_id": "",
  "iss": "",
  "software_roles": [],
  "exp": 1725634628,
  "iat": 1693926007,
  "jti": "",
  "lifetime": 86400
}
```
When this claim is set in SSA, DCR on AS side will automatically set lifetime of client to this value. This support is already implemented on AS side, SSA just needs the claim.

**Comment by Milton-Ch** [comment]
SSA support custom fields.

First, we have to add it in the `ssaCustomAttributes` parameter

```
...,
"ssaConfiguration": {
    "ssaEndpoint": "https://milton-ch-hardy-mite.gluu.info/jans-auth/restv1/ssa",
    "ssaCustomAttributes": ["lifetime"],
    "ssaSigningAlg": "RS256",
    "ssaExpirationInDays": 30
},
...,
```

With this, you can send the field in the creation request, note that these fields are of `String` type.

```
{
  "org_id": "test-1000",
  "description": "test",
  "software_id": "gluu-scan-api",
  "software_roles": [
    "passwurd"
  ],
  "grant_types": [
    "client_credentials"
  ],
  "expiration": "{{ssa-newlongtime}}",
  "one_time_use": true,
  "rotate_ssa": false,
  "lifetime": "86400"
}
```

Response:
```
eyJraWQiOiJjb25uZWN0XzI2OTg5ODU3LTQxODYtNDZjMS04OTNmLWFiZmU4ZGM4ODRkNV9zaWdfcnMyNTYiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzb2Z0d2FyZV9pZCI6ImdsdXUtc2Nhbi1hcGkiLCJncmFudF90eXBlcyI6WyJjbGllbnRfY3JlZGVudGlhbHMiXSwib3JnX2lkIjoidGVzdC0xMDAwIiwiaXNzIjoiaHR0cHM6Ly9taWx0b24tY2gtaGFyZHktbWl0ZS5nbHV1LmluZm8iLCJsaWZldGltZSI6Ijg2NDAwIiwic29mdHdhcmVfcm9sZXMiOlsicGFzc3d1cmQiXSwiZXhwIjoxNjk2NjM5NzU1LCJpYXQiOjE2OTY1NTMzNTYsImp0aSI6IjA4YThhYTZkLTk2NmYtNGVkZC04ZTkzLWMzODdlOTJhNzZjZSJ9.mz0xsazcgFh6Mhnn67-P8zG8yT_li5Z1W5WTB96eo3exypFNsNrSQYXyDf6KNyWt4Go1YrmvtjmBm3Vyx3AloO3YbP_v23w5Lx6DhoxJQOtj697YhWn4_RKTMC8GGH2TaMwDUi4H8PbeYwu4cCDJPhkwD494OfFQNu-FWJfI6rb7mbsc54mKDryqej9RQvxN__Q6LGEZ5X63SpIRfIjNEsI08s8gfj_a2mvyMO7Uj7o91lyePAemLscXJr1cF_L6g4uqoAJt7WFuBIArpNapPBQkAvazfdHtKDeYea6piId-q_1qIn4hmKK5zpggx9arkm2rSKgay2DqhxKFcgWOuQ
```
![image](https://github.com/JanssenProject/jans/assets/86965029/2168359b-93b4-44ba-9a6d-c71f658b574c)

Now the question is.
Do you need to add validations to this field, validations like not accepting negative values or 0, or does it need to be an integer?

**Comment by SafinWasi** [comment]
Yes, we do need constraints on this. The lifetime is defined as a positive non-zero `Integer`.

**Comment by Milton-Ch** [comment]
Ok @SafinWasi, then I will implement this new field.

**Comment by yuriyz** [comment]
@Milton-Ch it has to be int, not string.
