### ISSUE TITLE
fix(jans-cli-tui): remove hide attrbiute for custom scripts

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#6174]
**Describe the bug**
As disacussed in chat, we need to remove **Hide** attribute form **jansConfProperty**

**Comment by devrimyatar** [comment]
@yurem Shall I also remove that prperty from scipt templates? For example see
https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/scripts.ldif#L286

![image](https://github.com/JanssenProject/jans/assets/6398752/3ecf707a-606a-4c3c-93d7-8e35eeb1dfa2)

**Comment by yurem** [comment]
yes, we can remove it. In new scripts we always follow rule to encrypt passwords in GUI
