### ISSUE TITLE
fix(jans-setup): getting error in jans installation

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6184]
**Describe the bug**
getting error in jans installation

**To Reproduce**
1. donwload and install jans 1.0.19.nightly
2. run setup.py
3. See error

**Expected behavior**
should not get ant error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/fccba4df-6b70-4691-8425-7aebb3d4edd2)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 22
  - DB  opendj
  - jans 1.0.19.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Current stup is trying to download files from https://github.com/GluuFederation/flex/casa but formigration of Casa to Jannsen directory is deleted  https://github.com/GluuFederation/flex/commit/441a07b26eb93a2ce82ed0882dbf43196d620b16
