### ISSUE TITLE
fix(jans-tui): getting error while updating admin details

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6218]
**Describe the bug**
getting error while updating admin details

**To Reproduce**
1. install jans 1.0.19.nightly
2. launch tui
3. try to edit admin user and save 

**Expected behavior**
we should get proper message or if we are not allowed to modify admin then disable fields which we cant modify

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/734f526c-6879-4e25-a7c7-663d9bddbfa9)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp 4
  - jans 1.0.19.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs This shouldn't be TUI issue. And it can't be LDAP issue sice I were be able to modify admin user with attrbiute *jansAdminUIRole* by  JXplorer. Please check it.

**Comment by pujavs** [comment]
**Analysis:**
@devrimyatar, as per my analysis issue is in TUI request object for update user which contains incorrect value for `customObjectClasses`.
TUI should send the value for `customObjectClasses` for PUT request as returned by the GET user response.
I verified TUI logs for GET user and PUT user.
In GET user **"customObjectClasses":["top","jansCustomPerson"]**, but in PUT request the value being sent in **{"customObjectClasses": ["top", "jansPerson"]** and hence the issue.

- Attaching log for your reference
    - For GET refer line#434
    - For PUT refer line#470 to 473
[cli_debug.log](https://github.com/JanssenProject/jans/files/13685832/cli_debug.log)


- Update for user is working without issue from Rest Client.
![image](https://github.com/JanssenProject/jans/assets/43700552/2c85e0a8-34ea-411c-9dfb-da8d3a72d18b)

Request you to please verify and confirm

**Comment by manojs1978** [comment]
@pujavs , @devrimyatar 
this issue still exist , could you please check

**Comment by pujavs** [comment]
@manojs1978,request you to please share exact details, namely 
- Build version
- DB
- config-api logs, `/opt/jans/jetty/jans-config-api/logs`
-  screenshot/video

**Comment by manojs1978** [comment]
@pujavs please find below

jans1.1.0.nightly
os: ubuntu22
DB opendj
[log.zip](https://github.com/JanssenProject/jans/files/14457457/log.zip)
![image](https://github.com/JanssenProject/jans/assets/5729240/2b8c799e-aae2-4321-9605-65e2bd4bebe3)

**Comment by pujavs** [comment]
checking this

**Comment by devrimyatar** [comment]
This issue was resolved

https://github.com/JanssenProject/jans/assets/6398752/8ab87c73-03a4-4904-b506-e38470a4b169
