### ISSUE TITLE
feat(jans-config-api): need API to fetch list containing all script-types from persistence.

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#6219]
**Is your feature request related to a problem? Please describe.**
Everytime script of a new script type is added in persistence we need to make changes in clients like admin UI and TUI to add the script type so that it is available in the dropdown on the script form. For example recently a script of type authorization_challenge added to the persistence. 

It situation can be handled if there is an endpoint in config-api  to fetch all script-types from persistence.

![image](https://github.com/JanssenProject/jans/assets/32794267/44689b25-24ad-4831-98e6-4d9bb3782d21)

**Comment by pujavs** [comment]
new endpoint `/jans-config-api/api/v1/config/scripts/types`

![image](https://github.com/JanssenProject/jans/assets/43700552/7f244e64-0f0e-4032-9971-e0cff1b0a0c8)

**Comment by pujavs** [comment]
- `/jans-config-api/api/v1/config/scripts/types` return a list of `https://github.com/JanssenProject/jans/blob/main/jans-core/script/src/main/java/io/jans/model/custom/script/CustomScriptType.java` object.
![image](https://github.com/JanssenProject/jans/assets/43700552/791cf416-59ab-49c0-9135-3d8b9b61abb3)


- '/jans-config-api/api/v1/config/scripts/script-types` return a list of String of value of CustomScriptType.
![image](https://github.com/JanssenProject/jans/assets/43700552/82d7b8e7-0dca-43f2-873f-65738d02ff42)

**Comment by pujavs** [comment]
Implemented via PR [6276]( https://github.com/JanssenProject/jans/pull/6276)

**Comment by pujavs** [comment]
Swagger spec issue
