### ISSUE TITLE
fix(casa): uanble to launch casa after installation

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6220]
**Describe the bug**
uanble to launch casa after installation

**To Reproduce**
1. isntall jans 1.0.19.nightly
2. launch casa url
3. 
```
ec2-user@manojs1978-exotic-redbird:~> sudo systemctl list-units --all "casa*"
  UNIT         LOAD      ACTIVE   SUB  DESCRIPTION 
● casa.service not-found inactive dead casa.service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
```
**Expected behavior**
should able to launch casa

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/bedfdec4-b083-4b8b-9a1d-de4c20f71e90)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moabu** [comment]
its `/jans-casa` not `/casa` . Its working here.
