### ISSUE TITLE
feat(jans-linux-setup): setup Jans-keycloak-link 

### ISSUE THREAD

**Issue by shekhar16** [JanssenProject/jans#6280]
integrate Jans keycloak-link in jans setup

**Comment by shekhar16** [comment]
below are the steps to set up keycloak configuration.

1)  Install Keyclaok 21.1.1 or 
2)  Create client 
3)  In "settings" tab -> Authentication flow select only "service accoujts roles"
3)  In "Service accounts Roles" tab -> select "admin"
3)  Copy client ID and client secret
4)  Set all these parmeters in keycloakConfiguration and update the configguration. for ex: 
    "keycloakConfiguration": {
		"serverUrl": "http://localhost:8180",
		"realm": "master",
		"clientId": "clientserviceaccount",
		"clientSecret": "cbyFHt3MMU2vNluAmzXopl9SHx9CUmfC",
		"grantType": "client_credentials",
		"username": "admin",
		"password": "keycloak"
	}
5) Restart server.

**Comment by nynymike** [comment]
Why are you using `http` and not `https` ? We should use secure communication everywhere. Also, we should not store clear text passwords in config files.

**Comment by devrimyatar** [comment]
Fixed in https://github.com/JanssenProject/jans/pull/6281
