### ISSUE TITLE
fix(config-api): smtp test endpoint throwing error

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#6320]
**Describe the bug**
Error while testing SMTP connection

**To Reproduce**
1. Install jans server
2. Run TUI
3. Go to SMTP menu
4. Enter details and test
5
**Expected behavior**
SMTP test should return proper status

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/43700552/88da9774-c532-4ef9-bd11-20e80e00de45)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
Tested with latest build
1. Success, if i provide correct details
![image](https://github.com/JanssenProject/jans/assets/43700552/a625bc5e-ebc9-4bb1-84fe-d472bc0abaed)

2. No status/error in-case of incorrect data
![image](https://github.com/JanssenProject/jans/assets/43700552/468f0129-b4ee-4bc5-91dd-502fbdd41650)

![image](https://github.com/JanssenProject/jans/assets/43700552/5095020a-133a-4695-9309-51ba619be4b5)

**Comment by SafinWasi** [comment]
I was able to replicate exact scenario.
- On fresh setup with no existing SMTP configuration, test fails with 500 error.
- On install with existing SMTP configuration already saved, test succeeds.

**Comment by pujavs** [comment]
hi @SafinWasi, i was able to replicate the issue regarding SMTP test issue.

SMTP test code expects SMTP configuration already saved. This is common core service https://github.com/JanssenProject/jans/blob/main/jans-core/service/src/main/java/io/jans/service/MailService.java#L167

There are two options to fix the issue;
- Enable Test only if configuration is saved. Change in Tui code only.
- Write a new method in core to test without saving. Change required in config-api and jans-core, maybe TUI.

Please confirm what is preferred.

**Comment by SafinWasi** [comment]
1 is easier to implement, so let's go with that for now. We would need some message or warning that test is only available if SMTP configuration is saved.

**Comment by devrimyatar** [comment]
I modifed TUI, inorder to test, changes should be saved (https://github.com/JanssenProject/jans/pull/6378):

![save_before_test](https://github.com/JanssenProject/jans/assets/6398752/a54ce9a3-8950-4666-b1a9-0cf9ec7a5fc3)

**Comment by pujavs** [comment]
Closing the issue as fixed by @devrimyatar via PR [6378](https://github.com/JanssenProject/jans/pull/6378)
