### ISSUE TITLE
fix(jans-linux-setup): incorrect server endpoint for super gluu credentials

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#6327]
**Describe the bug**
On a fresh install, `/etc/certs/super_gluu_creds.json` has the SCAN endpoint as `https://account.gluu.org/scan/push-api-server`. This is incorrect. The correct default value should be `https://cloud.gluu.org/scan/push-api-server`.

**Comment by yurem** [comment]
If `-t` option specified we need to use `https://cloud-dev.gluu.cloud/scan/push-api-server`

**Comment by yurem** [comment]
The server URL is here `https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/static/auth/conf/super_gluu_creds.json#L15C60-L15C60`

**Comment by devrimyatar** [comment]
Test data url is missing
