### ISSUE TITLE
fix(jans-auth-server): the device-session is not saved on setting `use_device_session=true` in request

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#6352]
When using the `Authorization Challenge Endpoint` device-session is not saved in the persistence (`jansDeviceSess`) on setting `use_device_session=true` in request.

**Steps followed**

1. **Called /authorization_challenge**
```
curl -k https://duttarnab-uncommon-sloth/jans-auth/restv1/authorization_challenge -d 'grant_type=authorization_code' -d 'scope=openid' -d 'username=admin' -d 'password=Gluu1234.' -d 'state=0x74ab847000' -d 'nonce=8974ab847000' -d 'client_id=2001.3f0e2f69-049a-48c7-938e-ae3729cbe3b1' -d 'acr_values=simple_password_auth' -d 'use_device_session=true'
````
2. **Called /token**
```
curl -k -u '2001.3f0e2f69-049a-48c7-938e-ae3729cbe3b1:Gu7bmMB48c5R' https://duttarnab-uncommon-sloth/jans-auth/restv1/token -d 'grant_type=authorization_code' -d 'scope=openid' -d 'code=d396d712-6f89-4d4b-bbf1-c8ab6ac5dd6e' -d 'redirect_uri=https://duttarnab-uncommon-sloth/admin'
```

3. No entry in `jansDeviceSess` table. 
![image](https://github.com/JanssenProject/jans/assets/32794267/9b054d08-404b-4cb5-be56-8478e579fe25)

**Comment by yuriyz** [comment]
@duttarnab can you post `jans-auth.log` in TRACE log level ?

**Comment by duttarnab** [comment]
[jans-auth.log](https://github.com/JanssenProject/jans/files/13056466/jans-auth.log)

**Comment by yuriyz** [comment]
That logs file does not contain any logs from Authorization Challenge Endpoint. Also I've noticed that curl posted in ticket description has `acr_values=simple_password_auth`. We can't reference normal person authentication script. We must reference `AuthorizationChallenge` script. For test you can use default `default_challenge` or provide your own.

I've tested it and I can see that `device_session` is returned in error and also is persisted into DB.

![image](https://github.com/JanssenProject/jans/assets/2013070/40b0e9b3-33a8-49b7-bb95-c2ebc9180e74)

You can try following curl:
```
curl -k https://yuriyz-upward-ocelot.gluu.info/jans-auth/restv1/authorization_challenge \
-d 'grant_type=authorization_code' \
-d 'scope=openid' \
-d 'username=admin' \
-d 'state=0x74ab847000' \
-d 'nonce=8974ab847000' \
-d 'client_id=eca8a27b-7618-426e-a504-e98286e369dc' \
-d 'acr_values=default_challenge' \
-d 'use_device_session=true'
```

I will PM you creds to login for VM, so you can check DB on your own.

![image](https://github.com/JanssenProject/jans/assets/2013070/0719f55e-5130-4bc9-9982-b743128508d6)

Closing as not reproducible.
