### ISSUE TITLE
Not able to see enabled auth script in Authn.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#6440]
**Describe the bug**
Not able to see enabled auth script in Authn 

**To Reproduce**

1.install jans 1.0.20.nightly
2.enable any script on jans -tui
3. go to authn and check enabled scripts

**Expected behavior**
all enabled script should be available on authn 

**Screenshots**
![Screenshot (16)](https://github.com/JanssenProject/jans/assets/34593983/8906e6ec-c317-4ef6-be7a-c008cf7071cf)

if we check in jans-tarp enabled script is available 

![Screenshot (17)](https://github.com/JanssenProject/jans/assets/34593983/3ed3fe47-569d-40a6-9f46-362f59564b58)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version jans1.0.20nighlty + pgsql

**Comment by devrimyatar** [comment]
@pujavs This shouldn't be TUI issue. May be admin-ui queries all scripts and filter internally. I enabled DUO script on both LDAP and PostgreSQL backends. When I executed this query:

```
 python3 /opt/jans/jans-cli/cli/config_cli.py --operation-id=get-config-scripts --endpoint-args='fieldValuePair:scriptType=person_authentication,fieldValuePair:enabled=true'
```

OpenDJ backend response is good as expected:

![q-ldap](https://github.com/JanssenProject/jans/assets/6398752/36290d84-216c-469f-9fdd-cc5f39738325)

But PostgreSQL backends reponses error:

```
{
  "cause2": "Failed to build search entries query. Key: &apos;scripts&apos;, expression: &apos;(lower(doc.description) like %% || lower(doc.displayName) like %%) &amp;&amp; doc.jansEnabled = true &amp;&amp; doc.jansScrTyp = person_authentication&apos;",
  "cause1": "io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;scripts&apos;",
  "servlet": "io.jans.configapi.rest.ApiApplication",
  "cause4": "org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 448",
  "cause3": "com.querydsl.core.QueryException: Caught PSQLException for select &quot;doc&quot;.&quot;jansConfProperty&quot;, &quot;doc&quot;.&quot;displayName&quot;, &quot;doc&quot;.&quot;jansRevision&quot;, &quot;doc&quot;.&quot;description&quot;, &quot;doc&quot;.&quot;jansScrTyp&quot;, &quot;doc&quot;.&quot;jansModuleProperty&quot;, &quot;doc&quot;.&quot;inum&quot;, &quot;doc&quot;.&quot;jansAlias&quot;, &quot;doc&quot;.&quot;jansProgLng&quot;, &quot;doc&quot;.&quot;jansScrError&quot;, &quot;doc&quot;.&quot;jansScr&quot;, &quot;doc&quot;.&quot;jansEnabled&quot;, &quot;doc&quot;.&quot;jansLevel&quot;, &quot;doc&quot;.&quot;dn&quot;, &quot;doc&quot;.&quot;doc_id&quot;\nfrom &quot;public&quot;.&quot;jansCustomScr&quot; &quot;doc&quot;\nwhere (lower(&quot;doc&quot;.&quot;description&quot;) like ? or lower(&quot;doc&quot;.&quot;displayName&quot;) like ?) and (&quot;doc&quot;.&quot;jansEnabled&quot; = ? and &quot;doc&quot;.&quot;jansScrTyp&quot; = ?)\norder by &quot;inum&quot; asc, &quot;jansLevel&quot; asc\nlimit ?\noffset ?",
  "cause0": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;scripts&apos;",
  "message": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;scripts&apos;",
  "url": "/jans-config-api/api/v1/config/scripts",
  "status": "500"
}
```

See the error in config-api jetty log:

[2023_11_04.jetty.log](https://github.com/JanssenProject/jans/files/13257126/2023_11_04.jetty.log)

**Comment by pujavs** [comment]
Seems orm issue, have requested @yurem for guidance

**Comment by yurem** [comment]
In the log there are 2 SQL Exception parts:
`
com.querydsl.core.QueryException: Caught PSQLException for select "doc"."jansConfProperty", "doc"."displayName", "doc"."jansRevision", "doc"."description", "doc"."jansScrTyp", "doc"."jansModuleProperty", "doc"."inum", "doc"."jansAlias", "doc"."jansProgLng", "doc"."jansScrError", "doc"."jansScr", "doc"."jansEnabled", "doc"."jansLevel", "doc"."dn", "doc"."doc_id"|from "public"."jansCustomScr" "doc"|where (lower("doc"."description") like ? or lower("doc"."displayName") like ?) and ("doc"."jansEnabled" = ? and "doc"."jansScrTyp" = ?)|order by "inum" asc, "jansLevel" asc|limit ?|offset ?
`

and

`
org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = character varying|  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.|  Position: 448
`

According to the second one we compare boolean value with `character varying`. I think the issue in this filter part `"doc"."jansEnabled" = ?`.

Do you set boolean value or string in this filter part? Can you dump value/value_class_type of each parameter which you put into filter?

**Comment by pujavs** [comment]
@yurem, the field and value provided are query parameter and hence passed as string.
2023-11-07 14:52:18,142 TRACE [qtp366004251-17] [io.jans.service.custom.CustomScriptService] (CustomScriptService.java:113) - CustomScript entry.getKey():jansEnabled, entry.getValue():true, entry.getValue().getClass():class java.lang.String`

Please find attached logs for both LDAP and PLSQL.
- LDAP log - line#1742
[configapi_script_LDAP_Line#1742.log](https://github.com/JanssenProject/jans/files/13295045/configapi_script_LDAP_Line.1742.log)

- PLSQL Line#966
[configapi_persistence_PLSQL_Line#966.log](https://github.com/JanssenProject/jans/files/13295053/configapi_persistence_PLSQL_Line.966.log)

**Comment by yurem** [comment]
I added strings "true" and "1" to boolean "true" conversion if column type is boolean

**Comment by devrimyatar** [comment]
Fixed
