### ISSUE TITLE
fix(jans-config-api): `/api/v1/attributes` `POST` should allow to add attribute only if it is declared in schema

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#6446]
**Describe the bug**
 `/api/v1/attributes` `POST` should allow to add attribute if it is declared in schema. Otherwise it should throw error like `The attribute 'attribute-name' is not defied in LDAP/MySql schema.`

For example below step should be performed then only config-api attribute api should allow to add attribute.

 **in OpenDJ**

https://docs.jans.io/v1.0.19/admin/auth-server/openid-features/user-claims/custom-claims/#step-2-make-entry-of-the-claim-in-opendj-schema

**In RDBMS**

https://docs.jans.io/v1.0.19/admin/auth-server/openid-features/user-claims/custom-claims/#step-2-make-entry-of-the-claim-in-mysql-schema

**Comment by pujavs** [comment]
Implemented check for LDAP and tested as per https://docs.jans.io/v1.0.19/admin/auth-server/openid-features/user-claims/custom-claims/#step-2-make-entry-of-the-claim-in-opendj-schema

However in Postgresql even though the attribute is added in **jansPerson**  the verification is failing. https://docs.jans.io/v1.0.19/admin/auth-server/openid-features/user-claims/custom-claims/#step-2-make-entry-of-the-claim-in-mysql-schema.
Have requested @yurem for guidance

**Comment by yurem** [comment]
@pujavs I think config-api instead of scanning in schema should try to call ORM add/update method and catch exception. From exception it should get clue if it's schema error or another one. In this case config-api will not depend on ORM specifc implementation.

Can you add stack traces with attempt to call ORM add/update if there is undefined attribute. After that in places which throw exceptions we can add error code to escpetion or throw another one like `UndefinedAttributeInSchemaError`, etc.

**Comment by pujavs** [comment]
@yurem i will share the requested logs. 

But i also need guidance how to define new custom attribute.
- Like for LDAP one needs to first define new attribute 77-customAttributes.ldif and later create the attribute from UI.
- How to test this scenario in other DB type.

**Comment by yurem** [comment]
In other DB the process is similar to LDAP. We need to add custom attribute to table first and register it in UI. Here is [link](https://docs.jans.io/head/admin/reference/database/mysql-ops/#ldap-to-mysql-migration-script) to docs.

**Comment by pujavs** [comment]
@yurem, requirement is `should allow to add attribute only if it is declared in schema` 

If I call ORM add/update as per your suggestion then i am able to create an attribute that is not defined in schema

1. Logs: Search  `PujaNumber` in the logs
[6446_logs.zip](https://github.com/JanssenProject/jans/files/13589803/6446_logs.zip)

2.Screenshots for LDAP
- Attribute `PujaNumber` **not** defined in `77-customAttributes.ldif` yet able to create a random attribute
![image](https://github.com/JanssenProject/jans/assets/43700552/3aca9f42-8f64-413e-bf99-3a2eb134fa3d)

- Able to successfully create the attribute 
![image](https://github.com/JanssenProject/jans/assets/43700552/22d3176f-a04a-4a7a-a04e-1f0131524c3a)

Request your advice.

**Comment by yurem** [comment]
`ou=attributes` is our table to define Jans attributes metadata.
DB schema <> `ou=attributes`.
It's admin responsibility to maintain both.

But we can add to EntryManager method:
```
	private boolean hasSchemaAttribute(String key, String objectClass);
```

**Comment by pujavs** [comment]
1validateAttributeDefinition1 code works perfectly well for LDAP
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java#L354. 
We need similar common method for All DB types. Will it be possible in ORM?

**Comment by duttarnab** [comment]
This issue does not have high priority.

**Comment by pujavs** [comment]
As per discussion with @yurem, orm changes will be done for the same

**Comment by pujavs** [comment]
Tested custom attribute creation in MySQL and LDAP. **Note:** I had to restart LDAP as well as MySQL 

### MySQL Screenshots
- Before declaring new customAttribute in DB
![image](https://github.com/JanssenProject/jans/assets/43700552/5eef00ed-2beb-4f77-8e2b-2c29e0ec987b)

- Altered table to add new customAttribute
![image](https://github.com/JanssenProject/jans/assets/43700552/a2255e13-1639-4f8d-9389-25513ab4ecfd)

- After declaring new customAttribute in DB 
![image](https://github.com/JanssenProject/jans/assets/43700552/c4cc164c-67dd-4f82-91d6-d66a6fa4dedb)

**Comment by pujavs** [comment]
PR [7814](https://github.com/JanssenProject/jans/pull/7814) raised for the same

**Comment by pujavs** [comment]
@duttarnab, request you to please check and confirm if the solution works as per expectation

**Comment by pujavs** [comment]
@duttarnab, assigning the issue to you for verification. In-case of any issue you can re-assign to me

**Comment by duttarnab** [comment]
It is working when tested via. admin-ui.
