### ISSUE TITLE
fix(jans-tui): tui breaks when removing claim in scope

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6458]
**Describe the bug**
tui breaks when removing claim in scope

**To Reproduce**
1. install jans 1.0.20.nightly
2. add scope
3. select openid scope and add claim
4. try to remove scope by pressing d
5. See error

**Expected behavior**
should able to remove claim from scope

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/3a5438ff-dbd3-4ea2-ac65-726dc0fe8993)

**Desktop (please complete the following information):**
  - OS: suse15
  - Version 15
  - jans 1.0.20.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
I were be able to replicate this issue. But the way we add claim is not good. We should replace list with label container as in adding  scopes to clients:

![image](https://github.com/JanssenProject/jans/assets/6398752/1761a357-899f-4ced-bb83-6e10b81de558)
