### ISSUE TITLE
fix: gluu branding in jans devicecode screen

### ISSUE THREAD

**Issue by corriganjeff** [JanssenProject/jans#6534]
**Describe the bug**
The jans device code screen is using gluu branding instead of the jans logo/icons/

**To Reproduce**
Install the jans docker monolith (19_dev)
Upon completion, navigate to https://$yourhost/device-code?user_code=ABCD-EFGH

**Expected behavior**
Janssen branding/ is displayed. 

**Screenshots**
![Screenshot 2023-11-09 at 10 39 49 AM](https://github.com/JanssenProject/jans/assets/36687287/f175b082-cb4a-4320-9b2b-1b4b0294b7d5)

**Comment by ossdhaval** [comment]
We should track this as part of [redesign](#1302) effort
