### ISSUE TITLE
Support jansOrganization config via jans-config-api

### ISSUE THREAD

**Issue by Milton-Ch** [JanssenProject/jans#655]
Currently, via oxTrust we have the capability to modify favicon and logo, however via `jans-config-api` we don't have yet.

https://gluu.org/docs/gluu-server/4.2/admin-guide/oxtrust-ui/#organization-settings

**Solution**
We should have the option to upload logo and favicon images via `jans-config-api`.
There are other fields as part of `jansOrganization` as well, maybe worths adding all of these properties as part of a configurable endpoint.

**Context**
We had a client that couldn't modify these values accordingly, currently it's only allowed via DB access.
https://github.com/JanssenProject/jans/issues/374

**Comment by pujavs** [comment]
@Milton-Ch,iImplemented the basic feature to fetch and update values of Jans Organization.
[src.test.resources.feature.config.org.org-config.pdf](https://github.com/JanssenProject/jans/files/8033681/src.test.resources.feature.config.org.org-config.pdf)

**Comment by yurem** [comment]
This can be security issue. User who has access to API can specify path to system configuration file. And our favicon servlet will send it to browser.
Also I think we should not allow upload binary image and store it in DB.

@nynymike @Milton-Ch @yuriyz What do you think to host them on cuspomers machine? Example `jsFaviconPath: www.example.com/resource/favicon.jpg`

**Comment by pujavs** [comment]
@Milton-Ch favicon and logo path are saved in jans org. Pls chk @yurem comments and revert if any changes required...

**Comment by Milton-Ch** [comment]
Hi @pujavs I'm not too involved in `jans-config-api`, but if you want, I can take a look at your PR in order to see whether everything is ok. Other than that, based on @yurem's comment, we might need to verify security implications, in oxTrust, I understand that we are saving only paths, so we can follow the same pattern and save paths referring to the local machine, what do you think?

**Comment by pujavs** [comment]
Implementation for saving favicon and logo path are in jans org done hence closing the issue
