### ISSUE TITLE
feat(jans-tui): the `tag` field mandatory in request body when saving config-api permission in admin ui configuration.

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#6555]
When saving/modifying admin ui permission the `tag` field is mandatory.

**Sample POST and PUT request**

> curl -X PUT -k -H 'Authorization: Bearer <token-here...>' -H 'Content-Type: application/json' -i https://jv18creator-golden-crane/jans-config-api/admin-ui/adminUIPermissions --data '{`"tag":"saml-scope"`,"permission":"https://jans.io/oauth/config/saml-scope.readonly"}'

> curl -X POST -k -H 'Authorization: Bearer <token-here...>' -H 'Content-Type: application/json' -i https://jv18creator-golden-crane/jans-config-api/admin-ui/adminUIPermissions --data '{`"tag":"demo"`,"permission":"https://jans.io/oauth/config/demo.readonly"}'

**Comment by devrimyatar** [comment]
@duttarnab Should we post `tag` for only admin-ui endpoints? Or for all endpints of config-api?

**Comment by duttarnab** [comment]
only for `https://jv18creator-golden-crane/jans-config-api/admin-ui/adminUIPermissions ` endpoint.
