### ISSUE TITLE
fix: report correct state of feature flags on TUI

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#6611]
On a fresh install of Janssen Server(build: 1.0.21-nightly), feature flags are shown as below in TUI.

![image](https://github.com/JanssenProject/jans/assets/343411/df7750f0-41b0-4b9c-a568-df8748d58e91)

All checkboxes are unchecked. Giving an impression that all flags are disabled. At the same time, on AS all the flags are enabled by default. 

We need to fix this inconsistency. TUI should always show which flags are enabled/disabled on AS. There has to be a way of TUI to know which all flags are available on AS and out of those, which ones are enabled at that point in time.

Context: [discussion here](https://chat.gluu.org/group/service_jans_tui?msg=pjeJz6AFfKrD46uR8)

**Comment by yuriyz** [comment]
If "featureFlags" configuration is absent or if it has no values then AS consider it as everything is enabled. To keep it clear to end user I guess we can do following:

- All features enabled [x]
- Enable only particular AS features: 
   - End Session [x]
   - other flags below....

What do you guys think ?

**Comment by devrimyatar** [comment]
I think we are trying to determine which flags should be enabled when jans installed.

**Comment by yuriyz** [comment]
By default we don't specify any specific flag, Means no values for "featureFlags" which for AS means everything is enabled. 
So default behavior is everything is enabled. It's under admin responsibility to starting swithing on/off features if needed.

We can start maintaining that list and simply put all values there but then each time new feature flags is added we will need to remember to update it. Current approach is better because we don't need to maintain it. However I agree with Dhaval that we can't simply show everything unchecked while in fact everything is enabled. That's why I'm proposing solution described above with "All features enabled [x]" which should solve end-user confusion.

**Comment by yurem** [comment]
I agree with @yuriyz It's better to enable all by default and disable only specified. This will work fork new components as well

**Comment by devrimyatar** [comment]
Okay, I am going to check all flags if config-api does not return property *featureFlags*

**Comment by ossdhaval** [comment]
Does this not take away our capability to disable a particular flag at the start? we can still do it via a code change, correct?

I think it is important to be able to do so. Maybe, with the feature flags that we have currently, we are ok keeping everything enabled. In the future, we may have flags that are disabled by default and we want the admin to enable them explicitly. 

We already have [a user voicing concern](https://matrix.to/#/!FaGbwVkmnUUkbmfJJu:gitter.im/$SCddLgqBUISMBa6_Kqn9FhsDqySD7T5psBBgzcYZQYo?via=gitter.im&via=matrix.org) about this.

@nynymike can you opine on this?

**Comment by yuriyz** [comment]
> Does this not take away our capability to disable a particular flag at the start?

It does not.

> we can still do it via a code change, correct?

correct

**Comment by nynymike** [comment]
I need to consider this. The actualy defaults should be to max privacy and security... not just to all enabled or disabled.

**Comment by nynymike** [comment]
![image](https://github.com/JanssenProject/jans/assets/3717101/1dd601d8-79c3-4f3c-afff-b363dec061d0)
 See above. Although @ossdhaval TBH, I don't know what all these features do despite the [docs](https://docs.jans.io/v1.0.20/admin/reference/json/feature-flags/janssenauthserver-feature-flags/). For example, is the id_generation endpoint still used by any services? For the JANS_CONFIGURATION endpoint, which .well-knowns does it disable? All of them? What's the difference between STAT and METRIC? And STATUS_SESSION v. ACTIVE_SESSION ?

**Comment by yuriyz** [comment]
> For the JANS_CONFIGURATION endpoint, which .well-knowns does it disable? All of them?

It disables whole ./well-known endpoint. AS stops returning replies

> What's the difference between STAT and METRIC? 

- STAT is for `/stat` endpoint which returns MAU, tokens usage etc.
- METRIC - Enable/Disable metric reporter feature. Its original event reporter, e.g. user authorized successfully or failed or client is registered.

> STATUS_SESSION v. ACTIVE_SESSION ?

- ACTIVE_SESSION is for `/session/active` endpoint. Requested here : https://github.com/JanssenProject/jans/issues/604
- STATUS_SESSION is for `/session_status` endpoint. Returns status, time for session and custom state.

**Comment by ossdhaval** [comment]
Hi @nynymike I'll add more details to feature flag descriptions. I anyway have to update the default values for each flag. 

@yuriyz As suggested by @nynymike in the above picture, can you make code changes so these flags are disabled by default?

**Comment by yuriyz** [comment]
Feature flags state is set according to list provided above by @nynymike .
TUI will reflect state thus we can close discussion about absent "featureFlags" config.

**Comment by ossdhaval** [comment]
I was checking the new feature flag screen behavior after we merged and fixed this issue and #6779. What I see on the TUI is same as before. Is there something that we still need to do?

cc: @devrimyatar @yuriyz @pujavs
