### ISSUE TITLE
fix(jans-config-api): syntax error in jans-config-api swagger specs

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#6622]
Getting syntax error in https://editor.swagger.io/ on opening following config-api spec.

- https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml

**Comment by moabu** [comment]
Yes we can @ossdhaval . We have to understand that the head here `main` will always contain the placeholder.

**Comment by ossdhaval** [comment]
Ok, I'll work on this. cc: @pujavs .

**Comment by ossdhaval** [comment]
@pujavs we won't need to add complex version replacement mechanism there. We can add `version=""`. 

We don't really need `version` tag as the versioning info is captured in the spec path and URL as well. 

![image](https://github.com/JanssenProject/jans/assets/343411/265debb3-6354-43c0-9a0f-bd556ac6bb1a)
