### ISSUE TITLE
fix(jans-tui): unable to launch dev auth url

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6635]
**Describe the bug**

**To Reproduce**
1. install jans 1.0.21.nightly
2. launch tui
3. redirect to dev auth url

**Expected behavior**
url is not launching getting error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/7fb7f61d-ede6-4f02-8e99-d37a375b7f8d)

**Desktop (please complete the following information):**
  - OS: suse/rhel/ubuntu
  - jans 1.0.21.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This can't be tui issue

**Comment by devrimyatar** [comment]
Closing
