### ISSUE TITLE
feat(jans-linux-setup): config-idp-plugin related changes

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#6788]
### 1. Prerequisite: Keycloak server should be installed and Keycloak OpenID Client should be Created with admin role. 
@uprightech to be reached for KC server installation creation of Client for Jans 

### 2. idp-plugin: config changes: When idp-plugin is to be installed, it config needs to be created
New config definition `ou=trusted-idp,o=jans` 
I have already added config here. Please verify and modify if needed -> https://github.com/JanssenProject/jans/tree/jans-config-6288/jans-linux-setup/jans_setup/templates/jans-idp

2.1. Update idp-config.json with appropriate values  
[jans-idp-db-config-sample.json](https://github.com/JanssenProject/jans/files/13499363/jans-idp-db-config-sample.json)
Attached sample file used locally
Values that will change on setup is dependent on step#1

-  serverUrl": =>  KC server URL
-  "clientId": =>  KC clientId	
-   "clientSecret": =>  KC client secret 
-   "username": =>  KC server admin user
-   "password": KC server user pwd

### 3. Quite a few new attributes and two new schema object - `jansTrustedIdp` ad `jansRealm` changes defined in 
https://github.com/JanssenProject/jans/blob/jans-config-6288/jans-linux-setup/jans_setup/schema/jans_schema.json
**Please review and make changes if needed**

### 4. New directory structure to be created on jans server to store metadata file during installation of idp-plugin
#Dir for SP
mkdir -p /opt/idp/configs/keycloak/sp/metadata
chown jetty:jetty  /opt/idp/configs/keycloak/sp/metadata
chmod 0760  /opt/idp/configs/keycloak/sp/metadata

mkdir -p /opt/idp/configs/keycloak/sp/temp_metadata
chown jetty:jetty  /opt/idp/configs/keycloak/sp/temp_metadata
chmod 0760  /opt/idp/configs/keycloak/sp/temp_metadata
---
#Dir for IDP
mkdir -p /opt/idp/configs/keycloak/idp/metadata
chown jetty:jetty  /opt/idp/configs/keycloak/idp/metadata
chmod 0760  /opt/idp/configs/keycloak/idp/metadata

mkdir -p /opt/idp/configs/keycloak/idp/temp_metadata
chown jetty:jetty /opt/idp/configs/keycloak/idp/temp_metadata
chmod 0760 /opt/idp/configs/keycloak/idp/temp_metadata

### 5. config-api-idp-plugin: Jetty changes to configure new config-api plugin for idp-plugin
- 5.1 Copy new plugin jar: Copy idp-plugin-1.0.21-SNAPSHOT.jar from maven repo -> [https://maven.jans.io/maven/io/jans/jans-config-api/plugins/idp-plugin/<version>/](https://maven.jans.io/maven/io/jans/jans-config-api/plugins/idp-plugin/1.0.21-SNAPSHOT/)
to /opt/jans/jetty/jans-config-api/ custom/libs/
Example location for 1.0.15-SNAPSHOT->https://maven.jans.io/maven/io/jans/jans-config-api/plugins/idp-plugin/1.0.21-SNAPSHOT/

- 5.2 Rename jar to idp-plugin.jar in /opt/jans/jetty/jans-config-api/ custom/libs/

- 5.3 jans-config-api.xml changes: Modify /opt/jans/jetty/jans-config-api/webapps/jans-config-api.xml to **append** entry for new plugin /opt/jans/jetty/jans-config-api/custom/libs/idp-plugin.jar
Example entry for reference /opt/jans/jetty/jans-config-api/custom/libs/user-mgt-plugin.jar,/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar,/opt/jans/jetty/jans-config-api/custom/libs/fido2-plugin.jar,/opt/jans/jetty/jans-config-api/custom/libs/saml-plugin.jar**,/opt/jans/jetty/jans-config-api/custom/libs/idp-plugin.jar,**

**New scopes:** Create new scopes and add to the jans-config-api client. Details of the endpoint and scope as usual is in /jans-config-api/server/src/main/resources/config-api-rs-protect.json - This code should already be existing in jans-linux-setup but mentioning for completeness. New endpoint -/jans-config-api/idp/`

**Note:**
Jans config api changes for idp-plugin endpoints is still in branch [jans-config-5148](https://github.com/JanssenProject/jans/tree/jans-config-6288

**Related issues:**
https://github.com/JanssenProject/jans/issues/6288

**Comment by uprightech** [comment]
@pujavs could you help me with further information as to why an openid client needs to be created during setup ?

**Comment by pujavs** [comment]
@uprightech, we need to get Keycloak instance to invoke Rest API and it requires client details along with server url and user details. Do you have better suggestion?

**Comment by uprightech** [comment]
@pujavs do you mean the details will be used by Jans-TUI or the related Config-API plugin to perform modifications on keycloak?

**Comment by pujavs** [comment]
Yes @uprightech, that is the requirement as been sharing in @saml_service chat group `/jans-config-api/idp/kc/saml/: CRUD endpoints for creation and managing Identity Broker in Jans DB and KC server

**Comment by uprightech** [comment]
@devrimyatar  , we can use the kcadm tool that ships with keycloak. It allows you one to perform modifications to a running keycloak instance. 
We will integrate these steps and further improve it security wise, but for now , this should do. 
I have attached the relevant files [here](https://github.com/JanssenProject/jans/files/13506331/kcadm-template.zip)

Startup the keycloak server and do the following :

1. Setup credentials . This will configure credentials stored in the files 
```
kcadm.sh config credentials --server http://kc-instance.local:8080/ --realm master --user admin --password admin --config ./kcadm-jans.config
```

2. Change admin user password 
```
kcadm.sh set-password -r master --username admin --new-password <randomly-generated-password> --config ./kcadm-jans.config
```

3. Create a realm in keycloak called `jans`
```
kcadm.sh create realms -f jans.realm.json --config ./kcadm-jans.config
```

4. Create a client in keycloak called `jans-api-client`
```
kcadm.sh create clients -r jans -f jans.realm.json --config ./kcadm-jans.config
```

5. Create a user for the realm called `jans-api-user`
```
kcadm.sh create users -r jans -f jans.api-user.json --config ./kcadm-jans.config
```
This will return a message of the form `Created new user with id '5361728c-1770-415e-9fe4-b5c4ac98698f'`
Extract and keep the id 

6. Set the user's password. It must be randomly generated and made accessible in some way

```
kcadm.sh set-password -r jans --username "jans-api-user" --new-password "r@nd0m_p@ssw0rd!" --config ./kcadm-jans.config
```

6. Assign the appropriate roles for the user `jans-api-user`
```
kcadm.sh add-roles -r jans --uusername "jans-api-user" --cclientid "realm-management" \
--rolename 'manage-identity-providers' --rolename 'view-identity-providers' \
--config ./kcadm-jans.config

```
7. Delete the file `kcadm-jans.config`

**Comment by uprightech** [comment]
@pujavs please take a look at step `6`. If you need a user with more permissions than `manage-identity-provider` and `view-identity-providers` , let me know. Just describe what you need, I'll figure out the permissions needed.

**Comment by pujavs** [comment]
@devrimyatar, reopening issue for KC Server URL changes. Detailed captured from chat
![image](https://github.com/JanssenProject/jans/assets/43700552/afd0dbbe-8eaa-4e2d-8110-c1c9de2dfc25)

**Comment by devrimyatar** [comment]
Implemented
