### ISSUE TITLE
fix(casa): unable to login casa getting error "authentication_session_invalid"

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#6796]
**Describe the bug**
unable to login casa getting error "authentication_session_invalid"

**To Reproduce**
1. install jans 1.0.21.nightly
2. complete device auth
3. after some time launch jans-casa
5.check jans tui session it is still there but cant login to jans-casa
**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/a7eeb230-a458-4107-b210-b6fcecf7f98e)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-DB mysql
jans1.0.21.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ugoenyioha** [comment]
I am running into this too. What's a good version to run that avoids this problem? 1.0.20?

**Comment by manojs1978** [comment]
please check with latest version 1.0.22
