### ISSUE TITLE
Add support for jmx exporter

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#682]
Integrate https://github.com/prometheus/jmx_exporter with the image giving the user the ability to scrap metrics via prometheus.

Ref: https://itnext.io/monitoring-distributed-jetty-servers-in-k8s-using-prometheus-and-grafana-7b02fe3506ad

**Comment by iromli** [comment]
@moabu I've been tinkering with Grafana + Prometheus agent to scrape metrics from auth-server.

Here's an example of successful integration (based on issue description):

![image](https://user-images.githubusercontent.com/231601/174132531-7ee42a57-1a9c-40cb-b965-0e1cd6b408a7.png)

**Comment by mecsys** [comment]
Hi Gluu Team,

Very nice feature!

I am testing on pre-production environment.

![image](https://user-images.githubusercontent.com/418571/184249974-2de0f699-0697-497c-b8b5-ab6036aa73df.png)

Best regards,
Isaac Mecchi - Sensedia' Cloud Architect
