### ISSUE TITLE
fix(jans-ce-setup): revert Admin UI installation option from Janssen Vm installer

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#691]
**Describe the bug**
Janssen is an open-source, community-governed project. There should not be an option in the Janssen Vm installer to install `Admin UI` which is Gluu Commercial Product.

**There should not be any code to install Admin UI using  Janssen Vm installer.**
Please revert the changes asked in the following tickets: 
1. https://github.com/JanssenProject/jans/issues/469
2. https://github.com/JanssenProject/jans/issues/302

**Note:** Please keep a backup of the changes done so that we can use it to create `install_gluu_flex.py` script (in GluuFederation github repo) to install Admin UI on top of Janssen installation. I will raise another ticket for this task.

**Comment by mbaser** [comment]
Done
