### ISSUE TITLE
Jans CLI: Logout

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#706]
The access token for the Jans CLI are saved in `/root/.config/jans-cli.ini` in the var name `access_token_enc`. There should be a feature for the admin to delete the access token from the CLI.

**Comment by mbaser** [comment]
Done
x removes token from config file

![Screenshot_2022-01-27_20-44-37](https://user-images.githubusercontent.com/6398752/151414690-4f5714b0-d4d8-47dd-9a77-9b9750ae6730.png)
