### ISSUE TITLE
fix(config-api): user edit error due displayName field

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7082]
![image](https://github.com/JanssenProject/jans/assets/43700552/a38a35ae-a2f6-49cb-b8f0-8e5b494fd90c)

**Comment by yurem** [comment]
According to error we are trying to use displayValue. Is it new attribute? We use displayName

**Comment by yurem** [comment]
Can you attach full stack trace. It's not clear if this JSON serialization or ORM issue
