### ISSUE TITLE
fix(jans): enable uma feature flag still not getting  .well-known configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7102]
**Describe the bug**

**To Reproduce**
1. install jans
2. enable feature flag form uma in properties
3. run https://manojs1978-pretty-hound.gluu.info/.well-known/uma2-configuration

**Expected behavior**
should get well-known configuration for fido
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/6449f765-5569-49c6-b1ed-45c2c16b0e96)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans1.0.21.nightly
DB opendj
**Smartphone (please complete the following information):**

**Additional context**

**Comment by yuriyz** [comment]
@manojs1978 did you wait 15min before trying ? You can simply restart AS (which means new configuration is definitely loaded).
If still does not work please attach jans-auth.log in trace log leve.

**Comment by yuriyz** [comment]
ok, I've just tried on my VM and see it is loaded correctly. Closing as not reproducible.

![image](https://github.com/JanssenProject/jans/assets/2013070/08473c4b-dc5e-482f-923c-321fcc339539)
