### ISSUE TITLE
feat (TUI): Print Client Summary

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#7119]
When we are asking a Jans admin to share the client config, it would be nice if there was a way to export all the client metadata into one file.  It would be nice if we had a field to "Export Summary" which gathered all the client config that has values, and writes it to a text file like `client_name.txt` (replace any spaces with `_`...). This file should be written to the filesystem.

![image](https://github.com/JanssenProject/jans/assets/3717101/91c737ff-216f-4ed3-8463-5af774023bca)

**Comment by devrimyatar** [comment]
@nynymike There is a way to save client information. On the client list, press key *d* , you will see json representation of client, you can save it by using *Export* button. See the following video

https://github.com/JanssenProject/jans/assets/6398752/acca5f76-08e4-4ce9-b435-52b1360bd87b

**Comment by nynymike** [comment]
already done

**Comment by nynymike** [comment]
There should be a hint in the bottom left of the corner: `d - View / Export JSON`
