### ISSUE TITLE
fix(config-api): status response value of attributes

### ISSUE THREAD

**Issue by jv18creator** [JanssenProject/jans#7200]
**Describe the bug**
Endpoint [/api/v1/attributes](https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/GluuFederation/oxAuth/master/docs/oxAuthSwagger.yaml#/operations/Attribute/get-attributes) is responding with status `INACTIVE` & `ACTIVE` but from the [spec Response example](https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml) the value of status should be `active` or `inactive`

![Screenshot 2023-12-25 at 5 18 17 PM](https://github.com/JanssenProject/jans/assets/64732692/4cc5397b-c5bb-4c14-be8c-92540259d574)

**Comment by pujavs** [comment]
@jv18creator fixed the issue via PR [7238](https://github.com/JanssenProject/jans/pull/7238)
![image](https://github.com/JanssenProject/jans/assets/43700552/5eb51513-b6a1-4d06-92c9-19a6ece30ad5)
