### ISSUE TITLE
feat(jans-linux-setup): drop support for MariaDB

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#7214]
JSON indexing is not supported by MariaDB and there are some missing json features.
- [x] Drop support for MariaDB
- [x] Install MySQL on SuSE as explained here https://dev.mysql.com/doc/mysql-sles-repo-quick-guide/en/

**Comment by moabu** [comment]
I'd like to know if anyone from our community is using MariaDB. We haven't been having a lot of requests for MariaDB. I'm not sure we have enough community requests that can make a case to overcome hardships of maintaining support for MariaDB

**Comment by devrimyatar** [comment]
In addition to JSON indexing, the following quey is not valid for MairaDB
```
This query is not supported in MaraiDB
> SELECT col->"$.mascot" FROM qtest;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>"$.mascot" FROM qtest' at line 1
```

**Comment by yurem** [comment]
Our ORM should work well with MariaDB. The only one issue is JSON indexes. Maria DB not allow to index JSON columns. But this not very big performance issue, I think because we rarely use JSON fields in filters.

**Comment by yurem** [comment]
if we will get any issue with JSON filter we can use child [tables ](https://github.com/JanssenProject/jans/issues/5778) once this will be implemented.
