### ISSUE TITLE
fix(jans-config-api): message feature difference in spec & api response

### ISSUE THREAD

**Issue by jv18creator** [JanssenProject/jans#7224]
**Describe the bug**
From the REST client, the response of `postgresConfiguration` object from `/api/v1/config/message` is different from the one mentioned in [spec](https://raw.githubusercontent.com/JanssenProject/jans/main/jans-config-api/docs/jans-config-api-swagger.yaml) 
![Screenshot 2023-12-28 at 12 54 33 PM](https://github.com/JanssenProject/jans/assets/64732692/05aaeca1-523d-446d-8bd7-bc904b5238a7)
![Screenshot 2024-01-01 at 10 30 12 AM](https://github.com/JanssenProject/jans/assets/64732692/0e4fb06c-602c-4cbf-8883-04f6ab2af8b9)

Req URL: `https://admin-ui-test.gluu.org/jans-config-api/api/v1/config/message`
HTTP Method: `GET`

**Comment by yurem** [comment]
@jv18creator Can you retest it in latest build?

**Comment by jv18creator** [comment]
Fixed! Thanks @yurem
