### ISSUE TITLE
fix(jans-tui): TUI is breaking when edit scope

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7241]
**Describe the bug**

**To Reproduce**
1. install jans 1.0.22.nightly
2. go to auth server > attribute
3. edit any attribute

**Expected behavior**
should not get any error
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/512d5801-c31f-4b4d-9209-30d25778b6ad)

**Desktop (please complete the following information):**
  - OS: ubuntu
-jans 1.0.22.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate with online installer:

![image](https://github.com/JanssenProject/jans/assets/6398752/b0187cb7-23f6-42fa-bb43-e456575bd193)
