### ISSUE TITLE
fix(jans-tui): unable to add property

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7242]
**Describe the bug**
unable to add property, not getting fields to add property

**To Reproduce**
1. install jans 1.0.22.nightly
2. go to property
3. click on add property

**Expected behavior**
should get fields to add new property

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/13a3ceb7-acd5-4fbb-bd80-99b4d4015b54)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.0.22.nightly
-db opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Unable to replicate with online installer

![property](https://github.com/JanssenProject/jans/assets/6398752/1a9fca8c-c8b3-4118-9a61-ebab58104f3b)
