### ISSUE TITLE
feat(jans-cli-tui): add new Transaction Token properties to TUI client panel

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#7261]
### Description

Client will have 3 new properties responsible to TxToken signing&encryption.

- tx_token_signed_response_alg
- tx_token_encrypted_response_alg
- tx_token_encrypted_response_enc

Properties are identical to what was implemented for Introspection Response [here](https://github.com/JanssenProject/jans/pull/6574/files).
New properties must be shown on screenshot as shown in this [ticket](https://github.com/JanssenProject/jans/issues/6382).

This ticket must be implemented AFTER following PR is merged to main.
https://github.com/JanssenProject/jans/pull/7212

**Comment by devrimyatar** [comment]
Implemented in https://github.com/JanssenProject/jans/pull/6574/files
