### ISSUE TITLE
fix(jans): jans config-cli.py output not matching the set value

### ISSUE THREAD

**Issue by ganesh-at-wiw** [JanssenProject/jans#7281]
**config-cli.py outputs wrong value for ACR**
`/opt/jans/jans-cli/config-cli.py --schema AuthenticationMethod` outputs wrong value for ACR as per doc or the value which is in effect.
Doc link https://docs.jans.io/v1.0.21/admin/config-guide/default-authentication-method-config/#update-default-authentication-method shows the default output should be `null`. But the output is `string`.

**To Reproduce**
1. Run  `/opt/jans/jans-cli/config-cli.py --schema AuthenticationMethod`
2. Output is: `string`

**Expected behavior**
Output should be either `null` or the value which is set.

**Outputs from command line**
```
root@test-casa:~# /opt/jans/jans-cli/config-cli.py --operation-id put-acrs --data /tmp/patch-default-auth.json
Server Response:
{
  "defaultAcr": "string"
}

root@test-casa:~# vi /tmp/patch-default-auth.json 
root@test-casa:~# /opt/jans/jans-cli/config-cli.py --operation-id put-acrs --data /tmp/patch-default-auth.json
Server Response:
{
  "defaultAcr": "otp"
}

root@test-casa:~# /opt/jans/jans-cli/config-cli.py --schema AuthenticationMethod > /tmp/patch-default-auth.json
root@test-casa:~# /opt/jans/jans-cli/config-cli.py --schema AuthenticationMethod
{
  "defaultAcr": "string"
}
```
**Desktop (please complete the following information):**
  - OS: Ubuntu 22.04

**Comment by devrimyatar** [comment]
You are requesting sample schema. It is correct, if you want to query **defaultAcr** you have to call config-api:

`/opt/jans/jans-cli/config-cli.py --operation-id=get-acrs`

Sample output

![image](https://github.com/JanssenProject/jans/assets/6398752/49094cb1-b7bf-4e95-b459-7dbabea0c7ae)
