### ISSUE TITLE
feat(jans-casa): support, so that /assertion/options, generates without passing user

### ISSUE THREAD

**Issue by Milton-Ch** [JanssenProject/jans#7356]
**Is your feature request related to a problem? Please describe.**
It is necessary, that the endpoint /assertion/options, can generate without passing a user. This is because passkey at the beginning, it is not necessary to pass a user.

**Comment by Milton-Ch** [comment]
Hi @yurem

Will it be necessary to create a new endpoint for this, something like /assertion/options/initial, or do we keep the same /assertion/options, but still generate, even if we do not pass the user field?

What do you think?

**Comment by yurem** [comment]
We already have SG endpoints for one step authentication. In this flow we not put user/password on first step. Here is sample data for this request: https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/sg/converter/AssertionSuperGluuController.java#L73

**Comment by yurem** [comment]
Same scenario for attestation flow: https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/sg/converter/AttestationSuperGluuController.java

**Comment by Milton-Ch** [comment]
@yurem I see that the setting for `super gluu` works very well.

But for this case, I need it to work for all assertion, not a specific `fmt`, all the existing ones (`android-key`, `android-safetynet`, `tpm`, etc.) work.

Hence my suggestion to make a new endpoint something like `/assertion/options/generate`.

**Comment by Milton-Ch** [comment]
@yurem

Can you please take a look PR: https://github.com/JanssenProject/jans/pull/7573.
If you think this is correct, I can start with the unit tests.
