### ISSUE TITLE
fix(jans-config-api): getting 500 Server Error while creating IDP using endpoint

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7396]
Describe the bug
getting Server Error while creating IDP using endpoint

To Reproduce

install jan 1.0.22.nighty
copy saml descriptor as metada file
run POST API create IDP
ex:
curl --location 'https://manojs1978-evident-catfish.gluu.info/jans-config-api/kc/saml/idp/upload' \
--header 'Content-Type: multipart/form-data' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer f0ba6a3a-71e6-461b-b177-2bed93b442ea' \
--form 'identityProvider="{
	\"name\": \"SAML_IDP_3\",
	\"displayName\": \"Test SAML IDP 3\",	\"description\": \"SAML IDP 3 created using Rest API\",
	\"realm\": \"jans-api\",
	\"enabled\": true
   
}";type=application/json' \
--form 'metaDataFile=@"/home/manoj/Documents/janssen/KC/metadata.xml"'

getting  500 server error
5. See error
```
{
    "cause2": "Failed to build search entries query. Key: &apos;trusted-idp&apos;, expression: &apos;doc.NAME = SAML_IDP_3&apos;",
    "cause1": "io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;trusted-idp&apos;",
    "servlet": "io.jans.configapi.plugin.saml.rest.ApiApplication",
    "cause4": "org.postgresql.util.PSQLException: ERROR: column doc.NAME does not exist\n  Position: 878",
    "cause3": "com.querydsl.core.QueryException: Caught PSQLException for select &quot;doc&quot;.&quot;addReadTokenRoleOnCreate&quot;, &quot;doc&quot;.&quot;jansSAMLspMetaDataFN&quot;, &quot;doc&quot;.&quot;singleLogoutServiceUrl&quot;, &quot;doc&quot;.&quot;displayName&quot;, &quot;doc&quot;.&quot;creatorId&quot;, &quot;doc&quot;.&quot;description&quot;, &quot;doc&quot;.&quot;inum&quot;, &quot;doc&quot;.&quot;storeToken&quot;, &quot;doc&quot;.&quot;jansValidationStatus&quot;, &quot;doc&quot;.&quot;idpEntityId&quot;, &quot;doc&quot;.&quot;providerId&quot;, &quot;doc&quot;.&quot;jansSAMLspMetaLocation&quot;, &quot;doc&quot;.&quot;postBrokerLoginFlowAlias&quot;, &quot;doc&quot;.&quot;jansSAMLidpMetaDataURL&quot;, &quot;doc&quot;.&quot;singleSignOnServiceUrl&quot;, &quot;doc&quot;.&quot;encryptionPublicKey&quot;, &quot;doc&quot;.&quot;jansSAMLidpMetaDataFN&quot;, &quot;doc&quot;.&quot;validateSignature&quot;, &quot;doc&quot;.&quot;jansValidationLog&quot;, &quot;doc&quot;.&quot;signingCertificate&quot;, &quot;doc&quot;.&quot;nameIDPolicyFormat&quot;, &quot;doc&quot;.&quot;jansSAMLidpMetaLocation&quot;, &quot;doc&quot;.&quot;trustEmail&quot;, &quot;doc&quot;.&quot;linkOnly&quot;, &quot;doc&quot;.&quot;firstBrokerLoginFlowAlias&quot;, &quot;doc&quot;.&quot;name&quot;, &quot;doc&quot;.&quot;jansEnabled&quot;, &quot;doc&quot;.&quot;jansSAMLspMetaDataURL&quot;, &quot;doc&quot;.&quot;jansStatus&quot;, &quot;doc&quot;.&quot;realm&quot;, &quot;doc&quot;.&quot;authenticateByDefault&quot;, &quot;doc&quot;.&quot;dn&quot;, &quot;doc&quot;.&quot;doc_id&quot;\nfrom &quot;public&quot;.&quot;jansTrustedIdp&quot; &quot;doc&quot;\nwhere &quot;doc&quot;.&quot;NAME&quot; = ?\norder by &quot;displayName&quot; asc",
    "cause0": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;trusted-idp&apos;",
    "message": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: &apos;trusted-idp&apos;",
    "url": "/jans-config-api/kc/saml/idp/upload",
    "status": "500"
}
```
Expected behavior
should able to create IDP and return status should be 2000
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/68027b41-d20e-4e5e-ae7c-fdc381e0bc0c)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.0.22.nightly
-DB pgsql

**Smartphone (please complete the following information):**

**Additional context**
[config.zip](https://github.com/JanssenProject/jans/files/13963451/config.zip)

**Comment by yurem** [comment]
Thank you for detailed issue description with logs.

According to the logs:
```
Caused by: 
org.postgresql.util.PSQLException: ERROR: column doc.NAME does not exist|  Position: 878
```

there is no `NAME` column in jansTrustedIdp

**Comment by pujavs** [comment]
`name` column exists in the model class -> https://github.com/JanssenProject/jans/blob/main/jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/model/IdentityProvider.java#L40

**Comment by yurem** [comment]
PostgreSQL column names are case-sensitive (when double-quoted)
We need to use names specified in tables defintion

**Comment by pujavs** [comment]
Fixed via PR [7409](https://github.com/JanssenProject/jans/pull/7409)
