### ISSUE TITLE
fix(jans-config-api): error in saving Boolean custom user attribute value using `/mgt/configuser`

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#7401]
**Jans Database:** postgres

**Error found in following API:** /mgt/configuser `POST`

**Steps to reproduce:**

1. Add new column `test` in `jansPerson` table of type boolean.
   `ALTER TABLE "test" ADD COLUMN "emailPromotion" BOOLEAN;`

2. Then create the attribute of `Data Type` boolean using TUI/Admin UI.
![image](https://github.com/JanssenProject/jans/assets/32794267/9603dccd-0c22-4ae6-8fa9-4567bbdafa53)

3. Then try to create a new user, adding the new added user claim with true/false value in it.

![image](https://github.com/JanssenProject/jans/assets/32794267/9707f47a-537d-4c4c-bd70-9a5a31a71da0)

You will get the following error on submission.

```
code: "500" message: "ERROR: column \"emailPromotion\"is of type boolean but expression is of type character varying\n Hint: You will need to rewrite or cast the expression. \n Position: 137"
```

**Comment by duttarnab** [comment]
[2024_01_17.jetty.log](https://github.com/JanssenProject/jans/files/13966808/2024_01_17.jetty.log)
[logs.zip](https://github.com/JanssenProject/jans/files/13966897/logs.zip)

logs

**Comment by pujavs** [comment]
1. Alter table 
![image](https://github.com/JanssenProject/jans/assets/43700552/9ef4f708-b335-4b71-b682-66a5536e5582)

2. Verify newly added column
![image](https://github.com/JanssenProject/jans/assets/43700552/5b1e3545-4b1f-4369-9031-5875752a7a14)

3. Verify before adding custom attribute
![image](https://github.com/JanssenProject/jans/assets/43700552/7669d181-b457-42b5-bd45-9a6f8345e573)

4. Add new attribute
![image](https://github.com/JanssenProject/jans/assets/43700552/bc5e2fed-bb8c-4a8e-b672-21aaed35685f)

5. Verify newly created attribute in DB
![image](https://github.com/JanssenProject/jans/assets/43700552/afc00f6a-dc58-4e27-b738-3065ef7f909b)

**Comment by duttarnab** [comment]
Hi @pujavs thanks for investing. We found the root cause of bug in admin-ui.
