### ISSUE TITLE
fix(jans-config-api): multiple users can be created with the same userId and email

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#7415]
**Jans Database:** postgres

**Error found in following API:** /mgt/configuser `POST`

**Steps to reproduce:**

Below request-body can be to create multiple users with the same userId and mail.  

{"userId":"arnab","mail":"arnab@gmail.com","displayName":"arnab","jansStatus":"active","userPassword":"arnab","givenName":"arnab","customAttributes":[{"name":"displayName","multiValued":false,"values":["arnab"]},{"name":"sn","multiValued":false,"values":["arnab"]},{"name":"middleName","multiValued":false,"values":["arnab"]}]}

Required result:

The userId and mail fields should be unique in the jansPerson table.

**Comment by pujavs** [comment]
**Analysis:** Verified this issue both on LDAP as well as PostgreSQL.
LDAP throws unique constraint violation whereas PostgreSQL backend does not. Request you to please check.
A unique attribute conflict was detected for attribute uid: value user2 already exists in entry inum=30a58d5d-1922-486e-91d7-05cd39c2fa06,ou=people,o=jans&apos;, ldapSDKVersion=6.0.8, revision=52bb41d333b13d7d21e684ff0fb6622f3c8059fa)
![image](https://github.com/JanssenProject/jans/assets/43700552/cc309b88-90d1-44a7-91f6-ee7f4b3f1fea)

Capturing discussion of the issue from chat
![image](https://github.com/JanssenProject/jans/assets/43700552/f6a3c3d1-74fc-4b9e-9913-1325d10a01f5)

**Comment by pujavs** [comment]
@yurem is any change required to be done by me for this issue?

**Comment by devrimyatar** [comment]
This issue was resolved 

![image](https://github.com/JanssenProject/jans/assets/6398752/386c30a4-0852-4347-ad2f-a29917740779)
