### ISSUE TITLE
fix(jans-config-api): unable to create TR using metadat file URL

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7428]
**Describe the bug**
unable to create TR using metadat file URL

**To Reproduce**
1. install latest jans 1.0.22.nightly with KC
2. create TR 
3. select metadata url and add descriptor URL  and save it

**Expected behavior**
shold not get any error and TR should get created

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/7000b196-4c43-4f3d-bca3-156d0468497d)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.0.22.nightly
DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

[config.zip](https://github.com/JanssenProject/jans/files/13985464/config.zip)

[metadata.xml.txt](https://github.com/JanssenProject/jans/files/13985565/metadata.xml.txt)

**Comment by pujavs** [comment]
@manojs1978 please attach metadata file which caused the error

**Comment by manojs1978** [comment]
added

**Comment by pujavs** [comment]
@manojs1978 , i am not able to replicate the issue, please see the video here https://www.loom.com/share/4298a36399104920bc48feb0614d4d08

**Comment by manojs1978** [comment]
@devrimyatar we have URL option in metadata file ,
please check .

**Comment by devrimyatar** [comment]
I were not be able to re-produce either

https://github.com/JanssenProject/jans/assets/6398752/af04ea73-90d8-4ec9-b013-9bb2f325dfbc

**Comment by pujavs** [comment]
Fixed, https://www.loom.com/share/26134804372f4b488ccbcaef4a9d3690
