### ISSUE TITLE
feat(jans-config-api): user is able to see the user claim on create/edit user form even if the claim is disabled

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#7446]
1. The disabled user claim should not be obtained using `/mgt/configuser` `GET` API (also in response of POST and PUT). 

**Note:** If the user claim has been disabled after assigning its value for one or more user then also API should not send the claim value for those users.

![Clipboard - January 19, 2024 6_02 PM](https://github.com/JanssenProject/jans/assets/32794267/816f968c-b271-4f93-a4aa-b3142d68aed9)
![Clipboard - January 19, 2024 6_03 PM](https://github.com/JanssenProject/jans/assets/32794267/d364179a-3e5f-43b7-a5bc-08c31ce00925)

**Comment by pujavs** [comment]
working on it

**Comment by pujavs** [comment]
Changes made to exclude the inactive claim from response. Note, no exception thrown if inactive claim in POST, PUT request.
PR for fix -> [7533](https://github.com/JanssenProject/jans/pull/7533)

**Comment by duttarnab** [comment]
Getting following error.
**API:** `GET`  `https://duttarnab-notable-sparrow.gluu.info/jans-config-api/mgt/configuser?limit=10`

![Clipboard - February 7, 2024 7_23 PM](https://github.com/JanssenProject/jans/assets/32794267/030b2fbf-50c1-4fc9-b731-325be4228a16)
