### ISSUE TITLE
fix(jans-setup): SAML is not installed with jans 1.0.22

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7494]
**Describe the bug**
SAML is not installed with jans 1.0.22

**To Reproduce**
1. install jans 1.0.22 with KC

**Expected behavior**
should get SAML installation

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/c0043df7-a4aa-4116-b774-d071d57dc792)
![image](https://github.com/JanssenProject/jans/assets/5729240/2fe42929-eac7-4684-8409-4000103f0072)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.0.22
DB mysql/pgsql/opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Can't replicate

![image](https://github.com/JanssenProject/jans/assets/6398752/35cab976-ed18-4439-8f08-eb9b9fd81ede)

![image](https://github.com/JanssenProject/jans/assets/6398752/0d61c608-9647-42d8-9de4-935c2e0ff3b4)
