### ISSUE TITLE
fix(config-api): startup issue for scope update

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7539]
DB: MySQL 
Issue: Config-api on startup throwing 503
Error: 
![image](https://github.com/JanssenProject/jans/assets/43700552/0aa6aa65-d4d6-4e26-b9bf-b432717c900c)

Logs:
[2024_01_24.jetty.log](https://github.com/JanssenProject/jans/files/14048321/2024_01_24.jetty.log)

**Comment by yurem** [comment]
In ApiProtectionService code which all this there is debug line:
```
            log.debug("Re-verify ConfigApiScope rsScope.getName():{} with rsScope.getInum():{} in DB - scope:{} ",
                    rsScope.getName(), rsScope.getInum(), scope);
```
Can you share this debug message?

**Comment by pujavs** [comment]
Closing this issue as the root cause was found and dataMigration issue opened separately -> https://github.com/JanssenProject/jans/issues/7559 

Capturing discussion from group chat: 
![image](https://github.com/JanssenProject/jans/assets/43700552/f12749f4-c57f-4a2a-a7f0-b3e048b1c107)
