### ISSUE TITLE
feat(docker): add support for using external secrets for initialization phase

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7547]
As we support several secret managers such as AWS, GCP, and Hashicorops Vault. Some industry and company compliance policies force all secrets to exist in one place. At the moment, we require the initialization secret params in our helm chart to be in kubernetes. This feature request is proposing the following:
1. Use the secret adapter for the secrets located [here](https://github.com/JanssenProject/jans/blob/main/charts/janssen/charts/config/templates/secrets.yaml) . I do suggest that we use one secret here which would be the `generate.json` as that contains the secrets listed . Anything missing should be added to `generate.json`. The priority would be to the mounted `generate.json` then if not found check the secret adapter set and attempt to pull from it. In the latter, the user would have to create the secret in the secret manager ahead of time. This would also clean up our helm charts. Forexample , we would no longer need to mount the secrets in the chart as the secret would be pulled from generate.json k8s secret since that would be the default adapter in helm.
2. The chart needs to be then updated to remove the secret mount and we need to add a flag to allow the user to skip creating the generate.json secret.

**Comment by iromli** [comment]
Point no. 2 is moved to https://github.com/JanssenProject/jans/issues/9508
