### ISSUE TITLE
fix: add Hashicorps Vault external secret manager 

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7548]
- [ ] Add settings appropriately in the helm charts  to pass https://github.com/JanssenProject/jans/blob/main/jans-pycloudlib/jans/pycloudlib/secret/vault_secret.py#L26
- [ ] Add missing doc https://docs.jans.io/v1.0.22/admin/kubernetes-ops/external-secrets-configmaps/

**Comment by iromli** [comment]
@moabu please note that Vault only used for storing secrets, not configmaps

**Comment by moabu** [comment]
Thanks @iromli . @misba7 please take note of that
