### ISSUE TITLE
fix(jans-cli-tui): device auth flow failing

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7574]
**Describe the bug**
device auth flow failing

**To Reproduce**
1. install jans 1.0.22.nightly
2. run device auth flow
2. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/76bfe936-8f3b-45ac-87bf-16c2140265f8)

**Desktop (please complete the following information):**
  - OS: ubutnu22
-jans 1.0.22.nightly
DB mysql

**Smartphone (please complete the following information):**

**Additional context**
[auth.zip](https://github.com/JanssenProject/jans/files/14082072/auth.zip)

**Comment by devrimyatar** [comment]
I were not be able to replicate.
