### ISSUE TITLE
fix: change jetty favicon with jans favicon

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7618]
load janssen favicon in place of jettys'

You can see this in your browser settings: 

[chrome://settings/content/all?searchSubpage=gluu.org&search=cookies](chrome://settings/content/all?searchSubpage=gluu.org&search=cookies)

**Comment by syntrydy** [comment]
@mustafa  Below are the steps to override the default jetty favicon. 
- From JETTY_HOME move into *lib* folder
- 'mkdir -p org/eclipse/jetty'
- Move the official Jans favicon into the folder created above(*org/eclipse/jetty*)
- Then run 'jar -uf jetty-server-VERSION.jar org/eclipse/jetty/favicon.ico' where VERSION is the current jetty version.
   eg. *jar -uf jetty-server-11.0.15.jar org/eclipse/jetty/favicon.ico*

I think we need this apply during the setup process.

**Comment by syntrydy** [comment]
@mustafa  Below are the steps to override the default jetty favicon. 
- From JETTY_HOME move into *lib* folder
- 'mkdir -p org/eclipse/jetty'
- Move the official Jans favicon into the folder created above(*org/eclipse/jetty*)
- Then run 'jar -uf jetty-server-VERSION.jar org/eclipse/jetty/favicon.ico' where VERSION is the current jetty version.
   eg. *jar -uf jetty-server-11.0.15.jar org/eclipse/jetty/favicon.ico*

I think we need this apply during the setup process.

**Comment by iromli** [comment]
This has been implemented in #8334 and #8361
