### ISSUE TITLE
fix(jans-auth): configuration changes not taking effect

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#7631]
Modifying values in `jansConfDyn` attribute under `ou=jans-auth,ou=configuration,o=jans` is not taking any effect after updating `jansRevision`

Only a jans-auth restart is picking the change

Reproducible in  ubuntu 22 (deb) package and online installer too. As an example, change the log level

I can provide creds for access

Logs  not showing anything relevant

**Comment by yurem** [comment]
Fixed
