### ISSUE TITLE
fix(jans-cli-tui): getting error when launching tui on suse

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7633]
**Describe the bug**
getting error when launching tui on suse

**To Reproduce**
1. install jans 1.0.22 suse package
2. launch TUI

**Expected behavior**
should able to launch TUI

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/7909341c-68f3-4c5f-8baf-a9c8b84caa5b)

**Desktop (please complete the following information):**
  - OS: suse 15 sp5
-jans 1.0.22
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Closed by https://github.com/JanssenProject/jans/commit/b3f6834683ccd306cf088f4a96d25c30212a335d
