### ISSUE TITLE
feat(jans-cli-tui): add information about  how to delete agama project in TUI

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7638]
**Is your feature request related to a problem? Please describe.**
like deployment details and project configuration,
we should have some information about how to delete agama project in TUI.

**Describe the solution you'd like**
add "press del button to delete project"

**Describe alternatives you've considered**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 @nynymike I will remove all hints on the bottom bar, but will just add only **Press F1** for help, will ti work?
![image](https://github.com/JanssenProject/jans/assets/6398752/d37b3ebd-34f1-4e1b-b779-cc85c13c994c)

**Comment by ossdhaval** [comment]
In that case, the bottom bar should say `Press F1 for Help`

**Comment by devrimyatar** [comment]
> In that case, the bottom bar should say `Press F1 for Help`

That is my plan.
