### ISSUE TITLE
fix(jans-cli): getting error when deploying agam project through Jans-CLI

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7639]
**Describe the bug**
 getting error when deploying agam project through Jans-CLI

**To Reproduce**
1. install jans 1.0.22
2. complete device auth
3. deploy agama project using command ex: /opt/jans/jans-cli/config-cli.py --operation-id post-agama-prj  --url-suffix name:"agama-pw.gama"
4. get project status using comand ex: /opt/jans/jans-cli/config-cli.py --operation-id get-agama-prj-by-name --url-suffix name:"agama-pw"
5.  See error

**Expected behavior**
should not get any error while deploying through cli

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/9668533f-9477-4adc-9b6d-af7c7a4318b8)
![image](https://github.com/JanssenProject/jans/assets/5729240/db7c3137-f50e-41d7-b1c3-7f9fd8c8a59f)

**Desktop (please complete the following information):**
  - OS: ububntu22
-jans 1.0.22
DB mysql

**Smartphone (please complete the following information):**

**Additional context**

project agama-pw
https://github.com/GluuFederation/agama-pw/releases/tag/v1.0.1

**Comment by devrimyatar** [comment]
@manojs1978 You should provide agama project file with argument `--data`, for example:

```
/opt/jans/jans-cli/config-cli.py --operation-id=post-agama-prj --url-suffix="name:test-project" --data=/mnt/data/agama/journey.zip 
Server Response:
{
  "message": "A deployment task for project test-project has been queued. Use the GET endpoint to poll status"
}
```

The term **server_error** is replaced by **message** in commit 9fe6837b631595adc6fd0dae8ed9003a65ddcdd8
