### ISSUE TITLE
fix(jans-cli-tui): unable to add new admin ui permission

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7650]
**Describe the bug**
unable to add new admin ui permission

**To Reproduce**
1. install flex 5.0.22.nighlty
2. complete device auth flow
3. go to config script admin ui permission
4. create new permission ex:  https://jans.io/oauth/config/attributes.append
5. See error

**Expected behavior**
should able to create new permission

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/06bb0e51-2f70-4cae-a49e-7d9fe923595f)

**Desktop (please complete the following information):**
  - OS: ubuntu 22
-flex 5.0.22.nighlty
DB- pgsql
**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 I can't replicate, please re-test.


https://github.com/JanssenProject/jans/assets/6398752/fd5639a8-80ee-4489-9268-a55ab009dd44

**Comment by manojs1978** [comment]
@devrimyatar 
this is for adminui permissions not for creating role,
Please check below 

https://github.com/JanssenProject/jans/assets/5729240/ebc7f7e8-be73-466f-9f15-949194c1fb2b

**Comment by ossdhaval** [comment]
This issue is specific to Gluu Flex (downstream for Jans). It better be raised for Flex and not in Jans repo.
