### ISSUE TITLE
fix(jans-cli-tui): unable to delete admin ui role

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7652]
**Describe the bug**
unable to delete admin ui role

**To Reproduce**
1. install flex 5.0.22.nightly
2. add new admin ui role
3. check available fields while creating admin ui
4. delete newly created permission
5. See error

**Expected behavior**
should able to create and delete admin ui permission

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/85883ab1-95a1-4e12-90ae-39fe5845bb62)
![image](https://github.com/JanssenProject/jans/assets/5729240/a522879e-66ba-4d7f-89a5-3e2795f57361)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - flex 5.0.22.nightly
  - DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This is not error. It says "Set deletable" flag.
![image](https://github.com/JanssenProject/jans/assets/6398752/f213c5c0-2b27-4650-b6ca-bb1a6e2fc05d)

**Comment by manojs1978** [comment]
@devrimyatar 
i am not able to see this deletable option for role
could you please check on pgsql
![image](https://github.com/JanssenProject/jans/assets/5729240/da52b834-3d99-475b-afdc-74e238b46d69)
