### ISSUE TITLE
feat(CLI/TUI): provide ability to add Jans Keycloak Link configuration to Janssen Server

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#7667]
As discussed in the [chat](https://chat.gluu.org/group/service_link?msg=gXDyskQK8bnowSQig), currently, we have to manually add Keycloak configuration to the Janssen data store (LDAP/DB). This process is not user friendly and it is error-prone. 

This feature request is to provide options/screens in CLI and TUI so that the admin can easily update the configurations for Jans Link static and dynamic config.

**Comment by devrimyatar** [comment]
@pujavs I think we don't have a plugin for jans-keycloak-link for config-api. I need a jans-config-api endpoint to be able to implement this issue.

**Comment by devrimyatar** [comment]
@pujavs This endpoint will modify **jansConfDyn** property of dn **ou=jans-keycloak-link,ou=configuration,o=jans**
Setup writes content of this file https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jans-keycloak-link/jans-keycloak-link-config.json

**Comment by pujavs** [comment]
Changes via PR [7794](https://github.com/JanssenProject/jans/pull/7794)

**Comment by ossdhaval** [comment]
> @pujavs I think we don't have a plugin for jans-keycloak-link for config-api. I need a jans-config-api endpoint to be able to implement this issue.

We have just completed the config-api changes. To close this issue, we need changes in the TUI/CLI as well. Reopening this issue.
