### ISSUE TITLE
fix(auth-server-key-rotation): Key rotation breaks when jansAppConf[jansConfWebKeys] col exceeds ~65k characters in MySql.

### ISSUE THREAD

**Issue by saernz** [JanssenProject/jans#7675]
The kubernetes auth-server-key-rotation fails eventually as the data in the `jansAppConf` table in the `jansConfWebKeys` column is truncated as it exceeds the storage capacity of the data type being used in MySql, which then causes errors when trying to load the json value. This causes the auth server and config api to go down and subsequent key rotations fail.

I suspect this happens as the previous keys that haven't expired will be merged in with the new keys, this must at times exceed the storage capacity of the "TEXT" type that is being used for the jansConfWebKeys column. In the logs I get an error pointing to: https://github.com/JanssenProject/jans/blob/8f5d6a94817d96ed9cda570bd685d5e24201c4eb/docker-jans-certmanager/scripts/auth_handler.py#L353 with the error message:
```
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 65304 (char 65303)
```
I have the config for auth-server-key-rotation job currently set at the default:
- interval:48
- key-strategy:NEWER
- privkey-push-delay:0
- privkey-push-strategy:NEWER

I suspect my MySql server has sql mode not set to strict or else the code at: https://github.com/JanssenProject/jans/blob/8f5d6a94817d96ed9cda570bd685d5e24201c4eb/docker-jans-certmanager/scripts/auth_handler.py#L410 would of worked. As sql mode is not explicitly set to strict in the sql session an error is not returned when the TEXT col is automatically truncated by the sql engine and the num of rows changed still remains 1 which means the code to restore the backup is never ran as no error is detected.

**To Reproduce**
At the moment I'm not 100% sure of the steps to reproduce, other than I have at times ran manual key rotations while testing, so this has probably increased the amount of keys which have not reached their expiry and pushed the size of the json field over the storage capacity available for the column when they get merged. That being said, I haven't ran many manual key rotations (by manually running the k8s job), and I would expect there should be enough storage capacity for these occasions.

**Fix ideas**
I think this could easily be fixed by changing the data type of the jansConfWebKeys column to a MEDIUMTEXT or LONGTEXT so there is extra capacity for these occasions. I think it is set here: https://github.com/JanssenProject/jans/blob/cf5708654fa4f76e1bfe98f174eda43f0eaa28c7/jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json#L127

I think to make the code checks work properly, that when the update is performed here: https://github.com/JanssenProject/jans/blob/8f5d6a94817d96ed9cda570bd685d5e24201c4eb/docker-jans-certmanager/scripts/auth_handler.py#L166 that the code should explicitly set the session to a strict SQL mode or we would get unexpected behaviour if the engine automatically truncates the json and doesn't throw an error. This might require a change further down in https://github.com/JanssenProject/jans/blob/cf5708654fa4f76e1bfe98f174eda43f0eaa28c7/jans-pycloudlib/jans/pycloudlib/persistence/sql.py so we can set the SQL mode to strict for the session.

Another possibility is after storing the new config that the code attempts to load the new value and parse the json to ensure it is valid, then we'd still have the option to rollback if parsing the new config value fails.

I think there are a few problems to be addressed:
- Global SQL mode is being assumed to be strict, which causes fail safes to not work when the sql engine automatically truncates the TEXT col resulting in corrupt data.
- Not enough storage capacity is available for occasions when manual key rotations are performed so we probably need to use a larger data type.

**Additional context**
- Using janssen charts in k8s environment.
- MySQL, with strict mode off at the global level.

**Current work around**
- Set `jansConfWebKeys` data type to LONGTEXT in your `jansAppConf` table.
- Run `kubectl get -n jans secret/cn -o jsonpath='{$.data.auth_openid_key_base64}' | base64 -d | base64 -d` to get the uncorrupted keys. This assumes a k8 environment with default config.
-  Update your `jansConfWebKeys` column with the data from the previous step.
- Run a manual key rotation if the keys obtained previously are likely to be expired.

**Comment by iromli** [comment]
Hi @saernz thanks for the report. We will try to reproduce it first.

**Comment by iromli** [comment]
@saernz Just want to inform you about the patches we are working on.

1. `certmanager` will handle corrupted keys by deleting them and re-generate new ones.
2. `jans-pycloudlib` will enforce strict sql_mode while connecting to MySQL.

**Comment by saernz** [comment]
Awesome that is great! That will definitely stop the keys from getting corrupt. I wonder if the `jansConfWebKeys` col needs to be updated to MEDIUMTEXT or LONGTEXT as well? The above fixes should stop the data from being corrupted and make sure things error when they should, but the core issue was this column is too small for certain use cases. Possibly this could just be left to user preference, though with the default cert rotation being set to 48 hours on a new install we might need a bit more head room, especially if people are going to test the cert rotation functionality before rolling out to a production environment by running manual cert rotations.
Thanks for your help. Sorry I don't have any time to make some PRs myself.

**Comment by iromli** [comment]
@saernz the new key-rotation image should limit the keys around max. 36 keys. We can re-open this issue if we need to increase the size of jansConfWebKeys column in MySQL.
