### ISSUE TITLE
feat (jans-lock): Create `setup-lock.py` script to install Jans Lock Client Stub

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#7689]
If you are a application developer who wants to use Jans Lock for authorization, it would be convenient if we had a quick and easy way to install only the Jans Lock client and OPA.

**Comment by yurem** [comment]
This setup should do next:
1. Ask DB connection details to access CE DB. Lock reads configs from DB
2. If there is no Lock config in DB it should render it.
3. Ask which message server Lock should use: PostgreSQL/Redis and prompt user to enter details.
4. Install Lock jetty instance.
5. Install OPA.

In point 3 first priority is PostgreSQL

**Comment by devrimyatar** [comment]
When we install lock-server on another machine, **jansMessageConf** is read from db. Hence it was written at jans install time, and hostname of **connectionUri** for **postgresConfiguration** is **localhost**, remote jans-lock client can not connect to pgsql server:

```
jansdb=> select "jansMessageConf" from "jansAppConf" where dn='ou=configuration,o=jans';
                         jansMessageConf                         
-----------------------------------------------------------------
 {                                                              +
   "messageProviderType": "POSTGRES",                           +
   "postgresConfiguration": {                                   +
     "connectionUri": "jdbc:postgresql://localhost:5432/jansdb",+
     "dbSchemaName": "public",                                  +
     "authUserName": "jans",                                    +
     "authUserPassword": "FE0hN/uGxe0sM2Ap+38bRg==",            +
     "messageWaitMillis": 100,                                  +
     "messageSleepThreadTime": 200                              +
   },                                                           +
   "redisConfiguration": {                                      +
     "servers": "localhost:6379"                                +
   }                                                            +
 }                                                              +
 
(1 row)

jansdb=> 
```

@yurem 
I propose a solution as follows:
When jans-lock server is started, it shoud first look `/etc/jans/conf/jans-message-conf.json`, if there is such a file load configuration form this file, if not load configuration from db.
