### ISSUE TITLE
feat(jans-cli-tui): Show Agama Config if present

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#7782]
Exporting the config is not that convenient... it would be better to just displahy the config in the project details on this screen:

![Screen Shot 2024-02-19 at 3 34 22 PM](https://github.com/JanssenProject/jans/assets/3717101/5e72921c-c15b-4724-9fae-b04a8376f570)

**Comment by devrimyatar** [comment]
So the following options will be removed

![image](https://github.com/JanssenProject/jans/assets/6398752/11fc4642-46a1-4bc2-823b-59aa2ec132d6)
