### ISSUE TITLE
fix(jans-cli-tui): unable to create new attribute

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7784]
**Describe the bug**
unable to create new attribure

**To Reproduce**
1. install jans 1.1.0.nightly
2. launch tuo
3. create new attribute with mendetory fields

**Expected behavior**
shoudl not get any error while createing attribute

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/872c47cd-b659-48f8-87ca-0ed077b1b3d9)

**Desktop (please complete the following information):**
  - OS:ubuntu22
-jans 1.1.0.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 
This is not a bug. To create attrbiute, you need to create associated schema in opendj. 
Here is related document in:
https://gluu.org/docs/gluu-server/4.0/admin-guide/attribute/#custom-attributes
