### ISSUE TITLE
feat(jans-cconfig-api): user searching fields

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#7803]
Explained here: https://github.com/JanssenProject/jans/issues/7743#issuecomment-1956204406
When searching user, config-api should also look fields **givenName** and **sn**

**Comment by pujavs** [comment]
@devrimyatar, implemented this change via PR [7979](https://github.com/JanssenProject/jans/pull/7979)

**Comment by devrimyatar** [comment]
Implemented
