### ISSUE TITLE
chore: upgrade javascript libraries to newer versions in HTML files

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#7835]
Upgrade and remove JavaScript libraries as per [this](https://github.com/JanssenProject/jans/discussions/7117#discussioncomment-7947589) discussion.

**Comment by duttarnab** [comment]
We are re-opening this issue as we have the following comments from the customer:
(We need to use bootstrap of version  4.3.1)

```
Hi Mohib,

We recently conducted another penetration test and found that the vulnerable version of the Bootstrap v4.0 library is still being used in Gluu Jans-auth version v1.1.3.

Please see the attached screenshot, Gluu_Flex_11.JPG, for the request and response. You can see that with /jans-auth/js/bootstrap.min.js, the response still indicates Bootstrap v4.0.0.

Regards,

Longinus Chan
```

**Comment by mjatin-dev** [comment]
@duttarnab @jgomer2001 

I updated the bootstrap.min.css and bootstrap.min.js files to the latest version (v5.3.3). Below are the required class updates, as well as changes to other files like popper.js.

**Dropdown Alignment**
Changed dropdown-menu-right to dropdown-menu-end to align with Bootstrap 5.3's class for right-aligned dropdowns.

**Spacing Classes**
Replaced spacing classes like pr1, pl2, pr3, pv1, etc., with Bootstrap 5 utilities, such as ps-2, pe-3, and py-1.

**Font Size**
Updated font sizes using Bootstrap 5’s utilities like fs-7, fs-6, and fs-2 for better control over text sizing.

**Display Classes**
Replaced dn and di-ns with d-none and d-md-inline for responsive visibility.

**Button Styles**
Added Bootstrap 5’s color utility text-secondary and replaced gray hover-dark-gray with Bootstrap's color classes for consistent styling.

**Rounded Borders**
Updated rounded to rounded-circle for the user image and rounded-1 for dropdown styling.

**Shadow and Borders**
Adjusted classes to shadow-sm and border-0 for subtle shadows and borderless dropdowns, achieving a clean design.

**Width Classes**
Replaced miw-2r with min-w-50 and used w-100 to ensure consistent dropdown width scaling.

**Note**
1) I made these updates in the header.zul file, so please review those changes as well branch - jans-casa-7835.
2) To streamline testing, could you suggest a setup process for running jans-casa locally? This would allow for local testing without needing to upload the build repeatedly.
