### ISSUE TITLE
fix(saml): error in saving TR with samlMetadata

### ISSUE THREAD

**Issue by jv18creator** [JanssenProject/jans#7873]
**Describe the bug**
After testing #7523 changes, getting 500 exception on admin-ui-test with below payload.
If I remove the `samlMetadata` obj from req. body, then I get success.

**To Reproduce Use below info**
URL: `https://admin-ui-test.gluu.org/jans-config-api/kc/saml/trust-relationship/upload`
Req Body
```
{
    "enabled": false,
    "name": "test",
    "displayName": "dtest",
    "description": "desc",
    "spMetaDataSourceType": "uri",
    "spMetaDataFN": "https://mail.google.com/mail/u/0/",
    "releasedAttributes": [],
    "rootUrl": "",
    "adminUrl": "",
    "surrogateAuthRequired": false,
    "spLogoutURL": "",
    "samlMetadata": {
        "nameIDPolicyFormat": "urn:mace",
        "entityId": "http://localhost:4100",
        "singleLogoutServiceUrl": "http://localhost:4100"
    }
}
```

**Expected behavior**
Trust-Relation should be created using above mentioned payload.

**Screenshots**
![Screenshot 2024-02-28 at 2 08 26 PM](https://github.com/JanssenProject/jans/assets/64732692/5dbaee0e-8117-417f-a2d3-da0a9f1efefe)

**Additional context**
DB type: **postgres**

**Comment by jv18creator** [comment]
Hi @pujavs we have deployed https://jenkins.jans.io/maven/io/jans/jans-config-api/plugins/kc-saml-plugin/1.1.0-SNAPSHOT/kc-saml-plugin-1.1.0-SNAPSHOT-distribution.jar but still facing the error. could you please check?

**Comment by pujavs** [comment]
@jv18creator change was done yesterday and would be available in todays morning nightly build.
 It seems that you tested with yesterday's nightly build which would not have the code reflected.
 I installed todays nightly build and can see t he change. Please test with todays build

**Comment by jv18creator** [comment]
thanks @pujavs changes are reflected and working.
