### ISSUE TITLE
bug(jans-config-api): TrustRelationship API does not properly store file name of metadata files

### ISSUE THREAD

**Issue by uprightech** [JanssenProject/jans#7874]
The trust relationship API in it's current form , specifically the endpoints responsible for trustrelationship creation, do not store the metadata file uploaded properly. At least it's filenames.

## Steps to reproduce 
1. Either from an API client or from jans-config-api , create a new trust relationship specifying as metadata location `file`
2. Navigate from the command line to `/opt/idp/configs/keycloak/sp`. 
3. The metadata file is stored in the format `temp_metadata<displayname>_sp-metadata.xml<uuid>` where `<uuid>` is some 
    6-digit UUID.
4. None of the attributes (specifically `jansSAMLspMetaDataFN`) contain the generated filename, making it impossible to map and retrieve a metadata file for a specific client.

## Suggested fix 
1. Store the metadata file in the directory `/opt/idp/configs/keycloak/sp/`
2. Store the metadata file in the format  `<trustrelationship_inum>_sp-metadata.xml` . Where `trustrelationship_inum` is the inum of
    the trustrelationship. 
3. Store the generated file name in the `jansSAMLspMetaDataFN` attribute. It can then used later to retrieve the metadata file

**Comment by pujavs** [comment]
@uprightech we have two sub folder under ``/opt/idp/configs/keycloak`, namely `temp_metadata` and `metadata`
Is it alright if the file is stored in   `/opt/idp/configs/keycloak/sp/temp_metadata`?

**Comment by pujavs** [comment]
@uprightech, Implemented the change wrt file name. Please verify and revert in-case any change is required.
Fixed this issue via PR#[7894](https://github.com/JanssenProject/jans/pull/7894)
![image](https://github.com/JanssenProject/jans/assets/43700552/4a465221-8213-482e-a82a-dd1acd419353)
![image](https://github.com/JanssenProject/jans/assets/43700552/ad0ddc6c-03da-40d4-a03d-d62738b86f22)

**Comment by pujavs** [comment]
Capturing review comment by @uprightech
![Uploading image.png…]()

**Comment by pujavs** [comment]
@uprightech i have done the changes to accept only FILE and MANUAL as SPMetaDataSourceType.
If SPMetaDataSourceType is `FILE` then only `spMetaDataFN` is populated and manual elements for SPMetaData are null.
If SPMetaDataSourceType is `FILE` then `spMetaDataFN` is not set and manual elements should be available

PR for same is [7930](https://github.com/JanssenProject/jans/pull/7930)
