### ISSUE TITLE
feat(jans-config-api): add assertion consumer service url option for manual Saml SP configuration

### ISSUE THREAD

**Issue by uprightech** [JanssenProject/jans#7876]
Add the ability to specify at least one assertion consumer service url. 
Assertion consumer services are endpoints on the SP where the IDP sends saml assertions and are used by the former to establish an authentication session. 
For now , we should be able to specify one of the following:
- An ACS supporting HTTP GET binding. Let's call the attribute that will hold it's value `jansAttributeConsumerServiceGet`
- An ACS supporting HTTP POST binding. Let's call the attribute that will hold it's value `jansAttributeConsumerServicePost`

**Comment by pujavs** [comment]
@uprightech, can i request you to please share valid metadata file with these values.

**Comment by pujavs** [comment]
Capturing review comment by @uprightech 

![image](https://github.com/JanssenProject/jans/assets/43700552/ceb0c07e-613e-455f-90f7-d34c1e9ad501)

**Comment by pujavs** [comment]
@uprightech 
Changes done to accept only `FILE` and `MANUAL` as SPMetaDataSourceType.
If SPMetaDataSourceType then
