### ISSUE TITLE
feat(config-api): spec should have error response body

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7913]
For clients to use and display error message, swagger spec should have response body foe errors as well.

Requested by admin-ui team. Refer Issue [1593](https://github.com/GluuFederation/flex/issues/1593#issuecomment-1970992545)

**Comment by pujavs** [comment]
Fixed via PR [7930](https://github.com/JanssenProject/jans/pull/7930)

**Comment by duttarnab** [comment]
Hi @pujavs 

for bad password error should be 
![image](https://github.com/JanssenProject/jans/assets/32794267/abfb70e2-8f8c-4e3c-ab64-a002310ef914)
But now it is
![image](https://github.com/JanssenProject/jans/assets/32794267/d1847eb0-aa3a-4ed8-b53a-844d73f85e1f)

**Comment by duttarnab** [comment]
Another thing is when an exception is caught the response body is not returned. 

https://github.com/JanssenProject/jans/blob/main/jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java#L177

The error response body should be returned.  See

https://github.com/JanssenProject/jans/blob/main/jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java#L68-L71

https://github.com/JanssenProject/jans/blob/main/jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/adminui/AdminUIResource.java#L78-L90

**Comment by pujavs** [comment]
checking this

**Comment by pujavs** [comment]
Fixed via PR [7979](https://github.com/JanssenProject/jans/pull/7979)
![image](https://github.com/JanssenProject/jans/assets/43700552/65a40582-d9fc-4e35-a186-52de27e24426)

**Comment by pujavs** [comment]
@duttarnab, this seems to be fixed, kindly confirm

**Comment by duttarnab** [comment]
Yes this issue fixed. Kindly check this related issue https://github.com/JanssenProject/jans/issues/8034
