### ISSUE TITLE
feat(documnt-store): should support document for all types required for jans asset mgt

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7917]
Jans custom asset can have jar, css, images of different format, readme. txt, lib, ftlh. js, json , .flow 
Document Store needs to support these

Parent issue: [2419](https://github.com/JanssenProject/jans/issues/2419)
@moabu, request you to please add to the requirement of assets to support is missing

**Comment by yurem** [comment]
We can extend DocumentStore and add new methods:

```
	/**
	 * Save document into store
	 */
	boolean saveBinaryDocument(String path, byte[] documentContent, List<String> moduleList) throws WriteDocumentException;

	/**
	 * Save document stream into store
	 */
	boolean saveBinaryDocumentStream(String path, InputStream documentStream, List<String> moduleList) throws WriteDocumentException;

	/**
	 * Load binary document from store
	 */
	byte[] readBinaryDocument(String path);

	/**
	 * Load binary document from store as stream
	 */
	public InputStream readDocumentAsStream(String path) ;

```

**Comment by yurem** [comment]
In LocalDocumentStore we need to implement this too. These will be generic file operation. In JcaDocumentStoreProvider we can throw UnsupportedOperationException because we will deprecate this provider in future.

**Comment by yurem** [comment]
@pujavs since DocumentStore not know data type we need to call method to store files in text/plan and binary formats based on source type.

**Comment by yurem** [comment]
Implemented
