### ISSUE TITLE
feat(documentstore): should throw relevant exception rather than digest the exception

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7919]
**Describe the bug**

- Parent issue: [2419](https://github.com/JanssenProject/jans/issues/2419)
- Discussion chat [thread] (https://chat.gluu.org/group/service_config_api?msg=rYXXDq4ihP92W67Ng)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yurem** [comment]
According to @pujavs "...Right now methods return boolean making it difficult to calling client to understand the issue."

**Comment by yurem** [comment]
@shekhar16 LocalDocumentStore and DBDocumentStore should throw WriteDocumentException and DocumentException with parent exception. Both exceptions should extends RuntimeException. We don't need to add them to DocumentStore methods declarions

**Comment by shekhar16** [comment]
code has been merged closing this ticket. Please let me know if anything needed.
