### ISSUE TITLE
fix(jans-config-api): error in creating SP in tui

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7927]
**Describe the bug**
getting error in creating SP in tui.
Save failed: Status 400 - {"code":"OCA001","message":"A required attribute is missing.","description":"The attribute Name is required for this operation
"}    

**To Reproduce**
1. install jans 
2. create IDP
3. use sp metadata file from IDP created to create service provider in tui

**Expected behavior**
should able to create SP in tui

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/6afbed48-4337-4c54-aeb5-e518e41f679a)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version22
  - jans 1.1.0.nightly
  - DB pgsql
  - 

**Smartphone (please complete the following information):**

**Additional context**

[log.zip](https://github.com/JanssenProject/jans/files/14462196/log.zip)

**Comment by pujavs** [comment]
@devrimyatar request you to please check this issue as communicated via `https://chat.gluu.org/group/service_config_api?msg=ajwH7Pryg6EBSetJr` clientID is now name
