### ISSUE TITLE
fix(jans-cli-tui): new attribute creation getting error

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7938]
**Describe the bug**

**To Reproduce**
1. install jans 1.1.0.nighlty
2. create new attribure
3. See error

**Expected behavior**
should not get any error while creating attribute

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/fbce2579-af6c-465d-a184-223e64dd2528)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-DB opendj
-jans 1.1.0.nighlty

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
THIS IS NOT ISSUE.
See https://gluu.org/docs/gluu-server/4.0/admin-guide/attribute/#add-the-attribute-to-ldap
