### ISSUE TITLE
perf(jans-pycloudlib): handeling secret versioning

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#7944]
**Describe the bug**
The secret class currently for google does not compare the existent data in the secret and hence keeps creating new versions each time the secret class is called. This results in very high number of active versions held in the secret manager. This causes huge costs on the end user as the versions are not intuitively being destroyed or disabled. 

**Expected behavior**

Two things need to be done on this side:
1. Only create a new version if new info is entering the secret . This does endure an API call but keeps the secret clean.
2. Disable the old secret once the new secret version has been posted or limit the number of active secrets to `5`.

**Additional context**
Current workaround is to execute the following :

```bash
#!/bin/bash
gcloud secrets versions list flex-secret --filter="state = enabled" --filter="createTime < '2024-03-02'" | grep "NAME:" | tr -d "NAME: " > versions_to_disable.txt
while read -r line; do
  gcloud secrets versions destory "$line" --secret=flex-secret --quiet
done < "versions_to_disable.txt"
```

**Comment by iromli** [comment]
@moabu The following TODOs have been applied in a PR.

> Two things need to be done on this side:
>
> 1. Only create a new version if new info is entering the secret . This does endure an API call but keeps the secret clean.
> 2. Disable the old secret once the new secret version has been posted or limit the number of active secrets to 5.

I have concern about no. 2 (disabling old secret versions). The new changeset will keep 5 latest versions and automatically disable the rest of enabled versions. In this disabling scenario, bottleneck could happen if there are many enabled versions in current setup.

Perhaps we can set the *disabling versions* feature as inactive with logs on how to activate and the impact of this new feature (it can be also mentioned in docs only). This gives time to user to manually disable versions (if they have lots of enabled versions) before activating the feature.

Your feedback is appreciated.

**Comment by moabu** [comment]
Hey @iromli .

Yes due to the possible high number of versions this makes perfect sense. We should just include the workaround for any setup that has 50 versions and higher so the user runs it manually via the command provided :

```
#!/bin/bash
gcloud secrets versions list flex-secret --filter="state = enabled" --filter="createTime < '2024-03-02'" | grep "NAME:" | tr -d "NAME: " > versions_to_disable.txt
while read -r line; do
  gcloud secrets versions disable "$line" --secret=flex-secret
done < "versions_to_disable.txt"
```

**Comment by moabu** [comment]
We have made a slight mistake in that we have to destroy the secret version in order for it not to be charged instead of disabling it 

```
#!/bin/bash
gcloud secrets versions list flex-secret --filter="state = enabled" --filter="createTime < '2024-03-02'" | grep "NAME:" | tr -d "NAME: " > versions_to_disable.txt
while read -r line; do
  gcloud secrets versions destroy "$line" --secret=flex-secret --quite
done < "versions_to_disable.txt"
```
