### ISSUE TITLE
fix(jans-cli-tui): getting error display name required when adding new IDP 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7952]
**Describe the bug**
getting error display name required when adding new IDP 

**To Reproduce**
1. install jans 
2. add new IDP
3. add fields except display name

**Expected behavior**
should redmark mendatory fields

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/7fb4829e-f5d8-4d4a-82f4-d3b0c5670325)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.0. nightly
-D B mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Closed by commit https://github.com/JanssenProject/jans/commit/aff924650d16ebf002b5ee417cf210e6b1620d1e
