### ISSUE TITLE
fix(casa): incorrect link to the docs

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#7957]
The `docs` link on Casa page below doesn't lead to docs, but rather just reopens the same page.

![image](https://github.com/JanssenProject/jans/assets/343411/e5c4ec5e-aa2e-42ed-9833-3d152f0c4fd5)

To reproduce:
- On a fresh Janssen installation
- Open Casa: `https://<host>/jans-casa`
- login using admin credentials
- click on `administration console`
- click on `enabled authentication methods`
- The page show above will appear
- click on `docs` link

Observation:
Click on this link will just open a tab with the same Casa page

Expected output:
The link should take the user to [this page in the documentation](https://docs.jans.io/v1.0.22/casa/administration/admin-console/#enabled-authentication-methods)

**Comment by KyleChaukccs** [comment]
Hi @ossdhaval and @moabu,  

![image](https://github.com/user-attachments/assets/b7bb867b-8bcc-4476-a80e-ba7e4cfcd631)

Do I replace the # with the [link]( https://docs.jans.io/v1.0.22/casa/administration/admin-console/#enabled-authentication-methods?) hardcoded? My concern is this link can be invalid in the future as the URL is version-dependent. Are there any existing practices that the core team has that I should follow instead of hardcoding the link?

**Comment by ossdhaval** [comment]
@KyleChaukccs I am checking on what you proposed. Stay tuned.

**Comment by ossdhaval** [comment]
We can use the link that points to the latest docs. i.e HEAD. This link will not change. Downside is that the link doesn't point to the corresponding release's documentation. 

https://docs.jans.io/head/casa/administration/admin-console/#enabled-authentication-methods

This problem is taken care of for the Janssen main docs by the automation using the [release placeholder](https://docs.jans.io/head/CONTRIBUTING/#referencing-janssen-project-release-in-documents). But the change in question here is in the code base, which is not covered by the automation.

@moabu What is your view about expanding release placeholder replacement to entire codebase instead of just the `docs`.

**Comment by moabu** [comment]
Thats an interesting point. What I’m a little worried about is possible code syntax issues which can break the packages . In the above example there wouldn’t be any effect. Docs are relatively safe compared to code changes. 

 I think we should in a PR expand the list and see the files that may be affected and move from there.

**Comment by ossdhaval** [comment]
@moabu May be we should expand it on a need basis. For example, with the current issue we see a need to cover `*.properties` files under placeholder replacements. This can help us avoid unnecessary side-effects.
