### ISSUE TITLE
feat(ui):  SAML Trust Relationship UI

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7968]
SAML Trust Relationship UI for calrity

Screens for: `/jans-config-api/kc/saml/trust-relationship/upload` POST/PUT

Config Properties JSON as follows
{
    "enabled": false,
    "name": "testd_8",
    "displayName": "dtest_8",
    "description": "desc_8",
    "spMetaDataSourceType": "MANUAL",
    "rootUrl": "",
    "surrogateAuthRequired": false,
    "spLogoutURL": "https://pujavs-definite-dory.gluu.info",
    "samlMetadata": {
        "nameIDPolicyFormat": "urn:mace",
        "entityId": "http://localhost:4100",
        "singleLogoutServiceUrl": "http://localhost:4100",		
		"jansAssertionConsumerServiceGetURL":"https://pujavs-real-phoenix.gluu.info/kc/realms/jans-api/broker/SAML_IDP_21/endpoint",
		"jansAssertionConsumerServicePostURL":"https://pujavs-real-phoenix.gluu.info/kc/realms/jans-api/broker/SAML_IDP_21/endpoint/POST"
    }
}

2.1. Create new SAML TRScreen - Option#1 Upload Metadata File
![image](https://github.com/JanssenProject/jans/assets/43700552/0c4e8c7a-ac99-4376-bb2e-c24b0c53ba27)

2.2. Create new SAML IDP Screen - Option#2 Add individual metadata elements

![image](https://github.com/JanssenProject/jans/assets/43700552/6f154b6b-c869-4da1-9b0c-381e01d19296)

**Comment by devrimyatar** [comment]
Implemented in TUI
