### ISSUE TITLE
feat(document-store): add support to define path of the asset

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7980]
As per Custom asset requirement we need a property to define the path where document needs to be deployed on jetty server.
It needs to be of String data-type as it should be one to one mapping between document and path to deploy.
Example `"path":"/jans-auth/custom/libs"`
Linked Issues:
[2419](https://github.com/JanssenProject/jans/issues/2419)
[7932](https://github.com/JanssenProject/jans/issues/7932)

**Comment by yurem** [comment]
Now API allows to pass description paramters
