### ISSUE TITLE
refactor(TUI): confirmation message for `save` action

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#7983]
After changing any configuration using TUI, when we hit `save`, the confirmation message about changes getting successfully saved, is delivered in either of these two ways on different screens.

1. A pop-up

![image](https://github.com/JanssenProject/jans/assets/343411/0d4b5115-048b-415e-bff0-72703874a3ef)

2. A message in the bottom toolbar

![image](https://github.com/JanssenProject/jans/assets/343411/224a68f6-2616-4d5b-9682-eed72c0d45dc)

So, the user experience is inconsistent. I would request:

- Pick one approach to deliver this message and implement it consistently across TUI all screens
- I would recommend the first approach with a dedicated pop-up as the bottom bar's tooltip is hard to notice. In this case, to the user, the save button seems to be doing nothing till the time they spot the message at the bottom. Resulting in bad user experience.

**Comment by KyleChaukccs** [comment]
HI @ossdhaval and @moabu, Is it confirmed that the first approach will be used for the alignment? If so, I can work on this for the next couple of weekends.

**Comment by ossdhaval** [comment]
I am ok with first approach as proposed. @moabu ?

**Comment by moabu** [comment]
I suggest `1`.

**Comment by devrimyatar** [comment]
There is only one popup message for confirming saved changes. Others are in progress bar. If we display all in popup, it may be annoying.
