### ISSUE TITLE
fi(jans-cli-tui): TUI breaking when  creating SP  in jans--saml

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8013]
**Describe the bug**
TUI breaking when  creating SP in jans--saml

**To Reproduce**
1. create IDP in jans-saml
2. use sp_metadatafile to create service provider
3. add all details in sp details and use file as  metadata source file and save it
4. donot select file in metadata file
5. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/33a28c0b-a63a-454b-baaf-83766266def4)

**Desktop (please complete the following information):**
  - OS: ubuntu 22
-DB  opendj
jans 1.1.0.nighlty

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This issue was fixed by PR https://github.com/JanssenProject/jans/pull/7965

https://github.com/JanssenProject/jans/assets/6398752/b5813218-514f-47aa-ba62-439674193070
