### ISSUE TITLE
fix(config-api): saml idp delete scope issue

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8031]
Delete SAML IDP giving error for insufficient scopes in TUI
![image](https://github.com/JanssenProject/jans/assets/43700552/b28bb9c3-76b8-46a7-a5a8-5a8b20e8ac39)

**Comment by pujavs** [comment]
@devrimyatar this issue was fixed via PR [8022](https://github.com/JanssenProject/jans/pull/8022)
 request you to please confirm if this issue is fixed.

**Comment by devrimyatar** [comment]
Fixed
