### ISSUE TITLE
feat(jans-config-api): the password strength check should not be always done in PUT mode

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#8034]
**Affected API:**  `PUT` `/mgt/configuser`

As password is not mandatory, the password strength check should be only done if user's password is part of PUT request.

In current state, API is always throwing password strength error even if a strong password is used during user creation (POST request).

`PUT` `/mgt/configuser`
**Request-Body**

```
{
  "inum": "60d9401e-7e4c-464e-a570-4e8ff5331b51",
  "userId": "arnab",
  "mail": "arnab@gluu.org",
  "displayName": "arnab",
  "jansStatus": "active",
  "givenName": "arnab1",
  "customAttributes": [
    {
      "name": "sn",
      "multiValued": false,
      "values": [
        "arnab3"
      ]
    },
    {
      "name": "middleName",
      "multiValued": false,
      "values": [
        "arnab3"
      ]
    }
  ],
  "dn": "inum=60d9401e-7e4c-464e-a570-4e8ff5331b51,ou=people,o=jans"
}
```

![image](https://github.com/JanssenProject/jans/assets/32794267/a1764d21-dfcb-4ffd-ae1f-8c22d5e48ba8)

**Comment by pujavs** [comment]
Fixed via PR [8215](https://github.com/JanssenProject/jans/pull/8215)
