### ISSUE TITLE
fix(jans-cli-tui):getting error while creating attribute

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8047]
**Describe the bug**
getting error when creating attribute

**To Reproduce**
1. install jans 1.1.o.nightly
2. launch tui
3. create new attribute with adding all details required

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/41a02823-db3c-46fa-a009-3c2ab9fbad20)

**Desktop (please complete the following information):**
  - OS: suse 15
  - jans 1.1.0.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
This title was created before. This is not an issue. You have to first create db schema or rdbm column.
