### ISSUE TITLE
fix(jans-cli): agama project deployment response issue

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans#8098]
**Screenshots**
<img width="754" alt="Screenshot 2024-03-20 at 10 26 33" src="https://github.com/JanssenProject/jans/assets/20867846/50d88bae-5723-4b11-9b93-33493922e5ac">

It shows in the description that deployment is done successfully while the response type is `server_error`. 

**To Reproduce**
Try to deploy a agama-project and check what it displays in response.

Tested on jans 1.0.21, 1.0.22

**Comment by devrimyatar** [comment]
@imShakil I just tested, the response is different than your report:

```
$ python3 jans-cli-tui/cli_tui/cli/config_cli.py --operation-id=post-agama-prj --data /mnt/data/agama/7.zip --url-suffix="name:7-zip"
Server Response:
{
  "message": "A deployment task for project 7-zip has been queued. Use the GET endpoint to poll status"
}
```

**Comment by imShakil** [comment]
Hi, @devrimyatar 

I just tested on version 1.1.0. It's fine. It's an old version issue. I'm closing this issue then.
