### ISSUE TITLE
fix(jans-scim): SCIM not responding to applied Password validation

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#8146]
We have enabled custom validation for `Password` attribute. Which is: 

 - Flex: 5.1.0 in Ubuntu 22 with Postgresql backend. 
 - Regular expression: `^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$`
 - Minimum Length: 6, Maximum Length: 12
 - Admin-UI and jans TUI are respecting this validation and prohibiting users to create simple password. 
 - But, I can easily replace existing user's strong password to simple one like `1234` even when password validation is in place of configuration. 
 
 
![Screenshot from 2024-03-26 01-38-27](https://github.com/JanssenProject/jans/assets/7156097/ce19264e-8272-4bbb-abfb-3441ffca97c2)

**Comment by jgomer2001** [comment]
@mzico  a new property was added  to scim configuration to turn off validation if desired

![Screenshot from 2024-06-17 06-40-48](https://github.com/JanssenProject/jans/assets/5444180/f70468a1-2d7c-47be-83d3-365e18a28466)
