### ISSUE TITLE
fix(jans-ci-tui): smtp test response

### ISSUE THREAD

**Issue by mmrraju** [JanssenProject/jans#8152]
**Describe the bug**

In SMTP configuration if I use port 587 getting wrong response, but  configuration works fine like I can send OTP using mail.

![Screenshot from 2024-03-26 19-58-16](https://github.com/JanssenProject/jans/assets/43112579/8857e46d-d0c5-4566-830d-f0ed9fcd56c6)

**Comment by pujavs** [comment]
@devrimyatar, status code `200` indicates that the endpoint is successful and the return value `true` and `false` indicates the result of SMTP test. 
If the endpoint throws error in case STMP test failed then it will be confusing to the caller whether the endpoints itself failed or the SMTP test failed.

**Comment by devrimyatar** [comment]
@mmrraju I tested this several times. It works well. I just added more verbosity.

To be clear, ther should be a mailbox taht you wrote on field **From Email Address**. Let say we have configuration like:


**SMTP Host:** `mx.example.jans.io`
**From Email Address:** `devrim@example.jans.io`

The smtp server on host `mx.example.jans.io` should accept mail to  `devrim@example.jans.io`.
