### ISSUE TITLE
feat(jans-auth-server): introduce acr mappings and prefixed acr - "agama_<flow name> "

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#8216]
Let's say we have an authn request for `acr_values=org.gluu.agama.flow1`.  For an unknown acr, could we check it against all exsiting agama flows, and if it matches, invoke the agama bridge? Of course there would need to be a feature flag.
And we might want to filter what flows are exposed in the wild... but this would solve a big problem for agama... adding that extra param means any standard openid connect client can't specify the flow.

------------------

### Relevant documents that might need updates

**Note**: Developer needs to add to this list based on complete understanding of the feature and its implementation

- [ ] [ACR documentation](https://docs.jans.io/v1.1.0/admin/auth-server/openid-features/acrs/)

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by yuriyz** [comment]
![image](https://github.com/JanssenProject/jans/assets/2013070/df4e5314-9422-41e0-9a6c-a679e29c435b)

**Comment by yuriyz** [comment]
We will use prefixed version for agama acr with `_` as split symbol to avoid url encoding/decoding.
`acr_values=agama_<name>`
