### ISSUE TITLE
feat(jans-cli-tui): create ACR screen on TUI

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#8217]
### Description

 TUI "ACR" screen should have clear sections:
1) Built-in
For now it's just: `simple_password_auth`
2) Script acrs
all script names listed here
3) Aliases
Mappings between alias and technical name
`acr_values=myOTP` -> `acr_values=org.gluu.agama.otp.main`
4) Agama flows
`acr_values=agama_org.gluu.agama.otp.main`

https://chat.gluu.org/group/service_auth_server?msg=Dca2335PvjKNsFN8b

### Relevant documents that might need updates

**Note**: The developer needs to add to this list based on the complete understanding of the feature and its implementation

- Add a new document [under config guide](https://github.com/JanssenProject/jans/tree/main/docs/admin/config-guide) with screens and relevant explanation. Also, if the same is possible via CLI, then add those command too in the same document.

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by yuriyz** [comment]
Wait until this ticket is solved https://github.com/JanssenProject/jans/issues/8216

**Comment by ossdhaval** [comment]
updated the description for documentation tasks

**Comment by devrimyatar** [comment]
@yuriyz Should I extend the following screen for **Aliases** and **Agama Flow**

![Screenshot_2024-08-11_12-21-33](https://github.com/user-attachments/assets/41f69069-9709-4830-b2bf-6120576b4f39)

**Comment by nynymike** [comment]
It would be nice if `simple_password_auth` and `auth_ldap_server` were configurable by the admin.

**Comment by devrimyatar** [comment]
> It would be nice if `simple_password_auth` and `auth_ldap_server` were configurable by the admin.

Yes they are

![image](https://github.com/user-attachments/assets/cc892e34-0548-4c6c-ad3f-5e69cf85f234)

![image](https://github.com/user-attachments/assets/7477b861-38d8-430e-bef0-ccec3b97d534)

**Comment by yuriyz** [comment]
> @yuriyz Should I extend the following screen for Aliases and Agama Flow

@devrimyatar yes

**Comment by duttarnab** [comment]
Hi @yuriyz @devrimyatar @pujavs 

- `Agama flows` can be obtained from API (config-api). We need the fields list to be shown on screen
/jans-config-api/api/v1/agama-deployment

- For `Aliases` I think we need API. We also need the fields list to be shown on screen.

**Comment by yuriyz** [comment]
Aliases are part of AS config. So this should already work.

```
{
  ...
  "acrMappings": {
    "acr_alias1": "basic",
    "acr_alias2": "otp" 
  }
  ...
}
```

@duttarnab thanks for sharing info for `Agama flows`. I guess it was missing piece for @devrimyatar

**Comment by devrimyatar** [comment]
> Aliases are part of AS config. So this should already work.
> 
> ```
> {
>   ...
>   "acrMappings": {
>     "acr_alias1": "basic",
>     "acr_alias2": "otp" 
>   }
>   ...
> }
> ```
> 
> @duttarnab thanks for sharing info for `Agama flows`. I guess it was missing piece for @devrimyatar

@yuriyz I imeplemented **Aliases** section

![image](https://github.com/user-attachments/assets/901bfa6a-fb8b-43ad-a6a6-d78af4efebdc)

![image](https://github.com/user-attachments/assets/6b5fe1f7-9a70-4108-ba6c-17103a7f1bf6)

**Comment by duttarnab** [comment]
Hi @yuriyz my understanding is, for `Agama Flows` we need to show all the added Agama projects on the auth server. We already have a screen for this, we just need to shift this screen under a separate tab under `Authn ` menu. Kindly let us know if this understanding is incorrect.

![image](https://github.com/user-attachments/assets/79a0fc63-e37d-4a81-9950-bf9f7d9d63a7)

**Comment by yuriyz** [comment]
Right, idea is to show it on TUI as well.
