### ISSUE TITLE
fix(config-api): admin-ui license status inactive error when replicas scaled up

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8222]
When admin-ui replica's are scaled up license inactive error is displayed

Support ticket: [11733] (https://support.gluu.org/other/11733/license-status-inactive-when-scaled-up-the-replicas-of-each-deployment/#at89181)

**Comment by ossdhaval** [comment]
@pujavs Shouldn't this issue be part of Gluu repo? Admin-UI isn't part of Jans. Or if you are trying to fix a Janssen bug, then please can you change the verbiage?

**Comment by pujavs** [comment]
Closing the issue as support ticket is being assigned to admin-ui team
