### ISSUE TITLE
docs(casa): add documentation for strong authn settings plugin

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#8236]
Need to add documentation for [strong authn settings plugin](https://github.com/JanssenProject/jans/tree/main/jans-casa/plugins/strong-authn-settings) under the sections below on the doc site:

- casa -> administration guide -> Plugins
- [user guide](https://docs.jans.io/head/casa/user-guide/)

**Comment by jgomer2001** [comment]
already exists:

https://docs.jans.io/head/casa/plugins/2fa-settings/

**Comment by ossdhaval** [comment]
I see. Thanks for sharing this link @jgomer2001.

It seems that `Strong Authentication Settings Plugin` and `2fa` are interchangeably used. While the code uses `StrongAuthn` wordings, the docs refer to same as `2fa`(for example, the entry in the navigation menu).

Is it possible to use only one way to refer to this plugin? Either `Strong Authn` or `2fa`. This will help avoid the confusion when people refer to code vs Docs.

**Comment by jgomer2001** [comment]
checking...

**Comment by jgomer2001** [comment]
https://github.com/JanssenProject/jans/issues/8426
