### ISSUE TITLE
fix(jans-cli-tui): tui crash when press c to manage agama configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8238]
**Describe the bug**
ui crash when press c to manage agama configuration

**To Reproduce**
1. install jans 1.1.1.nightly
2. goto agama
3. press c to manage agama configuration

**Expected behavior**

TUI should not crash
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/42d5d728-abb8-48a5-bee1-90b40ad4f2b0)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp5
  - jans 1,1,1.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
I can't replicate this


https://github.com/JanssenProject/jans/assets/6398752/3eae0798-3b44-419e-aa29-3d849b9e8204

**Comment by manojs1978** [comment]
https://github.com/JanssenProject/jans/assets/5729240/7bbbddce-945e-403a-80d2-9d64e5de9b7b

please check VDO
tui crashing when we dont have any project 
and press enter in search box then press c
