### ISSUE TITLE
fix(jans-cli-tui): unable to add IMAP data claim to user

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8239]
**Describe the bug**
 unable to add IMAP data claim to user

**To Reproduce**
1. install jans 1.1.1.nighlty
2. create user
3. add claims IMAP data while creaing user and save it

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/0554df8d-13e5-4885-9a5d-96dcf8b6a4fc)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp5
  - jans 1.1.1.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed

https://github.com/JanssenProject/jans/assets/6398752/96f7fb7e-4fdf-4fd3-a57d-1833dcf86394
