### ISSUE TITLE
fix(casa): retry security key option to login is not working 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8277]
**Describe the bug**
 retry security key not working 

**To Reproduce**
1. launch TUI and enable fido and super gluu scirpt
2. complete SG configuration required
3. login to casa and enable 2FA and set fido script as preferred method
4. logout and login again with username passwd
5. 2step vrification prompted for fido device cancle it.
6. click on retry security key 
7.  See error

**Expected behavior**
should prompt for fido 2fa verificaion again

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/60e106b9-56c3-4f34-88d0-afc138849a04)

**Desktop (please complete the following information):**
OS: ubuntu
-jans 1,1,1.nightly-
-opendj
super gluu: - 4.5.1
andriod- andriod 13

**Smartphone (please complete the following information):**

**Additional context**
[casa.zip](https://github.com/JanssenProject/jans/files/14943862/casa.zip)

**Comment by jgomer2001** [comment]
What's the point here if your sever is  using a self-sign cert?

By now you should already know  you need a real cert for fido2 to work @manojs1978
