### ISSUE TITLE
fix(jans-tui): unable to create client auth client

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8284]
**Describe the bug**
unable to create client auth client

**To Reproduce**
1. install jans 
2. goto auth and create client 
3.  See error

**Expected behavior**
should not get eny error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/58a97177-ca8b-44ad-9bde-5055e785b416)

**Desktop (please complete the following information):**
  - OS:ubuntu22
-jans 1.1.1.nightly
DB opendj

**Smartphone (please complete the following information):**

**Additional context**
Add any other c
[config.zip](https://github.com/JanssenProject/jans/files/14954306/config.zip)
ontext about the problem here.

**Comment by pujavs** [comment]
@manojs1978 please share request jsons

**Comment by manojs1978** [comment]
{
  "inum": "",
  "disabled": false,
  "clientName": "testclient",
  "clientSecret": "",
  "description": "",
  "tokenEndpointAuthMethod": "client_secret_basic",
  "subjectType": "public",
  "sectorIdentifierUri": "",
  "grantTypes": [],
  "responseTypes": [
    "code"
  ],
  "trustedClient": false,
  "applicationType": "native",
  "redirectUris": [
    "https://localhost:9090/oidc_back"
  ],
  "accessTokenAsJwt": false,
  "includeClaimsInIdToken": false,
  "idTokenTokenBindingCnf": "",
  "accessTokenLifetime": "",
  "refreshTokenLifetime": "",
  "defaultMaxAge": "",
  "frontChannelLogoutUri": "",
  "postLogoutRedirectUris": [],
  "frontChannelLogoutSessionRequired": false,
  "clientUri": "",
  "policyUri": "",
  "logoUri": "",
  "contacts": [],
  "authorizedOrigins": [],
  "softwareId": "",
  "softwareVersion": "",
  "softwareStatement": "",
  "backchannelTokenDeliveryMode": "poll",
  "backchannelClientNotificationEndpoint": "",
  "backchannelUserCodeParameter": false,
  "rptAsJwt": false,
  "claimRedirectUris": [],
  "jwksUri": "",
  "jwks": "",
  "persistClientAuthorizations": false,
  "initiateLoginUri": "",
  "requestUris": [],
  "defaultAcrValues": [],
  "expirationDate": null,
  "scopes": [
    "inum=B9D2-D6E5,ou=scopes,o=jans",
    "inum=10B2,ou=scopes,o=jans",
    "inum=43F1,ou=scopes,o=jans",
    "inum=F0C4,ou=scopes,o=jans"
  ],
  "attributes": {
    "redirectUrisRegex": "",
    "parLifetime": 0,
    "requirePar": false,
    "backchannelLogoutUri": [],
    "additionalAudience": [],
    "rptClaimsScripts": [],
    "spontaneousScopeScriptDns": [],
    "runIntrospectionScriptBeforeJwtCreation": false,
    "backchannelLogoutSessionRequired": false,
    "jansDefaultPromptLogin": false,
    "allowSpontaneousScopes": false,
    "tlsClientAuthSubjectDn": "",
    "jansAuthorizedAcr": [],
    "introspectionSignedResponseAlg": null,
    "introspectionEncryptedResponseAlg": null,
    "introspectionEncryptedResponseEnc": null
  },
  "displayName": "testclient"
}

**Comment by devrimyatar** [comment]
@manojs1978 I was also able to create client with your sample json
```
$ python3 jans-cli-tui/cli_tui/cli/config_cli.py --operation-id=post-oauth-openid-client --data=/tmp/client.json 
Server Response:
{
  "dn": "inum=508ff17d-5d69-49ff-9e73-df4692809c89,ou=clients,o=jans",
  "deletable": false,
  "clientSecret": "fa2e968b-bb59-4686-9c21-8544e90c53a1",
  "frontChannelLogoutUri": "",
  "frontChannelLogoutSessionRequired": false,
  "redirectUris": [
    "https://localhost:9090/oidc_back"
  ],
  "responseTypes": [
    "code"
  ],
  "grantTypes": [],
  "applicationType": "native",
  "idTokenTokenBindingCnf": "",
  "clientName": "testclient",
  "logoUri": "",
  "clientUri": "",
  "policyUri": "",
  "clientNameLocalized": {},
  "logoUriLocalized": {},
  "clientUriLocalized": {},
  "policyUriLocalized": {},
  "tosUriLocalized": {},
  "jwksUri": "",
  "jwks": "",
  "sectorIdentifierUri": "",
  "subjectType": "public",
  "tokenEndpointAuthMethod": "client_secret_basic",
  "initiateLoginUri": "",
  "scopes": [
    "inum=B9D2-D6E5,ou=scopes,o=jans",
    "inum=10B2,ou=scopes,o=jans",
    "inum=43F1,ou=scopes,o=jans",
    "inum=F0C4,ou=scopes,o=jans"
  ],
  "trustedClient": false,
  "persistClientAuthorizations": false,
  "includeClaimsInIdToken": false,
  "customAttributes": [
    {
      "name": "displayNameLocalized",
      "multiValued": true,
      "values": [
        "{}"
      ],
      "value": "{}",
      "displayValue": "{}"
    },
    {
      "name": "jansClntURILocalized",
      "multiValued": true,
      "values": [
        "{}"
      ],
      "value": "{}",
      "displayValue": "{}"
    },
    {
      "name": "jansLogoURILocalized",
      "multiValued": true,
      "values": [
        "{}"
      ],
      "value": "{}",
      "displayValue": "{}"
    },
    {
      "name": "jansPolicyURILocalized",
      "multiValued": true,
      "values": [
        "{}"
      ],
      "value": "{}",
      "displayValue": "{}"
    },
    {
      "name": "jansTosURILocalized",
      "multiValued": true,
      "values": [
        "{}"
      ],
      "value": "{}",
      "displayValue": "{}"
    }
  ],
  "rptAsJwt": false,
  "accessTokenAsJwt": false,
  "disabled": false,
  "softwareId": "",
  "softwareVersion": "",
  "softwareStatement": "",
  "attributes": {
    "runIntrospectionScriptBeforeJwtCreation": false,
    "keepClientAuthorizationAfterExpiration": false,
    "allowSpontaneousScopes": false,
    "backchannelLogoutSessionRequired": false,
    "parLifetime": 600,
    "requirePar": false,
    "dpopBoundAccessToken": false,
    "jansDefaultPromptLogin": false,
    "minimumAcrLevel": -1
  },
  "backchannelTokenDeliveryMode": "poll",
  "backchannelClientNotificationEndpoint": "",
  "backchannelUserCodeParameter": false,
  "description": "",
  "displayName": "testclient",
  "authenticationMethod": "client_secret_basic",
  "allAuthenticationMethods": [
    "client_secret_basic"
  ],
  "baseDn": "inum=508ff17d-5d69-49ff-9e73-df4692809c89,ou=clients,o=jans",
  "inum": "508ff17d-5d69-49ff-9e73-df4692809c89"
}
```

**Comment by manojs1978** [comment]
this is with nightly build, i mentioned in description as well, i ll check again with latest nightly build
