### ISSUE TITLE
feat(documentstore): should have a relevant field for storing file-path on server

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8289]
At present the `description` field is being used to store path of the file on server we need a relevant field to store the same.

- Parent issue: [2419](https://github.com/JanssenProject/jans/issues/2419)
- Discussion chat [thread] (https://chat.gluu.org/group/service_config_api?msg=rYXXDq4ihP92W67Ng) and (https://chat.gluu.org/group/service_admin_ui?msg=2pQpLnd8zhtm6Bvji)

**Comment by shekhar16** [comment]
@pujavs  @yurem  closing this ticket..
