### ISSUE TITLE
bug(document-store): document api not saving value of some fields

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8290]
**Describe the bug**
DB Document Store not storing/ updating values of 
`jansLevel`
`jansRevision`
`selected`

- Parent issue: [2419](https://github.com/JanssenProject/jans/issues/2419)
- Discussion chat [thread] (https://chat.gluu.org/group/service_config_api?msg=rYXXDq4ihP92W67Ng) and (https://chat.gluu.org/group/service_admin_ui?msg=2pQpLnd8zhtm6Bvji)

![image](https://github.com/JanssenProject/jans/assets/43700552/0b7d261c-398d-49b8-b6c0-c4792fae85cd)

**Comment by shekhar16** [comment]
@pujavs You can directly use the dbDocumentService.class to save/update the Document/Asset by directly passing Document object with your preferable values... like below 
https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AssetService.java#L247

You can ignore the DBDocumentStoreProvider for you Asset service as it hold the interface signature.

**Comment by pujavs** [comment]
@yurem, shall i go ahead with the approach suggested by @shekhar16 to bypass `DBDocumentStoreProvider ` and directly call 
`DBDocumentService.class` for save/update operation

**Comment by yuremm** [comment]
@pujavs DBDocumentStoreProvider  and other providers provides same interfaces to work with document
In you case you always know which provider to use. Hence yes, you can always use DBDocumentService.

**Comment by shekhar16** [comment]
@yurem  @pujavs  Can I close this ticket?

**Comment by pujavs** [comment]
@shekhar16,  re-opening the issue as in spite of using `DBDocumentService.class for save/update operation, value of `selected` is still not getting updated.

Kindly check and revert

**Comment by devrimyatar** [comment]
**selected** field is not saving. Other fields are okay

**Comment by yurem** [comment]
`selected` is defined as transient [field](https://github.com/JanssenProject/jans/blob/0febaa435438f79d27dc41a9bd15a88ffe274bd1/jans-core/document-store/src/main/java/io/jans/service/document/store/service/Document.java#L29). I think this were added for oxTrust. How we use it now? Is it really needed as field in document? If yes, we simply need to add `@AttributeName` to this field and remove `transient`.

**Comment by pujavs** [comment]
@yurem, as a client of `DocumentStore` it is found that the values set by the client is not set and hence reported.
the usage of `selected` field might be same as oxTrust. 
However if it is not required then can it be removed from Document class

**Comment by yurem** [comment]
I offer to remove `selected` field. @devrimyatar @shekhar16 do you have any objections?

**Comment by shekhar16** [comment]
chnages has been merged closing this ticket, please me know if anything needed.
