### ISSUE TITLE
fix(jans-tui): edit attribute showing popup server error occured

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8291]
**Describe the bug**

**To Reproduce**
1. install jans 1.1.1.nightly
2. go to attribute and edit any attrbute and update any field
3. save it

**Expected behavior**
attribute get updated still getting this error, we shold not get error 

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/cf5f611a-f80e-4603-9a1a-1e3107800315)

**Desktop (please complete the following information):**
  - OS: ubuntu
  - Version 22
  - jans 1.1.1.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Create schema in db

**Comment by devrimyatar** [comment]
@pujavs This seem config-api issue.

**Comment by pujavs** [comment]
@manojs1978 request you to please share config-api logs as it helps

**Comment by manojs1978** [comment]
[config.zip](https://github.com/JanssenProject/jans/files/14961435/config.zip)

**Comment by pujavs** [comment]
Fixed via PR [8292](https://github.com/JanssenProject/jans/pull/8292)
