### ISSUE TITLE
feat(jans-auth): remove extra info from `acr` claim in `id_token` when it's an agama flow

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#8348]
Formerly (when using `acr_values=agama&agama_flow=...`) for an authn request, the `agama_flow` param might optionally carry some extra data like

`<flow qname>-<extra>`

Please ensure to ignore any stuff after (and including) the hyphen, if present, when populating the `acr` in `id_token`. In other words, keeping just the flow name

**Comment by yuriyz** [comment]
@jgomer2001 in [this PR](https://github.com/JanssenProject/jans/pull/8304) AS is switched to `agama_<flow>`. So I will make sure that `agama_<flow>-params` will end up as `acr: agama_<flow>` in `id_token` (without `-params`).

**Comment by yuriyz** [comment]
We need to allow parameters preserve till script and cut it only for `id_token`. Re-opening ticket.
