### ISSUE TITLE
BUG: after monorepo related changes PR does not build the impacted projects

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#841]
If a PR has changes to multiple projects then the build should be triggered for all, however the build is triggered only for one project causing the maven run to fail as dependent changes not avialable.

Example: https://github.com/JanssenProject/jans/pull/840
In same PR there are changes in jans-core as well as jans-config-api
jans-config-api changes are dependent on jans-core and while sonar build it is not able to find the jans-core changes because it’s not there in the maven repo yet and fails.

**Comment by pujavs** [comment]
@ossdhaval 
I have not noticed this lately. To test this we have to change more than one module and then raise a PR.

**Comment by ossdhaval** [comment]
@pujavs 

Thank you for your comments. For now, I am closing this. If you see a reoccurrence, feel free to reopen.
