### ISSUE TITLE
feat(jans-auth-server): use JWT as typ claim value

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#8419]
### Description

As per the recommendation from https://www.rfc-editor.org/rfc/rfc7519#section-5.1, the `typ` value of a JWT's header section should be `JWT` in uppercase. Jans uses lowercase `jwt`.

### Test cases and code coverage

- [x] Write unit test to cover added/changed code

**Comment by yuriyz** [comment]
From spec
```
If present, it is RECOMMENDED that
   its value be "JWT" to indicate that this object is a JWT.  While
   media type names are not case sensitive, it is RECOMMENDED that "JWT"
   always be spelled using uppercase characters for compatibility with
   legacy implementations.  Use of this Header Parameter is OPTIONAL.
```
