### ISSUE TITLE
fix: feat(jans-cli-tui): Not able to add Identity Provider in jans-saml

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#8432]
**Describe the bug**
 Not able to add Identity Provider in jans-saml)

**To Reproduce**
1. Go to  jans-TUI.
2. Go to jans-saml.
3. Go to identity-provider.
4. add a new provider 
5. See the error

**Expected behavior*
A new Provider must be added

**Screenshots**
![Screenshot (33)](https://github.com/JanssenProject/jans/assets/34593983/832f255b-fb16-422d-bee7-5bbdcc0d10c5)

**Desktop (please complete the following information):**
  - Version: jans 1.1.2 nightly
  - Browser [
  - OS: ubuntu 22.04

**Additional context**

**Comment by devrimyatar** [comment]
This should be fixed by commit https://github.com/JanssenProject/jans/pull/8425/commits/49bf0695affb92326b94d4532e4fbe26133d9813

**Comment by manojs1978** [comment]
able to create IDP  in jans
![image](https://github.com/JanssenProject/jans/assets/5729240/fccd9e5f-b41e-483e-b002-82bf51057112)
