### ISSUE TITLE
fix(jans-casa): OTP as 2FA preferred method not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8443]
**Describe the bug**
OTP as 2FA preferred method not working

**To Reproduce**
1. install jans 1.1.2.nightly with casa
2. enable fido ,otp ,super gluu scripts in jans
3. launch casa and register supergluu and otp
4. set otp  as preferred method
5. logout and login 
6. See error , 
7. 

**Expected behavior**
we should get page to add OTP number  but we are getting supergluu option 

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/cf6d19d0-6f52-4e63-bcfc-88548fdc3b7f)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - jans 1.1.2.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
Problem caused after this [commit](https://github.com/JanssenProject/jans/commit/d769dea697be9449e07bcc298035f8a57c95a196#diff-242191a169b79274098d7f22ec4c6198dcf2aa5bdc7b685fff0f958fa6838b0c), now `user.getAttributeValues("jansExtUid")` evaluates `null`

I could fix the casa script but i'm sure there are several places besides jans-casa where this logic is used

**Comment by jgomer2001** [comment]
backward compatibility of the method call will be tackled in https://github.com/JanssenProject/jans/issues/8458
