### ISSUE TITLE
fix(jans-casa): unable to delete registered super gluu device from casa

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8445]
**Describe the bug**
unable to delete registered super gluu device from casa

**To Reproduce**
1. install jans
2. enable super gluu script, otp script and enable 2FA
3. delete super gluu from casa

**Expected behavior**
should able to delete super gluu form casa

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/cc039353-2563-4a8e-8178-25e70823de3a)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Browser [e.g. firefox]
-jans 1.1.2.nightly
DB opendj
**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
@manojs1978  Unable to reproduce... it worked for me with latest (nightly) ubuntu 22 package.

Please provide some logs or access to a machine where it is not working
