### ISSUE TITLE
fix(jans-casa): try another way to sign option not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8480]
**Describe the bug**
 try another way to sign not working

**To Reproduce**
1.install jans
2. enable supergluu,otp script
3. login casa and register super gluu device and otp
4. set otp as referred methid 
5. logout and login again
6. 2FA otp script and try another wayto sign in option appears
7. select try another wayto sign
8. See error

**Expected behavior**
should get super gluu 2FA page to login but it is redirecting to OTP

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/3bbce6e7-0eef-46af-96dd-4df9c717275f)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.2.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**
[log.zip](https://github.com/JanssenProject/jans/files/15272245/log.zip)

**Comment by MohitMaliFtechiz** [comment]
this issue has been fixed.
