### ISSUE TITLE
fix(jans-cli): unable to create asset

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8485]
**Describe the bug**
unable to create asset

**To Reproduce**
1. install jans 1.1.2.nighlty
2. launch cli-tui
3. create asset

**Expected behavior**
should able to create asset
**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/1df82efd-3736-4089-9994-67e09f8b8b3e)

**Desktop (please complete the following information):**
  - OS: ubuntu
-jans 1.1.2.nightly
DB - pgsql
**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
@pujavs 
in latest build ,
getting below error in asset creation

![image](https://github.com/JanssenProject/jans/assets/5729240/53868cc1-40dd-448f-bae9-890b7cca88cf)

**Comment by pujavs** [comment]
@manoj @devrimyatar this is valid validation if jansModuleProperty" is null or empty.
So asset mgt does two things
1. Saves assets in DB DocumentStore
2. Uploads assets on jetty server. For this we need the fileName is stored in `displayName` and it needs to be fileName with valid extension and `jansModuleProperty` is list of valid module service names where the file can be saved. example `jans-auth`, `jans-scim`, `jans-config-api`, etc

**Comment by devrimyatar** [comment]
This is not TUI issue and was fixed by https://github.com/JanssenProject/jans/pull/8526
