### ISSUE TITLE
fix(install): Jans docker setup has errors which doesn't install TUI/CLI config tools

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#8494]
**Describe the bug**

I have install Jans via docker compose using [these instructions](https://docs.jans.io/v1.1.2.nightly/admin/install/docker-install/compose/).

Post install, the well-known endpoints respond as expected. But there is no config tool installed at these paths:

```
/opt/jans/jans-cli/config-cli.py
/opt/jans/jans-cli/config-cli-tui.py
```

Without these tools, Janssen Server is not usable.

When investigated further, the `/opt/jans/jans-setup/logs/setup_error.log`(attached), and `/setup_log`(attached) have
 errors.

**Desktop (please complete the following information):**
  - OS: Ubuntu 22.04 (full OS)

[setup_error.log](https://github.com/JanssenProject/jans/files/15292280/setup_error.log)
[setup_log.txt](https://github.com/JanssenProject/jans/files/15292334/setup_log.txt)

**Comment by iromli** [comment]
@ossdhaval seems issue while downloading archive file.

**Comment by ossdhaval** [comment]
As pointed by @moabu, the [TUI has to be separately installed](https://docs.jans.io/v1.1.2.nightly/admin/kubernetes-ops/tui-k8s/). Closing this issue.
