### ISSUE TITLE
feat(document-store): enhancements to module for asset management

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8518]
![image](https://github.com/JanssenProject/jans/assets/43700552/e2a7b70f-1445-4b34-ab5b-135ea7fc4d47)

As per above chat request
 - Part1: Enhancement here would be to remove the path requirement as discussed so that it follows a pre defined service location.- Thus remove `jansFilePath` field. 
 - Part 2: All the jans services need to pull from persistence also following the same logic regarding the path requirement being predefined. I think this is a core service @yurem There cannot be any dependency on the filesystem to persist anything.
 - Suggestion from @syntrydy to  replace `jansModuleProperty` field with new field called `services`. This also imply that the column is present on the db side" 
 - Suggestion from @syntryd - There should be predefined list of service where assests can be copied to

**Comment by shekhar16** [comment]
https://github.com/JanssenProject/jans/commit/2ee1ee10413b580388f9ac4628692392b7105a96

**Comment by shekhar16** [comment]
@pujavs can we close this issue as code has been merged.

**Comment by shekhar16** [comment]
closing this issue.
