### ISSUE TITLE
fix(document-store): jansLevel datatype mismatch error in pgsql

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8519]
**Describe the bug**
**Error:** Getting error on saving a document  `jansLevel` is of type integer but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression.\n  Position: 250"
**Env:** PgSQL
![image](https://github.com/JanssenProject/jans/assets/43700552/e49ef8fc-b04a-45f9-9f92-b4d807bb0d9d)

**Datatype mismatch:
- In Document class `jansLevel` is defined as `string`
- In schema it is defined as `integer`
![image](https://github.com/JanssenProject/jans/assets/43700552/8ef25ded-b0f2-4fb2-89f2-3e4758cb1326)
![image](https://github.com/JanssenProject/jans/assets/43700552/63a99f6e-6343-4b51-a544-f56ed8c0325e)

**Comment by shekhar16** [comment]
changes has been merged closing this ticket. let me know if anything needed,.
