### ISSUE TITLE
feat:  change in path of jans-config-api plugins

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#855]
We have changed the path of jans-config-api plugins in the maven repository to bring all plugins under `jans-config-api/plugins` folder.

Please change the following paths in jans-linux-setup so that the plugins jars are downloaded from the new location. 

1. In `https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/install.py#L234` the download path should be `https://jenkins.jans.io/maven/io/jans/jans-config-api/plugins/scim-plugin/1.0.0-SNAPSHOT/scim-plugin-1.0.0-SNAPSHOT-distribution.jar`.

2. In `https://github.com/GluuFederation/flex/blob/main/flex-linux-setup/flex-setup.py#L79` the download path should be `https://jenkins.jans.io/maven/io/jans/jans-config-api/plugins/admin-ui-plugin/1.0.0-SNAPSHOT/admin-ui-plugin-1.0.0-SNAPSHOT-distribution.jar`.

**Comment by mbaser** [comment]
Commits that addresses issues
1) https://github.com/JanssenProject/jans/commit/885a06d0be03c72778afaf1a80000e917885a9b9
2) https://github.com/GluuFederation/flex/pull/90/commits/9c92b0ae9851a84f88b8a78215e827e23b8609bb
