### ISSUE TITLE
fix: jans-cli throws this error on startup when jans is uninstalled and re-installed multiple times

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#857]
**Describe the bug**
Error when jans-cli is run. 
Note: I have uninstalled and re-installed jans multiple times

**To Reproduce**
1. Install jans server
2. run ` /opt/jans/jans-cli/config-cli.py`
3. See error
4. Cli menu items are displayed after the error
 
**Expected behavior**
Error in step 3 should not be shown.

**Screenshots**
See Error in screenshot
![Error](https://user-images.githubusercontent.com/12072533/154682341-b1739b0f-2b52-4242-946b-3dd7899b9c90.png)

**Comment by mbaser** [comment]
Fixed in https://github.com/JanssenProject/jans/commit/81fe29e57eabb31775fa9136cee5f0496df1b9a0
