### ISSUE TITLE
fix(jans-cli): getting error when launching TUI

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8587]
**Describe the bug**
getting error when launching TUI

**To Reproduce**
1. installn jan 1.1.2.nightly
2. launch TUI

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/55caea67-5ed2-4fef-842c-7a3131911fc1)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 
  - jans 1.1.2.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
I think this issue was fixed by https://github.com/JanssenProject/jans/commit/c89fb50f1ccfdba8ac8f6e050ff3648e3106bdb3
