### ISSUE TITLE
fix(jans-cli-tui): getting error while launching TUI

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8628]
**Describe the bug**
getting error while launching TUI

**To Reproduce**
1. install jans 1.1.3.nightly
2. launch tui

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/3a8485cb-e306-4b65-ac0c-a1da5cb11cbb)

**Desktop (please complete the following information):**
  - OS: ubuntu22
--jans 1.1.2.nighlty
--DB pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Tested with lastest build, it works
