### ISSUE TITLE
fix(jans-config-api): spelling mistake in JansAttribute schema

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#8665]
When we fetch the JansAttribute schema using the command below:

```
/opt/jans/jans-cli/config-cli.py --schema JansAttribute > /tmp/attribute.json
```

It show schema which has a spelling mistake, where `requred` should be spelt as `required`

**Comment by pujavs** [comment]
@yurem can i rectify the spelling mistake in JansAttribute model class?

**Comment by yurem** [comment]
yes, sure we can remove `requred` property and set/get methods. We not use them in Jans projects

**Comment by pujavs** [comment]
Fixed via PR [8673](https://github.com/JanssenProject/jans/pull/8673)
