### ISSUE TITLE
fix(jans-cli): CLI allows default authentication method to be set to a method which is not available

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#8683]
**Describe the bug**

CLI allows default authentication method to be set to a method which is not available as an ACR in TUI or (OpenId Wellknown endpoint acr list).

Before:

I have my TUI showing available ACRs (with Casa as default) as below:

![image](https://github.com/JanssenProject/jans/assets/343411/38a1e443-725f-4fd8-939b-6680c19696ca)

and OpenId well-known endpoint is showing ACR list as below:

```
  "acr_values_supported": [
    "casa",
    "simple_password_auth"
  ],
```

Now when I update the default authentication method as `passport_saml` using CLI command below, I expected the command to fail as `passport_saml` is not an available method. Instead, the CLI command returns a response as below:

![image](https://github.com/JanssenProject/jans/assets/343411/be6682f7-c1f2-4b57-8ed2-7398b3ffb5fe)

After this operation, when I check TUI, it has removed Casa as the default auth method. 

![image](https://github.com/JanssenProject/jans/assets/343411/6cc188ed-f9be-4ef3-9f8f-3444d694dccf)

So, overall, there are three issues.

- CLI should only allow available ACR methods to be set as default.
- If someone tries to set something which is not available as an ACR, it should return an appropriate error.
- ACR `auth_ldap_server` is available on TUI, but it is not available on ACR list coming from OpenId well-known endpoint.

**Comment by pujavs** [comment]
Implementation details, validate the default authentication method against enabled custom script.
If the default authentication method script is disabled by config-api endpoint then remove the default authentication value.

**Comment by devrimyatar** [comment]
> Implementation details, validate the default authentication method against enabled custom script. If the default authentication method script is disabled by config-api endpoint then remove the default authentication value.

CLI should not contain any specific code. I will keep it as a wrapper for yaml files.

**Comment by ossdhaval** [comment]
Hi @pujavs, in that case, can we put this logic in config-api?

**Comment by pujavs** [comment]
yes the implementation details i mentioned was for config-api

**Comment by ossdhaval** [comment]
> yes the implementation details i mentioned was for config-api

Superb! Removing TUI label.

**Comment by pujavs** [comment]
No change required in any UI.   UI code to call api as usual and show the error message, which i assume should already  be there.

![image](https://github.com/JanssenProject/jans/assets/43700552/443330dc-77d5-47a6-b133-ab1d28f59d2b)
