### ISSUE TITLE
docs: correct typo in security-best-practices.md

### ISSUE THREAD

**Issue by Rehket** [JanssenProject/jans#8708]
-------------------

### Description
- Documentation: Properties is misspelled in https://github.com/JanssenProject/jans/blob/main/docs/admin/planning/security-best-practices.md

- Development target issue: NA

- Implementation Details: NA

-------------------

### Prepare

- [x] Read contribution guidelines
- [x] Read license information

------------------

### Identified code changes

- [x] Update documentation to fix the typo.

-------------------

### Test cases and code coverage

- NA

-------------------

### Document the changes

- NA

**Comment by Rehket** [comment]
I created a PR for the typo fix, I've not really contributed to open source before, if there is anything I have missed, please let me know!

In this instance, since I created the PR to correct the typo, should I assign the issue to myself?

Thanks for the feedback!

**Comment by ossdhaval** [comment]
@Rehket First of all, thank you for coming forward and making this contribution .. :+1: 

We are reviewing your PR. 

Yes, go ahead and assign it to yourself.

**Comment by Rehket** [comment]
It looks like I don't have permission to assign myself.

Regardless, let me know if actions or additional input is needed. Thank you!
