### ISSUE TITLE
Fix: able to register user credentials using super gluu but authentication fails.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#8725]
**Describe the bug**
able to register user credentials using super gluu but authentication fails.

**To Reproduce**
1. install flex admin UI
2.  go script 
3. enable super-gluu script 
4. go to fido configuration -> dynamic configuration
5. go to jans-tarp and authenticate user via super-gluu
6. try to register device and authenticate user 

**Expected behavior**
User must be registered and authenticate 

**Screenshots** 

**Desktop (please complete the following information):**
  - OS:  ubnutntu
  - Browser chrome/firefox
  - Version  5.1.3 nightly
**Smartphone (please complete the following information):**

**Additional context**

**Comment by nynymike** [comment]
And you have properly configured the account to use the Gluu SCAN API to push the messages?

**Comment by duttarnab** [comment]
This issue has been fixed by following PR.
