### ISSUE TITLE
feat(jans-lock-master): process telemetry data from Cedraling and post it to config api

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#8733]
Calendaring has communication channel with Lock master only. In this case it should post periodically telemetry data to `/audit` endpoint.

Data should be send in CBOR format and have at least next properties:
```
/audit/telemetry:
last_policy_load_time
last_policy_load_size
last_policy_load_status

policy_success_load_counter
policy_failed_load_counter

last_policy_evaluation_time_ns
avg_policy_evaluation_time_ns
mem_usage_mb
count_evaluation_requests
```

After getting this data Lock master should forward it to config-api

**Comment by pujavs** [comment]
Looking into it

**Comment by pujavs** [comment]
# Impacted modules changes in 
- `lock-master` 
- `config-api`
- `setup`

# Changes:
- `lock-master` **/jans-lock/v1/audit/telemetry** endpoint internally calls  `config-api` **jans-config-api/lock/audit/telemetry** with required oauth scope to persist the data.
- `config-api`: persists the telemetry data in DB
- `setup`: New config properties for lock client and endpoint details
should have its pre-registered client, during setup a client with with required scope should be created and its details should be updated in lock DB config.
For testing i manually updated lock configuration in DB as follows;
Only snippet of newly added config property
{
...........
"issuerUrl": "https://pujavs-probable-alpaca.gluu.info",
  "clientId": "1800.222ebcc3-6f3f-4a27-bf99-6d1fc57f8295",
  "clientPassword": "e4HafedZpRWR6ZbB6h6V8Q==",
  "tokenUrl": "https://pujavs-probable-alpaca.gluu.info/jans-auth/restv1/token",
  "endpointDetails": {
    "jans-config-api/lock/audit/telemetry": [
      "https://jans.io/oauth/lock/telemetry.readonly",
      "https://jans.io/oauth/lock/telemetry.write"
    ],
    "jans-config-api/lock/audit": [
      "https://jans.io/oauth/lock/audit.readonly",
      "https://jans.io/oauth/lock/audit.write"
    ],
    "jans-config-api/lock/audit/health": [
      "https://jans.io/oauth/lock/health.readonly",
      "https://jans.io/oauth/lock/health.write"
    ]
  },
.................................
}

# Screenshot
![image](https://github.com/user-attachments/assets/d566f5bc-4d8b-4b16-8fff-288cb29f197e)

![image](https://github.com/user-attachments/assets/9691b439-95a0-4045-9fae-a3cefd4a65e2)

**Comment by pujavs** [comment]
![image](https://github.com/user-attachments/assets/9336f56d-71f5-4302-9f01-2b21ce242705)
