### ISSUE TITLE
fix(orm): orm returns wrong paged results for "descending" order.

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#8751]
### Description

![image](https://github.com/JanssenProject/jans/assets/2013070/ace8a9e9-c937-4cad-a893-65f5d80185a2)

- create 2 entries: jansNum=0, jansNum=1
- run 
```
entryManager.findPagedEntries(clusterNodesBaseDn, ClusterNode.class, getTypeFilter(), null, "jansNum", SortOrder.DESCENDING, 0, 1, 1);
```
Result: 0 is returned instead of 1.

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code

**Comment by yurem** [comment]
In case with ORM we need to fetch all entries instead of one to get right item. We not use VLV Ldap indexes due to performance issues
