### ISSUE TITLE
fix(agama): not able to see my code flow

### ISSUE THREAD

**Issue by shekhar16** [JanssenProject/jans#8752]
I am able to see lib and web code but when I m trying to see my code flow getting blank page,

![image](https://github.com/GluuFederation/agama-duo/assets/15937500/93c6290f-9b70-4948-a7f3-0740876c0a6e)

here is my repo link:
https://github.com/shekhar16/agama-duo/blob/agama-lab-branch/projects/agama-duo/code/org.gluu.agama.duo.main.flow

below is the video link to reproduce the issue.
https://www.loom.com/share/81f43ed449564c96b1a929e0fe352607

**Comment by jgomer2001** [comment]
duplicate of https://github.com/GluuFederation/private/issues/8241
