### ISSUE TITLE
docs(jans-lock): add swagger for lock master 

### ISSUE THREAD

**Issue by SafinWasi** [JanssenProject/jans#8753]
Need to add swagger for lock master. May be replaced in the future with autogenerated swagger.

**Comment by ossdhaval** [comment]
@SafinWasi Can you please add an entry for Lock in [this API reference listing](https://docs.jans.io/v1.1.2/admin/reference/openapi/#rest-api)?

**Comment by SafinWasi** [comment]
@ossdhaval Lock Master is not a Janssen component. It is an independent Jetty server.
https://github.com/JanssenProject/jans/tree/main/jans-lock/lock-master
![image](https://github.com/JanssenProject/jans/assets/6601566/d04c04ed-8ff6-4f1a-89a4-5d87f1f19f11)
