### ISSUE TITLE
feat(jans-cli-tui): allow users to install Agama Lab community projects from TUI

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#8785]
As discussed on group chat [here](https://chat.gluu.org/group/project_jans?msg=xYghGhfpARR7RQZe8)

The idea is to bundle the Agama Lab community projects with the Jans.

So immediately after installing the Janssen Server, if the user goes to `TUI ->auth->agama`, they see a list of agama projects.

All the admin needs to do is provide config for the project they want to use. That is it.
This will reduce a few steps of downloading the project from GitHub and uploading the .gama to the Janssen Server.
Plus, this becomes ready-to-use functionality being available out of the box.

**Comment by jgomer2001** [comment]
More info here too https://chat.gluu.org/group/service_agama_lab?msg=HJrSwC5mWygBfWnRz @devrimyatar
