### ISSUE TITLE
fix(jans): not getting QR code to scan for OTP script

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8793]
**Describe the bug**
not getting QR code to scan

**To Reproduce**
1. install jans 1.1.3.nighly
2. enable otp script
3. launch jans-casa and install google authenticator app and  try to register for soft token

**Expected behavior**
should get QR code to scan 

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/764f86cf-d0d6-40dd-96ee-79f2d0d28915)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Browser chrome
  - Version 22
  - jans 1.1.3.nightly
  - DB pgsql
  -

**Smartphone (please complete the following information):**

**Additional context**
Add any oth
[casa.zip](https://github.com/user-attachments/files/16011474/casa.zip)
er context about the problem here.

**Comment by jgomer2001** [comment]
Unable to reproduce
