### ISSUE TITLE
fix(jans):uninstall jans showing error "sh: 0: getcwd() failed:"

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8798]
**Describe the bug**
getcwd() failed: No such file or directory while uninstalling jans

**To Reproduce**
1. install jans 1.1.3.nightly
2. uninstall jans with `sudo python3 /opt/jans/jans-setup/install.py -uninstall`

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/16386804-315c-44cf-bb7e-5e7613b10e7c)

**Desktop (please complete the following information):**
  - OS: ubuntu22
jans 1.1.3nihglty
DB - pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
You should not execute `install.py` under directory `/opt/jans/jans-setup/`
