### ISSUE TITLE
fix(jans-cli-tui): when edit scope UMA type is not showing

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8829]
**Describe the bug**
when edit scope UMA type is not showing

**To Reproduce**
1.install jans 1.1.3.nightly
2. create new scope of any type except UMA
3. edit scope'

**Expected behavior**
when edit created scope ALL scope type should be showin

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/4431acbe-f2dd-4443-9582-37f9b58afb96)
![image](https://github.com/JanssenProject/jans/assets/5729240/32528af6-9b60-4361-baa0-7a64f3809a6c)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - jans 1.1.3.nightly
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
As explained by @yuriyz and @nynymike we leave this as it is
