### ISSUE TITLE
fix(jans-auth):unable to login with super_gluu as acr

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8883]
steps:
install flex 5.1.3.nigthly
enable super_gluu script
register super_gluu device
set super_gluu as default acr
logout from application and login again
push notification should appear on super_gluu app
selecdt yes for allow to login

expected:
should able to login application

Acdtual:
unable to login application and nothing is happening

Screenshots
image

Desktop (please complete the following information):

OS: ubuntu22
-flex 5.1.3.nightly
opendj
Smartphone (please complete the following information):

Additional context
[log.zip](https://github.com/user-attachments/files/16110304/log.zip)

**Comment by yurem** [comment]
We need to update SG login.xhtml to conform changes applied in https://github.com/JanssenProject/jans/commit/8dfc3f45acaf4f7dee15994b51fbcc5296882a38

With this update SG login.xhtml throws JS errors like:
![346170232-7fc8a209-8a30-4521-8ed5-10dfcb4acfb5](https://github.com/JanssenProject/jans/assets/6104200/22514574-5d94-45a1-97eb-4ce2d16b1312)
