### ISSUE TITLE
Janssen 1.1.2 Installation failing for OpenSuse-Leap ( 15.6 )

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#8896]
I am trying to install Janssen 1.1.2 in OpenSuse by following [this](https://docs.jans.io/v1.1.2/admin/install/vm-install/suse/) doc but it's failing with error that... "python3-ldap3" package not available. 

I tried to manually ( and separately ) installed python3 and ldap3 but still it's failing. Here is the screenshot: 

![Screenshot from 2024-07-08 23-11-39](https://github.com/JanssenProject/jans/assets/7156097/607d1a5f-d2c3-44aa-b47d-08f327e5e62a)

**Comment by devrimyatar** [comment]
Suse packages are not consistent accross versions.
In 15.6, suse is moving to python3.11, but in 15.5 python3.6 is used.
For 15.6, you need to install these packages manually
```
zypper install python3-ruamel.yaml
zypper install https://download.opensuse.org/distribution/leap/15.5/repo/oss/noarch/python3-ldap3-2.6.1-1.1.noarch.rpm
```
