### ISSUE TITLE
fix(jans-linux-setup): Janssen 1.1.2 Installation failing for OpenSuse-Leap ( 15.6 ) - setup.py error

### ISSUE THREAD

**Issue by mzico** [JanssenProject/jans#8900]
It's the continuation of previously reported [bug](https://github.com/JanssenProject/jans/issues/8896). If I select number 2 from above prompt described in previous issue, installation move forward. 

But, it's failing with `setup.py`: 

```
00:27:42 07/09/24 Configuring system
00:27:43 07/09/24 FATAL
00:27:43 07/09/24 Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 385, in do_installation
    jansInstaller.configureSystem()
  File "/opt/jans/jans-setup/setup_app/installers/jans.py", line 159, in configureSystem
    for l in open(systemd_conf_fn):
FileNotFoundError: [Errno 2] No such file or directory: '/etc/systemd/system.conf'
```

![Screenshot from 2024-07-09 10-53-39](https://github.com/JanssenProject/jans/assets/7156097/9d3972ae-cffd-4b79-a72a-f15b0d43ad75)

**Comment by mzico** [comment]
**WORKAROUND**

- Reason of failure: Systemd Configuration File missing. 
- Workaround: 
  - Verify Systemd configuration files: 
    ```
    sudo systemctl --version
    ls /etc/systemd/

    ```
  - Create the missing file: 
    ```
    sudo touch /etc/systemd/system.conf
    sudo cp /usr/lib/systemd/system.conf /etc/systemd/system.conf
  
    ```
  - Ensure permission: 
    ```
    sudo chmod 644 /etc/systemd/system.conf

    ```
  
  - Rerun setup script:

**Comment by devrimyatar** [comment]
@mzico This issue was fixed by commit https://github.com/JanssenProject/jans/commit/3702661bc501eac779bb367bc88dbdd00bca7e72
