### ISSUE TITLE
ProjectPasskeys: Add support for BS / BE flags in AuthData

### ISSUE THREAD

**Issue by yackermann** [JanssenProject/jans#8903]
https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/AuthenticatorDataParser.java

See https://w3c.github.io/webauthn/#authdata-flags

**Comment by duttarnab** [comment]
**Points to ponder:** 
- If the [BE](https://w3c.github.io/webauthn/#authdata-flags-be) bit of the [flags](https://w3c.github.io/webauthn/#authdata-flags) in authData is not set, verify that the [BS](https://w3c.github.io/webauthn/#authdata-flags-bs) bit is not set.
- If the [Relying Party](https://w3c.github.io/webauthn/#relying-party) uses the credential’s [backup eligibility](https://w3c.github.io/webauthn/#backup-eligibility) to inform its user experience flows and/or policies, evaluate the [BE](https://w3c.github.io/webauthn/#authdata-flags-be) bit of the [flags](https://w3c.github.io/webauthn/#authdata-flags) in authData.
- If the [Relying Party](https://w3c.github.io/webauthn/#relying-party) uses the credential’s [backup state](https://w3c.github.io/webauthn/#backup-state) to inform its user experience flows and/or policies, evaluate the [BS](https://w3c.github.io/webauthn/#authdata-flags-bs) bit of the [flags](https://w3c.github.io/webauthn/#authdata-flags) in authData.
-

**Comment by duttarnab** [comment]
w3c actual site does not have details on BS/ BE flags. It is only on editor's draft site. 

Ref: https://www.w3.org/TR/webauthn/#authenticator-data

**Comment by yackermann** [comment]
@duttarnab actually the latest version is https://www.w3.org/TR/webauthn-3/

But in reality the versioning system for w3c has very little to do with real world browser state. Browsers may start to support features even before they approved, or not supported features even if they been part of the specs for a long time.

In my experience, using ED https://w3c.github.io/webauthn/ make life just much simpler

**Comment by duttarnab** [comment]
I have made the following changes :

1. check if Backup Eligible (BE) flag is 1 (true/false)
2. check if Backup State (BS) flag is 1 (true/false)
3. if BE=0 and BS=1 then throw exception that combination is not allowed.
4. Then store values of these flags in database

Now I think need to implement below points. Let me know for any suggestion.

![image](https://github.com/user-attachments/assets/19e5353a-70e8-4cc5-9603-8762ce025d6d)

**Comment by yackermann** [comment]
@duttarnab I am ok with it

**Comment by duttarnab** [comment]
We have the custom script in the Janssen authentication server to include custom business logic for authentication etc. The above-discussed points can be handled by custom scripts.

![image](https://github.com/user-attachments/assets/8becfd1e-c272-4cbd-9f2b-4bee66f072bc)
