### ISSUE TITLE
ProjectPasskeys: Add support for WebAuthn Hints

### ISSUE THREAD

**Issue by yackermann** [JanssenProject/jans#8908]
In the latest iterations of the WebAuthn specification, a new mechanism for managing experience was added called "hints".

https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-hints
https://w3c.github.io/webauthn/#enum-hints
This mechanism allows RP to control what user experience they with to push, such as enforce "security-key", or just include "client-device". Together with authenticatorSelection, and `transports` field, RP will be able to carefully control resulting experience.

**Comment by shekhar16** [comment]
its done closing this ticket.
