### ISSUE TITLE
ProjectPasskeys: Add support for Enterprise Attestation

### ISSUE THREAD

**Issue by yackermann** [JanssenProject/jans#8909]
Add support Enterprise Attestation, so that custom enterprise attestation keys can be used.

**Comment by yackermann** [comment]
- Add EP mode credential creation
- Add support for EP extension
- Add per-customer metadata store.
- Add configurations:
  + Add "Mandatory EP" option, with list of applicable customer metadatas

**Comment by yackermann** [comment]
Expected experience:

1. Configuration:

Customer accesses their admin panel. In the "My Authenticator Metadatas" they add their enterprise metadata. They mark their metadata as "Enterprise only".

In the settings they then enable "Enterprise Attestation" and add "Allowed RPIDs"(The RPIDs that were used to configure authenticators)

They then set enterprise attestation mode to either:

Detect mode - will try running enterprise attestation, but won't fail if it does not match user store. 
Enforce mode - will try enterprise attestation, and if its does not match customer metadat a store, it will fail.

2. Usage.

During credential creation (authenticator adding), make credential request payload extensions will include "ep": true.

Once response is received, server will check attestation against customer metadata.

If server in enforce mode, server will respond with error "unauthorized", and log that non-permitted authenticator was attempted to add.

If server in detect mode, then attestation will be checked against public store.

If attestation is required, and that fails too, then error is returned.

**Comment by maduvena** [comment]
Notes for implementation:

1. LocalMdsService service maintains a json file containing authenticator metadata configured by the administrator. The location of the json file can be configured using config-api

https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/mds/LocalMdsService.java 

2. Currently, During Attestation, the LocalMetadataService is first checked, then the MDS3MetaDataservice is checked. 
https://github.com/JanssenProject/jans/blob/51eaf5945fe705482550186c88c642aa2eb50f4d/jans-fido2/server/src/main/java/io/jans/fido2/service/mds/AttestationCertificateService.java#L118

- [ ] So, here we need to go as per Detect mode / Enforce mode which will be set using config-api: 
Detect mode - will try running enterprise attestation, but won't fail if it does not match user store.
Enforce mode - will try enterprise attestation, and if its does not match customer metadat a store, it will fail.

**Comment by yackermann** [comment]
TODO: 

- [ ] Add diagrams
- [ ] Add description for hybrid (Attested + Non-attested creds)
