### ISSUE TITLE
jans-cli: suggestion for better usability 

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#892]
Attached are the better user experience.
[Jans-Cli-Feedback.pdf](https://github.com/JanssenProject/jans/files/8130380/Jans-Cli-Feedback.pdf)

Request you to please review and let me know if any change in config-api swagger spec to support the suggestion.

**Comment by mbaser** [comment]
Suggestions are good, but some of them is not possible with simple input. Making these changes won't be sufficient.
At the beginning, config-cli was aimed something like dsconfig command. I propose to use UI. urwid (https://github.com/urwid/urwid) seems a good choice.

**Comment by manojs1978** [comment]
we need add mendatory fields on "create new openid client"  which need to be populated while creating new openID client.
ex: client secret

**Comment by mbaser** [comment]
> we need add mendatory fields on "create new openid client" which need to be populated while creating new openID client. ex: client secret

This is not inside CLI, it comes from https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L5088-L5108

**Comment by mbaser** [comment]
> It has to be CLI only. A lot of people will be dropping in from a docker shell. Let's go through each issue that was raised by @pujavs in more detail.

By **UI** I meant to say **TUI** that is similar to we use for Gluu Setup:

![image](https://user-images.githubusercontent.com/6398752/156345824-a3bc8c61-f25b-4892-8041-4824e7a2e40f.png)

So it can run on docker shell.
