### ISSUE TITLE
fix(jans-setup): error "kc did start in 120 sec, giving up configuration" while installing jans on opensuse

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#8946]
**Describe the bug**
 error "kc did start in 120 sec, giving up configuration" while installing jans on opensuse

**To Reproduce**
1. download and install jans 1.1..4.nightly
2. select all component with KC as well
3. See error

**Expected behavior**
should not get error 

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/d40e225c-faa1-4432-849d-c184c1438686)

**Desktop (please complete the following information):**
  - OS: opensuse Leap 
  - Version 15 sp5
  - jans 1..1.4.nightly
  - opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moabu** [comment]
I got 

```
ackends                                                 pgsql[R]
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans Link Server                                     True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True
Load Test Data                                               True

Process jans: Calculating application memory
Process jre: Installing Jre
Process jre: Downloading amazon-corretto-17-x64-linux-jdk.tar.gz
Process jetty: Installing Jetty
Process jetty: Downloading jetty-home-11.0.15.tar.gz
Process jython: Installing Jython
Process jython: Downloading jython-installer-2.7.3.jar
Process jans: Generating smtp keys
Process rdbm-server: Installing Rdbm-Server
Process rdbm-server: Downloading jans-orm-spanner-libs-distribution.zip
Process opendj: Downloading opendj-server-legacy-4.5.1.zip
Process rdbm-server: Importing ldif files to pgsql
Process apache2: Configuring apache2
Process jans-auth: Installing Jans-Auth
Process jans-auth: Downloading jans-auth.war
Process jans-auth: Downloading jans-fido2-client.jar
Process jans-auth: Downloading twilio.jar
Process jans-auth: Deploying Jetty Service
Process jans-auth: Generating OAuth openid keys
Process jans-config-api: Installing Jans-Config-Api
Process jans-config-api: Downloading jans-config-api.war
Process jans-config-api: Downloading facter
Process jans-config-api: Downloading scim-plugin.jar
Process jans-config-api: Downloading user-mgt-plugin.jar
Process jans-config-api: Downloading fido2-plugin.jar
Process jans-config-api: Downloading jans-link-plugin.jar
Process jans-config-api: Deploying Jetty Service
Process jans-fido2: Installing Jans-Fido2
Process jans-fido2: Downloading jans-fido2.war
Process jans-fido2: Downloading Apple_WebAuthn_Root_CA.pem
Process jans-fido2: Downloading toc.jwt
Process jans-fido2: Downloading root-r3.crt
Process jans-fido2: Deploying Jetty Service
Process jans-scim: Installing Jans-Scim
Process jans-scim: Downloading jans-scim.war
Process jans-scim: Deploying Jetty Service
Process jans-casa: Installing Jans-Casa
Process jans-casa: Downloading jans-casa.war
Process jans-casa: Downloading jans-casa-config.jar
Process jans-casa: Downloading twilio.jar
Process jans-casa: Downloading jans-fido2-client.jar
Process jans-casa: Deploying Jetty Service
Process jans-link: Installing Jans-Link
Process jans-link: Downloading jans-link.war
Process jans-link: Deploying Jetty Service
Process jans-keycloak-link: Installing Jans-Keycloak-Link
Process jans-keycloak-link: Downloading jans-keycloak-link.war
Process jans-keycloak-link: Downloading kc-link-plugin.jar
Process jans-keycloak-link: Deploying Jetty Service
Process jans-cli: Installing Jans-Cli
Process jans-cli: Downloading pyjwt.zip
Process jans-cli: Downloading prompt_toolkit.zip
Process jans-cli: Downloading wcwidth.zip
Process jans-cli: Downloading pygments.zip
Process jans-cli: Downloading requests_toolbelt.zip
Process jans-cli: Installing Jans Cli
Process jans-saml: Installing Jans-Saml
Process jans-saml: Downloading jans-scim-model.jar
Process jans-saml: Downloading keycloak.zip
Process jans-saml: Downloading kc-saml-plugin.jar
Process jans-saml: Downloading kc-jans-scheduler-deps.zip
Process jans-saml: Downloading kc-jans-scheduler.jar
Process jans-saml: Downloading kc-jans-spi.jar
Process jans-saml: Downloading kc-jans-spi-deps.zip
Process jans-saml: Installing KC
FATAL: True
NoneType: None

FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 469, in do_installation
    jans_saml_installer.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 48, in start_installation
    self.service_post_setup()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 171, in service_post_setup
    self.config_api_idp_plugin_config()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 217, in config_api_idp_plugin_config
    self.logIt("KC did not start in 120 seconds. Giving up configuration", errorLog=True, fatal=True)
  File "/opt/jans/jans-setup/setup_app/utils/setup_utils.py", line 53, in logIt
    base.logIt(*args, **kwargs)
  File "/opt/jans/jans-setup/setup_app/utils/base.py", line 227, in logIt
    sys.exit(1)
SystemExit: 1
```

**Comment by moabu** [comment]
With Open DJ I got 

```
Installing Janssen Server...
For more info see:
  /opt/jans/jans-setup/logs/setup.log  
  /opt/jans/jans-setup/logs/setup_error.log
Profile         :  jans
Detected OS     :  Ubuntu 22.04
Janssen Version :  1.1.4-SNAPSHOT
Detected init   :  bash
Detected Apache :  2.4
hostname                                      demoexample.jans.io
orgName                                                   Janssen
os                                                         ubuntu
city                                                       Austin
state                                                          TX
countryCode                                                    US
Applications max ram (MB)                                   10608
OpenDJ max ram (MB)                                          2652
Backends                                            opendj, pgsql
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Auth Server                                          True
Install Jans Config API                                      True
Install Fido2 Server                                         True
Install Scim Server                                          True
Install Jans Link Server                                     True
Install Jans KC Link Server                                  True
Install Jans Casa                                            True
Install Jans Lock                                            True
Install Jans KC                                              True
Load Test Data                                               True
Process jans: Calculating application memory
Process jre: Installing Jre
Process jre: Downloading amazon-corretto-17-x64-linux-jdk.tar.gz
Process jetty: Installing Jetty
Process jetty: Downloading jetty-home-11.0.15.tar.gz
Process jython: Installing Jython
Process jython: Downloading jython-installer-2.7.3.jar
Process jans: Generating smtp keys
Process opendj: Installing OpenDJ
Process opendj: Downloading opendj-server-legacy-4.5.1.zip
Process opendj: Extracting OpenDJ
Process opendj: Installing OpenDJ
Process opendj: Setting up OpenDJ service
Process opendj: Preparing OpenDJ schema
FATAL: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Process opendj: Creating OpenDJ backends
Process opendj: Configuring OpenDJ
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/setup.py", line 415, in do_installation
    openDjInstaller.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 38, in start_installation
    self.install()
  File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 67, in install
    self.configure_opendj()
  File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 239, in configure_opendj
    self.dbUtils.ldap_conn.modify(
AttributeError: 'DBUtils' object has no attribute 'ldap_conn'
Downloading https://github.com/JanssenProject/jans/archive/refs/heads/main.zip as /opt/dist/jans/jans.zip
Extracting jans-setup package
```

**Comment by devrimyatar** [comment]
I did not get any error installing KC. @manojs1978 Probably your VM has limited resources, try with better VM

![image](https://github.com/user-attachments/assets/798e0ea9-22bb-474d-a7c0-7ed4f668cb92)

**Comment by devrimyatar** [comment]
> With Open DJ I got
> 
> ```
> Installing Janssen Server...
> For more info see:
>   /opt/jans/jans-setup/logs/setup.log  
>   /opt/jans/jans-setup/logs/setup_error.log
> Profile         :  jans
> Detected OS     :  Ubuntu 22.04
> Janssen Version :  1.1.4-SNAPSHOT
> Detected init   :  bash
> Detected Apache :  2.4
> hostname                                      demoexample.jans.io
> orgName                                                   Janssen
> os                                                         ubuntu
> city                                                       Austin
> state                                                          TX
> countryCode                                                    US
> Applications max ram (MB)                                   10608
> OpenDJ max ram (MB)                                          2652
> Backends                                            opendj, pgsql
> Java Type                                                     jre
> Install Apache 2 web server                                  True
> Install Auth Server                                          True
> Install Jans Config API                                      True
> Install Fido2 Server                                         True
> Install Scim Server                                          True
> Install Jans Link Server                                     True
> Install Jans KC Link Server                                  True
> Install Jans Casa                                            True
> Install Jans Lock                                            True
> Install Jans KC                                              True
> Load Test Data                                               True
> Process jans: Calculating application memory
> Process jre: Installing Jre
> Process jre: Downloading amazon-corretto-17-x64-linux-jdk.tar.gz
> Process jetty: Installing Jetty
> Process jetty: Downloading jetty-home-11.0.15.tar.gz
> Process jython: Installing Jython
> Process jython: Downloading jython-installer-2.7.3.jar
> Process jans: Generating smtp keys
> Process opendj: Installing OpenDJ
> Process opendj: Downloading opendj-server-legacy-4.5.1.zip
> Process opendj: Extracting OpenDJ
> Process opendj: Installing OpenDJ
> Process opendj: Setting up OpenDJ service
> Process opendj: Preparing OpenDJ schema
> FATAL: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
> 	Is the server running on that host and accepting TCP/IP connections?
> connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
> 	Is the server running on that host and accepting TCP/IP connections?
> (Background on this error at: http://sqlalche.me/e/13/e3q8)
> Process opendj: Creating OpenDJ backends
> Process opendj: Configuring OpenDJ
> FATAL: True
> Traceback (most recent call last):
>   File "/opt/jans/jans-setup/setup.py", line 415, in do_installation
>     openDjInstaller.start_installation()
>   File "/opt/jans/jans-setup/setup_app/installers/base.py", line 38, in start_installation
>     self.install()
>   File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 67, in install
>     self.configure_opendj()
>   File "/opt/jans/jans-setup/setup_app/installers/opendj.py", line 239, in configure_opendj
>     self.dbUtils.ldap_conn.modify(
> AttributeError: 'DBUtils' object has no attribute 'ldap_conn'
> Downloading https://github.com/JanssenProject/jans/archive/refs/heads/main.zip as /opt/dist/jans/jans.zip
> Extracting jans-setup package
> ```

We don't support multiple backens in jans

**Comment by devrimyatar** [comment]
No isssues with pgsql either
![image](https://github.com/user-attachments/assets/5bec50a8-35ab-4f2f-80d9-cdcedcaf6851)

**Comment by manojs1978** [comment]
@devrimyatar did you checked on opensuse leap 15.5 ?
bcs we have  this issue on opensuse only

**Comment by devrimyatar** [comment]
> @devrimyatar did you checked on opensuse leap 15.5 ? bcs we have this issue on opensuse only

Yes I tested on OpenSUSE
