### ISSUE TITLE
fix(jans-config-api): broken build of saml config-api plugin

### ISSUE THREAD

**Issue by uprightech** [JanssenProject/jans#8963]
Related to issue #8954
Breaking changes were introduced to `jans-core-saml`. Make appropriate changes in the saml config-api plugin to align to the breaking changes.

**Comment by pujavs** [comment]
@uprightech is this issue still open/ require any action from myside?

**Comment by pujavs** [comment]
@uprightech, can this be closed?

**Comment by uprightech** [comment]
I think this can be closed.
