### ISSUE TITLE
feat(setup): to setup lock configuration properties

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#8983]
Dynamic properties for lock to be set.
Please check latest config at  `/jans-linux-setup/jans_setup/templates/jans-lock\dynamic-conf.json`
Snippet:
{...
 "baseEndpoint": "https://%(hostname)s/%(base_endpoint)s/v1", 
  "openIdIssuer": "https://%(hostname)s",
"clientId": "${jca_client_id}",
"tokenUrl": "${tokenEndpoint}"
...
}

Note: Create new client for lock it should have the basic scope like openid and all scopes as present in `/jans-config-lock/jans-config-api/plugins/docs/lock-plugin-swagger.yaml`

**Comment by pujavs** [comment]
@yurem FYI

**Comment by devrimyatar** [comment]
Implemented in commit https://github.com/JanssenProject/jans/commit/85e06b78758923a9570fc206ee181f2fe160fddb
