### ISSUE TITLE
feat (jans-fido): Add interception script for registration

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#8995]
-------------------

### Prepare

- [x] Read contribution guidelines
- [x] Read license information

------------------

### Identified code changes

- [ ] Define interface
- [ ] Implement Code for Java only (python not needed)

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] Update FIDO Admin Guide 
- [ ] Provide documentation and sample script for [Developer Section](https://docs.jans.io/head/admin/developer/scripts/)

**Comment by shekhar16** [comment]
code ha been merged, closing this ticket.
