### ISSUE TITLE
ProjectPasskeys: Minimum support ES256, RS1, RS256, ED25519

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#9025]
- [ ] There is no link between the algorithms supported in config-api vs the ones used in Attestation code, Webauthn
- [ ] Remove hardcoding

**Comment by maduvena** [comment]
notes :

1. https://github.com/JanssenProject/jans/blob/51eaf5945fe705482550186c88c642aa2eb50f4d/jans-fido2/server/src/main/java/io/jans/fido2/service/mds/TocService.java#L175

**Comment by yackermann** [comment]
- [ ] RS1
- [ ] ES256
- [ ] RS256
- [ ] ED25519

**Comment by duttarnab** [comment]
RS1 is now depricated.
ref: https://datatracker.ietf.org/doc/html/rfc8812?ref=https://githubhelp.com#name-rsassa-pkcs1-v1_5-signature

**Comment by yackermann** [comment]
@duttarnab this is still a requirement to support for legacy authenticators

**Comment by duttarnab** [comment]
@yackermann I am trying to understand so sorry for my dumb queries. Here they have asked for only support of 
- ES256
- RS256
- Ed25519

https://w3c.github.io/webauthn/#sctn-public-key-easy

**Comment by yackermann** [comment]
@duttarnab FIDO Alliance certification requires support for ES256/RS256/ED25519/RS1

WebAuthn spec just suggesting algorithms.

**Comment by yackermann** [comment]
Per our call, RS1 support can be dropped
