### ISSUE TITLE
fix(config-api): asset file should be optional for update operation

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#9060]
Edit asset is throwing error if asset file is not provided.
![image](https://github.com/user-attachments/assets/f2703ab8-b3cf-450d-9dfb-19edf4b7ec19)

*Analysis:* For asset update, the asset file was made mandatory assuming that an asset update will always require an asset to be uploaded. But now since we have other meta-data for asset like `jansService`  list there can be a scenario that an existing asset remains same and only `jansService` require modification. 
Thus will make changes asset file optional for update.

**Comment by ossdhaval** [comment]
Hi @pujavs 

This change should be noted in [this](https://docs.jans.io/head/admin/config-guide/custom-assets-configuration/#update-existing-custom-assets) section of the documentation.

**Comment by pujavs** [comment]
@ossdhaval made changes to docs via PR [9258](https://github.com/JanssenProject/jans/pull/9258)

**Comment by pujavs** [comment]
Issue fixed via PR [9082](https://github.com/JanssenProject/jans/pull/9082)
doc updated via PR [9258](https://github.com/JanssenProject/jans/pull/9258)
