### ISSUE TITLE
feat(jans-linux-setup): config db attribute update based on modules deployed

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#9068]
Need to update the `jansServiceModule` for asset in config-api DB config based on modules deployed.
Right now it is static hard coded list.

`It should contain list of all deployed modules and dynamically handled on every module deployment and removal.`

https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jans-config-api/dynamic-conf.json#L80
![image](https://github.com/user-attachments/assets/0f31a607-6843-4b72-991d-68fc1e295c9b)

**Comment by devrimyatar** [comment]
@pujavs Should **jansServiceModule** oln contain Jetty Services? I mean those deployed unde `/opt/jans/jetty`

**Comment by pujavs** [comment]
Yes @devrimyatar, i had confirmed the list before hard coding and all these are jetty service
