### ISSUE TITLE
fix(jans-setup): installation failing for KeyError: 'fido2_extension_fido2extensionSample'

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9087]
**Describe the bug**
installation failing for KeyError: 'fido2_extension_fido2extensionSample'

**To Reproduce**
1. install jans 1.1.4.nightly
2. See error

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/a88f3215-6f0a-4626-81ad-87a792bfda8a)

**Desktop (please complete the following information):**
  - OS:  ubuntu22
jans 1.1.4.nightly
db - opendj
**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@shekhar16 I assigned this to you. I messeged this before
https://github.com/JanssenProject/jans/pull/9075#issuecomment-2263644769
