### ISSUE TITLE
fix(jans-config-api): calling assets API produces unreadable bytes in logs

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#9089]
When calling API endpoint of `jans-config-api/api/v1/jans-assets/upload`, unreadable bytes are emitted into jans-config-api logs. See example below:

![image](https://github.com/user-attachments/assets/24581972-045e-4a75-8efa-ca9bf75d61e9)

This makes the logs difficult to read and parse (especially when using aggregator/parser like Logstash or Google cloud logging).

Expected behavior is to not emit the bytes into the logs.

**Comment by pujavs** [comment]
Fixed via PR[9133](https://github.com/JanssenProject/jans/pull/9133)
