### ISSUE TITLE
Feat: Add mod_auth_openidc Apache module during linux setup

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#909]
The [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) is a certified authentication and authorization module for the Apache 2.x HTTP server that implements the OpenID Connect Relying Party functionality. 

If the software is installed by default, it would make it easier for developers to quickly create demos.

**Comment by mbaser** [comment]
Implemented

**Comment by nynymike** [comment]
I think we should back out this change. For demos, we are now advocating for the https://github.com/JanssenProject/jans/tree/main/demos/jans-tent Python Flask based Relying Party.
