### ISSUE TITLE
ProjectPasskeys: Refactor MDS3 codebase and server config

### ISSUE THREAD

**Issue by yackermann** [JanssenProject/jans#9111]
### Configuration refactoring
- [ ] Deprecate `mdsCertsFolder`, 
- [ ] Deprecate `mdsTocsFolder`, 
- [ ] Deprecate `authenticatorCertsFolder` (https://github.com/JanssenProject/jans/issues/9369)
- [x] replace `metadataUrlsProvider` with `metadataServers` [{"url": "https://mds.fidoalliance.org/", "certificate": "...base64 of certificate..."}]
- [x] Add `metadataRefreshInterval` to allow adjustment of when metadata is refreshed
- [ ] #9248
- [x] Rename `userAutoEnrollment` to `debugUserAutoEnrollment`
- [x] Rename `requestedCredentialTypes` to `enabledFidoAlgorithms`
- [x] Rename `skipDownloadMdsEnabled` to `disableMetadataService`
- [x] #9332

"disabled" means attestation "none"
"monitor" means attestation "direct" but still accept if none return
"enforced" means that credential creation will fail if attestation is not returned

- [x] #9705 https://github.com/JanssenProject/jans/issues/8906

**Comment by yackermann** [comment]
## MDS Code Base refactoring

[TODO]

**Comment by yurem** [comment]
These 2 folders Fido2 uses for devices root certs:
```
Deprecate mdsCertsFolder
Deprecate authenticatorCertsFolder
```

Should we deprecate related to these folders functionality or there is replacement for this?

**Comment by yackermann** [comment]
There should not be a separate folder for device roots. All checks must be done against metadata @yurem

**Comment by yurem** [comment]
This is right approach. But how to do this edge cases if device not in MDS3 list yet? For example we also need to add SG roots.

**Comment by yackermann** [comment]
@yurem standard metadata will have the device root.

**Comment by shekhar16** [comment]
I'm closing this ticket as all are done or having corresponding different tickets.
