### ISSUE TITLE
fix(jans-cli-tui):  display correct message on script list page.

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9132]
**Describe the bug**
display correct message on script list page

**To Reproduce**
1. install jans 1.1.4.nightly
2. go to script
3. click on next button in script list 

**Expected behavior**
should get <prev> button on last page  but when we click on next button 2-3 times getting message as showin in screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/2d72dead-94a1-499b-aed5-d6e81acbd6e6)

**Desktop (please complete the following information):**
  - OS: ubuntu22
--jans 1.1.4.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@manojs1978 Can you provide a video?
