### ISSUE TITLE
fix(jans-cli-tui): unable to switch to simple_passwd_auth as default auth method 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9161]
**Describe the bug**
unable to switch to simple_passwd_auth as default auth method 

**To Reproduce**
1. install jans 1.1.4.nightly
2. enroll casa/fid/super gluu etc
3. change defualt auth method to any one from list 
4. again swtich to simple_password _Auth
5. See error

**Expected behavior**
should able to switch any of selected

**Screenshots**

https://github.com/user-attachments/assets/b6d6b807-b2ab-4841-b853-52936cabc77a

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version 5
  - jans 1.1.4.nighlty
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs Can you help me setting non-script acrs?

1. Firsly I retreived default acr:
```
curl -k https://myjans.local/jans-config-api/api/v1/acrs -H "Authorization: Bearer 6196943a-2dad-45ba-bb8b-77f4a0e8517d"
{"defaultAcr":"simple_password_auth"}
```
As you can see, it is **simple_password_auth**

2. I set **basic_lock** script as default acr (I enabled it before):

```
curl -k -X PUT https://myjans.local/jans-config-api/api/v1/acrs -H "Authorization: Bearer 6196943a-2dad-45ba-bb8b-77f4a0e8517d" -H "Content-Type: application/json" -d '{"defaultAcr": "basic_lock"}'
{"defaultAcr":"basic_lock"}
```

3. When I try to set default acr back to **simple_password_auth**, I get error. It seems config-api treats is as script. But we should be able to set default acr, as well as auth ldap servers
```
curl -k -X PUT https://myjans.local/jans-config-api/api/v1/acrs -H "Authorization: Bearer 6196943a-2dad-45ba-bb8b-77f4a0e8517d" -H "Content-Type: application/json" -d '{"defaultAcr": "simple_password_auth"}'
{"code":"400","message":"INVALID_ACR","description":"Authentication script {simple_password_auth} is not active"}
```

**Comment by pujavs** [comment]
@devrimyatar i do not find a script named `simple_password_auth` in the DB
![image](https://github.com/user-attachments/assets/5603766c-d2d0-4cb5-aafb-f099f802c363)


As per change requested by @ossdhaval Issue#[8683](https://github.com/JanssenProject/jans/issues/8683)  -  CLI allows default authentication method to be set to a method which is not available 

@yuriyz request your advice and feedback on this issue

**Comment by yuriyz** [comment]
@pujavs `simple_password_auth` is internal acr and is always available. It is not script, it is acr built inside AS.

**Comment by pujavs** [comment]
The change to chk if the acr script is valid was done as per request #[8683](https://github.com/JanssenProject/jans/issues/8683)

But as confirmed in below is the additional change requested
![image](https://github.com/user-attachments/assets/fffd1d71-ffdb-46f4-82ac-e5c1ea7758f0)

**Comment by pujavs** [comment]
Fixed via PR [9240](https://github.com/JanssenProject/jans/pull/9240)

**Comment by pujavs** [comment]
@manojs1978 request you to please verify the fix and confirm
