### ISSUE TITLE
fix(jans): 2 identical fido scripts in jans

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9164]
**Describe the bug**
2 identical fido scripts in jans

**To Reproduce**
1. install jans 1.1.4.nightly
2. check for fido in scripts

**Expected behavior**
there should be one fido script or there should be some difference in script

**Screenshots**
![image](https://github.com/user-attachments/assets/c26e1fcb-ab9b-4f12-852c-a2e7f81c94f1)

**Desktop (please complete the following information):**
  - OS: suse 15
  - Version sp5
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@shekhar16 You added this one recently `inum=9BAF-90D7,ou=scripts,o=jans`. There was another script with same displayname and description `inum=8BAF-80D7,ou=scripts,o=jans`, please check them.

**Comment by devrimyatar** [comment]
Fixed in https://github.com/JanssenProject/jans/commit/1a86124407fdd8adb9f6360c8210b7e86291212f
