### ISSUE TITLE
docs(SCIM config): update the configuration guides for SCIM

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#9337]
Current SCIM configuration guides for [user](https://docs.jans.io/v1.1.4/admin/config-guide/scim-config/user-config/) and [group](https://docs.jans.io/v1.1.4/admin/config-guide/scim-config/scim-group-config/) management are not complete and may be out-dated. 

We need to:

- add more details and align it with the structure followed by [other config guides](https://docs.jans.io/v1.1.4/admin/config-guide/auth-server-config/openid-connect-client-configuration/).
- Possibly merge the user and group configuration docs in one.
- Update any references to these documents from rest of the document

**Comment by ossdhaval** [comment]
Hi @imShakil 

Please check if the point below has been taken care:

```
Update any references to these documents from rest of the document
```

**Comment by imShakil** [comment]
I am closing this issue as PR merged.
