### ISSUE TITLE
fix(jans-casa): unable to load jans-casa url

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9338]
**Describe the bug**

**To Reproduce**
1. install jans/flex nightly build
2. launch jans-casa

**Expected behavior**
should able to launch jans-casa 

**Screenshots**
![image](https://github.com/user-attachments/assets/6191fb01-65ec-4d2d-acd0-d325f25ea2ba)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - Version 
-jans 1.1.5.nightly
DB - pgsql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
deb package has an issue, we're checking
