### ISSUE TITLE
fix(jans-cli-tui): edit asset not working

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9376]
**Describe the bug**
 edit asset not working

**To Reproduce**
1. install jans
2. launch TUI
3. add asset
4. edit asset
5. See error

**Expected behavior**
should able to edit asset and save changes

**Screenshots**
![image](https://github.com/user-attachments/assets/99ce79c7-2deb-4507-ae40-de78e5da3834)

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - jans 1.1.5.nightly
  - mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs We discussed this before. Could you ask @uprightech how he implemented SAML plugin, so that when editing config-api won't require re-uploading asset.

**Comment by pujavs** [comment]
@devrimyatar, I had fixed the issue of asset file should be optional for update operation -> https://github.com/JanssenProject/jans/issues/9060
Request you to please confirm if TUI is calling PUT and not POST in this of edit?
