### ISSUE TITLE
feat(jans-config-api): allow to specify filePath in file upload request

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#9404]
Current jans-config-api determine filePath based on file extension. This works well but we need to extend this functionality.

It should support more than one folder for each file type. For this it can use folderPath as first factor to find validation rule(s). After that it can do same validation which it do now.

Example document in request:
```
--form 'document="{
\"fileName\": \"kc-saml-plugin.jar\",
\”folderPath\": \"/opt/jans/test/lib\",
\"description\": \"Test asset 3\",
...
```

After getting such request config-api should filter rules and find which belong to `/opt/jans/test/lib`. After that it can check if this folder can accpept this file types.

**Comment by pujavs** [comment]
@yurem, you are right at present `config-api` determines `filePath` based on file extension and the validation to chk if the mapping for the fileType being uploaded exists.  The assetMapping data as defined in DB is the bases for all the validation.
[that is types of asset type that are allowed, asset type and file path mapping](https://github.com/JanssenProject/jans/blob/main/jans-linux-setup/jans_setup/templates/jans-config-api/dynamic-conf.json#L94-L127)

Reference of the asset mapping is https://docs.jans.io/v1.1.3/admin/developer/customization/customize-web-pages/#default-pages-bundled-in-the-jans-authwar-are

Thus i think caller should not be allowed to  specify `filePath` as it defeacts the purpose of asset-mapping.
Though i understand that `filePath` would be required by Documentcore to save/upload assets on service start-up and we can declare that attribute as utility field.

Thus i do not understand the statement `It should support more than one folder for each file type. For this it can use filePath as first factor to find validation rule(s). After that it can do same validation which it do now.`
Request you to please elaborate on this

**Comment by yurem** [comment]
`...it can use filePath as first factor...` My idea is that `file Path` can be used as hint to select right asset Mapping rules. Final `file Path` should be provided from `asset Mapping`  in the way how it works now to avoid security issues.

**Comment by pujavs** [comment]
`filePath` cannot overide the mapping DB it will only add to complexity and me the functionality error prone.

**Comment by yurem** [comment]
Current `assetMapping` rules work well for customizations (https://docs.jans.io/v1.1.3/admin/developer/customization/customize-web-pages/#default-pages-bundled-in-the-jans-authwar-are)

But for non standard cases it will not work For example Fido2 stores files in:
```
/etc/jans/conf/fido2
├── authenticator_cert
│   ├── Apple_WebAuthn_Root_CA.pem
│   ├── HyperFIDO_CA_Cert_V1.pem
│   ├── HyperFIDO_CA_Cert_V2.pem
│   └── yubico-u2f-ca-cert.crt
├── mds
│   ├── cert
│   │   └── root-r3.crt
│   └── toc
│       └── toc.jwt
└── server_metadata
```

Example mapping with `filePath for case above`:

```
    "assetDirMapping":[
      {
        "directory":"/etc/jans/conf/fido2/authenticator_cert",
        "jansServiceModule":[
          "jans-fido2"
        ],
        "type":[
          "pem"
        ],
        "description":"PEM files."
      },
      {
        "directory":"/etc/jans/conf/fido2/authenticator_cert",
        "jansServiceModule":[
          "jans-fido2"
        ],
        "type":[
          "crt"
        ],
        "description":"CRT files."
      },
      ...
    ]
``

**Comment by yuriyz** [comment]
We do need path because same extension can end up in different folders. I guess picture above illustrates it quite clearly.

**Comment by pujavs** [comment]
Implemented via PR [9665](https://github.com/JanssenProject/jans/pull/9665)
- Modified asset mapping as per [Custom-Asset-Intake-Mapping](https://github.com/JanssenProject/jans/wiki/Custom-Asset-Intake-Mapping)
![image](https://github.com/user-attachments/assets/bc8bb6aa-54ea-4686-91df-3468905cb468)

- Testing asset upload 
![image](https://github.com/user-attachments/assets/31d88078-f934-49af-884b-ea9a6c4f8a86)
