### ISSUE TITLE
feat (jans-tui): Show tokens in Client View

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#9413]
### Description

![image](https://github.com/user-attachments/assets/43f8f818-ff43-437b-b2c0-a0836ec07d2a)

There could be a lot of tokens for a given client, especially for a shared client_id (for example, a mobile application that uses the same client_id). So search is needed and paged results.  If a token is deleted, the TUI should invoke the OAuth Global Token Validation endpoint. 

-------------------

### Prepare

- [ ] Read contribution guidelines
- [ ] Read license information

------------------

### Identified code changes

- [ ] task 1
- [ ] task 2
- [ ] task 3

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] task for updating user guides if needed
- [ ] task for updating installation and configuration guides if needed 
- [ ] task for updating developer documentation if needed
- [ ] task for updating technical documentation if needed

**Comment by yuriyz** [comment]
This requires API on config-api side to list tokens for given client.

**Comment by devrimyatar** [comment]
> This requires API on config-api side to list tokens for given client.

CC @pujavs

**Comment by pujavs** [comment]
Fixed via PR [9554](https://github.com/JanssenProject/jans/pull/9554)

**Comment by devrimyatar** [comment]
Currently  search is not possible. This is expressed in issue body:

_**So search is needed and paged results.**_

**Comment by pujavs** [comment]
@devrimyatar, the issue description stated that one should be able to search based on client_id and hence the GET endpoints takes `client-inum` as parameter -> `/jans-config-api/api/v1/token/client/<client-inum>`

**What other option is needed to search please specify.**

The response to GET is paginated result as seen in the screenshot in https://github.com/JanssenProject/jans/issues/9413#issuecomment-2363936673

**Comment by devrimyatar** [comment]
@nynymike Will we be able to search tokens by **jansUsrId**, **grtTyp**, **scp**, **exp**? Or just list associated tokens as a list*

**Comment by pujavs** [comment]
@devrimyatar, If you want generic search i will implement that

**Comment by pujavs** [comment]
@devrimyatar, i have implemented search to take in dynamic search,
**Note:** `fieldVauePair` is query param that takes comma separated field=value pairs example -> field1=value1,field2=value2
Try /jans-config-api/api/v1/config/scripts?fieldValuePair=level=10

Example:
1. Searching all token
![image](https://github.com/user-attachments/assets/126ed1f7-2ad2-472c-8d80-b742f91d14ca)

2. Searching based on `clnId`
![image](https://github.com/user-attachments/assets/9c0445a9-48d0-463f-b0b4-a851d27d001d)

3. Searching based on `referenceId`
![image](https://github.com/user-attachments/assets/fb27a569-47ef-496b-9e5b-750599484055)

4. Search based on `scope`
![image](https://github.com/user-attachments/assets/66103150-d106-4706-b43a-41105cee0021)
