### ISSUE TITLE
fix(jans-auth-server): new jans server installation show `null` in place of client_name

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#9415]
On new installed jans server [v1.1.5.nightly](https://github.com/JanssenProject/jans/releases/tag/v1.1.5.nightly) the authorization page is displaying `null` instead of displaying client-name.

**Authz URL**

```
https://duttarnab-fancy-silkworm.gluu.info/jans-auth/restv1/authorize?scope=openid%20profile&response_type=code&redirect_uri=https%3A%2F%2Fduttarnab-fancy-silkworm.gluu.info&client_id=1475bfbd-4b1b-406b-9b9f-c7a486b4b55e&code_challenge_method=S256&code_challenge=l-luB8tvc7K2TT16350QLQNDW43YQg5YDd7fYD_SEZQ&nonce=d5964cdc-b8d0-45c7-b114-508f1faf21da&acr_values=simple_password_auth&state=bwcak6vohs
```

![image](https://github.com/user-attachments/assets/b0b7648b-3de4-4e3a-95ac-47a205035993)

**Comment by yuriyz** [comment]
I was able to reproduce this issue and fixed it.

![image](https://github.com/user-attachments/assets/9291f398-650c-4e34-8004-6cda2d2ea2ea)
