### ISSUE TITLE
fix(jans-trap): Next Month Arrow is Hidden in calender of client expiry date input while register new OIDC client.

### ISSUE THREAD

**Issue by mjatin-dev** [JanssenProject/jans#9430]
**Describe the bug**
 Next Month Arrow is Hidden in calender of client expiry date input while register new OIDC client.

**To Reproduce**
1. Go to 'Add new client'
2. Click on 'client expiry date'

**Expected behavior**
Next Month Arrow should be visible in client expiry date input while register new OIDC client.

**Screenshots**
![Clipboard - September 6, 2024 7_55 PM](https://github.com/user-attachments/assets/3d4d4477-ff21-4241-b7c9-c2faf7e40a24)

**Desktop (please complete the following information):**

**Comment by duttarnab** [comment]
Fixed in latest release
