### ISSUE TITLE
fix(config-api): fido device fetch error

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#9442]
**Describe the bug**
Getting 500 Internal error while invoking GET endpoint.

* Endpoint:* https://jans-server>/jans-config-api/fido2/registration/entries/admin

*Error:*
{
"cause1": "io.jans.orm.exception.MappingException: Base DN to find entries is null",
"servlet": "io.jans.configapi.plugin.fido2.rest.ApiApplication",
"cause0": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.MappingException: Base DN to find entries is null",
"message": "org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.MappingException: Base DN to find entries is null",
"url": "/jans-config-api/fido2/registration/entries/admin",
"status": "500"
}

even the entry is present in "_jansFido2RegistrationEntry" table.

**Comment by pujavs** [comment]
@mjatin-dev , i am not able to replicate the issue, kindly recheck your setup and confirm

![image](https://github.com/user-attachments/assets/de0dfc99-300a-4796-891f-2a6d5778261e)
![image](https://github.com/user-attachments/assets/3ff459a7-ae0e-4006-8b8b-0b8233468720)

**Comment by pujavs** [comment]
@mjatin-dev are you still facing issue?

**Comment by mjatin-dev** [comment]
No, Its working fine.
