### ISSUE TITLE
feat(jans-auth-server): forbid plain pkce if fapi=true (fapi1-advanced-final-par-plain-pkce-rejected fail)

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#946]
**Description**
feat: forbid plain pkce if fapi=true (fapi1-advanced-final-par-plain-pkce-rejected fail)

**Comment by yuriyz** [comment]
Issue is fixed.
@HemantKMehta can you run fapi test and confirm ?

**Comment by HemantKMehta** [comment]
Tested and it is working fine.
