### ISSUE TITLE
fix(jans-cli-tui): tui breaking on search Asset

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9466]
**Describe the bug**
tui breaking on search Asset

**To Reproduce**
1. install jans 1.1.5.nightly
2. launch  TUI
3. search asset

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/b9fb522d-5cf7-4fb8-8981-3bc501a81914)

**Desktop (please complete the following information):**
  - OS: ubuntu/suse
  - Db opendj
  - jans 1.1.5.nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
can't replicate


https://github.com/user-attachments/assets/0afa9f24-ef49-4d23-b7ab-5a478f5377ed
