### ISSUE TITLE
fix(jans-cli-tui):unable to add asset

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9467]
**Describe the bug**
unable to add asset

**To Reproduce**
1. install jans 1.1.5.nightly
2. lauch cli 
3. add asset

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/c7beec14-a8e6-4314-b854-35d967ff6fca)

**Desktop (please complete the following information):**
  - OS: ubuntu/suse
  - Version 22/15 
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
Fixed by https://github.com/JanssenProject/jans/issues/9467
