### ISSUE TITLE
fix(jans-casa): error 400 when selecting acr as openid agama project

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9471]
**Describe the bug**
error 400 when selecting acr as openid agama project

**To Reproduce**
1. install jans 1.1.5.nightly
2. launch tui 
3. deploy agama openid project from community

**Expected behavior**
should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/e181c241-dc9e-4894-8e8b-9cccec7d4518)

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
@pujavs @devrimyatar any idea?

**Comment by jgomer2001** [comment]
@pujavs @devrimyatar any idea?

**Comment by pujavs** [comment]
Implemented via PR [9919] (https://github.com/JanssenProject/jans/pull/9919)

- Testing
![Image](https://github.com/user-attachments/assets/f0be8737-cbda-4e12-ba67-ac37bfdbd9c2)

![Image](https://github.com/user-attachments/assets/39565a9e-095d-4bd9-9a8f-fd68298c3424)

![Image](https://github.com/user-attachments/assets/7f7c7d83-4557-4911-92b6-9696ba4b038a)
