### ISSUE TITLE
fix(jans-monolith-docker): Install Script fails when importing ruamel.yaml

### ISSUE THREAD

**Issue by tawaren** [JanssenProject/jans#9483]
**Describe the bug**
When using the docker compose monolith according to the [installation guide](https://docs.jans.io/v1.1.4/admin/install/docker-install/compose/#how-to-run) fails during the installation script.
When running the command ./up.sh the error `ModuleNotFoundError: No module named 'ruamel'` is produced during the execution of `install.py`. The setup script then completes immediately with the message `*****   Setup script completed!!    *****`. But as the installation actually was aborted the services can not be started producing the error `app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory` repeatedly, not recovering from it. Janssen never arrives in a state where it is responsive.

**To Reproduce**
Steps to reproduce the behavior: (Mostly a copy of the steps in the installation guide)
1. Create a fresh empty folder.
2. Download the following files into the folder:
2.1. https://raw.githubusercontent.com/JanssenProject/jans/main/docker-jans-monolith/jans-mysql-compose.yml 
2.2. https://raw.githubusercontent.com/JanssenProject/jans/main/docker-jans-monolith/up.sh
2.3. https://raw.githubusercontent.com/JanssenProject/jans/main/docker-jans-monolith/down.sh
2.4. https://raw.githubusercontent.com/JanssenProject/jans/main/docker-jans-monolith/clean.sh
3. Start Janssen by executing: up.sh
4. Inspect the logs over: docker compose -f jans-mysql-compose.yml logs jans
5. See error

**Expected behavior**
After step 2 the installation should start and run through, which can take some time but after a while  the message `*****   Setup script completed!!    *****` appears and then the services are started without producing the message `/app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory`. After starting is complete it is reachable and responsive.

**Screenshots**
Excerpt of the Console output:
```
jans-1  | *****   Writing properties!!   *****
jans-1  | Installing with RDBMS
jans-1  | Installing with MySql
jans-1  | *****   Running the setup script for Janssen!!   *****
jans-1  | *****   PLEASE NOTE THAT THIS MAY TAKE A WHILE TO FINISH. PLEASE BE PATIENT!!   *****
jans-1  | Executing https://raw.githubusercontent.com/JanssenProject/jans/b645f0bdb706b933bf5c93fc261a6f00ce5a1882/jans-linux-setup/jans_setup/install.py > install.py
jans-1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
jans-1  |                                  Dload  Upload   Total   Spent    Left  Speed
100 13180  100 13180    0     0  32871      0 --:--:-- --:--:-- --:--:-- 32950
jans-1  | Executing python3 install.py -yes --args=-f setup.properties -n
jans-1  | Traceback (most recent call last):
jans-1  |   File "/opt/jans/jans-setup/setup.py", line 43, in <module>
jans-1  |     from setup_app.utils import arg_parser
jans-1  |   File "/opt/jans/jans-setup/setup_app/utils/arg_parser.py", line 8, in <module>
jans-1  |     from setup_app.utils import base
jans-1  |   File "/opt/jans/jans-setup/setup_app/utils/base.py", line 20, in <module>
jans-1  |     import ruamel.yaml
jans-1  | ModuleNotFoundError: No module named 'ruamel'
jans-1  | Downloading https://github.com/JanssenProject/jans/archive/refs/heads/main.zip as /opt/dist/jans/jans.zip
jans-1  | Extracting jans-setup package
jans-1  | Launching Janssen Setup
jans-1  | Executing /usr/bin/python3 /opt/jans/jans-setup/setup.py -f setup.properties -n
jans-1  | *****   Setup script completed!!    *****
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
jans-1  | Janssen Authorization has already been installed. Starting services...
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
jans-1  | Janssen Authorization has already been installed. Starting services...
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
jans-1  | Janssen Authorization has already been installed. Starting services...
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
jans-1  | Janssen Authorization has already been installed. Starting services...
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
jans-1  | Janssen Authorization has already been installed. Starting services...
jans-1  | /app/scripts/entrypoint.sh: line 161: /etc/init.d/apache2: No such file or directory
...
```
The last two lines will repeate approximately every minute.

**Setup:**
***Desktop:***
  - OS: Windows 10 Pro 22HS2
  - Docker Version: Docker version 27.2.0, build 3ab4256
  - Janssen Version: 1.1.5_dev

The error also appears on a server but it uses older versions.

***Server:***
  - OS: Debian 6.1.90-1 (2024-05-03) x86_64
  - Docker Version: Docker version 26.1.0, build 9714adc
  - Janssen Version: 1.0.23_dev

**Comment by nynymike** [comment]
@misba7 can you confirm?

**Comment by misba7** [comment]
I am confirming the error.
We will work on a fix.

**Comment by misba7** [comment]
We pushed a new image with the fix i.e. `1.1.5-1`.
You can update `up.sh` with the new tag: `JANSSEN_VERSION="1.1.5-1"`
or just pull latest up.sh `wget https://raw.githubusercontent.com/JanssenProject/jans/main/docker-jans-monolith/up.sh
`

**Comment by tawaren** [comment]
The fix works, it installs and runs properly again. 
Thanks for your effort.
