### ISSUE TITLE
FIx : Not able to enable Fido2-extention script.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [JanssenProject/jans#9485]
**Describe the bug**

 Not able to enable Fido2-extention script.

**To Reproduce**
1. Install jans '
2. Go to Jans-TUI
3. Go to script
4. Search for fido2-extention script 
5.  Try to enable it

**Expected behavior**
 script must be  enabled 

**Screenshots**
![Screenshot (116)](https://github.com/user-attachments/assets/92a8df7d-2539-4932-8bac-44c4ba225788)

**Desktop (please complete the following information):**
  - 
  - Version jans 1.1.5 nightly + mysql/pgsql

**Additional context**

**Comment by devrimyatar** [comment]
Thi is not TUI issue, config-api refuse to save the script and raises this error in log

`message: Name should contain only letters, digits and underscores`

@shekhar16  Please rename **fido2 extension** to **fido2_extension**
