### ISSUE TITLE
feat (cedarling): Log Startup message

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#9495]
After init is called, the cedarling should write a startup log message with details about its configuration. This is a good way to test the log functionality via Python too. 

### Identified code changes

- [ ] Create **new** log interface in Rust
- [ ] Add `CEDARLING_LOG_TYPE` bootstrap variable to control logging behavior, default to `in_memory`
- [ ] Add `CEDARLING_LOG_EXP_TIME` bootstrap variable, default to `60`
- [ ] Create log message in cedarling memory and expire it accordingly
- [ ] Adjust Python binding for response, which should be a dictionary of log messages, each with a unique identifier representing the log message identifier, so the client can discard duplicate messages if they happen to return.

-------------------

### Test cases and code coverage

- [ ] Rust unit test
- [ ] Python integration test

-------------------

### Document the changes

- [ ] Update python docs
- [ ] Make sure method in Rust is propery documented with an example.

**Comment by olehbozhok** [comment]
we discussed that it would be OK to use `Circular buffer` so I change `CEDARLING_LOG_EXP_TIME` to the `CEDARLING_LOG_CACHE_SIZE`

**Comment by nynymike** [comment]
Ok for now.
