### ISSUE TITLE
feat(jans-auth-server): OpenID AuthZEN 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#9557]
### Description

OpenID AuthZEN is in the first implementers draft:  https://openid.github.io/authzen/

This issue is a placeholder to track all the various tasks that would be involved to implement support for this new spec. 

The backend for this service would be a Cedarling with a certain policy store loaded.

**Comment by yuriyz** [comment]
WG https://openid.net/wg/authzen/
