### ISSUE TITLE
fix(config-api): user should not be able to see fido/super gluu credentials of all users

### ISSUE THREAD

**Issue by mjatin-dev** [JanssenProject/jans#9639]
**Describe the bug**
Getting all the registered devices while invoking GET endpoint.

Endpoint:* [https://jans-server>/jans-config-api/fido2/registration/entries/admin](https://jans-server%3E/jans-config-api/fido2/registration/entries/admin)

**Expected behavior**
User should be able to see only those registered devices that linked with their name. 

**Screenshots**
[Screencast from 01-10-24 05:14:36 PM IST.webm](https://github.com/user-attachments/assets/e7fa5fbf-5b58-4a0f-a738-78ffee73358d)

**Comment by pujavs** [comment]
@mjatin-dev, sorry i do not understand, can you share a response that you think is incorrect and what is expected.

**Comment by mjatin-dev** [comment]
@mjatin-dev, Sorry for that
We need list of fido2 registration entries based on particular user. Currently its returning all the entries.

In below response we fetched registration entries for user **admin user** which is correct but its also giving same response for **user admin** as well

Endpoint - /jans-config-api/fido2/registration/entries/**admin** (correct response)
[
  {
    "dn": "jansId=ad4c3e97-8cc1-458f-ab30-3eb924fa1737,ou=fido2_register,inum=1e73f801-22c2-4c19-a757-f96a87a5c713,ou=people,o=jans",
    "id": "ad4c3e97-8cc1-458f-ab30-3eb924fa1737",
    "challange": "71wZlhdNfcQOZmOqG7MRv7EeSkOrIpKtPBh5sMFycBE",
    "challengeHash": 78708,
    "creationDate": "2024-10-01T07:21:19",
    "userInum": "1e73f801-22c2-4c19-a757-f96a87a5c713",
    "rpId": "admin-ui-test.gluu.org",
    "deletable": false,
    "publicKeyId": "Du3boeYFTvF09Ja7yzZ_wg",
    "publicKeyIdHash": 21255,
    "registrationData": {
      "createdDate": "2024-10-01T07:21:19",
      "updatedDate": "2024-10-01T07:22:23",
      "createdBy": "admin",
      "updatedBy": "admin",
      "username": "admin",
      "domain": "admin-ui-test.gluu.org",
      "userId": "1TcyS5KhOV4eg8sSaBUpUNzu7N7zF1RyFbh5fdSjsmI",
      "challenge": "71wZlhdNfcQOZmOqG7MRv7EeSkOrIpKtPBh5sMFycBE",
      "attenstationRequest": "{\"attestation\":\"direct\",\"displayName\":\"admin\",\"authenticatorSelection\":{\"authenticatorAttachment\":\"platform\",\"userVerification\":\"discouraged\",\"requireResidentKey\":\"false\"},\"username\":\"admin\"}",
      "attenstationResponse": "{\"type\":\"public-key\",\"id\":\"Du3boeYFTvF09Ja7yzZ_wg\",\"response\":{\"attestationObject\":\"o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YViUjZHVp5tBCFVmGadN9klm_j50zRn-V4OMG9wljvmxv3ddAAAAAOqbjWZNAR0hPOS2tIy1ddQAEA7t26HmBU7xdPSWu8s2f8KlAQIDJiABIVggjm2ND63AU_u_a899zBiel0EhvGi2mlM4S0hFKp0wBGQiWCB-48cKj7QPhAncJ8UmtPWCoBx4_AFHSUB4p2VmlB8jNQ\",\"clientDataJSON\":\"eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiNzF3WmxoZE5mY1FPWm1PcUc3TVJ2N0VlU2tPcklwS3RQQmg1c01GeWNCRSIsIm9yaWdpbiI6Imh0dHBzOi8vYWRtaW4tdWktdGVzdC5nbHV1Lm9yZyIsImNyb3NzT3JpZ2luIjpmYWxzZX0\"},\"clientExtensionResults\":{}}",
      "uncompressedECPoint": "pQECAyYgASFYII5tjQ-twFP7v2vPfcwYnpdBIbxotppTOEtIRSqdMARkIlggfuPHCo-0D4QJ3CfFJrT1gqAcePwBR0lAeKdlZpQfIzU",
      "publicKeyId": "Du3boeYFTvF09Ja7yzZ_wg",
      "type": "public-key",
      "status": "registered",
      "counter": 0,
      "attestationType": "none",
      "signatureAlgorithm": 0,
      "applicationId": "admin-ui-test.gluu.org"
    },
    "counter": 0,
    "registrationStatus": "registered",
    "baseDn": "jansId=ad4c3e97-8cc1-458f-ab30-3eb924fa1737,ou=fido2_register,inum=1e73f801-22c2-4c19-a757-f96a87a5c713,ou=people,o=jans"
  }
]


Endpoint - /jans-config-api/fido2/registration/entries/**admin** (incorrect response)
[
  {
    "dn": "jansId=ad4c3e97-8cc1-458f-ab30-3eb924fa1737,ou=fido2_register,inum=1e73f801-22c2-4c19-a757-f96a87a5c713,ou=people,o=jans",
    "id": "ad4c3e97-8cc1-458f-ab30-3eb924fa1737",
    "challange": "71wZlhdNfcQOZmOqG7MRv7EeSkOrIpKtPBh5sMFycBE",
    "challengeHash": 78708,
    "creationDate": "2024-10-01T07:21:19",
    "userInum": "1e73f801-22c2-4c19-a757-f96a87a5c713",
    "rpId": "admin-ui-test.gluu.org",
    "deletable": false,
    "publicKeyId": "Du3boeYFTvF09Ja7yzZ_wg",
    "publicKeyIdHash": 21255,
    "registrationData": {
      "createdDate": "2024-10-01T07:21:19",
      "updatedDate": "2024-10-01T07:22:23",
      "createdBy": "admin",
      "updatedBy": "admin",
      "username": "admin",
      "domain": "admin-ui-test.gluu.org",
      "userId": "1TcyS5KhOV4eg8sSaBUpUNzu7N7zF1RyFbh5fdSjsmI",
      "challenge": "71wZlhdNfcQOZmOqG7MRv7EeSkOrIpKtPBh5sMFycBE",
      "attenstationRequest": "{\"attestation\":\"direct\",\"displayName\":\"admin\",\"authenticatorSelection\":{\"authenticatorAttachment\":\"platform\",\"userVerification\":\"discouraged\",\"requireResidentKey\":\"false\"},\"username\":\"admin\"}",
      "attenstationResponse": "{\"type\":\"public-key\",\"id\":\"Du3boeYFTvF09Ja7yzZ_wg\",\"response\":{\"attestationObject\":\"o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YViUjZHVp5tBCFVmGadN9klm_j50zRn-V4OMG9wljvmxv3ddAAAAAOqbjWZNAR0hPOS2tIy1ddQAEA7t26HmBU7xdPSWu8s2f8KlAQIDJiABIVggjm2ND63AU_u_a899zBiel0EhvGi2mlM4S0hFKp0wBGQiWCB-48cKj7QPhAncJ8UmtPWCoBx4_AFHSUB4p2VmlB8jNQ\",\"clientDataJSON\":\"eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiNzF3WmxoZE5mY1FPWm1PcUc3TVJ2N0VlU2tPcklwS3RQQmg1c01GeWNCRSIsIm9yaWdpbiI6Imh0dHBzOi8vYWRtaW4tdWktdGVzdC5nbHV1Lm9yZyIsImNyb3NzT3JpZ2luIjpmYWxzZX0\"},\"clientExtensionResults\":{}}",
      "uncompressedECPoint": "pQECAyYgASFYII5tjQ-twFP7v2vPfcwYnpdBIbxotppTOEtIRSqdMARkIlggfuPHCo-0D4QJ3CfFJrT1gqAcePwBR0lAeKdlZpQfIzU",
      "publicKeyId": "Du3boeYFTvF09Ja7yzZ_wg",
      "type": "public-key",
      "status": "registered",
      "counter": 0,
      "attestationType": "none",
      "signatureAlgorithm": 0,
      "applicationId": "admin-ui-test.gluu.org"
    },
    "counter": 0,
    "registrationStatus": "registered",
    "baseDn": "jansId=ad4c3e97-8cc1-458f-ab30-3eb924fa1737,ou=fido2_register,inum=1e73f801-22c2-4c19-a757-f96a87a5c713,ou=people,o=jans"
  }
]

**Comment by pujavs** [comment]
@mjatin-dev issue fixed via PR [9889] (https://github.com/JanssenProject/jans/pull/9889)
