### ISSUE TITLE
fix(config-api): LDAP issues wrt to ORM wildcard filters

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#9641]
**Describe the bug**
Getting error on LDAP for search when the serach pattern is empty.
The same filters were working earlier 

**To Reproduce**
1. Execute custom script search `curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization:Bearer 0bf6d1bd-b71e-4848-9ccb-bb265a0e9d6a" -X GET https://pujavs-sincere-lioness.gluu.info/jans-config-api/api/v1/config/scripts`
2. See error

Log File: [2024_10_01.jetty.log](https://github.com/user-attachments/files/17212891/2024_10_01.jetty.log)

**Expected behavior**
Should return all the custom script

**Screenshots**
![image](https://github.com/user-attachments/assets/206cfc16-b0d9-4d80-811a-6db833c94ff6)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-jans 1.1.6.nightly
-DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pujavs** [comment]
@yurem has there been any change to LDAP in setup or for ORM filters as this was working earlier and no change

**Comment by manojs1978** [comment]
below is the error in jans when launching TUI

![image](https://github.com/user-attachments/assets/f6a1d879-9a4e-45dd-a99e-9217faa368be)
@pujavs @yurem

**Comment by pujavs** [comment]
Closing this issue as LDAP support is removed from Janssen distribution
