### ISSUE TITLE
chore: remove LDAP support from setup, AS, config-api and other places including documentation

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#9653]
### Description

chore: remove LDAP support from setup, AS, config-api and other places

LDAP support should NOT be removed from ORM.

![Image](https://github.com/user-attachments/assets/218f2bc4-088a-4068-b3bb-40bb5a059a34)

### Test cases and code coverage

- [ ] ~Drop from AS~ @yuriyz 
  Persistence is abstracted via ORM layer. We have few places on AS side where we check whether tree structed is supported. But there is no much value in removing it. If in future we will add some other layer that supports tree structure it may be useful. I'm going to leave it "as is". Documenation and setup are key points for removal.

- [ ] Drop from config-api @pujavs 
- [x] Drop from setup/tui @devrimyatar 
- [x] Drop from images @iromli @moabu 
- [x] Drop from charts @iromli @moabu 
- [ ] #9656 @ossdhaval

**Comment by pujavs** [comment]
@yuriyz should i remove the LDAP Configuration endpoint from config-api 
![Image](https://github.com/user-attachments/assets/99e98836-5c16-4666-b18d-a2665f4ddf8d)

**Comment by yuriyz** [comment]
No, we still support LDAP authentications.

**Comment by yuriyz** [comment]
LDAP is removed from docs, CN and setup. Closing this ticket as done. 
LDAP authentication and ORM layer stays.
