### ISSUE TITLE
feat(jans-cedarling): implement structs for JWT claims

### ISSUE THREAD

**Issue by rmarinn** [JanssenProject/jans#9678]
**Is your feature request related to a problem? Please describe.**
Currently, the JWT Engine requires a mechanism for validating JWT tokens and extracting claims. The absence of proper structs for handling claims makes it cumbersome to work with the returned data. This leads to frustrations when developers try to access claims, as the process lacks clarity and structure.

**Describe the solution you'd like**
A simple call to the `Token::validate(token, kind, decoding_key, algorithm)` then return the claims if the token is valid, an error if otherwise.

I propose implementing a straightforward method, that performs the following actions:
1. Validate the provided JWT token based on its kind.
2. Return the claims as a structured enum if the token is valid.
3. Provide an error message or code if the token validation fails.

The function could be called like this:
```rust
Token::validate(token, kind, decoding_key, algorithm)
```

**Additional context**

Below is a proposed structure for the `TokenKind` enum and the `Token` enum, along with the method signature for validation:
```rust
pub enum TokenKind {
    AccessToken,
    IdToken,
    TransactionToken,
    UserInfoToken,
}

/// Represents the various types of supported JWT tokens.
/// Each variant encapsulates a corresponding struct that holds the claims.
pub enum Token {
    AccessToken(AccessToken),
    IdToken(IdToken),
    TransactionToken(TransactionToken),
    UserInfoToken(UserInfoToken),
}

impl Token {
    /// Validates the given token against the specified kind and returns the appropriate token variant
    /// if valid, or an error if validation fails.
    pub fn validate(
        token: &str,
        kind: TokenKind,
        decoding_key: &Vec<u8>,
        algorithm: Algorithm,
    ) -> Result<Self, _> {
        // implementation here
    }
}
```

The function signature could be changed in the future once the rest of the auth logic gets implemented.

**Comment by nynymike** [comment]
Nice work. Please proceed.
