### ISSUE TITLE
fix(jans): rename schema file name 'Keycloak Link:JsonPatch' and 'Jans Link Plugin:AppConfiguration'  properly 

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9699]
**Describe the bug**
rename schema file name "Keycloak Link:JsonPatch" and "Jans Link Plugin:AppConfiguration"  properly 
we should not require to use double quote for schema file 

**To Reproduce**
1. install jans
2. run command like ` sudo $config_command --info JansLinkConfiguration` or `sudo $config_command --info KcLinkConfiguration`
3.  See error

**Expected behavior**
schema file name should be  proper , not with ' '

**Screenshots**

**Desktop (please complete the following information):**
  - OS: ubuntu22

**Smartphone (please complete the following information):**

**Additional context**

```
root@manojs1978-resolved-cougar:~# sudo $config_command --info JansLinkConfiguration
Operation ID: get-jans-link-properties
  Description: Gets Jans Link App configuration.
Operation ID: put-jans-link-properties
  Description: Updates Jans Link configuration properties.
  Schema: Jans Link Plugin:AppConfiguration

To get sample schema type /opt/jans/jans-cli/config-cli.py --schema-sample <schema>, for example /opt/jans/jans-cli/config-cli.py --schema-sample "Jans Link Plugin:AppConfiguration"
root@manojs1978-resolved-cougar:~# sudo $config_command --info KcLinkConfiguration
Operation ID: get-kc-link-properties
  Description: Gets KC Link configuration properties
Operation ID: put-kc-link-properties
  Description: Update KC Link configuration properties
  Schema: Keycloak Link:AppConfiguration
Operation ID: patch-kc-link-properties
  Description: Partially modifies KC Link configuration properties.
  Schema: Array of Keycloak Link:JsonPatch

To get sample schema type /opt/jans/jans-cli/config-cli.py --schema-sample <schema>, for example /opt/jans/jans-cli/config-cli.py --schema-sample "Keycloak Link:JsonPatch"
```

**Comment by devrimyatar** [comment]
CLI uses this convention:
`Plugin Name: Schema Name`. If schema is in main config-api swagger yaml file, we omit **Plugin Name**, so this requirment is not relevant.
