### ISSUE TITLE
feat(jans-config-api): remove session_id from API and use sid in API instead.

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#9723]
### Description

feat(jans-config-api): remove session_id from API and use sid in API instead.

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code
- [ ] documentation

**Comment by pujavs** [comment]
Implemented via PR#[9739](https://github.com/JanssenProject/jans/pull/9739)
Removed following fields from response
- `id`
- `dn`
- `sessionAttributes.session_id`
- `sessionAttributes.old_session_id`
