### ISSUE TITLE
fix(ProjectPasskeys): Authentication for Touch ID not working

### ISSUE THREAD

**Issue by imran-ishaq** [JanssenProject/jans#9765]
![Image](https://github.com/user-attachments/assets/21eb6545-b4ad-4f26-ba68-a5903ed8f3fb)

**Comment by maduvena** [comment]
![Image](https://github.com/user-attachments/assets/b40bbea8-f334-46a4-8c46-d9f3b146892c)
I dont know why apple attestation is going under "packed" format :(

**Comment by nynymike** [comment]
@yackermann, any idea?
