### ISSUE TITLE
test(jans-cedarling): rectify intermittent failure in get_token_claim_type_boolean_error

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#9778]
Failure of test `authz::entities::get_token_claim_type_boolean_error` is intermittent. Seems to pass on the first test run, but subsequent runs occasionally fail, approximately 1 in 5 on my setup.

To reproduce:

`cargo test get_token_claim_type_boolean_error`

**Comment by djellemah** [comment]
@duttarnab Do the title and description now properly correspond to the PR?

**Comment by duttarnab** [comment]
I find it ok. Just assign the issue to yourself.
