### ISSUE TITLE
Remove fido u2f endpoints

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans#978]
There is no need for u2f endpoints anymore since we already expose FIDO2 functionalities.

Supergluu is not a requirement for Jans, so these endpoints can be safely removed. SG will be migrated to use FIDO2

Additionally, we can skip the **u2f** and **supergluu** scripts from the installation process and from `jans-linux-setup/jans_setup/static/extension/person_authentication`. Remove file `U2fExternalAuthenticator.py` as well

Likewise, remove **u2f** directory from `jans-auth-server/webapp/auth` and u2f.xhtml from `jans-auth-server/webapp/auth/casa`

**Comment by yurem** [comment]
Removed
