### ISSUE TITLE
feat(jans-cedarling): Implement Validation Layer and ServiceFactory

### ISSUE THREAD

**Issue by olehbozhok** [JanssenProject/jans#9854]
**Is your feature request related to a problem? Please describe.**
Currently, we have a DI structure that works like HashMap for service structures. All checks on creating service exist only in the runtime. It leads to potential panics during initialization.

We need to have dependency manager service. That initialize all services in proper sequence and to be strong typed to show any mistakes during compilation time.

**Describe the solution you'd like**
We need to implement `validation layer` that:
- validate all raw data from config to strong typed value objects.
- load all what we need from disk/network
- return error if happened

this layer can be `init` module

Implement ServiceFactory 
service that create/initialize service or gives access to already created service singleton.

**Describe alternatives you've considered**
initialize service using builder pattern and put service to DI container HashMap.  Each service returns error on validation during building

**Additional context**
Also, I need to figure out if we need to have folder models.
And add possible improve to project structure

**Comment by rmarinn** [comment]
> validate all raw data from config to strong typed value objects.

i think the `validation layer` should be called `deserialization layer` or `parsing layer` instead. it might be confusing because it suggests only checking for correctness or ensuring constraints are met, while _deserialization_ or _parsing_ more accurately describe the process of transforming raw configuration data (e.g., JSON, YAML) into structured, strongly-typed objects that the system can work with.. then it should return errors like `Error::MalformedPolicyStore` for mis-configured configs.

**Comment by duttarnab** [comment]
Also consider this point: 
![Image](https://github.com/user-attachments/assets/2b89858f-6fe9-4df6-9f86-5edda15380d6)

**Comment by olehbozhok** [comment]
> > validate all raw data from config to strong typed value objects.
> 
> i think the `validation layer` should be called `deserialization layer` or `parsing layer` instead. it might be confusing because it suggests only checking for correctness or ensuring constraints are met, while _deserialization_ or _parsing_ more accurately describe the process of transforming raw configuration data (e.g., JSON, YAML) into structured, strongly-typed objects that the system can work with.. then it should return errors like `Error::MalformedPolicyStore` for mis-configured configs.

This module not only parse/deserialize but will do all what we need to start application. Disk / network read  (or some handshake) and convert to validated and strong typed value object

**Comment by rmarinn** [comment]
> This module not only parse/deserialize but will do all what we need to start application. Disk / network read (or some handshake) and convert to validated and strong typed value object

if the module will do all of that then it's probably overloaded and should be split into smaller parts.

**Comment by olehbozhok** [comment]
wait https://github.com/JanssenProject/jans/pull/9870 to be merged
