### ISSUE TITLE
fix(jans-cli-tui) : uploaded assets are not stored on server locations

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9943]
**Describe the bug**
uploaded assets are not stored on server locations

**To Reproduce**
1. install jans/flex 1.1.6.nightly/ 5.1.6.nightly
2. upload any type of asset file 
3. showing asset uploaded on screen but it is not stored at desired location

**Expected behavior**
when any asset uploaded it should store at their desired location

**Screenshots**
![Image](https://github.com/user-attachments/assets/c9bfa889-78d9-4a64-942c-e4d2df79fe7c)
![Image](https://github.com/user-attachments/assets/8b31e80d-ecbb-4ee4-82f5-e4622ccd0c5e)

**Desktop (please complete the following information):**
  - OS: ubuntu 22
-jans 1.1.6.nightly
-DB pgsql/mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
@pujavs I were be able to replicate this issue. CLI uploades the file and it is on database, but not on disk:
```
root@example:~# ls -al //opt/jans/jetty/jans-auth/custom/static
total 8
drwxr-xr-x 2 jetty jetty 4096 Oct 26 11:13 .
drwxr-xr-x 6 jetty jetty 4096 Oct 26 11:13 ..
```


 See the query of documents,

![Image](https://github.com/user-attachments/assets/8098603f-19b1-450c-826b-eb4f0e3636c9)

**Comment by devrimyatar** [comment]
wrong reference in PR body

**Comment by yurem** [comment]
Can you retest it again?

**Comment by manojs1978** [comment]
files uploaded are showing on server
![Image](https://github.com/user-attachments/assets/cd03591a-2074-43ed-b865-f33681b02241)
![Image](https://github.com/user-attachments/assets/2222acbd-44ae-43c9-9ef8-3ec3d3c1a3e0)

**Comment by devrimyatar** [comment]
I still can't see

**Comment by pujavs** [comment]
@devrimyatar,  just clarify how asset-mgt works,
- config-api: Persists the details of asset to be uploaded in DB. I have made it config driven so you just need to specify the service and folder mapping in DB for it to up.
- service-module: Needs to integrate with document-store to enable asset upload.
- document-store: reads the entry from DB for the integrated service to upload the asset.

**Comment by moabu** [comment]
Is this still an active issue ? The pull mech did make it in .
