### ISSUE TITLE
fix(tui): last items on top menu bar are not visible due to lack of space

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#9968]
When all the modules are installed, the number of TUI top menu bar items grow and last few items are not properly displayed.

![Image](https://github.com/user-attachments/assets/7064bb07-71df-477f-8567-f62cbb536236)

**Comment by devrimyatar** [comment]
@ossdhaval Can you suggest a solution?

**Comment by ossdhaval** [comment]
@devrimyatar Here are few options that can help the situation.

Some of the possible solutions:
- Create logical groups and put multiple items under group name as a drop down (should be group `jans link` and `KC link, may be SCIM and User sections)?
- Not sure about the technical feasibility but can the top bar wrap around in the following line? It won't look as elegant but at least all the options will be visible
- Can the top bar be scrollable? Meaning as the focus moves to the items on the right they become visible.

@nynymike @moabu Please add your views here.

**Comment by devrimyatar** [comment]
Second suggestion was implemented. Now navigation bar is responsive

https://github.com/user-attachments/assets/cc0cd4a4-3a0b-4de4-9abe-528a710a5692
